### ISSUE TITLE
A bug: pysam.pileup will not work if all the reads per base qualities are 10 (+) 

### ISSUE THREAD

**Issue by dolittle007** [pysam-developers/pysam#1002]
An interesting bug,
If reads per base qualities are all 10, (+++++++++), the pysam.pileup will not work properly.

**Comment by jmarshall** [comment]
In what way did it did not work properly? Please add an example program that demonstrates the problem.

**Comment by dolittle007** [comment]
dsf


[example.txt](https://github.com/pysam-developers/pysam/files/6244866/example.txt)

**Comment by jmarshall** [comment]
Thanks, that's an example SAM file. Could you please also add an example Python program that shows the Pysam functions and fields that you're using that demonstrates the problem.

(I have tried with just a `bamfile.pileup()` loop and not noticed any problem. So I would need to know what functions and fields you are using.)

**Comment by jmarshall** [comment]
`pileup()` can omit bases with low quality scores. The default is to omit < 13, which means all your base quality 10s (`+`) are dropped. If you lower the quality threshold via e.g. `sam.pileup(min_base_quality = 5)` you will see all these bases in the output.
