### ISSUE TITLE
pysam/libcalignmentfile.pyx FileNotFoundError: [Err No 2] No such file or directory

### ISSUE THREAD

**Issue by BerkKilicoglu** [pysam-developers/pysam#1014]
Hi ! I'm trying to read bam file using a command: `with pysam.AlignmentFile(bamfile, "rb", require_index=True) as samfile:` but i getting an error

`[E::idx_find_and_load] Could not retrieve index file for 'bamfile.bam'`
`Traceack (most recent call last):`
 ` File "seq.py", line 185, in <module>`
    `with pysam.AlignmentFile(bamfile, "rb", require_index=True) as samfile:`
`  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__`
  `File "pysam/licalignmentfile.pyx", line 1007, in pysam.libcalignmentfile.AlignmentFile._open`
`FileNotFoundError: [Errno 2] No such file or directory`

I would appreciate it if you could help politely. Thanks

**Comment by fulaibaowang** [comment]
hi, how did you solve it?

> Hi ! I'm trying to read bam file using a command: `with pysam.AlignmentFile(bamfile, "rb", require_index=True) as samfile:` but i getting an error
> 
> `[E::idx_find_and_load] Could not retrieve index file for 'bamfile.bam'` `Traceack (most recent call last):` ` File "seq.py", line 185, in <module>` `with pysam.AlignmentFile(bamfile, "rb", require_index=True) as samfile:` ` File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__` `File "pysam/licalignmentfile.pyx", line 1007, in pysam.libcalignmentfile.AlignmentFile._open` `FileNotFoundError: [Errno 2] No such file or directory`
> 
> I would appreciate it if you could help politely. Thanks

**Comment by BerkKilicoglu** [comment]
> hi, how did you solve it?
> 
> > Hi ! I'm trying to read bam file using a command: `with pysam.AlignmentFile(bamfile, "rb", require_index=True) as samfile:` but i getting an error
> > `[E::idx_find_and_load] Could not retrieve index file for 'bamfile.bam'` `Traceack (most recent call last):` ` File "seq.py", line 185, in <module>` `with pysam.AlignmentFile(bamfile, "rb", require_index=True) as samfile:` ` File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__` `File "pysam/licalignmentfile.pyx", line 1007, in pysam.libcalignmentfile.AlignmentFile._open` `FileNotFoundError: [Errno 2] No such file or directory`
> > I would appreciate it if you could help politely. Thanks

Hello, you need to add the bam index file of that bam file to the directory where your bam file is located. When you add the index file, the error will be solved.

**Comment by fulaibaowang** [comment]
Cool, thanks a lot!

**Comment by BerkKilicoglu** [comment]
> Cool, thanks a lot!

bam index files usually have a .bai extension
