### ISSUE TITLE
Iterating through unindexed bam file

### ISSUE THREAD

**Issue by dylkot** [pysam-developers/pysam#102]
I need to iterate line by line simultaneously through 2 bam files that are sorted by read name (query name) rather than by chromosomal position. Because of this constraint, the files are not indexed. Is there a mechanism in place to iterate through files line by line without using the .fetch() method which fails because it requires that the files are indexed?

Also, let me know if there is a better place for me to post questions like this--I couldn't find anything on the documentation page.

Thanks!

**Comment by TyberiusPrime** [comment]
You should be able to iterate through unindexed files by passing until_eof=True to fetch.

**Comment by dylkot** [comment]
That works great. Thank you!

**Comment by dylkot** [comment]
A related question: is there an intended method for iterating line by line through bam files? I've been explicitly making an iterator and going line by line as such: 

    bam = pysam.Samfile(bamfile, "rb")
    bamiter = bam.fetch(until_eof=True)
    read = bamiter.__next__()
    while read:
        ...
        read = bamiter.__next__()
        


but then I have to catch the StopIteration exception when the file ends which seems clumsy. Is this kind of iteration supported and I'm just not seeing it anywhere in the documentaiton?

**Comment by AndreasHeger** [comment]
Does the following not work:
```
for read in bam.fetch()
    print read
```

**Comment by dylkot** [comment]
I need to go through 2 files at once and decide whether or not to go to the next line of one or the other or both depending on information in the read if that makes sense. So I think I need a way to ask for the next line specifically wihin a while loop.

**Comment by AndreasHeger** [comment]
Hi, @dylkot , raising a StopIteration is standard behaviour for iterators, see here:
https://docs.python.org/2/reference/expressions.html#generator.next

```

generator.next()

    Starts the execution of a generator function or resumes it at the last executed yield expression. When a generator function is resumed with a next() method, the current yield expression always evaluates to None. The execution then continues to the next yield expression, where the generator is suspended again, and the value of the expression_list is returned to next()‘s caller. If the generator exits without yielding another value, a StopIteration exception is raised.
```

I am closing this for now as I don't think it is a bug or feature, please reopen if you disagree.

Best wishes,
Andreas

**Comment by keiranmraine** [comment]
I know this is ancient but the following will return None when the iterator is exhausted:

```
next(read_iter, None)
```
