### ISSUE TITLE
get_aligned_pairs not working as expected pysam 0.16.0.1

### ISSUE THREAD

**Issue by alexvnesta** [pysam-developers/pysam#1022]
Hi,

I am trying to use get_aligned pairs to retrieve the reference nucleotide of a read/reference mismatch so I can make a catalog of mismatches in each read.

Some googling showed that get_aligned_pairs would help with this.

code I used: 
```
import pysam
x = pysam.AlignedRead()
x.query_sequence = "A" * 10
x.cigarstring = "5M2D2I2M"
x.set_tag("MD", "4C^TT1C")
print(x.get_reference_sequence())
print(x.get_aligned_pairs(with_seq=True))

print(pysam.__version__)
```

Output:
```
AAAAcTTAc
[(None, 4, 'A'), (None, 5, 'A'), (0, None, None), (1, None, None), (2, 6, 'A'), (3, 7, 'A')]
0.16.0.1
```

This behavior is different from when the function was first implemented. See https://github.com/pysam-developers/pysam/issues/163

Specifically, This is the expected output:
```
>>> import pysam
>>> x = pysam.AlignedRead()
>>> x.query_sequence = "A" * 10
>>> x.cigarstring = "5M2D2I2M"
>>> x.set_tag("MD", "4C^TT2")
>>> print x.get_aligned_pairs(with_seq=True)
[(0, 0, 'A'), (1, 1, 'A'), (2, 2, 'A'), (3, 3, 'A'), (4, 4, 'c'), (None, 5, 'T'), (None, 6, 'T'), (5, None, None), (6, None, None), (7, 7, 'A'), (8, 8, 'A')]
```

**Comment by jmarshall** [comment]
There are a couple of incidental problems with the way you've set up this record:

* The query_sequence says the read is 10 bases in length, but the cigarstring represents only 9 bases.
* The MD tag is invalid and should be `4C0^TT1C`. In more complicated cases this makes a difference for `get_aligned_pairs` et al — see #895.

But the main problem is:

* You have not initialised the reference_start field, which is being left as None.

If you add `x.reference_start = 0` you will get your expected output.
