### ISSUE TITLE
Running pysam on non-indexed vcfs 

### ISSUE THREAD

**Issue by zhemingfan** [pysam-developers/pysam#1023]
Hi pysam developers,

The examples on the documentation show that running something like: 

```
     for read in vcf_file.fetch("chr1", 10000, 20000):
            output_vcf.write(read)
```
would work given that the file is a vcf or bcf. I've been getting an error that 
I've noticed that I've been getting a `ValueError: fetch requires an index` error upon running it on a vcf. This was resolved after running `bgzip` and `tabix` on the VCF.  I was wondering if this was intended behaviour.

**Comment by jmarshall** [comment]
This is the expected behaviour. As the error message says, `fetch` requires an index. And indexing a VCF file (currently, though not in principle) requires it to be bgzipped first.

**Comment by zhemingfan** [comment]
Thank you!
