### ISSUE TITLE
RTD hasn't been updated since 0.15

### ISSUE THREAD

**Issue by keiranmraine** [pysam-developers/pysam#1026]
Fixes to documentation have been made but the site is out of date, e.g. #802

**Comment by jmarshall** [comment]
Yes, it's a bit unfortunate.

@AndreasHeger: I have recently created an account on Read The Docs, so if you wanted to add **jmarshall** as a maintainer of the pysam readthedocs project I would be happy to take a look at this. (It might help if I was (temporarily) an administrator of pysam@GitHub too if there are issues with the GH/RTD web hook configuration — if indeed pysam has been using that.)

**Comment by AndreasHeger** [comment]
Hi @jmarshall , thanks, I have added you as a readthedocs maintainer and as a github owner.

**Comment by jmarshall** [comment]
Thanks @AndreasHeger. And I see you have pressed the buttons to build v0.16.0.1 / stable / latest, which largely resolves the issue.

**Comment by jmarshall** [comment]
I have enabled the RTD web hook integration, so **latest** should track new commits to **master**. And I see the **stable** and **v0.17.0** docs have updated for the recent 0.17.0 release, so I think we can consider this resolved now.
