### ISSUE TITLE
Add AArch64 wheel support

### ISSUE THREAD

**Issue by odidev** [pysam-developers/pysam#1029]
Problem summary-

On Linux AArch64 machine, installing pysam via pip tries to build and install from the source code. It takes significant time to install it on the AArch64 user machine also user needs to have the development environment ready to install and use it on his system. Overall, we can speedup the installation time and avoid development environment dependency by release Linux.

Resolution-
`pip install pysam` should be able to download AArch64 wheels from PyPi and install it.

@jmarshall, please let me know your interest, I can help in this.

**Comment by jmarshall** [comment]
Travis has mostly gone away, so we will have to redo wheel production in a different way when the time comes to make the next release — probably using GitHub Actions. So I have closed the PR, but we will certainly want to produce AArch64 builds too and your example of that will be useful when the time comes.

**Comment by AndreasHeger** [comment]
I have been trying to build aarch64 packages, but have not yet found a way to do so via github actions.
Will release. If you have a wheel, happy to upload it to pypi manually.

**Comment by arogozhnikov** [comment]
Not an expert, but could this help you: https://github.com/pypa/cibuildwheel ? Tools claims to be able to build wheels from github actions by using emulation

**Comment by odidev** [comment]
We need to setup the qemu emulation as additional action. Please add below lines to your work flow before building the wheel-

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

If you are interested, I can raise a PR.
