### ISSUE TITLE
AlignedSegment not hashable or comparable?

### ISSUE THREAD

**Issue by timodonnell** [pysam-developers/pysam#103]
I'm new to Cython, so sorry if I'm misunderstanding something here.

AlignedSegment implements comparison in the regular `compare` method, but does not implement a `__cmp__` method (or `__richcmp__`). It also doesn't implement hashing (using only a trivial hash implementation based on the object address):

```
    # Disabled so long as __cmp__ is a special method
    def __hash__(self):
        return _Py_HashPointer(<void *>self)
```

is there a rationale for this? I'd be happy to submit a PR with object comparison and hashing implemented if that makes sense to you.

**Comment by AndreasHeger** [comment]
Hi @timodonnell, many thanks for the suggestions. I haven't really thought about this. I understand testing for equality, but when is an AlignedRead object smaller or larger than another?

I am also not sure about the hashing, what would be the use case? 

Best wishes,
Andreas

**Comment by timodonnell** [comment]
Hey @AndreasHeger , thanks for getting back. Yeah, I'm only interested in equality and hashing. The < comparison can be arbitrary. My need for hashing comes from wanting to have a `set` of `AlignedSegment` objects. In order to do something like this currently, I have to manually key on certain properties of an `AlignedSegment`, e.g. https://github.com/hammerlab/varcode/blob/master/varcode/read_evidence/util.py

At a higher-level, my use case is counting unique reads supporting genomic variants, in the `read_evidence` module of this project: https://github.com/hammerlab/varcode

Hope this makes sense. Let me know if you'd like a PR for this.

Thanks,

Tim

**Comment by AndreasHeger** [comment]
Hi @timodonnell , if you have a suggestion for a good hash function, please let me know. I assume it will need to cover all fields in bam1_t core and data.
Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Hi, I implemented a first attempt. Let us see how it works in practice.
