### ISSUE TITLE
.fetch(ref) doesn't work properly with .csi index

### ISSUE THREAD

**Issue by lpryszcz** [pysam-developers/pysam#1033]
Hi, 

I've spotted wrong output for pysam `.fetch(chr)` when working with .csi indexed BAM files. The .csi files were generated by `samtools merge --write-index`
Interestingly, `.fetch(chr)` works as expected when .bai index is created (and .csi index is removed). 
I've encountered this problem with several other files. So far all cases that I've spotted the problem were generated by `samtools merge` from single input file - maybe this is relevant? But both, `samtools idxstats` and `samtools view -c BAM ref` behave as expected with both, .csi and .bai index. 
Relevant files can be downloaded from [here](https://public-docs.crg.es/enovoa/public/lpryszcz/test/pysam/csi/). 

I'm using Python v3.7.9, the latest release of pysam 0.16.0.1 and samtools v1.11. 

Code to reproduce:
```python
import os, pysam, numpy as np

bam = "RNA345944_snR60.bam"
print(pysam.idxstats(bam))

print("using .csi")
sam = pysam.AlignmentFile(bam)
for ref in sam.references:
    i = 0
    for i, a in enumerate(sam.fetch(reference=ref), 1): pass
    print(ref, i)

print("\nusing .bai")
csi = bam+".csi"
os.rename(csi, csi+".bck")
pysam.index(bam)
sam = pysam.AlignmentFile(bam)
for ref in sam.references:
    i = 0
    for i, a in enumerate(sam.fetch(reference=ref), 1): pass
    print(ref, i)
    
os.rename(csi+".bck", csi)
```

gives
```bash
cc6m_2244_T7_ecorv	2276	0	0
cc6m_2459_T7_ecorv	2492	0	0
cc6m_2595_T7_ecorv	2625	1	0
cc6m_2709_T7_ecorv	2742	0	0
5s	121	0	0
5.8s	158	58	0
18s	1800	946	0
25s	3396	621	0
*	0	0	0

using .csi
cc6m_2244_T7_ecorv 0
cc6m_2459_T7_ecorv 0
cc6m_2595_T7_ecorv 1
cc6m_2709_T7_ecorv 0
5s 0
5.8s 58
18s 0
25s 0

using .bai
cc6m_2244_T7_ecorv 0
cc6m_2459_T7_ecorv 0
cc6m_2595_T7_ecorv 1
cc6m_2709_T7_ecorv 0
5s 0
5.8s 58
18s 946
25s 621
```

**Comment by jmarshall** [comment]
Thanks for the reproducible test case. This produces the correct results for _.csi_ for me with current **master**. I suspect it was a problem with 0.16.0.1's embedded HTSlib 1.10.2, and bisecting pysam confirms that it was fixed by PR #962.
