### ISSUE TITLE
Pip install fails with missing "os/rand.c"

### ISSUE THREAD

**Issue by erikbgithub** [pysam-developers/pysam#1044]
I'm trying to pip install the package on Fedora 34 with Python 3 in a virtualenv.

While building `gcc [...] -o build/temp.linux-x86_64-3.9/htslib/hts_os.o [...]` I run into the following error:
```
    htslib/hts_os.c:30:10: fatal error: os/rand.c: No such file or directory
       30 | #include "os/rand.c"
          |          ^~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
```

I tried to install several packages that I use in my debian stack, where installation worked fine. But neither seems to satisfy this requirement.

```
sudo yum install htslib
sudo yum install htslib-tools
sudo yum install gcc
sudo yum install zlib-devel
sudo yum install ncurses-devel ncurses
sudo yum install Cython
sudo yum install htslib-devel
sudo yum install zlib zlib-static
sudo yum install xz-devel
sudo yum install cryptopp
sudo yum install ncurses-devel ncurses
sudo yum install gsl-devel gsl
sudo yum install perl-devel perl
sudo yum install BEDTools                          <- sadly doesn't exist anymore
sudo yum install libstdc++-devel libstdc++
sudo yum install glibc
sudo yum install bzlib bzlib-devel
sudo yum install gambas3-gb-compress-bzlib2
sudo yum install lbzip2 bzip2 lbzip2-utils
```

**Comment by erikbgithub** [comment]
On my debian 11 systems I install this:

```
sudo apt update
sudo apt upgrade -y
sudo apt install \
  git vim make tmux zip bc pigz rsync\
  apache2-utils \
  sshfs \
  clang gcc autoconf \
  zlib1g zlib1g-dev \
  libbz2-dev libbz2-1.0 \
  liblzma5 liblzma-dev \
  libcurl4 libcurl4-gnutls-dev \
  libcrypto++8 libcrypto++-dev \
  libncurses5-dev libncursesw5-dev \
  libgsl25 libgsl-dev \
  libperl-dev \
  bedtools \
  python3-dev \
  pyvcf \
  python3 \
  default-jre \
  python3-venv \
  python3-pysam \
  python3-pyvcf \
  python3-numpy
```

And there I also manually compile all the libs (htslib, samtools, bcftools, bwa, minimap2, bwa-mem2)

**Comment by jmarshall** [comment]
What version of pysam are you trying to build? This was #645 and is thought to have been fixed from v0.15.2 onwards.

**Comment by erikbgithub** [comment]
Good point! It is actually erroring out on the newest version and then tries the next older version, rinse & repeat, until it fails in a 0.14 package and doesn't continue trying an older version.

If I force him to `pip install pysam==0.16.0.1` then I can see the actual error for the current version:

```
    configure: error: libbzip2 development files not found
```

**Comment by erikbgithub** [comment]
If I interpret #645 correctly, then it is possible to provide these header files in the packaging and I as a user don't have to provide anything on the system by myself anymore? This sounds like luxury! If I can help figure this out, give me some keywords to google. Would be happy to learn about this automation.

**Comment by jmarshall** [comment]
That issue's _os/lzma_stub.h_ is a special case for macOS and LZMA, which is in the uniquely unfortunate position of the OS buggily providing a link-time _liblzma.dylib_ but not header files and having no vendor/distribution-provided way of adding the header files. See the discussion in PR samtools/htslib#628 which added it.

The `libbzip2 development files not found` error is the clue you need. On your Debian machines you have `libbz2-dev libbz2-1.0` but on your Fedora machine you have

```
sudo yum install lbzip2 bzip2 lbzip2-utils
```

You are missing `bzip2-devel`.

**Comment by erikbgithub** [comment]
Needed `bzip2-devel` and `python3-devel`. Then it worked!

```
$ pip freeze
pysam==0.16.0.1
```

Awesome, thanks John!

**Comment by marcelm** [comment]
This problem should actually be solved by providing pysam wheels (pre-compiled binaries) for Python 3.9. At the moment, only wheels for Python 2.7/3.5/3.6/7/8 [are available](https://pypi.org/project/pysam/#files). On those Python versions, `pip install pysam` will do no compilation at all, no need for any development headers or compilers.

(Python 3.9 was released after the current pysam version, so it’s no suprise that Python 3.9 wheels are missing, but still.)
