### ISSUE TITLE
record.get_aligned_pairs returning longer index than present in the read's sequence

### ISSUE THREAD

**Issue by aleighbrown** [pysam-developers/pysam#1056]
I'm using trying to use the MD tag to get specific mutation types in a read

```
mdSeq = record.get_aligned_pairs(matches_only=True, with_seq=True)
readSeq = record.query_alignment_sequence
```

For each mismatch to get what the mutation was (from A > G for example) I take all the MD strings where the 3rd position in the tuple is lower case and then index using the first value in the tuple into the query alignment

It worked on a minimal test set, however is causing issues which there is soft clipping on the strings

```
Start of problems
cigar string is 18S82M
output of query_alignment_sequence: AAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCACCCCAGCTGTGTGGC
this output is 82 characters
this is the position causing problems:
(84, 14521, 'g')
```

```
print(pysam.__version__)
0.15.3
```

**Comment by HRtech-lab** [comment]
Hello
The output is correct as there is 82M in the cigar string and 18S is the soft clipping in this case. What are expecting in your output? Didn't understand your question though.

**Comment by jmarshall** [comment]
`query_alignment_sequence()` is documented as returning the remaining sequence after omitting (soft-)clipped bases. Thus in your example, as it is preceded by 18 soft-clipped bases as @HRtech-lab said, the output you showed is likely as expected.

The first item in the returned tuple is more easily interpreted as the offset into the complete read sequence as returned by `query_sequence`.
