### ISSUE TITLE
lack of pysam.mpileup() docs

### ISSUE THREAD

**Issue by nick-youngblut** [pysam-developers/pysam#1059]
The FAQ states:

```
Why is there no SNPCaller class anymore?
SNP calling is highly complex and heavily parameterized. There was a danger that the pysam implementations might show different behaviour from the samtools implementation, which would have caused a lot of confusion.

The best way to use samtools SNP calling from python is to use the pysam.mpileup() command and parse the output directly.
```

...but there is almost no documentation on `pysam.mpileup()` that I could find at https://pysam.readthedocs.io/en/latest/index.html, and no documentation on actually implementing SNP calling via `pysam.mpileup()`.

**Comment by xguse** [comment]
this is not my area of expertise, but I think that the `pysam.mpileup` just calls the underlying `samtools mpileup` from inside python. I think at that point you are just dealing with `samtools mpileup` options and output yourself.

Devs will correct me if I am wrong I am sure.

**Comment by sbslee** [comment]
If you are looking for a way to call SNVs and indels using just `pysam`, I've just started implementing such pipeline under my `fuc` [package](https://github.com/sbslee/fuc). Check out the [API](https://sbslee-fuc.readthedocs.io/en/0.31.0-dev/api.html#fuc.api.pyvcf.call) and [CLI](https://sbslee-fuc.readthedocs.io/en/0.31.0-dev/cli.html#vcf-call) so you don't need to reinvent the wheel!

**Comment by jmarshall** [comment]
@xguse is correct. The relevant (brief) documentation is “[Using samtools commands within python](https://pysam.readthedocs.io/en/latest/usage.html#using-samtools-commands-within-python)”.
