### ISSUE TITLE
get_index_statistics on cram gives 0 mapped and total reads

### ISSUE THREAD

**Issue by isthisthat** [pysam-developers/pysam#1060]
Steps to reproduce:

    from pysam import AlignmentFile
    bamFile = AlignmentFile("a.cram", mode="rc", reference_filename="hg38.fa")
    bamFile.get_index_statistics()

The output I get is:

    [IndexStats(contig='chr1', mapped=0, unmapped=0, total=0),
     IndexStats(contig='chr2, mapped=0, unmapped=0, total=0),
     ...
    ]

I've tested a few crams and gotten the same behaviour.
`samtools idxstats a.cram`, as well as `pysam.idxstats("a.cram")` give non-zero counts.

tested on pysam 0.16.0.1 and 0.17.0
samtools 1.13

**Comment by jmarshall** [comment]
CRAM indexes do not contain this information. `idxstats` [scans the entire CRAM file](https://www.htslib.org/doc/samtools-idxstats.html) to simulate it:

> If run on a […] CRAM file […], this command will still produce the same summary statistics, but does so by reading through the entire file. This is far slower than using the BAM indices.

**Comment by isthisthat** [comment]
Thanks for the explanation! I did not realise because I was testing on a small file.
