### ISSUE TITLE
Pip install issue in documentation

### ISSUE THREAD

**Issue by williamhobbs** [pysam-developers/pysam#1069]
It seems that installation from pypi requires `pip install nrel-pysam`, not `pip install pysam` as is shown in the documentation:

https://github.com/pysam-developers/pysam/blob/master/doc/installation.rst

https://pysam.readthedocs.io/en/latest/installation.html#installation-from-repository

**Comment by jmarshall** [comment]
The package in this repository is about genomics. You are presumably looking for <https://github.com/NREL/pysam>, which is an unrelated package in a [different field of endeavour](https://nrel-pysam.readthedocs.io/en/master/):

> NREL-PySAM is a wrapper for the National Renewable Energy Laboratory’s System Advisor Model (SAM), a simulator for renewable energy, not to be confused with pysam, which is for reading sequence alignment files often used in genetics.

**Comment by williamhobbs** [comment]
Oh, goodness. That's embarrassing. No wonder I couldn't get it to install properly...

**Comment by jmarshall** [comment]
Heh :smile: — no harm done. It's lucky I had come across the coincidence of NREL also having a package named PySAM before, or it would have taken us rather longer to figure out what the confusion here was!

We should probably add a “not to be confused with NREL-PySAM” note and link to our introduction too. You are the first renewable energy engineer to have inadvertently found us instead (or the first we have heard from, at least)…

**Comment by williamhobbs** [comment]
Yeah, I could see how my issue/comment could have been confusing. 

At least one other person has made the same mistake as me, https://sam.nrel.gov/forum/forum-sdk/3256-unable-to-install-pysam-on-windows-10.html, which makes me feel a little better.
