### ISSUE TITLE
Bug on bases qualities with pileup

### ISSUE THREAD

**Issue by fescudie** [pysam-developers/pysam#1075]
Hello,

The pileup method returns pileupreads that contain incorrect bases qualities (0) for some reads when calling pileupread.alignment.query_qualities (see example below in "step to reproduce").
This bug was introduced in release 0.14.0 and it triggers the loss of some reads due to the filter on min_base_quality in pileup method.

I haven't identified why some reads are affected and not others.

Do you have a fix for this problem ?

Thanks in advance

# Step to reproduce

## Test data:
    [user@login debug_pysam]$ samtools view test.bam | grep "M03389:94:000000000-AM973:1:1103:15395:9878"
    M03389:94:000000000-AM973:1:1103:15395:9878     99      14      68252785        60      202M    =       68252785        202     CTAATGTTCCAAGTCCAGGAGAAGAAAAGAGAAAAAAGCAACTCACCTGATTTGGTTTGACTGGCTGACATAAGCAGATAATTGAGACTCTTACTGATTTGCTGAAGAACAACTGGAAAACCTCGAATGCCATCAGCATTTAGGAGTACGTGGTCTATCCGTCGACCTGGAAATAGATGAAGGAAGAGGGAATGCAAAAAAA      CCCEDFFFFFFFGGGGGGGGGGHHHHHHHGHHHHHHGGHHHHHHHHHHHHHHHHHGHHGHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHGGHHHHHHHHHHGHHHHHHHGHHHHGHHGHHHHHHHGGHGGGGGHHHHHHHHHHHHHHHHHHHHHGGHHHHHHHHHGG  MC:Z:202M       MD:Z:202        PG:Z:MarkDuplicates     RG:Z:1  NM:i:0  AS:i:202   XS:i:21
    M03389:94:000000000-AM973:1:1103:15395:9878     147     14      68252785        60      202M    =       68252785        -202    CTAATGTTCCAAGTCCAGGAGAAGAAAAGAGAAAAAAGCAACTCACCTGATTTGGTTTGACTGGCTGACATAAGCAGATAATTGAGACTCTTACTGATTTGCTGAAGAACAACTGGAAAACCTCGAATGCCATCAGCATTTAGGAGTACGTGGTCTATCCGTCGACCTGGAAATAGATGAAGGAAGAGGGAATGCAAAAAAA      GHHHHFFFHHHHFHGHHHHHHHHHHHHHHHHGHHHHHHHHHHHHDHHHHHHHHGHHHHHHHHHHFGHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHGHHGGHHHHHHHHHHHHHHHHHHFHHHHHHHHGHHHGHHGGGGGGGGHHHHHHHHHHHGHHHHHGGGGGGGGGGFFFFCCDDDDDC  MC:Z:202M       MD:Z:202        PG:Z:MarkDuplicates     RG:Z:1  NM:i:0  AS:i:202   XS:i:22

## Test code

	#!/usr/bin/env python3
	import pysam

	# Init test data
	aln_file = "test.bam"
	chrom = "14"
	start = 68252978
	end = 68252980
	max_depth = 999999999

	# Process test
	with pysam.AlignmentFile(aln_file, "rb") as SAM_reader:
		for pileupcolumn in SAM_reader.pileup(chrom, start, end, max_depth=max_depth, min_base_quality=0):
			for pileupread in pileupcolumn.pileups:
				read_id = pileupread.alignment.query_name + "_r" + ("2" if pileupread.alignment.is_read2 else "1")
				if read_id == "M03389:94:000000000-AM973:1:1103:15395:9878_r2":
					print(
						read_id,
						pileupread.alignment.cigartuples,
						pileupread.alignment.query_qualities
					)

### pysam 0.13.0

    (pysam_0.13.0) [user@login debug_pysam]$ ./test.py
    M03389:94:000000000-AM973:1:1103:15395:9878_r2 ([(0, 202)], array('B', [38, 39, 39, 39, 39, 37, 37, 37, 39, 39, 39, 39, 37, 39, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 35, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 37, 38, 39, 39, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 37, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 38, 39, 39, 38, 38, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 39, 39, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37, 37, 37, 37, 34, 34, 35, 35, 35, 35, 35, 34]))

=> No problem on qualities.

### pysam 0.14.0

    (pysam_0.14.0) [user@login debug_pysam]$ ./test.py
    M03389:94:000000000-AM973:1:1103:15395:9878_r2 ([(0, 202)], array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

=> **Problem**: the qualities should not be 0.

### pysam 0.18.0

    (pysam_0.18.0) [user@login debug_pysam]$ ./test.py
    M03389:94:000000000-AM973:1:1103:15395:9878_r2 ([(0, 202)], array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

=> **Problem**: the qualities should not be 0.

**Comment by jmarshall** [comment]
These two reads are a pair with exactly the same POS and length, so they overlap exactly. By default, pysam's pileup uses HTSlib's overlapping reads detection:

https://github.com/samtools/htslib/blob/4289991d9c37981d6ef1c1436ec6e791d9993437/htslib/sam.h#L2029-L2042

Use [`SAM_reader.pileup(…, ignore_overlaps=False)`](https://pysam.readthedocs.io/en/latest/api.html?highlight=ignore_overlaps#pysam.AlignmentFile.pileup) to have the raw qualities returned unadjusted.
