### ISSUE TITLE
AlignnedSegment with pos but aend is None

### ISSUE THREAD

**Issue by dylkot** [pysam-developers/pysam#108]
I'm wondering why it could be the case where a read (pysam.calignmentfile.AlignedSegment) could have a valid pos attributed but have aend = None. Printing the first such offending read in my file gives this:

080829_SOLEXA-1GA-2_0003_FC30DJG:4:28:1424:1782	20	16	81165607	37	16M1I11M	-1	-1	28	GTGTGGTGGGTGGGTGATGGGTGTGGTA	array('B', [19, 5, 7, 23, 40, 12, 14, 40, 39, 23, 3, 4, 7, 2, 18, 15, 2, 4, 2, 10, 40, 4, 25, 5, 14, 11, 9, 40])	[('XT', 'U'), ('NM', 2), ('XN', 1), ('X0', 1), ('X1', 0), ('XM', 1), ('XO', 1), ('XG', 1), ('MD', '8T18')]

read.pos correctly gives 81165607 but read.aend is None. Is this a bug?

**Comment by AndreasHeger** [comment]
Thanks. None is returned because the read is marked as unmapped (flag=20). I am not exactly sure why I added this test - I guess it made sense at the time. I will remove it.

Best wishes,
Andreas

**Comment by dylkot** [comment]
Thanks for the response and clarification. Best, Dylan

**Comment by AndreasHeger** [comment]
Hi, there is a test within i for unmapped reads. In the case where a read is unmapped or there is no cigar alignment, the returned aend is pos + 1. I wil keep the None in pysam for now, added some text to the documentation.

Best, Andreas
