### ISSUE TITLE
mentioning wheel in pypi install docs

### ISSUE THREAD

**Issue by aiqc** [pysam-developers/pysam#1086]
It would be helpful to mention that `wheel` is required for the non-legacy install w pypi:
https://pysam.readthedocs.io/en/latest/installation.html#pypi-installation

---

Here is an install attempt on a fresh venv with/ without wheel:

![image](https://user-images.githubusercontent.com/74990642/157480260-ea4c827f-1a50-4c4e-94a7-fadd1ef400b1.png)

^ let it run for ~3min then killed it

---

*Recreated venv, installed wheel, and retried:*

![image](https://user-images.githubusercontent.com/74990642/157480332-7244dc80-a302-4426-a109-2a5cf92dbb1a.png)

**Comment by FionaMoon** [comment]
Hi,
I also met this problem when I try to install pysam.
When I try to install pysam directly by `pip install pysam`:

``` note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pysam

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
I'll try to install wheel as you say to see whether this problem can be solved.
Thank you!

**Comment by pettyalex** [comment]
One way to fix this would be to move to `pyproject.toml`, which allows projects to specify that they need wheel at install time: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

**Comment by jmarshall** [comment]
I think typically `wheel` will already be installed, and in any case the O.P.'s Installation would likely have eventually succeeded in building from source if he had let it continue. Anyway, I've added a note about wheels vs sdists.

We do now use a _pyproject.toml_ file, but I expect once pip has downloaded the sdist to see it, it will be committed to building from the sdist and will not go back to try a wheel instead. So updating the documentation now that wheels are commonplace suffices.
