### ISSUE TITLE
Non-compliance with BAM specification regarding missing QUAL

### ISSUE THREAD

**Issue by divonlan** [pysam-developers/pysam#1089]
I am the author the www.genozip.com. I encountered a BAM file that appears to have been produced by pysam. This BAM has no quality values (i.e. QUAL="*"). The BAM specification (https://samtools.github.io/hts-specs/SAMv1.pdf section 4.2.3) mandates that a "missing quality" QUAL field in BAM be filled with 0xff, however this file has 0xff in the first byte, followed by 0x00. This non-compliance breaks Genozip (and perhaps other tools).  I will add a "feature" to Genozip to support this QUAL representation as well, but you might want to consider fixing pysam too.

**Comment by jmarshall** [comment]
That is somewhat unfortunate, but eminently fixable (in `AlignedSegment.query_qualities.__set__()` etc).

When reading BAM, both htslib and htsjdk determine missing QUAL by checking only the first byte for 0xff. So this is unlikely to affect any other tools.

**Comment by jmarshall** [comment]
Note BTW that the first text mentioning that QUAL in BAM should be “a sequence of 0xFF if absent” was added in November 2010, eight months after this code was written. At the time the code was written, the spec of the day ambiguously merely said “QUAL — Phred base quality (0xFF if absent)”.
