### ISSUE TITLE
Package unavailable via conda

### ISSUE THREAD

**Issue by MMAThijssen** [pysam-developers/pysam#1094]
Yesterday I installed the package pysam without any problems. Today I want to install the package on another machine, but keep getting back 'nothing provides requested pysam' when I try to install with conda. The used command was `mamba install -c bioconda pysam` and `conda install -c bioconda pysam`. Any ideas on what is causing this?

**Comment by KamranAbbaszadeIbrahim** [comment]
The same issue observed for me. Did exactly the same commands, also few more, but the same issue, could not find package pysam.

**Comment by AndreasHeger** [comment]
Hi, thanks for reporting. It seems to work form me. I used this command:
```
conda create -n test-pysam -c bioconda pysam
```
Could you please retry? Maybe it was a transient glitch?
If the issue persists, can you please provide more information about your environment and log messages received?

**Comment by MMAThijssen** [comment]
Thank you for replying. I decided to use an alternative as I had to find an immediate solution.
