### ISSUE TITLE
pysam.faidx() writes to stdout in a uwsgi environment

### ISSUE THREAD

**Issue by eblume** [pysam-developers/pysam#110]
I'm trying to use `pysam.faidx(fasta_file, sequence_id)` in a web application written in Flask. In development we are using Flask's built in web server (I believe it is a single-threaded werkzeug server). This works just fine.

However when we move to production we are hosting the app through uWSGI, and the behavior becomes quite bizarre - the function call returns either None or an empty string (sorry, I don't remember which and can't find it right now - let me know if you need it). Additionally, the sequence that *should* have been returned is instead printed to stdout.

I'm sure this has to do with how uwsgi handles stdout, but I'm hoping you might be able to shed some light on how to fix this issue. I saw in the SamtoolsDispatcher class that there is an argument called 'catch_stdout', might this be related? I wasn't sure how to specify that argument in the `faidx` call.

**Comment by AndreasHeger** [comment]
Thanks. Currently passing the catch_stdout parameter to the Samtools dispatcher is not possbible - will change this!

**Comment by AndreasHeger** [comment]
closed by 2acfcf02b1a9ad2ac55183ca3211d749b7e6eea4
