### ISSUE TITLE
feat: a faster way to add samples to a VCF

### ISSUE THREAD

**Issue by aryarm** [pysam-developers/pysam#1104]
Thanks for making `pysam`! It's such a useful library!

## My use case
I'm trying to create a VCF of 400,000 samples (and just a few variants) from python. But unfortunately, the operation appears to take a very long time.

## The issue
The first culprit appears to be `VariantHeader.add_sample()`, which does not appear to be linear.
Consider the following python snippet:
```python
from pysam import VariantHeader
vh = VariantHeader()
for i in range(num_samples):
    vh.add_sample(f"sample{i}")
```
Running this snippet under various values of `num_samples` results in the following.
![image](https://user-images.githubusercontent.com/23412689/169433331-33893fae-5e32-43d7-8300-abb3418a1bb1.png)
Extrapolating for 400,000 samples: it would probably take me ~13 hrs to run this snippet.

## A hypothesis
I'm guessing [this realloc()](https://github.com/pysam-developers/pysam/blob/be6bc7b445d5ff8ecce217143ecc7e8dd9ceee13/htslib/vcf.c#L116) is [making a new copy](https://en.cppreference.com/w/c/memory/realloc) of the list of samples every time `add_sample()` is called?

## My feature request
Can there be a way to add multiple samples at once, instead of adding them one at a time? Or could there be an option to declare the number of samples when initializing the VariantHeader object, so that the memory can be preallocated?

Apologies if there already is a way of doing this that I'm just unfamiliar with!

## Potential workarounds
One idea is to use [`pgenlib`](https://github.com/chrchang/plink-ng/tree/master/2.0/Python) to create a PLINK2 PSAM (and PGEN + PVAR) file and then use the `plink` command-line utility to convert it to VCF.

Another idea is to create an empty VCF with just a header consisting of a few samples via `pysam`, append the rest of the samples to the file via python's `open('file.vcf', 'a').write()`, and then read the VariantHeader from the file back again using `pysam` or another library.

I've tested neither of these ideas so far, though.

**Comment by jmarshall** [comment]
While reallocing every time is not ideal, I suspect the real cause of this slowness is that `add_sample()` does a `bcf_hdr_sync()` (itself an O(N) operation) for every sample added, leading to O(N<sup>2</sup>) behaviour:

https://github.com/pysam-developers/pysam/blob/040ce8b5ad68de1cc291eaed94e121a41e13f254/pysam/libcbcf.pyx#L2182-L2188

PR #1105 adds a new function that can add multiple samples at once, only calling `bcf_hdr_sync()` once afterwards. This is the same approach that bcftools takes when reading a VCF file (see `bcf_hdr_parse_sample_line()` and the code calling it in HTSlib's _vcf.c_). This would enable you to write the example code as e.g.:

```python
from pysam import VariantHeader
vh = VariantHeader()
vh.add_samples(f"sample{I}" for i in range(num_samples))
```

Or just build up a list and use it as the argument to `add_samples()`.

**Comment by aryarm** [comment]
Thank you so much, @jmarshall! This will make it much easier for me to work with the large number of samples I have.

And thanks for taking the time to explain the cost of `bcf_hdr_sync()`. I wouldn't have thought of that.

I also like that `add_samples()` can take either an iterable or an arbitrary number of parameters. Very slick!
