### ISSUE TITLE
template_length attribute

### ISSUE THREAD

**Issue by joshfactorial** [pysam-developers/pysam#1106]
This may not be an error, but rather a misunderstanding. I am parsing a bam file, and for example there is this record:

`D00360:77:H2YHWBCXX:2:2216:15494:44967	99	chr1	18559	40	250M	=	19071	762	AGGGTCGAGGAGTTGACGGTGCTGAGTTCCCTGCACTCTCAGTAGGGACAGGCCCTATGCTGCCACCTGTACATGCTATCTGAAGGACAGCCTCCAGGGCACACAGAGGATGGTATTTACACATGCACACATGGCTACTGATGGGGCAAGCACTTCACAACCCCCCATGATCACGTGCAGCAGACAATGTGGCCTCTGCAGAGGGGGAACGGAGACCGGAGGCTGAGACTGGCAAGGCTGGACCTGAGTG	ADCDDIIIIIIHGHHFHIHHHHIIFHIIIIIHHIGHHHHHHHHHIHGHIIIIIIIIHIHIHIIHHIHIHIHIIIIIH?FHHGIIGHH?CGHIIIIHFHIIIDFHHIIIIEHIIGHHGHIIIIHGGHGHIIHH@ECHHGHI?HHHGHIIHIIIIHIIIHHHIIIHHIICHHIHGHHEHIEHI@HHHHHHFHIGHIHHHHIIH.EEHDH-6BHCHICH@HHC?HEBE-B?66FC@-@@EB-8C@H?6--@F-	NM:i:1	MD:Z:164T85	MC:Z:250M	AS:i:245	XS:i:245	RG:Z:Trio_lane2-41755AAC`

In my python script, I have:

`file_to_parse = pysam.AlignmentFile(bam_file, check_sq=False)`

and 

```
for item in file_to_parse:
     my_tlen = abs(item.template_length)
```

which gives a value of 0.

I do not understand how it is not 762. Can someone clarify the meaning of this attribute, or how it is calculated? Thank you.

**Comment by jmarshall** [comment]
The `template_length` property does indeed literally represent the field from the SAM/BAM/CRAM file that you are expecting. In attempting to reproduce this, I get the expected 762.

You would have to attach a complete script and data file exhibiting the problem for us to help you figure out what's happening here.

**Comment by joshfactorial** [comment]
What I determined for this sample was that I had my code slightly wrong. I changed it to for item in file_to_parse.fetch() and filtered out unmapped reads, and then I started getting more expected results.
