### ISSUE TITLE
Create a new release with htslib 1.15.1

### ISSUE THREAD

**Issue by magicmaaaaan** [pysam-developers/pysam#1107]
Hi all,

Are there any plans to release a pysam 0.19.1 with htslib 1.15.1? I see that this was imported about four weeks ago in https://github.com/pysam-developers/pysam/commit/be6bc7b445d5ff8ecce217143ecc7e8dd9ceee13. My institution won't install samtools/htslib 1.15.0 or pysam 0.19.0 because 1.15.1 notes a "security fix" (https://github.com/samtools/htslib/blob/develop/NEWS).

Thanks!

**Comment by AndreasHeger** [comment]
Yes, in the works, was trying to fix other potential security issues #1097 , but giving up.

**Comment by jmarshall** [comment]
Pysam 0.19.1 containing htslib 1.15.1 was released on 27 May 2022.
