### ISSUE TITLE
Read counting

### ISSUE THREAD

**Issue by goranrakocevic** [pysam-developers/pysam#111]
Seems like Samfile().unmapped and Samfile().count are skipping some unmapped reads.
I'm counting reads in a whole genome:
Samfile().count  = 1357176500
Samfile().unmapped = 1962182

However, if I iterate through read by read and look at the flags, I get:
(These numbers also match Picard Alignment Summary metrics)
Total: 1383584070
Unmapped: 28369752
The unmapped reads by flag: 69: 101074, 77: 13203785, 117: 101132, 133: 880353, 141: 13203785, 181: 879623
Thus, it looks like reads with flags 141 and 77 are not taken into account

Any ideas what might cause this? Unfortunately, I can't share the files, but I can look at anything that might be helpful.

**Comment by AndreasHeger** [comment]
Thanks. This is badly explained, but by default the count() method only iterates over mapped reads.
Set "until_eof=True" to also include unmapped reads:
```
total = AlignmentFile('x.bam').count(until_eof=True)
```
Can you confirm that you then get the same number?

The .mapped and .unmapped functions return the number of mapped/unmapped reads according to the statistics within the index file. I am not sure why the counts differ there. 

I have added some text to explain where the numbers come from.

**Comment by goranrakocevic** [comment]
The BAM file was made with Picard Gather BAM files (unaligned reads were in a separate file). Looks like that messes up something in the index...

**Comment by AndreasHeger** [comment]
Thank you. I keep this open until I know of a solution.

**Comment by AndreasHeger** [comment]
@goranrakocevic , I have dug a little deeper, differences in counts might be the way reads are counted that have the unmapped flag, but are nevertheless assigned a position.

I have made it explicit in a test case and added read_callback to count() to control filtering.
However, this might not fully explain your numbers.
