### ISSUE TITLE
 CIGAR length too long

### ISSUE THREAD

**Issue by zou-yawen** [pysam-developers/pysam#1126]
hi;
I meet a problem "CIGAR length too long error",when i use pysam.
![image](https://user-images.githubusercontent.com/72124697/186831536-9dd5fe2e-990e-4fc8-a2fb-03c00a9455ca.png)

**Comment by jmarshall** [comment]
The error message comes from htslib; this is not a pysam issue.

The issue is with your SAM file, line 27 of which includes a CIGAR operation that is too long to be represented in SAM's CIGAR notation.

**Comment by zou-yawen** [comment]
Thank you very much.how can I solve this problem,can you give me some advice
