### ISSUE TITLE
AlignmentFile.pileup should return PileupColumns

### ISSUE THREAD

**Issue by mpcusack-color** [pysam-developers/pysam#1129]
I might be missing something, but it seems like the `AlignmentFile.pileup` function is type annotated to return the wrong types. From the code and documentation they appear to be `PileupColumn`s, but the type hints say they are `AlignedSegment`s.

- `AlignmentFile.pileup` returns a subclass of `IteratorColumn`: https://github.com/pysam-developers/pysam/blob/56b1624c21b02762fdcea3aa5f657a4152ca178e/pysam/libcalignmentfile.pyx#L1351
- `IteratorColumn`s return `PileupColumn` objects: https://github.com/pysam-developers/pysam/blob/56b1624c21b02762fdcea3aa5f657a4152ca178e/pysam/libcalignmentfile.pyx#L2814
- `IteratorColumn`s are annotated to return `AlignedSegment`s: https://github.com/pysam-developers/pysam/blob/56b1624c21b02762fdcea3aa5f657a4152ca178e/pysam/libcalignmentfile.pyi#L204

**Comment by jmarshall** [comment]
I think perhaps the problems are even a bit more than that. e.g.:

* The `makePileupColumn()` call on line 2814 is in fact in `class IteratorColumnAll`, but that's not annotated
* `IteratorColumn`'s `__iter__()` method surely returns an `IteratorColumn`

Would you be interested in auditing these classes' annotations further?
