### ISSUE TITLE
Read group change of type when updating read tags (RG:Z to RG:A)

### ISSUE THREAD

**Issue by andreas-wilm** [pysam-developers/pysam#113]
Hi,

the read group type is automatically and wrongly changed from Z to A, if read tags are updated and if the read group is numeric (in my case 1). This leads to problems with GATK (see https://code.google.com/p/pysam/issues/detail?id=92).

Example code:

    from collections import OrderedDict
    
    import pysam
    
    sam_in = pysam.Samfile("/tmp/rgz-to-rga.bam")
    sam_out = pysam.Samfile("/tmp/rgz-to-rga.out.bam", "wb", template=sam_in)
    for r in sam_in:
        tags = OrderedDict(r.tags)
        # pseudo operation on tags
        tags['BD'], tags['BI'] = tags['BI'], tags['BD']
        r.tags = tags.items()
        sam_out.write(r)
    sam_in.close()
    sam_out.close()
    
    samtools view /tmp/rgz-to-rga.out.bam | grep -o 'RG:.:.'
    # RG:A:1
    samtools view /tmp/rgz-to-rga.bam | grep -o 'RG:.:.'
    RG:Z:1

Input file rgz-to-rga.bam (1.4kB) is available here: https://dl.dropboxusercontent.com/u/4119940/rgz-to-rga.bam. All it takes is a file with RG ID:1 in the header (which is default for Picard's  AddOrReplaceReadGroups)

I've tried pysam 0.7.7 and 0.8.2.

Andreas

**Comment by AndreasHeger** [comment]
Hi @andreas-wilm , have you tried the set_tag or set_tags methods? They permit specification of the tag type instead of auto-detection.

Best, Andreas

**Comment by andreas-wilm** [comment]
Hi @AndreasHeger,

set_tag() works fine!

Andreas
