### ISSUE TITLE
Mac ARM64 wheels are not available

### ISSUE THREAD

**Issue by pettyalex** [pysam-developers/pysam#1135]
Hello,

I noticed while installing a tool that depends on pysam that wheels are not available for any of the Apple Silicon post-2020 macs. The specific triple of my machine is `arm64-apple-darwin21.6.0`. 

It would be great to have those wheels aviailable.

**Comment by hermanzhaozzzz** [comment]
I have met the same trouble. please have a check.

**Comment by antomicblitz** [comment]
Same :(. Actually I am having an issue installing Galaxy on an M1 mac and this is one of the dependencies (of a few) which doesn't seem to work yet.

**Comment by ryandward** [comment]
Same. I'd love to see this working.

**Comment by jmarshall** [comment]
ARM macOS wheels have been built for the 0.22.0 release.
