### ISSUE TITLE
fails on import in m1 MacBook

### ISSUE THREAD

**Issue by explodecomputer** [pysam-developers/pysam#1149]
I can't seem to import pysam after it appears to install successfully.

```
$ python -m vent testenv 

$ . testenv/bin/activate

$  pip install --upgrade pip
Requirement already satisfied: pip in ./testenv/lib/python3.10/site-packages (22.2.2)
Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3.1

$ pip install pysam 
Collecting pysam
  Using cached pysam-0.20.0.tar.gz (4.0 MB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pysam, since package 'wheel' is not installed.
Installing collected packages: pysam
  Running setup.py install for pysam ... done
Successfully installed pysam-0.20.0
```

```
$ python
Python 3.10.7 (v3.10.7:6cc6b13308, Sep  5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gh13047/testenv/lib/python3.10/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(/Users/gh13047/testenv/lib/python3.10/site-packages/pysam/libchtslib.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_rans_compress_O0_32x16_neon)
```

This is only in M1 MacBook, I'm able to install it fine on a linux server with intel processor

**Comment by jarbesfeld** [comment]
I too am experiencing the same issue with the M1 MacBook.

**Comment by shimbalama** [comment]
Same

**Comment by sanghoonio** [comment]
Same issue with M1 MBP

**Comment by tburcham-alidabio** [comment]
Exactly the same problem on a new M2 Max MacBook using both the xcode installed python 3.9 and an installed version of python3.10.10. Our older (~6 months to a 1 year) MacBook Pro (M1 Pro) running python 3.10.10 got the import to work with no issues, so not quite sure what has changed...

**Comment by jmarshall** [comment]
Please post the output from

```
pip uninstall pysam
pip install -v pysam
```

i.e., run the pip installation again with `-v` added.

**Comment by tburcham-alidabio** [comment]
I will do that in the next post to re-create the problem
HOWEVER -- I got it to install using pip 23.0.1 (python3.10.10) on a new MacBook M2 Pro by installing the previous version. 
That is: 
pip3 install pysam==0.19.1

**Comment by jmarshall** [comment]
It's unsurprising that 0.19.1 works, because that older version does not contain the SIMD-optimised versions of the rANS codec code that are causing this problem.

Thanks, that install log shows the issue:

```
# pysam: (sysconfig) CFLAGS=-Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g
# pysam: (sysconfig) LDFLAGS=-arch arm64 -arch x86_64 -g
[…]
checking whether C compiler accepts -mssse3 -mpopcnt -msse4.1... no
checking whether C compiler accepts -mavx2... no
checking whether C compiler accepts -mavx512f... no
checking whether C compiler supports ARM Neon... no
```

You would expect that the x86_64 compiler would accept `-mavx2` et al and that the arm64 compiler would support Neon. Probably they do, but because `CFLAGS` specifies a multi-arch build, the test compiles for the opposite architecture are failing hence leading to `no` overall.

Can you also show _…/htslib/config.log_ within the pysam build directory? You may have to rerun the build again with `pip install --no-clean -v pysam`.

**Comment by tburcham-alidabio** [comment]
Here you go...
[config.log](https://github.com/pysam-developers/pysam/files/10807854/config.log)

**Comment by jmarshall** [comment]
Thanks, that _config.log_ confirms my theory about why it's saying `no` overall.

There are ways to fix this, but the problem is in htslib and/or htscodecs so I have raised this as samtools/htscodecs#76 to get those projects' maintainers' views on how best to address this problem.

**Comment by jmarshall** [comment]
Please try applying PR #1173 and see if this addresses the problem. (For now, you would have to build from the Git repo rather than via `pip`.)
