### ISSUE TITLE
external samtools/bcftools?

### ISSUE THREAD

**Issue by luke-dt** [pysam-developers/pysam#1150]
Is it possible to use external samtools/bcftools instead of the bundled versions? I use a [package manager called spack](https://github.com/spack/spack) in my centers cluster, which is designed to be flexible for multiple architectures, OSes, and build systems. I'm trying to update the pysam package, but the preferred function would be to use external, spack-installed dependencies, as it allows spack to inject compiler flags, add patches for specific OSes/compilers, and patch security vulnerabilities.

I can link against external htslib, but didn't know if there was something analogous for samtools and bcftools.

**Comment by jmarshall** [comment]
If it was practical, then pysam would provide functionality for doing so as it does for htslib.

For obvious reasons, samtools and bcftools do not provide a public API in the same way that htslib does. Instead pysam reaches into samtools and bcftools directly, so it is not possible to use external samtools or bcftools.

**Comment by jmarshall** [comment]
From the linked spack PR:

> For example, our bcftools package contains a number of patches that likely aren't in pysam.

All of those patches are for prehistoric versions of bcftools. They are all either not applicable to pysam or long-since fixed in pysam's imported bcftools code or both.
