### ISSUE TITLE
pysam vcf record 

### ISSUE THREAD

**Issue by tanyasarkjain** [pysam-developers/pysam#1167]
I am iterating through records of a variantfile, and trying to access VariantRecordSamples. The object exists (can access record.sample) however the length of this object is 0, and i am unsure how to access the sample data, the documentation on VariantRecordSamples appears to be missing. Is there another way I can see the dosage matrix for a particular snv?

**Comment by BuysDB** [comment]
You can verify what samples are read from the file using:
```
with pysam.VariantFile("myvcf.vcf") as v:
    print( list( v.header.samples ) )
```

And by dosage matrix I guess you mean reading the allelic depth (AD)?
```
for sample_name, sample_data in record.samples.items():
    print(sample_name, sample_data['AD'] )
```
If you need the matching alleles to the depths:
```
dict(zip(record.alleles, sample_data['AD'] ))
```

**Comment by AndreasHeger** [comment]
Thanks, @BuysDB for responding!

**Comment by AndreasHeger** [comment]
Closing for now.
