### ISSUE TITLE
with_value_type option not implemented in get_tags(self, with_value_type=False)

### ISSUE THREAD

**Issue by shenwei356** [pysam-developers/pysam#119]
Hi,

Although the doc included this, but the *with_value_type* option was not implemented in **get_tags(self, with_value_type=False)**.

link: https://github.com/pysam-developers/pysam/blob/master/pysam/calignmentfile.pyx#L3485

**Comment by AndreasHeger** [comment]
Thanks. I missed your issue and filed an issue separately, please see #133 
Best wishes,
Andreas
