### ISSUE TITLE
pysam requires openssl 1.1.1t-1.1.2a but that is ancient

### ISSUE THREAD

**Issue by aldertzomer** [pysam-developers/pysam#1190]
pysam requires openssl 1.1.1t-1.1.2a , but that version is ancient, it is the long term support version but it will end in a few months.

(base) [azomer@AWSBNDIRLL0006 recipe]$ cat meta.yaml |grep openssl
    - openssl 1.1.1t h0b41bf4_0
    - openssl >=1.1.1t,<1.1.2a

**Comment by jmarshall** [comment]
That is a bioconda issue that has nothing to do with pysam. See bioconda/bioconda-recipes#39356.
