### ISSUE TITLE
Issue installing pysam from bioconda with python 3.11

### ISSUE THREAD

**Issue by fgvieira** [pysam-developers/pysam#1191]
Has `pysam` been updated on `bioconda`? I am trying to install it on an existing environment that contains `python 3.11.3`, but I am getting:

```
    Encountered problems while solving:
      - package pysam-0.21.0-py39h9abd093_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
    
    The environment can't be solved, aborting the operation
```

**Comment by jmarshall** [comment]
Bioconda does not yet make Python 3.11 builds, which is a bioconda issue that has nothing to do with pysam. See bioconda/bioconda-recipes#37805.
