### ISSUE TITLE
pysam.FastaFile.fetch() does not consist of "0-based coordinates" for the end position

### ISSUE THREAD

**Issue by yhoogstrate** [pysam-developers/pysam#120]
According to the manual, pysam.FastaFile.fetch() "*...consists of reference name (‘chr1’), start (100000), and end (200000). 0-based coordinates*". After an implementation based on this scentence I realized that sequences were too short.

Then I tested the following:

\>>> p = pysam.FastaFile("\<somefastafile>.fa")
\>>> p.fetch("\<some chromosome>",0,0)
''
\>>> p.fetch("\<some chromosome>",0,1)
'G'

This means that only the start is 0-based and the end-position is 1-based (0-based **half open**?). Would it be possible to change the documentation and provide an example to illustrate this?

**Comment by AndreasHeger** [comment]
Thanks, I have updated the documentation.

**Comment by yhoogstrate** [comment]
Great! It is clearly written down at: http://pysam.readthedocs.org/en/latest/glossary.html#term-region

Could you also change it over here: http://pysam.readthedocs.org/en/latest/api.html?highlight=fasta#pysam.FastaFile.fetch

"fetch sequences in a region using 0-based indexing" to "fetch sequences in a region using 0-based, half open indexing."
