### ISSUE TITLE
Can't install via conda on Apple Silicon macOS

### ISSUE THREAD

**Issue by koh2ng0** [pysam-developers/pysam#1206]
Hi,
I tried to install pysam in macOS vi conda, such as `conda install -c bioconda pysam`.
But, It couldn't work with the below error.
<img width="1003" alt="Screenshot 2023-07-26 at 21 03 39" src="https://github.com/pysam-developers/pysam/assets/60956806/2d785f4e-62e7-4660-a00a-1d1263e8cf18">
How can I install pysam in macOS via conda?
My conda information is this.
<img width="1003" alt="Screenshot 2023-07-26 at 21 04 37" src="https://github.com/pysam-developers/pysam/assets/60956806/a3cc02b2-b48d-47e3-9d09-4c8f0af794ce">
Thanks.

**Comment by jmarshall** [comment]
Bioconda does not yet make Apple Silicon builds, which is a bioconda issue that has nothing to do with pysam.
See bioconda/bioconda-utils#706.

**Comment by jmarshall** [comment]
As of today, bioconda supports Apple silicon and pysam has been built for this platform. See https://github.com/bioconda/bioconda-recipes/issues/33333#issuecomment-2221176852.
