### ISSUE TITLE
Improve performance of accessing AlignedSegment.qual

### ISSUE THREAD

**Issue by marcelm** [pysam-developers/pysam#121]
Currently, when accessing the `.qual` attribute of an AlignedSegment, the full sequence of quality values is computed every time. This results in unnecessarily bad performance especially when accessing `read.qual[i]` for more than one i. (See also the report on the mailing list from June 1).

**Comment by AndreasHeger** [comment]
Added caching for the fields `.query_qualities`, `.query_alignment_qualities`, `.query_sequence` and `.query_alignment_sequence`. This should also speed-up access to `.qual`.

A potential problem is that the returned arrays are mutable, but the changes are currently not written to disk. The returned strings don't have that problem.

How I wish I had stayed away from properties and used only getters/setters.

**Comment by marcelm** [comment]
Cool, thanks!
