### ISSUE TITLE
pysam.fetch on S3 Bucket

### ISSUE THREAD

**Issue by StephanHolgerD** [pysam-developers/pysam#1215]
Hi, 
I want to report a potentially problematic behaviour using pysam.fetch on AWS S3 bucket infrastructure.
Using the following pseudo code on a Bam file in a S3 Bucket will create requests without a defined end range.

**Code**

`with pysam.AlignmentFile(bamfile_S3,filepath_index=baifile_S3) as f:`
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`for r in f.fetch(chrom,start,end):`

**Request**

![image](https://github.com/pysam-developers/pysam/assets/28348674/dfb71873-11ab-40c0-a1f2-76a167180616)

This kind of 'open' request results in high egress costs because aws logs the whole file after the start byte as delivered, even if you stop reading the data at the end of your fetch coordinates. 

---

Compared to the requests from IGV on S3 data (low egress costs, only the exact byte range is logged)

**Request**
![image](https://github.com/pysam-developers/pysam/assets/28348674/6002d4cc-e65d-4328-b77d-696f24b1c7fd)

**Comment by jmarshall** [comment]
As the User-Agent header suggests, pysam is simply using the wrapped htslib code to implement S3 access. That htslib code (in _hfile_libcurl.c_) still implements seeks using `CURLOPT_RESUME_FROM_LARGE` rather than `CURLOPT_RANGE`, which would be better placed to Include an ending offset.

Please report this issue to [htslib](https://github.com/samtools/htslib) directly.

**Comment by StephanHolgerD** [comment]
ok, so it makes sense that pysam.view creates clean range requests ? 

I thought pysam uses the same lib like samtools (htslib)

**Comment by jmarshall** [comment]
Pysam (both fetch and view) uses the same library as samtools. This is why you should report this issue to the library where the problem is, namely htslib.

**Comment by StephanHolgerD** [comment]
ok because pysam.view has a clean range request, that's why I was wondering

**Comment by jmarshall** [comment]
Please report this problem to htslib.
