### ISSUE TITLE
Relaxing Python version requirement in Bioconda?

### ISSUE THREAD

**Issue by cmeesters** [pysam-developers/pysam#1221]
Hi,

Installing pysam with conda in an environment with Python version 3.10.12 the attempt to install pysam results in 

```
Could not solve for environment specs
The following packages are incompatible
└─ pysam 0.21**  is installable with the potential options
   ├─ pysam 0.21.0 would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   ├─ pysam 0.21.0 would require
   │  └─ python >=3.6,<3.7.0a0 , which can be installed;
   ├─ pysam 0.21.0 would require
   │  └─ python >=3.7,<3.8.0a0 , which can be installed;
   ├─ pysam 0.21.0 would require
   │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   └─ pysam 0.21.0 would require
      └─ python >=3.9,<3.10.0a0 , which can be installed.
      
```

Any ideas (other than downgrading the environment)? Who maintains the conda build?

**Comment by jmarshall** [comment]
For 3.10.12, you would think it would have picked that first one.

If you actually meant you have Python 3.11.x, this is #1202 as pinned at the top of our issues page.

In any case, please report conda-related issues to [bioconda](https://github.com/bioconda/bioconda-recipes).
