### ISSUE TITLE
InError: Invalid BCF, the FORMAT tag id=91 at chr20:60137 not present in the header

### ISSUE THREAD

**Issue by karinkumar** [pysam-developers/pysam#1222]
Hello I am getting the error: 
Invalid BCF, the FORMAT tag id=91 at chr20:60137 not present in the header

Which does not make sense as I have no FORMAT items named 91. This is the code I am using and I've printed my header below. Could you please point me to what exactly this error is referring to? I tried to add a format line with id=91 but 91 was considered invalid id option.

```
vcf_reader = VariantFile(input_vcf, 'r')
    
vcf_out = VariantFile(output_vcf, 'w', header=vcf_reader.header)


# Define the 'PL' format field
vcf_reader.header.add_meta('FORMAT', items=[('ID',"PL"), ('Number',2), ('Type','String'),
    ('Description','Phred Scaled Likelihood')])

#vcf_reader.header.add_meta('FORMAT', items=[('ID',"91"), ('Number',2), ('Type','String'),
 #   ('Description','Error Fix')])
#print(vcf_reader.header)
for rec in vcf_reader:
    #rec.info['PL'] = []
    dp = rec.info['DP']
    for sample in rec.samples.values():
        #print(sample['PL'])
        sample['PL']  = simulate_DP_PL(sample['GT'], dp, coverage_frac, error)
        #print(sample['PL'])
    # Write the processed variant to the output VCF file
    vcf_out.write(rec)

vcf_reader.close()
vcf_out.close()

```

##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr20>
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AC_AFR,Number=A,Type=Integer,Description="Allele count in genotypes in AFR">
##INFO=<ID=AC_AMR,Number=A,Type=Integer,Description="Allele count in genotypes in AMR">
##INFO=<ID=AC_EAS,Number=A,Type=Integer,Description="Allele count in genotypes in EAS">
##INFO=<ID=AC_EUR,Number=A,Type=Integer,Description="Allele count in genotypes in EUR">
##INFO=<ID=AC_Het,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes">
##INFO=<ID=AC_Het_AFR,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in AFR">
##INFO=<ID=AC_Het_AMR,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in AMR">
##INFO=<ID=AC_Het_EAS,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in EAS">
##INFO=<ID=AC_Het_EUR,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in EUR">
##INFO=<ID=AC_Het_SAS,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in SAS">
##INFO=<ID=AC_Hom,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes">
##INFO=<ID=AC_Hom_AFR,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in AFR">
##INFO=<ID=AC_Hom_AMR,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in AMR">
##INFO=<ID=AC_Hom_EAS,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in EAS">
##INFO=<ID=AC_Hom_EUR,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in EUR">
##INFO=<ID=AC_Hom_SAS,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in SAS">
##INFO=<ID=AC_SAS,Number=A,Type=Integer,Description="Allele count in genotypes in SAS">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AF_AFR,Number=A,Type=Float,Description="Allele frequency in AFR">
##INFO=<ID=AF_AMR,Number=A,Type=Float,Description="Allele frequency in AMR">
##INFO=<ID=AF_EAS,Number=A,Type=Float,Description="Allele frequency in EAS">
##INFO=<ID=AF_EUR,Number=A,Type=Float,Description="Allele frequency in EUR">
##INFO=<ID=AF_SAS,Number=A,Type=Float,Description="Allele frequency in SAS">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AN_AFR,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in AFR">
##INFO=<ID=AN_AMR,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in AMR">
##INFO=<ID=AN_EAS,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in EAS">
##INFO=<ID=AN_EUR,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in EUR">
##INFO=<ID=AN_SAS,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in SAS">
##INFO=<ID=BaseQRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref base qualities">
##INFO=<ID=ClippingRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref number of hard clipped bases">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##INFO=<ID=DS,Number=0,Type=Flag,Description="Were any of the samples downsampled?">
##INFO=<ID=END,Number=1,Type=Integer,Description="Stop position of the interval">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=HWE,Number=A,Type=Float,Description="HWE test (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=HWE_AFR,Number=A,Type=Float,Description="HWE test in AFR (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=HWE_AMR,Number=A,Type=Float,Description="HWE test in AMR (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=HWE_EAS,Number=A,Type=Float,Description="HWE test in EAS (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=HWE_EUR,Number=A,Type=Float,Description="HWE test in EUR (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=HWE_SAS,Number=A,Type=Float,Description="HWE test in SAS (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=HaplotypeScore,Number=1,Type=Float,Description="Consistency of the site with at most two segregating haplotypes">
##INFO=<ID=InbreedingCoeff,Number=1,Type=Float,Description="Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared against the Hardy-Weinberg expectation">
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality">
##INFO=<ID=MQ0,Number=1,Type=Integer,Description="Total Mapping Quality Zero Reads">
##INFO=<ID=MQRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities">
##INFO=<ID=NEGATIVE_TRAIN_SITE,Number=0,Type=Flag,Description="This variant was used to build the negative training set of bad variants">
##INFO=<ID=POSITIVE_TRAIN_SITE,Number=0,Type=Flag,Description="This variant was used to build the positive training set of good variants">
##INFO=<ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth">
##INFO=<ID=RAW_MQ,Number=1,Type=Float,Description="Raw data for RMS Mapping Quality">
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
##INFO=<ID=SOR,Number=1,Type=Float,Description="Symmetric Odds Ratio of 2x2 contingency table to detect strand bias">
##INFO=<ID=VQSLOD,Number=1,Type=Float,Description="Log odds of being a true variant versus being false under the trained gaussian mixture model">
##INFO=<ID=VariantType,Number=1,Type=String,Description="Variant type description">
##INFO=<ID=culprit,Number=1,Type=String,Description="The annotation which was the worst performing in the Gaussian mixture model, likely the reason why the variant was filtered out">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Phased Genotype">
##INFO=<ID=AN_EUR_unrel,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in EUR (2504 unrelated samples)">
##INFO=<ID=AN_EAS_unrel,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in EAS (2504 unrelated samples)">
##INFO=<ID=AN_AMR_unrel,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in AMR (2504 unrelated samples)">
##INFO=<ID=AN_SAS_unrel,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in SAS (2504 unrelated samples)">
##INFO=<ID=AN_AFR_unrel,Number=1,Type=Integer,Description="Total number of alleles in called genotypes in AFR (2504 unrelated samples)">
##INFO=<ID=AC_EUR_unrel,Number=A,Type=Integer,Description="Allele count in genotypes in EUR (2504 unrelated samples)">
##INFO=<ID=AC_EAS_unrel,Number=A,Type=Integer,Description="Allele count in genotypes in EAS (2504 unrelated samples)">
##INFO=<ID=AC_AMR_unrel,Number=A,Type=Integer,Description="Allele count in genotypes in AMR (2504 unrelated samples)">
##INFO=<ID=AC_SAS_unrel,Number=A,Type=Integer,Description="Allele count in genotypes in SAS (2504 unrelated samples)">
##INFO=<ID=AC_AFR_unrel,Number=A,Type=Integer,Description="Allele count in genotypes in AFR (2504 unrelated samples)">
##INFO=<ID=AC_Hom_EUR_unrel,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in EUR (2504 unrelated samples)">
##INFO=<ID=AC_Hom_EAS_unrel,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in EAS (2504 unrelated samples)">
##INFO=<ID=AC_Hom_AMR_unrel,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in AMR (2504 unrelated samples)">
##INFO=<ID=AC_Hom_SAS_unrel,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in SAS (2504 unrelated samples)">
##INFO=<ID=AC_Hom_AFR_unrel,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes in AFR (2504 unrelated samples)">
##INFO=<ID=AC_Het_EUR_unrel,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in EUR (2504 unrelated samples)">
##INFO=<ID=AC_Het_EAS_unrel,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in EAS (2504 unrelated samples)">
##INFO=<ID=AC_Het_AMR_unrel,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in AMR (2504 unrelated samples)">
##INFO=<ID=AC_Het_SAS_unrel,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in SAS (2504 unrelated samples)">
##INFO=<ID=AC_Het_AFR_unrel,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes in AFR (2504 unrelated samples)">
##INFO=<ID=AF_EUR_unrel,Number=A,Type=Float,Description="Allele frequency in EUR (2504 unrelated samples)">
##INFO=<ID=AF_EAS_unrel,Number=A,Type=Float,Description="Allele frequency in EAS (2504 unrelated samples)">
##INFO=<ID=AF_AMR_unrel,Number=A,Type=Float,Description="Allele frequency in AMR (2504 unrelated samples)">
##INFO=<ID=AF_SAS_unrel,Number=A,Type=Float,Description="Allele frequency in SAS (2504 unrelated samples)">
##INFO=<ID=AF_AFR_unrel,Number=A,Type=Float,Description="Allele frequency in AFR (2504 unrelated samples)">
##INFO=<ID=ExcHet_EAS,Number=A,Type=Float,Description="Test excess heterozygosity in EAS; 1=good, 0=bad">
##INFO=<ID=ExcHet_AMR,Number=A,Type=Float,Description="Test excess heterozygosity in AMR; 1=good, 0=bad">
##INFO=<ID=ExcHet_EUR,Number=A,Type=Float,Description="Test excess heterozygosity in EUR; 1=good, 0=bad">
##INFO=<ID=ExcHet_AFR,Number=A,Type=Float,Description="Test excess heterozygosity in AFR; 1=good, 0=bad">
##INFO=<ID=ExcHet_SAS,Number=A,Type=Float,Description="Test excess heterozygosity in SAS; 1=good, 0=bad">
##INFO=<ID=ExcHet,Number=A,Type=Float,Description="Test excess heterozygosity; 1=good, 0=bad">
##bcftools_viewVersion=1.17+htslib-1.17
##bcftools_viewCommand=view -S ../samples.txt --force-samples -Oz -o ../validation/230813ASWvalidation.vcf.gz /net/1000g/hmkang/data/1KG.3202/20201028_3202_phased/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz; Date=Sun Aug 13 21:00:11 2023
##FORMAT=<ID=PL,Number=2,Type=String,Description="Phred Scaled Likelihood">

**Comment by jmarshall** [comment]
The root of the problem is in the record at chr20:60137, so you might need to show us the VCF records at that position too.

**Comment by karinkumar** [comment]
I ended up resolving this issue but writing to a new vcf rather than trying to modify the one I am reading in
