### ISSUE TITLE
Is there a way to sort VCF/BCF, like pysam.sort?

### ISSUE THREAD

**Issue by antonylebechec** [pysam-developers/pysam#1223]
Hi!

I would like to sort a VCF/BCF file, especially before tabix.
However, pysam.sort is exclusively for SAM/BAM.

Is there a way to sort a VCF file with pysam?

Thanks a lot!

Best,

**Comment by jmarshall** [comment]
`pysam.sort()` is really a shorthand for `pysam.samtools.sort()`.

There is also `pysam.bcftools.sort()`, which is what you're looking for. You'll need to add `import pysam.bcftools` too.
