### ISSUE TITLE
Error when compiling pysam from source; Python3.4; CentOS

### ISSUE THREAD

**Issue by shashidhar22** [pysam-developers/pysam#124]
Getting the following error when I try to compile pysam from source on python3.4

gcc: pysam/csamtools.c: No such file or directory

The csamtools.c file is not available in the repository

**Comment by AndreasHeger** [comment]
Thanks, I will need more information to help.

**Comment by dannon** [comment]
When I've seen this, farther up in the log, it's generally due to cython failing to build csamtools.c in the first place.  @shashidhar22 Are you using the latest cython?

**Comment by AndreasHeger** [comment]
Thanks, @dannon, for your help. Closing for now.
