### ISSUE TITLE
Seeking assistance

### ISSUE THREAD

**Issue by liujilei156231** [pysam-developers/pysam#1244]
I possess numerous sorted `BAM` files; however, for my project, I am required to randomly select a subset of reads (1e5) from them. I have explored the option of converting a `pysam` object to a list, but encountered issues with substantial memory usage and slow processing. Similarly, the downsampling APIs of `samtools` and `picard` present similar challenges. Is there any efficiency may?

**Comment by jmarshall** [comment]
This is not a pysam question.

I suggest you post your question at <https://biostars.org/> or <https://bioinformatics.stackexchange.com/>.
