### ISSUE TITLE
Serialize AlignedSegment to SAM string

### ISSUE THREAD

**Issue by danvk** [pysam-developers/pysam#125]
[According to the code][1], the `str` representation of AlignedSegment "is an approximate :term:`sam` format."

I believe the only way to get an exact SAM format is to serialize the alignment to a temp file on disk and then read it back. Is this correct? If so, it would be nice to have a more direct way.

(context: I'd like to read segments of a BAM file using pysam and send them over the network in a standard format.)

[1]: https://github.com/pysam-developers/pysam/blob/d3b8556dbafe62142f5a2bca78565ae9e58fae24/pysam/calignmentfile.pyx#L2465

**Comment by AndreasHeger** [comment]
Hi @danvk , the problem with AlignedSegment is that these objects can live in a context that is independent of a SAM-file. The SAM-file keeps track of chromosome names, while the AlignedSegment contains only an index of the chromosomal identifier (tid). Hence, the only time an AlignedSegment
can be written as a full SAM entry is within the context of a SAM-file (AlignmentFile). Thus, str can never be complete SAM format.
It might be worth adding a json dump to AlignedSegment.

**Comment by AndreasHeger** [comment]
Thanks, tostring() should cover this use case.
