### ISSUE TITLE
 infer_query_length ignores soft-clipped (S) bases

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [pysam-developers/pysam#1252]
Dear pysam developers,

Why infer_query_length method doesn't consider S bases as part of the length of the read?

I am developing a soft-clipping Python tool with Pysam due to this limitation found in _Ampliconclip_ https://github.com/samtools/samtools/issues/1948 

and I am developing some tests. In my custom soft-clipping tool, reads with a S (from the alignment tool) should be unmapped. The last assertion checks the length of the read 

```python
def test_soft_clip_from_bwa():
    """ This test includes an 'S' in the CIGAR string"""
    counter = get_new_counter()
    read = MockRead(100, [(4, 10), (0, 80)], '10S80M')
    primer_F_end = 110
    primer_R_start = 190
    softclip_positive_read1(read, primer_F_end, primer_R_start, counter)
    assert read.reference_id == -1, "Reference ID should be -1 for unmapped reads"
    assert read.reference_start == -1, "Reference start should be -1 for unmapped reads"
    assert read.mapping_quality == 0, "Mapping quality should be 0 for unmapped reads"
    assert read.cigarstring == "*", "CIGAR string should be '*' for unmapped reads"
    assert read.next_reference_id == -1, "Next reference ID should be -1 for unmapped reads"
    assert read.next_reference_start == -1, "Next reference start should be -1 for unmapped reads"
    assert read.template_length == 0, "Template length should be 0 for unmapped reads"
    assert read.flag & 4, "Unmapped flag should be set in the read's flag"
    assert counter['Anmapped due S, X or H'] == 1, "Counter for unmapped reads due to insertion in primer region should be incremented"
    expected_length = read.infer_query_length() + 10 # infer_query_length should include S in the length of the read ???
    actual_length = sum(length for op, length in read.cigartuples if op in [0, 1, 2, 4, 7, 8])  # Summing lengths for M, I, D, S, =, X
    assert expected_length == actual_length, f"Length mismatch: Expected {expected_length}, Actual {actual_length}"
```

and I have noticed that infer_query_length() doesn't sum S bases. Why?? Is this a bug??

I have added that +10 otherwise the test fails with `E    assert 80 == 90`

**Comment by jmarshall** [comment]
As you can see from the source code (_pysam/libcalignedsegment.pyx_'s `infer_query_length()` and `calculateQueryLengthWithoutHardClipping()`) and the tests (`test_infer_query_length()`), in fact `infer_query_length()` does count S CIGAR operations. It counts exactly the operations listed as “consum[ing] query” in the table in §1.4 of the SAM spec, as you would expect.

You don't show us your `MockRead()` or `softclip_positive_read1()` functions, but presumably one of them is not setting up the CIGAR-related fields of `read` in the way you expect.
