### ISSUE TITLE
Update API doc for query_sequence

### ISSUE THREAD

**Issue by eftsung** [pysam-developers/pysam#126]
The note and code snippet at http://pysam.readthedocs.org/en/latest/api.html#pysam.AlignedSegment.query_sequence still uses the old pre-0.8.1 names. 

Perhaps it could be updated using the new names. . .

Note that assigning to ~~seq~~ ```query_sequence``` will invalidate any quality scores. Thus, to in-place edit the sequence and quality scores, copies of the quality scores need to be taken. Consider trimming for example:
```python
q = read.query_qualities
read.query_sequence = read.query_sequence[5:10]
read.query_qualities = q[5:10]
```

**Comment by AndreasHeger** [comment]
Thanks, done.
