### ISSUE TITLE
Fetch with callback object does not work in pysam v0.8.3

### ISSUE THREAD

**Issue by dparks1134** [pysam-developers/pysam#128]
Hello,

I am using a callback object with fetch() in order to process individual reference sequences:

    class Counter:
        mCounts = 0

    def __call__(self, alignment):
        self.mCounts += 1

    bamfile = pysam.Samfile('test.bam', 'rb')
    for seqId, seqLen in zip(bamfile.references, bamfile.lengths):
        c = Counter()
        bamfile.fetch(seqId, callback = c )
        print c.mCounts

For pysam v0.7.7 this code counts the number of reads mapped to each reference sequence. Under v0.8.3, the callback is not called. Are callback objects no longer supported or is this a bug?

It would appear to be a bug with callbacks in general, since even a simple callback function does not work:

    def my_fetch_callback( alignment ):
        print str(alignment)

    bamfile = pysam.Samfile('test.bam', 'rb')
    for seqId, seqLen in zip(bamfile.references, bamfile.lengths):
        bamfile.fetch(seqId, callback = my_fetch_callback )

**Comment by AndreasHeger** [comment]
Apologies, callbacks indeed are not supported any more. Callbacks were implemented in the old samtools code base, but htslib does not provide this interface any more. Is it possible to change your code to use the iterators?

I have taken it out of the argument list of fetch.
Best wishes,
Andreas
