### ISSUE TITLE
ability to get direct access to tag buffer (no decoding to python list)

### ISSUE THREAD

**Issue by dalexander** [pysam-developers/pysam#129]
Hi!  Thanks for pysam, it's handy!

We (PacBio) use tags that encode arrays of per-base features.

In pysam, the `AlignedSegment.opt` method gives access to the tag values, but it immediately converts our arrays to lists.  This is unfortunate, because processing python lists is dead slow; even *converting* them back to numpy arrays is very slow.

Is there a way you could expose a raw buffer interface to tags values with array types? (or maybe tag values in general?), or perhaps `array` types instead of lists?

https://docs.python.org/2.7/c-api/buffer.html
https://docs.python.org/2/library/array.html

**Comment by AndreasHeger** [comment]
@dalexander , yes that is a very good idea and following the lead of Florian for quality values. I am planning to do some pysam work within the next two weeks and this will be part of the list.
Best wishes, Andreas

**Comment by dalexander** [comment]
Thank you @AndreasHeger , I look forward to testing it out.

Cheers,
Dave

**Comment by kyleabeauchamp** [comment]
I'm not sure if this belongs in the same issue or not, but speedups in `_pack_tags()` and `set_tags()` would also be very welcome :)

I don't know if list iteration is the culprit here as well; cProfile doesn't break down the contributions of the underlying `cdef` compiled code.

**Comment by dnephi** [comment]
Along similar lines, how feasible do you think explicitly supporting 'H', or 'B' tags would be? array.array even uses the same character codes.

Currently, in order to store arrays of numbers as tags, I have encoding them as comma-separated lists of strings and then splitting them out, which is memory inefficient, and rather slow. In fact, I'll try my hand at adding that over the next few days.

BTW, Kyle, if you add cython's profile=True compiler directive in your module, that should instruct cython to profile it for you. It'd slow you down a bit, so I wouldn't have it set for production scale, but for development, it's pretty handy.

**Comment by dnephi** [comment]
I wrote a method which I think should work - I've got more testing to do.

convertBinaryTagToArray (https://github.com/dnephi/pysam/blob/cb9d41346c96d4405cb4ad581477a9b0ac98dd75/pysam/calignmentfile.pyx), line 219

**Comment by AndreasHeger** [comment]
Thanks all, I am actively working on an implementation to remove lists as much as possible - I have implemented read, but now need to implement write.
Best, Andreas

**Comment by AndreasHeger** [comment]
Thanks you all, please see the current master. When reading, binary tags are now always python arrays, while they can be set from arrays, lists and tuples.

Best wishes,
Andreas

**Comment by dalexander** [comment]
I tried out master and it looks pretty good, I am able to get the buffers into numpy very fast now.

**Comment by kyleabeauchamp** [comment]
Do u have a code snippet that showcases the speed difference?

**Comment by kyleabeauchamp** [comment]
*edit* what I'm actually curious about is whether anyone has any benchmark numbers on the speedup with the latest patch, I did a quick test and I had trouble seeing speedup, presumably because I was just doing simple calls to `get_tag` and `set_tag`

**Comment by dnephi** [comment]
The improved efficiency is in working with the tags rather than getting or setting them. If they're already in memory as lists, you're just getting a pointer to that list. I think it largely depends on what you're doing with them after you get or set the tag.

**Comment by kyleabeauchamp** [comment]
Thanks!

**Comment by dalexander** [comment]
seems to work well.

**Comment by dalexander** [comment]
I should let Andreas decide when he wants to close

**Comment by AndreasHeger** [comment]
Thanks, closed!
