### ISSUE TITLE
[BUG][Typing] `PileupColumn` not imported in `libcalignmentfile.pyi`

### ISSUE THREAD

**Issue by vepain** [pysam-developers/pysam#1298]
## Summary

Python type checkers are not able to correctly infer the type of the object returned by `pysam.AlignmentFile.pileup(...).__next__` (i.e. by `IteratorColumn.__next__`).

For example, `mypy==1.10.1` infers it as `AlignedSegment`.

## Observations

In `libcalignmentfile.pyi`:
```py
from pysam.libcalignedsegment import AlignedSegment
```
The import `pysam.libcalignedsegment.PileupColumn` is missing.

The `pysam.libcalignedsegment.PileupColumn` class is used for typing in:
```py
class IteratorColumn:
    def __iter__(self) -> IteratorRow: ...
    def __next__(self) -> PileupColumn: ...
    # ...
```

## Partial fix

Add the import in `libcalignmentfile.pyi`:
```py
from pysam.libcalignedsegment import AlignedSegment, PileupColumn
```

## Notes

Something is missing to completely fix this typing bug, as `mypy` continues to infer `AlignedSegment` even after the previous partial fix.

**Comment by jmarshall** [comment]
Thanks for the report. Fixed by #1296.
