### ISSUE TITLE
Trouble to install Pysam through Conda

### ISSUE THREAD

**Issue by UCMaoCell** [pysam-developers/pysam#1305]
I followed the instruction to install Pysam:

conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
conda install pysam

But I got the following error:

Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pysam

Any help will be highly appreciated!

**Comment by UCMaoCell** [comment]
I am using Python 3.12 and Anaconda as the programming environment, on Windows 11. Thanks.

**Comment by UCMaoCell** [comment]
I did install Pysam with WSL-Ubuntu. How can I connect Anaconda with Pysam installed with Ubuntu? Thanks.

**Comment by jmarshall** [comment]
The bioconda channel does not support Windows.
