### ISSUE TITLE
query_name property of AlignedSegment class typed as Optional[str]

### ISSUE THREAD

**Issue by svm-zhang** [pysam-developers/pysam#1307]
Hello,

I am trying to write some programs to parse BAM file using pysam. However, when I, for instance, access the query_name property, mypy tells me that it is `Optional[str]` type. I can check for the NoneType to bypass the mypy error. But may I ask why it is typed as Optional[str], given that it is a mandatory field according to [SAM/BAM file specification](https://samtools.github.io/hts-specs/SAMv1.pdf)? For a given alignment, in what scenario we could see a missing `QNAME` field? I am likely missing something here. Please let me know. 

Similarly, the following properties are also typed as `Optional`, and they are mandatory as well:

- reference_name (RNAME)
- cigarstring (CIGAR)
- query_sequence (SEQ)
- query_qualities (QUAL)

Thanks in advance for your time and help.

**Comment by jmarshall** [comment]
If a read is unmapped, `reference_name` and `cigarstring` will be None.
If you study the SAM specification, you will see that — although it is uncommon — QNAME, SEQ, and QUAL may be omitted and written as ‘`*`’. In those cases, the corresponding pysam properties will be returned as None.

This is the sort of question that would be better asked on a forum such as [Biostars](https://www.biostars.org/) or [Bioinf.SE](https://bioinformatics.stackexchange.com/).
