### ISSUE TITLE
QUAL (record.qual) listed as `Optional[int]` but actually takes a `float` 

### ISSUE THREAD

**Issue by awgymer** [pysam-developers/pysam#1316]
Type hints in `libbcf.pyi` imply that the `qual` attribute and methods to set it (i.e. `header.new_record(...)`) should take an `int` (or `None`). 

However qualities can be floats. 
```
>>> record = header.new_record(contig='chr1', start=10, stop=11, alleles=('A','T'), qual=2.5 )
>>> print(record)
chr1	11	.	A	T	2.5	.	.
```

Indeed some tools output such numbers and the 4.2 spec on BCF encoding suggests this is the case:
```
QUAL float Variant quality; 0x7F800001 for a missing value
```

**Comment by jmarshall** [comment]
Yes indeed. The 4.1 VCF spec was quite explicit:

> Although traditionally people use integer phred scores, this field is permitted to be a floating point to enable higher resolution for low confidence calls if desired. […] (Numeric)

The 4.2 spec is probably the least clear: “QUAL: [Nothing specific] (Numeric)”. The 4.3 and later specs refine this to “QUAL: [Nothing specific] (Float)”.

Both the pysam code and the specs indicate that this should be `Optional[float]`, which happily encompasses both `int` and `float`.
