### ISSUE TITLE
pysam release to support htslib 1.21

### ISSUE THREAD

**Issue by emollier** [pysam-developers/pysam#1317]
Hi,

I have begun some work to bump htslib version to 1.21 in Debian and noted a couple of failing items in [Debian bug#1087457] affecting the last release 0.22.1 of pysam when bumping the htslib version 1.21 using Debian experimental.  I parsed from issue #1312 that the git master branch should already work fine with the latest htslib.  I'm wondering: are there plans for an upcoming pysam release?

I'm not particularly in a hurry; we're still pending upcoming Debian testing's stabilisation schedule.  I'm just trying to assess whether to put more work into bumping the htslib ecosystem, or let things rest a bit until they are ready for publication.

[Debian bug#1087457]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087457

Have a nice day,  :)
Étienne.

**Comment by jmarshall** [comment]
A new release is imminent.

**Comment by emollier** [comment]
Hi John,

Gentle ping about pysam release.  :)

I didn't want to sound pushy, but you mentioned imminent release last month.  I just wanted to make sure it didn't drop off the radar.  We were beginning to devise on alternate approaches on Debian Med side to move the [transition to htslib ecosystem 1.21] forward in case we were to run into Trixie freeze dates.  If there's help needed, don't hesitate to let us know.

Have a nice day,  :)
Étienne.

[transition to htslib ecosystem 1.21]: https://lists.debian.org/debian-med/2024/12/msg00018.html

**Comment by jmarshall** [comment]
As you know, life as an open source maintainer means that by definition it does not drop off the radar.

Sometimes life and the day job interfere with imminent plans. It remains imminent, but of course each gentle ping [pushes it out by a month](https://twitter.com/jomarnz/status/1183661437891334144).

**Comment by emollier** [comment]
Thanks for the status, your comment all too much resonates to me.

**Comment by emollier** [comment]
Hi John,

Thank you for the notification, I have begun to work on the
package update on Debian side.  I see that there is a lot of
work that went into the new revision of pysam, and that it was
well worth the patience.

Have a nice day,  :)
Étienne.
