### ISSUE TITLE
AlignmentFile.count_coverage Python3 str issue

### ISSUE THREAD

**Issue by beukueb** [pysam-developers/pysam#141]
count_coverage gives an error when called in Python3:
pysam/calignmentfile.pyx in pysam.calignmentfile.AlignmentFile.count_coverage (pysam/calignmentfile.c:12445)()

TypeError: expected bytes, str found

I assume this is due to the python2 strings being handled as bytes versus python3 str as str s

**Comment by DarwinW13** [comment]
I would love to see this addressed. I really love using this module, and so far this seems to be the only thing that doesn't work in Python3.

**Comment by AndreasHeger** [comment]
Thanks both, it took me a while to locate error.
Best wishes,
Andreas
