### ISSUE TITLE
query_position returns a None when is_del

### ISSUE THREAD

**Issue by Bratdaking** [pysam-developers/pysam#145]
Hey all,

This is actually more a discussion point then a real issue, but could not find a discussion board. Apologies if it is misplaced.
However within the last version (0.8.3) you changed the old behaviour to return the position before a deletion within an aligned read as the query_position when the query contains a deletion at that position. It now returns a None. That sounds logical, because the reference position is not present in the read, so there is no query position for it, that is the whole idea of a deletion. However, this introduces a problem as well. For a particular PileupRead, I cannot retrieve any information any more where I am within this particular read. For example I have no clue any longer if my deletion is at the border of a read (and as such less trustworthy) or right in the middle. 
So I personally think this is a loss of function, and would propose to reintroduce the old behaviour. Also because a deletion itself has a position: it is located between two bases. That is a bit problematic, because you do not want to return 2 numbers (and returning a position and a half is an ugly solution), however the old behaviour was following the vcf style of referencing to the position of a deletion by referencing to the position of the base before. So I think the old solution was the best and most elegant to indicate the position of deletion within a PileupRead.

Kind regards, 
Bart

**Comment by AndreasHeger** [comment]
Thanks, interesting point. This has been added in pull request #100, after some discussion in the thread to bug #93. I think at that time the argument was advanced that returning None was safer.

I have not come across either problem in practice, what do others think?

One solution is to add a method "previous_query_position" that is defined whenever is_del is True and returns the htslib defined value. However, this will not be available for reads which are aligned at a particular position.

**Comment by AndreasHeger** [comment]
I can see that the old behaviour can be useful. I have added the old behaviour as:
read.query_position_or_previous.
