### ISSUE TITLE
ImportError: Undefined symbol 'bam_aux_get' (Or, how to using pysam's cython interface properly)

### ISSUE THREAD

**Issue by NoSeatbelts** [pysam-developers/pysam#148]
This isn't a bug with the python functionality of pysam. However, it is making it difficult for me to take advantage of pysam's wrapping of htslib.

Currently, the portion of my setup.py for my project looks like this:
```python
ext = list(chain.from_iterable(map(cythonize, ['*/*.pyx', '*/*.py'])))
for x in ext:
    x.extra_link_args += pysam.get_libraries()
    x.define_macros += pysam.get_defines()
includes = [np.get_include(), os.path.abspath("include"), os.path.abspath("include/cephes")] + pysam.get_include()
```
I then pass ext as 'ext_modules' to setup, and includes to setup as 'include_dirs'.

This compiles correctly, but when I attempt to import my module, I get this error:

$AbsPath/anaconda/lib/python2.7/site-packages/$PACKAGE/ModuleName.so: undefined symbol: bam_aux_get

Strangely enough, it looks like I'm able to use bam_aux2Z, bam_hdr_t, bam_get_seq, and bam_get_aux.

My aim was to use bam_aux_get to write more nogil/faster code, rather than interacting with the python objects, but I can't get it to work properly. Have you run into such an issue with linking?

**Comment by AndreasHeger** [comment]
Thanks, I am not sure what the reason could be, especially if you see the other symbols. Are you using the htslib that is part of pysam (default) or are you linking against an external htslib library?

Can you check:
1. What does pysam.get_libraries() return, does it include libchtslib.so?
2. Does the library libchtslib.so include bam_aux_get?

This is what I  use in our code collection's setup.py (see https://github.com/CGATOxford/cgat/blob/master/setup.py)

'''(python)
pyx_files = glob.glob("scripts/*.pyx")
script_extensions = []
pysam_dirname = os.path.dirname(pysam.__file__)
include_dirs = [numpy.get_include()] + pysam.get_include()

if IS_OSX:
    # linking against bundles does no work (and apparently is not needed)
    # within OS X
    extra_link_args = []
else:
    extra_link_args = [os.path.join(pysam_dirname, x) for x in (
        'libchtslib.so',
        'TabProxies.so',
        'cfaidx.so',
        'csamfile.so',
        'cvcf.so',
        'ctabix.so')]

for pyx_file in pyx_files:
    script_name = os.path.basename(pyx_file)
    script_prefix = script_name[:-4]
    script_extensions.append(
        Extension("CGAT.%s" % (script_prefix),
                  sources=[pyx_file],
                  extra_link_args=extra_link_args,
                  include_dirs=include_dirs,
                  define_macros=pysam.get_defines())
    )
'''
Note that it seems not be necessary to use pysam.get_libraries()

**Comment by AndreasHeger** [comment]
Closing for now, please reopen if problem persist.
