### ISSUE TITLE
Error calling AllignmentFile pysam

### ISSUE THREAD

**Issue by mkelder** [pysam-developers/pysam#151]
Hi all, I am intending to work with SAM files in python, for which I need pysam. However, having installed pysam, I get the following error:
    >>> import pysam
    >>> samfile = pysam.AlignmentFile("ex1.bam", "rb")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'AlignmentFile'

Anyone who could help me out with this? Many thanks in advance.

**Comment by AndreasHeger** [comment]
Which pysam version are you using?

**Comment by mkelder** [comment]
Hi Andreas,

I used the latest version, so that should have been release 0.8.4.

Thanks,


Martijn

**Comment by cboustred** [comment]
I had the same issue.
I ran:
import pysam
pysam.version

and noted the pysam that was importing was coming from CrossMap (http://crossmap.sourceforge.net/) and not the latest pysam package I had installed

I resolved by uninstalling an old version of CrossMap (pip2 uninstall CrossMap) 

Serves as a reminder to myself to start using virtualenvs properly!

**Comment by AndreasHeger** [comment]
Thanks, closing this for now.
