### ISSUE TITLE
pysam.AlignmentFile.fetch causes python kernel to die

### ISSUE THREAD

**Issue by ekernf01** [pysam-developers/pysam#154]
Hi Pysam developers,
The following code kills my python kernel reliably, but does so after a seemingly random amount of time. Similar things happen to me whenever I use fetch, pileup, or the pysamstats package. I'd appreciate any help you can offer.
Eric

###Version info:
The kernel dies in an IPython Notebook and also when using Spyder. I have Mac OS 10.9.5.

    >>>print pysam.__version__
    0.8.3
    >>>sys.version 
    '2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) \n[GCC 4.2.1 (Apple Inc. build 5577)]'

###The code:

    import os
    import pysam
    chrom_label="22"
    start_pos=14464594 
    final_pos=14464644
    alignment_ftp_path = "ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/" \
                                         "other_exome_alignments/HG00096/exome_alignment/"
    alignment_filename = "HG00096.mapped.illumina.mosaik.GBR.exome.20111114.bam"
    alignment_ftp_path = os.path.join(alignment_ftp_path, alignment_filename) 
    # Watch out: as a side effect, SAMtools (and by extension, pysam) will 
    #   save the bai file in the current working directory. 
    bamfile = pysam.AlignmentFile(alignment_ftp_path)

    for i in range(10000):
        read_depth = sum([1 for aligned_read in bamfile.fetch("22", start_pos, final_pos)])

    bamfile.close()

**Comment by AndreasHeger** [comment]
thanks, interesting, will investigate.

**Comment by AndreasHeger** [comment]
Hi, I am using the latest pysam -0.8.5 branch and it does seem to work. I am on:
```
2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

**Comment by ekernf01** [comment]
OK. I am no longer at the job for which I was using Pysam, so I would like to just let this drop unless it is important to you to ferret out what happened.

**Comment by AndreasHeger** [comment]
Many thanks for your response! I am closing the issue for now.
