### ISSUE TITLE
pysam 0.8.3 - AlignedSegment orientation and reference positions

### ISSUE THREAD

**Issue by linsson** [pysam-developers/pysam#158]
Hi,

I wonder if positions (get_reference_positions,reference_start, reference_end) should be reversed (in reverse order, from larger reference coordinates to lower ones) in case "is_reverse" were TRUE.

Thanks.

**Comment by AndreasHeger** [comment]
Thanks for the suggestion. Would it not confuse things?

**Comment by AndreasHeger** [comment]
Closing this for now. Beginning in genomics years ago I used to start working in forward/reverse coordinates, but it seems the general expectation is that coordinates are on the forward strand.
