### ISSUE TITLE
pysam.merge crashes when merging BAM files with only headers

### ISSUE THREAD

**Issue by chihlee** [pysam-developers/pysam#161]
We are using version 0.8.0. Not sure if this happens with newer versions.
Error message:
pysam.merge("-f", args.outputFile, *perContigFiles)
File "/lib/python2.7/site-packages/pysam/__init__.py", line 68, in __call__
(retval, "\n".join(stderr)))
pysam.SamtoolsError: 'csamtools returned with error 1: '

**Comment by AndreasHeger** [comment]
Thanks. Could you check if this happens as well when running samtools merge from the command line on the same files?

Best wishes,
Andreas

**Comment by chihlee** [comment]
Hello Andreas,

I realized that it crashed because I was merging too many BAMs (2,580), most of which are empty.
samtools crashes merging this many files at the command line as well.

Best,
Steve

**Comment by AndreasHeger** [comment]
Thanks, I am closing this for now.
