### ISSUE TITLE
Bug fix in psyam/ctabixproxies.pyx

### ISSUE THREAD

**Issue by TomSmithCGAT** [pysam-developers/pysam#162]
The psyam/TabProxies.pyx needs a very minor update to the GTFProxy.as.Dict() method.

Currently, the attribute lines are split by "; ". Attributes ending in "; " therefore generate a final empty split product (''). Previously the final split was done on ";" and the final split product was discarded but it looks like this was amended to accommodate attributes which end in ";" rather than "; ".  I'd propose the change below.

Line 498:
< fields = [x.strip() for x in attributes.split("; ")]
\> fields = [x.strip() for x in attributes.strip().split("; ")]

**Comment by TomSmithCGAT** [comment]
@AndreasHeger Are you happy for me to make these change and issue a pull request or do you want to test it yourself. I assume you have regression tests for pysam?

**Comment by AndreasHeger** [comment]
Thanks, done!
