### ISSUE TITLE
No code provided to parse MD tags

### ISSUE THREAD

**Issue by adamnovak** [pysam-developers/pysam#163]
In order to work out which bases in an alignment are matches and which are mismatches, you can parse the MD tag if your SAM/BAM file has one. Unfortunately, pysam does not include code to make sense of the MD tag, so now I have to write my own.

pysam should include code to parse useful alignment information out of the MD tag, or at least example code using pysam to work with MD-tag-encoded alignment information.

**Comment by breichholf** [comment]
I've been considering incorporating this and submitting a PR for quite a while now, but couldn't settle on a useful representation of how the parsed MD-tag would be available. A dictionary over each position with FromBase>ToBase mutation? Only a list of those positions that include mutations and which these are?

As it's something I use quite often on a day to day basis, I settled on pushing my regions of interest through a separate pileup-creation step, which I can then use to read out the percentage of FromBase>ToBase mutations in that area. Loading the pileup into pandas this becomes a trivial task:
```python
import pandas as pd
import numpy as np
import pysam

def GetPileup(bam_file, region=None, start_pos=None, pileup_len=100, reference=None):
    region_str = region + ':' + str(start_pos) + '-' + str(start_pos + pileup_len)
    pileup_sam = pysam.mpileup(bam_file, '-r', region_str, '-f', reference, '-d', '20000000')

    parsed_pileup = [dict(zip(['ref_id', 'ref_pos', 'ref_base', 'coverage', 'read_base'],
                     x.split()[:-1])) for x in pileup_sam]

    return pd.DataFrame(parsed_pileup)

def ParsePileup(pileup_df):
    alphabet = 'ACGT'
    for nuc in alphabet:
        pileup_df.loc[:, nuc] = np.where(pileup_df.ref_base.str.upper() != nuc, pileup_df.read_base.str.count(nuc), np.nan)
    for f_base in alphabet:
        for t_base in alphabet:
            if f_base != t_base:
                pileup_df.loc[:, f_base + '>' + t_base] = np.where(pileup_df.ref_base.str.upper() == f_base, pileup_df[t_base] / pileup_df.coverage * 100, np.nan)
    return pileup_df


pileup = GetPileup(bam_file, region, start_pos, ref_file_str)
pileup = ParsePileup(pileup)
```
This should give you a pd.DataFrame object, with a column for each X>Y mutation and it's percentage, and does so relatively quickly, too. However, keep in mind, that the region supplied for the pileup results in ALL reads covering this region, regardless if they start at `start_pos` or only overlap there.

**Comment by AndreasHeger** [comment]
Thanks for the suggestion, and thanks, @breichholf for providing the example. I will take a look at both of this and #160.

**Comment by breichholf** [comment]
Recently I needed to parse the MD string directly from SAM, instead of going through a pileup file. While I haven't assembled a pull request yet, here, in brief, is one way of parsing the MD string and locating the positions of nucleotide mismatches:

```python
import re
import numpy as np

def RepresentsInt(i):
    '''
    Helper function that returns True if `i` is an int.
    '''
    try:
        int(i)
        return True
    except ValueError:
        return False

def parseMD(mdstr):
    '''
    Returns a numpy array with positions for where a `fromMM` base is, in the
    reference genome. This can then be used to intersect with the query string
    to find all desired mutations.
    '''
    # Split MD String at every single [ACGT] or ^:
    mdSub = re.sub(r'([\\^]*[ACGT]+)[0]*', ' \\1 ', mdstr)
    mdSplit = re.split('[ ]+', mdSub)

    mutArr = np.array([]).astype(str)

    # Iterate over Array and replace all mutations from the MD string with the
    # letter of the corresponding reference.
    # eg: 2G1 will produce the numpy array: 'M M G M'
    # All ^[ACGT]* by "D" and the number with a corresponding stretch of "M"
    for i in range(len(mdSplit)):
        mdPos = mdSplit[i]
        if len(mdPos) > 0 and RepresentsInt(mdPos):
            mutArr = np.concatenate((mutArr, np.repeat("M", int(mdPos))))
        elif re.match('\\^', mdPos):
            mutArr = np.concatenate((mutArr, np.repeat('D', len(mdPos) - 1)))
        elif len(mdPos) == 1:
            mutArr = np.concatenate((mutArr, np.array([mdPos])))
        else:
            # I'm not yet quite sure, if this won't just break at some point.
            # In my BAM/SAM files I have seen rare cases with two consecutive
            # mismatches in the MD tag causing this series of ifs to report incorrect
            # positions if I don't catch this.
            mutArr = np.concatenate((mutArr, np.array(list(mdPos))))

    # Return mismatch positions
    return mutArr

mdstring = read.get_tag('MD')

if not RepresentsInt(mdstring):
    mutLocation = parseMD(mdstring)
```

Using `RepresentsInt` allows me to only search the MD string if it contains mismatches (and therefore is not an int). The returned `np.ndarray` now gives you all positions of each mismatch (represented by the letter of each NT), match, or deletion.
You could expand the regex to capture [A-Z] instead to be fully SAM compliant, but keep in mind that you'll need to encode deletions and matches differently then.
Using a numpy array allows you to easily extract the position of specific mismatches, too.

eg:
```python
In [13]: md_array = parseMD('12G6C7^A5')

In [14]: md_array
Out[14]:
array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'G',
       'M', 'M', 'M', 'M', 'M', 'M', 'C', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'D', 'M', 'M', 'M', 'M', 'M'],
      dtype='|S32')

In [15]: np.nonzero(md_array == 'G')[0]
Out[15]: array([12])
```

**Comment by AndreasHeger** [comment]
Thanks. Apologies for the delay in getting back. I will try to change it into a python array implementation, ideally I would like to avoid extra dependencies.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Hi all, I have added a with_seq option to get_aligned_pairs::

```python

>>> import pysam
>>> x = pysam.AlignedRead()
>>> x.query_sequence = "A" * 10
>>> x.cigarstring = "5M2D2I2M"
>>> x.set_tag("MD", "4C^TT2")
>>> print x.get_aligned_pairs(with_seq=True)
[(0, 0, 'A'), (1, 1, 'A'), (2, 2, 'A'), (3, 3, 'A'), (4, 4, 'c'), (None, 5, 'T'), (None, 6, 'T'), (5, None, None), (6, None, None), (7, 7, 'A'), (8, 8, 'A')]
```

Will this be sufficient? Substitutions are lower-case.

**Comment by breichholf** [comment]
Thanks! Looks perfectly suited to my needs. I'll clone and give it a try tomorrow.

**Comment by MichaelVyverman** [comment]
Hi, I was checking into the new with_seq option to get_aligned_pairs, and I think it does not take into account BAM_CREF_SKIP (N cigar code). This code does not create entries in the MD-tag, but consumes positions in the reference sequence.

Example: cigar is 5M500N5M and MD-tag is '10'. This will create an IndexError in the code.

Best wishes,
Michaël

**Comment by AndreasHeger** [comment]
Thanks, I will check. It currently does (Line 1496):
```python
elif op == BAM_CDEL or op == BAM_CREF_SKIP:
```
Best wishes,
Andreas

**Comment by noporpoise** [comment]
I'm getting a exception with `get_aligned_pairs` when using `with_seq=True` in Python3.5:

    >>> read.get_aligned_pairs(with_seq=True)
    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pysam/calignedsegment.pyx", line 1440, in pysam.calignedsegment.AlignedSegment.get_aligned_pairs (pysam/calignedsegment.c:17130)
      File "pysam/calignedsegment.pyx", line 555, in pysam.calignedsegment.reconstituteSequenceFromMD (pysam/calignedsegment.c:8457)
    TypeError: expected bytes, str found

It runs fine on Python2.7.

**Comment by kyleabeauchamp** [comment]
@AndreasHeger  I finally got around to using the new code and it's a big usability improvement.  Thanks a bunch!

**Comment by mdshw5** [comment]
Here is the code I use to parse the MD tags: https://github.com/mdshw5/simplesam/blob/master/simplesam.py#L336

It looks like `get_aligned_pairs` is a more robust method, but the above is a basic and efficient way to reconstruct the reference sequence.

**Comment by mdshw5** [comment]
Either way - I'll take a look at sending a pull request, but if you want to just tag me in a commit that's okay too - thanks for asking.

**Comment by minillinim** [comment]
First, thanks for all your efforts.
I like the `get_aligned_pairs` option BUT can you please make it so that it throws an exception when called on files _without_ the MD tags.

**Comment by AndreasHeger** [comment]
Thanks, it does now raise a ValueError.

**Comment by j-scot** [comment]
It would be great if this automatically handled reverse-aligned reads (wrt the read position and aligned reference base), akin to how we already have read.modified_bases_forward etc. :)
