### ISSUE TITLE
BAM file SQ header not parsing correctly

### ISSUE THREAD

**Issue by jeromekelleher** [pysam-developers/pysam#167]
Using the following code:

```python
from __future__ import print_function
import pysam

filename = "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00533/alignment/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam"

samFile = pysam.AlignmentFile(filename)
for referenceInfo in samFile.header['SQ']:
    print()
    for k, v in referenceInfo.items():
        print(k, v)
```
I get
```
LN 35477943
M5 5b6a4b3a81a2d3c134b7d14bf6ad39f1
SN hs37d5
UR ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz        AS:NCBI37       SP:Human
```
Note that AS and SP are not being correctly parsed out here, but are included in the UR line. I think these should be included as keys in the info dict.

**Comment by mp15** [comment]
I could be wrong but I believe pysam is behaving correctly and it was a bug in the 1000 genomes pipeline that did this. "        AS:NCBI37       SP:Human" was accidentally separated with spaces rather than a tab as mandated in the specification. Thus pysam is parsing them as part of the UR line.

**Comment by jeromekelleher** [comment]
Thanks for pointing this out @mp15, very interesting. I'm happy to close this issue if @AndreasHeger and @bioinformed agree with this.

Out of interest, is there anywhere to complain about 1000G serving malformed bams?

**Comment by jmarshall** [comment]
Previously noted [in this 2013 samtools-devel thread](http://sourceforge.net/p/samtools/mailman/message/31360356/).  It was a manual error while building some early 1000G BAM files.  The 1000 genomes folks are aware of the problem; they didn't have much appetite for going back and fixing the already extant flawed ones for fear of changing checksums of files that people had already started analysing.

**Comment by jeromekelleher** [comment]
Thanks for clearing this up @jmarshall --- looks like we were unlucky with our choice of samples!

I agree this isn't a pysam issue, so I'm closing this issue. Thanks for the quick information @mp15 and @jmarshall, this made the problem a lot easier to deal with.
