### ISSUE TITLE
Invoking samtools commands

### ISSUE THREAD

**Issue by guillermomarco** [pysam-developers/pysam#168]
I've some scripts invoking samtools fixmate with pysam like this:

```python
pysam.fixmate('/tmp/test.bam')

'csamtools returned with error 1: '
Traceback (most recent call last):
  File "/home/user/test.py", line 216, in <module>
    main(arguments)
  File "/home/user/test.py", line 102, in main
    test2 = pysam.fixmate('/tmp/test.bam')
  File "/usr/local/lib/python2.7/dist-packages/pysam/__init__.py", line 71, in __call__
    (retval, "\n".join(stderr)))
SamtoolsError: 'csamtools returned with error 1: '
```
I've also tried using:

```python
pysam.fixmate('my_file.bam', 'my_file_ok.bam')
```

None of those commands are working. Any idea?

**Comment by AndreasHeger** [comment]
Thanks for reporting this. There is a selection of commands that fail with segmentation faults. At the time I was not sure what was causing this. I will look a bit deeper.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Fixmate seems to work in principle, it is important that the outputt argument contains a .bam header so that it
can identify the file type (as you already found out).

I have made sure that the stderr message is reported, hopefully that will help us to see what is the problem.

**Comment by AndreasHeger** [comment]
Closing  for now, please reopen if issues persist.
