### ISSUE TITLE
AlignedRead not found error in Pysam 0.8.3

### ISSUE THREAD

**Issue by tinuthomas** [pysam-developers/pysam#175]
I am trying to run the software JointSNVMix https://code.google.com/p/joint-snv-mix/
This has Pysam as dependency

jsm.py classify snv_mix_one /rawdata/data/REF/Human_Decoy_REF/hs37d5.fa /rawdata/data/snvmix_model.txt 2432_baserecal.bam 2432tLym1_baserecal.bam 2432_JointSNVMix.out
Traceback (most recent call last):
  File "/rawdata/data/Python_Packages/bin/jsm.py", line 9, in <module>
    from joint_snv_mix.runners.train import snv_mix_one_train, snv_mix_two_train, joint_snv_mix_one_train, \
  File "/rawdata/data/Python_Packages/lib64/python2.7/site-packages/joint_snv_mix/runners/train.py", line 8, in <module>
    from joint_snv_mix.counters.joint_binary_counter import JointBinaryBaseCounter
  File "joint_binary_counter.pyx", line 1, in init joint_snv_mix.counters.joint_binary_counter (joint_snv_mix/counters/joint_binary_counter.c:3141)
  File "csamtools.pxd", line 383, in init joint_snv_mix.counters.ref_iterator (joint_snv_mix/counters/ref_iterator.c:3115)

AttributeError: 'module' object has no attribute 'AlignedRead'

python
Python 2.7.5 (default, Jun 24 2015, 00:41:19)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> print pysam.__version__
0.8.3
>>> dir(pysam)
['AlignedRead', 'AlignedSegment', 'AlignmentFile', 'FastaFile', 'Fastafile', 'FastqFile', 'Fastqfile', 'GZIterator', 'GZIteratorHead', 'IndexedReads', 'IteratorColumn', 'IteratorRow', 'Pileup', 'PileupColumn', 'PileupRead', 'SAMTOOLS_DISPATCH', 'Samfile', 'SamtoolsDispatcher', 'SamtoolsError', 'TabProxies', 'TabixFile', 'Tabixfile', 'VCF', 'VCFRecord', 'VariantFile', 'VariantHeader', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__samtools_version__', '__version__', 'asBed', 'asGTF', 'asTuple', 'asVCF', 'bam2fq', 'bamshuf', 'bedcov', 'calignmentfile', 'calmd', 'cat', 'cbcf', 'cfaidx', 'cmd', 'csamfile', 'csamtools', 'ctabix', 'cvcf', 'depad', 'depth', 'faidx', 'fixmate', 'flagstat', 'fromQualityString', 'get_defines', 'get_include', 'get_libraries', 'get_verbosity', 'idxstats', 'index', 'key', 'libchtslib', 'merge', 'mpileup', 'options', 'os', 'pad2unpad', 'parser', 'phase', 'reheader', 'rmdup', 'samimport', 'set_verbosity', 'sort', 'tabix_compress', 'tabix_file_iterator', 'tabix_generic_iterator', 'tabix_index', 'tabix_iterator', 'targetcut', 'toQualityString', 'tview', 'version', 'view']

I see AlignedRead in pysam. What could be reason for the error ?

Thanks !

**Comment by AndreasHeger** [comment]
Thanks. My first suspicion would be that somehow you pick up an old version of pysam from somewhere. Can you rule this out?

Best wishes,
Andreas

**Comment by tinuthomas** [comment]
Thanks for your response.

I just have the given below locations in PYTHONPATH and each of these locations doesn't have anyother pysam

echo $PYTHONPATH
/usr/bin/:/bin/:/rawdata/data/Python_Packages/lib64/python2.7/site-packages/pysam-0.8.3-py2.7-linux-x86_64.egg/pysam/:/rawdata/data/Python_Packages/lib64/python2.7/site-packages/

Python 2.7.5 (default, Jun 24 2015, 00:41:19)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> print pysam.__file__
/rawdata/data/Python_Packages/lib64/python2.7/site-packages/pysam-0.8.3-py2.7-linux-x86_64.egg/pysam/__init__.pyc
>>> dir(pysam)
['AlignedRead', 'AlignedSegment', 'AlignmentFile', 'FastaFile', 'Fastafile', 'FastqFile', 'Fastqfile', 'GZIterator', 'GZIteratorHead', 'IndexedReads', 'IteratorColumn', 'IteratorRow', 'Pileup', 'PileupColumn', 'PileupRead', 'SAMTOOLS_DISPATCH', 'Samfile', 'SamtoolsDispatcher', 'SamtoolsError', 'TabProxies', 'TabixFile', 'Tabixfile', 'VCF', 'VCFRecord', 'VariantFile', 'VariantHeader', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__samtools_version__', '__version__', 'asBed', 'asGTF', 'asTuple', 'asVCF', 'bam2fq', 'bamshuf', 'bedcov', 'calignmentfile', 'calmd', 'cat', 'cbcf', 'cfaidx', 'cmd', 'csamfile', 'csamtools', 'ctabix', 'cvcf', 'depad', 'depth', 'faidx', 'fixmate', 'flagstat', 'fromQualityString', 'get_defines', 'get_include', 'get_libraries', 'get_verbosity', 'idxstats', 'index', 'key', 'libchtslib', 'merge', 'mpileup', 'options', 'os', 'pad2unpad', 'parser', 'phase', 'reheader', 'rmdup', 'samimport', 'set_verbosity', 'sort', 'tabix_compress', 'tabix_file_iterator', 'tabix_generic_iterator', 'tabix_index', 'tabix_iterator', 'targetcut', 'toQualityString', 'tview', 'version', 'view']


What could be other reason ?

**Comment by AndreasHeger** [comment]
Thanks. Could you please give me the full set of instructions.

Instructions here: https://code.google.com/p/joint-snv-mix/wiki/installation
require pysam==0.5

Best wishes,
Andreas

**Comment by tinuthomas** [comment]
Thank you..

Yes I tried with pysam 0.5 and I am was getting the below error and read that this was a issue with that pysam version, not sure though.

Trial with pysam 0.5 - command used to run JointSNVMix
-------------------------------------------------------------------------
jsm.py classify snv_mix_one hs37d5.fa snvmix_model.txt Sample234.bam Sampl234_tumor.bam Sample234_JointSNVMix.out
ValueError: file does not have valid header (mode='rb') - is it SAM/BAM format?


But the BAMs do have header, so upgraded to pysam 0.8.3. But that was giving the error
"AttributeError: 'module' object has no attribute 'AlignedRead'

Let me know if you need more information. Also if you think this couldn't be related to pysam, I would followup with the author of JointSNVMix.

Thanks for the support,
Tinu

**Comment by AndreasHeger** [comment]
Hi Tinu,

you might be out of luck, the differences between 0.5 and 0.8.3 are large.

But let us checkt if pysam 0.8.3 is correctly installed, does the following work:

'''
python -c 'import pysam; f = pysam.AlignmentFile("ex1.bam"); print f.next()'
'''

substituting ex1.bam for a bam-file you have lying around?
Best, Andreas

**Comment by tinuthomas** [comment]
Thanks..


This is what I get

 python -c 'import pysam; f = pysam.AlignmentFile("2432_baserecal.bam"); print f.next()'
HWI-ST972:1257:C4HY1ACXX:7:1214:12655:30104     99      0       10000   12      21S42M12S       0       10042   42      ACCCTCACCCAGCCCCACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCC     array('B', [30, 31, 29, 35, 33, 37, 34, 38, 36, 35, 35, 38, 34, 34, 34, 34, 35, 35, 35, 35, 35, 34, 34, 35, 36, 34, 34, 34, 34, 35, 36, 34, 34, 37, 35, 35, 36, 35, 35, 36, 35, 35, 36, 35, 35, 37, 35, 35, 34, 35, 35, 36, 34, 35, 36, 38, 38, 33, 34, 37, 38, 36, 38, 33, 34, 37, 29, 32, 35, 37, 31, 32, 27, 33, 2])       [('BD', 'MMOLRPQOPLPQQPLKOMNKKNMLMNKNMLMOLONMNOLONMNOLONMNOLONMNOMPONOPMPPOPROSRMNOM'), ('MD', '42'), ('PG', 'MarkDuplicates'), ('RG', 'L007'), ('XG', 0), ('BI', 'QQRNSQSPQLRRROLLROPLLQQNPPLQQNPPLQQNPPLQQNQQMRROQQMRROQQMRROQQMRROQQNSTPRRQ'), ('AM', 12), ('NM', 0), ('SM', 12), ('XM', 0), ('XO', 0), ('MQ', 12), ('XT', 'M')]

**Comment by AndreasHeger** [comment]
Thanks, it seems that pysam is installed correctly, it might be worth getting in touch with the JointSVNMix authors and how they interface with pysam.

Best wishes,
Andreas

**Comment by tinuthomas** [comment]
Sure. Thanks for the support

**Comment by AndreasHeger** [comment]
Thanks, I will close this issue for now.
