### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by csuliweilong** [pysam-developers/pysam#178]
I build pysam and get an error:

running build
running build_py
package init file 'htslib/__init__.py' not found (or not a regular file)
package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
package init file 'samtools/__init__.py' not found (or not a regular file)
package init file 'samtools/win32/__init__.py' not found (or not a regular file)
running build_ext
skipping 'pysam/csamtools.c' Cython extension (up-to-date)
skipping 'pysam/chtslib.c' Cython extension (up-to-date)
skipping 'pysam/csamfile.c' Cython extension (up-to-date)
skipping 'pysam/calignmentfile.c' Cython extension (up-to-date)
skipping 'pysam/ctabix.c' Cython extension (up-to-date)
skipping 'pysam/TabProxies.c' Cython extension (up-to-date)
skipping 'pysam/cvcf.c' Cython extension (up-to-date)
skipping 'pysam/cbcf.c' Cython extension (up-to-date)
skipping 'pysam/cfaidx.c' Cython extension (up-to-date)

How to solve this problem?
ps. Ubuntu 12.04.2 
      gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
      Python 2.7.3

**Comment by AndreasHeger** [comment]
Thanks, can you please specify the commands you used?

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Closing this for now, please reopen if persists.
