### ISSUE TITLE
Updated hts-specs

### ISSUE THREAD

**Issue by mattay** [pysam-developers/pysam#179]
The Sequence Alignment/Map Format Specification have been updated as of 28 Aug 2015.
http://samtools.github.io/hts-specs/SAMv1.pdf

In the specs for the Read Group line (@RG) the 'PM' tag is a valid.
>PM |  Platform model. Free-form text providing further details of the platform/technology used.

This update is not reflected in pysam

    File "pysam/calignmentfile.pyx", line 1258, in pysam.calignmentfile.AlignmentFile.header.__get__ (pysam/calignmentfile.c:15426)
    ValueError: unknown field code 'PM' in record 'RG'

**Comment by AndreasHeger** [comment]
Many thanks, added! Best wishes, Andreas
