### ISSUE TITLE
fromQualityString() and toQualityString() renamed/removed in v0.8.4

### ISSUE THREAD

**Issue by PeteHaitch** [pysam-developers/pysam#181]
These are changes I've found (based on https://github.com/pysam-developers/pysam/compare/v0.8.3...v0.8.4) that are currently undocumented in the release notes (https://github.com/pysam-developers/pysam/blob/master/doc/release.rst):

- `fromQualityString()` -> `qualitystring_to_array()`
- `toQualityString()` -> `qualities_to_qualitystring()`

There may be others, but it is only the change from `fromQualityString()` to `qualitystring_to_array()` that has bitten me (see https://github.com/PeteHaitch/methtuple/issues/100). It'd be good with future releases to have a complete list of methods that have been removed/renamed, ideally with backwards compatibility for at least one release cycle.

Thanks for all your hard work on pysam.

**Comment by AndreasHeger** [comment]
Thanks, sorry you ran into trouble. I had intended to do better this time in terms of documenting the changes, but I seem not to have covered it all.

I will run backwards compatibility tests before the next release to catch more changes.

I have added those two functions to the docs. I will keep the issue to see if there are more.

Best wishes,
Andreas

**Comment by PeteHaitch** [comment]
Thanks, Andreas.

**Comment by AndreasHeger** [comment]
Closing for now.
