### ISSUE TITLE
CRAM index (.crai) not recognized

### ISSUE THREAD

**Issue by mcieslik-mctp** [pysam-developers/pysam#185]
CRAI file is not recognized or found

```
>>> samfile = pysam.AlignmentFile("0120b5b1-d204-429a-aa21-704fd98624ea-1-1_alig_csort_pack-alig_csort.cram", "rb")
>>> samfile.has_index()
FALSE
```
... but is present:
```
$ls *cram*
0120b5b1-d204-429a-aa21-704fd98624ea-1-1_alig_csort_pack-alig_csort.cram  0120b5b1-d204-429a-aa21-704fd98624ea-1-1_alig_csort_pack-alig_csort.cram.crai
```

Thanks!

**Comment by AndreasHeger** [comment]
Thanks, pysam's autodetection of formats is not working very well.
The following should work:

```python
samfile = pysam.AlignmentFile("0120b5b1-d204-429a-aa21-704fd98624ea-1-1_alig_csort_pack-alig_csort.cram", "rb")
```

See also #186

Best wishes,
Andreas

**Comment by duxan** [comment]
Proposed solution is same like in a problem. Maybe you meant different *mode*?

I have found from [source](https://github.com/pysam-developers/pysam/blob/master/pysam/calignmentfile.pyx#L450) that mode could be set to `rc`, so this line worked for me:

```{python}
samfile = pysam.AlignmentFile("0120b5b1-d204-429a-aa21-704fd98624ea-1-1_alig_csort_pack-alig_csort.cram", "rc")
```

**Comment by AndreasHeger** [comment]
Thanks! Apologies.  I have added some more documentation.
