### ISSUE TITLE
release  wheel package to pypi server

### ISSUE THREAD

**Issue by liuchang23** [pysam-developers/pysam#187]
hi, thanks for your pysam, it's easy to use, and very powerful library. but `pip install pysam` is too slow, may be your should release binary format package to pypi server.

you could release wheel format package as following:

```bash
python setup.py bdist_wheel
```

BTY, you could use trivis's `deploy` feature which it automatic release package and push to pypi server. for ref: https://github.com/Liuchang0812/OSSPy/blob/master/.travis.yml

**Comment by kyleabeauchamp** [comment]
If you want binary packages, there are conda packages available here: https://bioconda.github.io/

**Comment by AndreasHeger** [comment]
Thanks, last time I tried wheels were not uploadable for linux -- I will 
look into it.

A wheels repository that I maintain for pysam is here:

https://www.cgat.org/downloads/public/pysam/wheels/

Best wishes,
Andreas

**Comment by liuchang23** [comment]
Thanks @AndreasHeger 

I will have a try.

**Comment by graingert** [comment]
@AndreasHeger wheels are uploadable to PyPI for manylinux1, OS X and Windows
