### ISSUE TITLE
Segmentation fault (core dumped) on ubuntu 14.04

### ISSUE THREAD

**Issue by sfchen** [pysam-developers/pysam#191]
pysam works on Mac OS X, but may throw Segmentation fault (core dumped) on Ubuntu 14.04

Same error for python2 or python3

**Comment by sfchen** [comment]
Has anyone else met this issue before?

**Comment by laurensvdwiel** [comment]
I have no problem running pysam in ubuntu 14.04 (via virtualbox) using python 3.5.1
I installed pysam via pip and have the latest gcc and g++ installed.

Does this error occur during a certain method call? If so, can you provide the details so I may try to reproduce?

**Comment by AndreasHeger** [comment]
Thanks, will need more information (what command exactly fails) to help.

**Comment by AndreasHeger** [comment]
Closing for now.
