### ISSUE TITLE
Can't compile on FreeBSD

### ISSUE THREAD

**Issue by brianwalenz** [pysam-developers/pysam#194]
gcc48 -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -Isamtools -Ipysam -Ihtslib -I/usr/local/include/python2.7 -c htslib/cram/cram_io.c -o build/temp.freebsd-10.1-RELEASE-amd64-2.7/htslib/cram/cram_io.o -Wno-error=declaration-after-statement -DSAMTOOLS=1
htslib/cram/cram_io.c: In function 'bgzf_open_ref':
htslib/cram/cram_io.c:1546:26: error: 'R_OK' undeclared (first use in this function)
     if (access(fai_file, R_OK) != 0)
                          ^
htslib/cram/cram_io.c:1546:26: note: each undeclared identifier is reported only once for each function it appears in
error: command 'gcc48' failed with exit status 1

R_OK is defined in unistd.h.  Including this in htslib/cram/cram_io.c resolves the problem.

**Comment by jmarshall** [comment]
(Has been fixed in htslib 1.3; see samtools/htslib@0ec5202de5691b27917ce828a9d24c9c729a9b81.)

**Comment by jmarshall** [comment]
Fixed now that pysam has imported htslib 1.3.

**Comment by AndreasHeger** [comment]
Thanks, I will close the issue.
