### ISSUE TITLE
Update to HTSlib 1.3

### ISSUE THREAD

**Issue by david4096** [pysam-developers/pysam#195]
HTSlib released an update last week with greatly improved network support

https://github.com/samtools/htslib/releases/tag/1.3

**Comment by AndreasHeger** [comment]
Thanks - scheduled over the xmas break. Best wishes, Andreas

**Comment by david4096** [comment]
Hey anything we can do to help? Any kind of timeline? Thanks!

**Comment by AndreasHeger** [comment]
Hi David,

it is pretty much done, I am thinking this weekend or next weekend.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Hi all, I have merged the changes on the pysam-0.8.5-dev branch back into master. 

I am happy to release, but would appreciate if anybody could give it a go, in particular to see if any of the htslib 1.3 features are missing.

Best wishes,
Andreas

**Comment by jeromekelleher** [comment]
Thanks @AndreasHeger, we'll give it a spin and let you know.

**Comment by jeromekelleher** [comment]
Would it be possible to provide a pip-installable tarball for the current version please @AndreasHeger? I'm hitting various issues installing from the git version.

**Comment by AndreasHeger** [comment]
Thanks, will do. Can you send an error log? I want to make the barrier to contribute as low as possible and if working from the repo is troublesome, I would like to see if I can fix that.

**Comment by AndreasHeger** [comment]
Hi @jeromekelleher ,

there is a tar-ball at https://www.cgat.org/downloads/public/pysam/sdist/pysam-0.8.5.tar.gz and a wheel
at https://www.cgat.org/downloads/public/pysam/wheels/pysam-0.8.5-cp27-none-linux_x86_64.whl.

Please let me know if these do/don't work.

Best, Andreas

**Comment by jeromekelleher** [comment]
Thanks @AndreasHeger, they work great! My problem with the repo was with ``libchtslib``:
```
jk@ubuntu-15$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/__init__.py", line 1, in <module>
    from pysam.libchtslib import *
ImportError: No module named libchtslib
```
I'm not sure where I was going wrong. Does setup.py expect the dependencies to be in a particular location? I tried running the travis script, but that didn't seem to be very happy on a Ubuntu 15.10 VM.

Anyway, thanks for the wheel, that's super useful. I'll take a look at the new functionality tomorrow and let you know how it goes.

**Comment by jeromekelleher** [comment]
It's working great @AndreasHeger, thanks! (see #87)

**Comment by AndreasHeger** [comment]
I will close this issue as htslib 1.3 is now basically incorporated and a release imminent. There are still a few outstanding niggles, which are better dealt in separate issues.
