### ISSUE TITLE
How to match the mates from fetched reads (paired-end)

### ISSUE THREAD

**Issue by huangyh09** [pysam-developers/pysam#196]
Dear pysam developer,

I am a user of pysam, and would like to know a better way to match the mates from fetched reads. Currently, I am using `is_read1` and `is_read2` to put all fetched reads into two sets. And then use the `qname` to see whether they are a pair. 

In most cases, it works in this way. But the `qname` of `read1` and `read2` do not need to be the same or similar. So I am wondering if there are other better ways.

Many thanks,
Yuanhua

**Comment by AndreasHeger** [comment]
Thanks for using pysam. Unfortunately solving this problem is out of the scope of pysam.

Unfortunately you will need a way to identify if two reads belong to the same pair, the read name should usually be that link. Sometimes it is necessary to remove a suffix (.1/.2, \#1/\#2) to make read names match up.

**Comment by huangyh09** [comment]
Thanks for the clarification. The method you suggested works well in my experience.

**Comment by fredsamhaak** [comment]
Dear pysam developer,
I am using pysam these days too but I face a problem like huangyh09. 
I assign a position to get reads aligned to that position and then I use is_read1 and is_read2 to estimate it is read1 or read2. If it is read1, how can I get its corresponding read2's position? 

Thanks a lot,
FredSamhaak

**Comment by huangyh09** [comment]
As the developer suggested, using the `qname` is a good way, which is also supported from my experience.
