### ISSUE TITLE
TagToString fails with "TypeError: expected bytes, str found"

### ISSUE THREAD

**Issue by humburg** [pysam-developers/pysam#197]
I'm trying to use the *tostring* method of *AlignedSegment* to get a string representation of the read alignment (using Python 3.4.3). If the alignment object contains any optional tags this fails with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/calignedsegment.pyx", line 739, in pysam.calignedsegment.AlignedSegment.tostring (pysam/calignedsegment.c:10523)
  File "pysam/calignedsegment.pyx", line 773, in pysam.calignedsegment.AlignedSegment.tostring (pysam/calignedsegment.c:10383)
  File "pysam/calignedsegment.pyx", line 779, in pysam.calignedsegment.AlignedSegment.get_tag_string (pysam/calignedsegment.c:10644)
  File "pysam/calignedsegment.pyx", line 139, in pysam.calignedsegment.TagToString (pysam/calignedsegment.c:3674)
TypeError: expected bytes, str found
```

Alignments without tags work fine.

**Comment by humburg** [comment]
On closer inspection alignments without tags are broken as well. They don't cause an exception when calling *tostring* but they have corrupted base qualities. Looks like there is some confusion over the use of `str` and `bytes` in *tostring*.

**Comment by AndreasHeger** [comment]
Thanks, I will have a look!

**Comment by NoSeatbelts** [comment]
I wrote TagToString and tostring, and I wrote them primarily concerned with python 2.

I've modified the methods to not use cython.str declarations.

humburg, would you see if the issue's been fixed for you?

https://github.com/pysam-developers/pysam/pull/200

**Comment by humburg** [comment]
@NoSeatbelts, Thanks for looking at this. I tried to test your fix but I get

```
86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -Isamtools -Ipysam -Ihtslib -I/usr/include/python3.4m -c pysam/csamtools.c -o build/temp.linux-x86_64-3.4/pysam/csamtools.o -Wno-error=declaration-after-statement -DSAMTOOLS=1
x86_64-linux-gnu-gcc: error: pysam/csamtools.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```

when trying to build with `python3 setup.py build`. Should I do something different to build pysam?

**Comment by NoSeatbelts** [comment]
Ah, looks like I needed to pull in the recent updates/refactoring to pysam. I've brought it up to date. Give that a gander? I've gotten it to build.

**Comment by humburg** [comment]
I managed to build it successfully now. It turns out the environment I was using for the build was missing cython, causing the build error. Apologies for the trouble. 

Using your fix I'm still getting errors. Here is the relevant part of the traceback:

```
 File "pysam/calignedsegment.pyx", line 739, in pysam.calignedsegment.AlignedSegment.tostring (pysam/calignedsegment.c:10598)
  File "pysam/calignedsegment.pyx", line 764, in pysam.calignedsegment.AlignedSegment.tostring (pysam/calignedsegment.c:10373)
TypeError: Expected bytes, got str
```

This is clearly related but slightly different. I included a (very temporary) workaround for the original error in my code and haven't tested this without the workaround yet so I can't say whether that part has been fixed or not. I'll try to put a reproducible example together tomorrow, hopefully that will make it a bit easier to get this sorted out.

**Comment by NoSeatbelts** [comment]
That line was missing a type coercion from the member attribute cigarstring, which I've added in. Give it one more shot?

**Comment by AndreasHeger** [comment]
Thanks both, this is really hard to get right, see also #29. I am currently concentrating on incorporating htslib 1.3, once this is done I will merge your changes in.

Best wishes, 
Andreas

**Comment by humburg** [comment]
Thanks, that fixed the issue I had yesterday. Doing some more testing it seems that the original problem persists, however. Example code that reproduces the error from the original post can be found [here](https://gist.github.com/humburg/c128a613bf2f4d2304eb)

This is based on the one of the examples from the [documentation](http://pysam.readthedocs.org/en/latest/usage.html#creating-sam-bam-files-from-scratch) but a few more issues came to light in the process so I had to adapt it slightly.

**Comment by humburg** [comment]
While looking at this I've encountered additional byte/string issues that, I think, are not directly related to the `tostring` code. Clearly this is a pretty thorny issue and making everything work smoothly in Python 2 and 3 isn't trivial. It seems to me that the best approach would be to put together some unit tests to ensure all strings are handled as they should be.

I'd be happy to get this started by providing tests for the issues I've encountered. Before I do this I would like to make sure that I'm clear about what the intended behaviour is. Reading the discussion surrounding #29 it sounds to me as if all text should be returned as string rather than bytes, is that correct?

**Comment by AndreasHeger** [comment]
Hi @humburg , yes, that is correct, the return types should always be strings.

There is some coverage of string issues in the unit tests, but it is definitely incomplete. Some unit tests would be great. Best wishes,
Andreas

**Comment by humburg** [comment]
@AndreasHeger , to get started on this I tried to run the existing unit tests in `tests/AlignedSegment_test.py`under Python 3.4 on my machine and all but two of them are failing due to this exact issue (see below for representative examples). I was a bit surprised by that because these tests obviously pass when *travis* is running them.

I see two possible explanations. Either something is off with my python or pysam installation or *travis* isn't actually running these tests under Python 3. While it is entirely possible that something is wrong at my end (and I'd be quite happy if all the issues I've been having with this could be resolved that way) there is some evidence that *travis* is actually running the tests under Python 2.7. The [log for the latest build of master](https://travis-ci.org/pysam-developers/pysam/jobs/102838618) contains a lot of references to Python 2.7, including this one at the end of the pysam installation process (right before running the tests):

```
Processing pysam-0.8.4-py2.7-linux-x86_64.egg
creating /usr/local/lib/python2.7/dist-packages/pysam-0.8.4-py2.7-linux-x86_64.egg
Extracting pysam-0.8.4-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding pysam 0.8.4 to easy-install.pth file
```

- - -

Here are the promised examples for the failing tests. All failures seem to be due to one of three errors. The third failure below is reproduces the error I reported above.

```
======================================================================
ERROR: testBlocks (AlignedSegment_test.TestAlignedSegment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/sf_share/Documents/GitHub/pysam/tests/AlignedSegment_test.py", line 226, in testBlocks
    a = self.buildRead()
  File "/media/sf_share/Documents/GitHub/pysam/tests/AlignedSegment_test.py", line 28, in buildRead
    a.query_qualities = pysam.qualitystring_to_array("1234") * 10
TypeError: Argument 'input_str' has incorrect type (expected bytes, got str)
```

```
======================================================================
ERROR: see issue 62
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/sf_share/Documents/GitHub/pysam/tests/AlignedSegment_test.py", line 63, in testSettingTagInEmptyRead
    a.tags = (("NM", 1),)
  File "pysam/calignedsegment.pyx", line 2121, in pysam.calignedsegment.AlignedSegment.tags.__set__ (pysam/calignedsegment.c:25483)
  File "pysam/calignedsegment.pyx", line 1959, in pysam.calignedsegment.AlignedSegment.set_tags (pysam/calignedsegment.c:22013)
  File "pysam/calignedsegment.pyx", line 359, in pysam.calignedsegment.packTags (pysam/calignedsegment.c:6875)
KeyError: b'C'
```

```
======================================================================
ERROR: testAsString (AlignedSegment_test.TestAsString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/sf_share/Documents/GitHub/pysam/tests/AlignedSegment_test.py", line 584, in testAsString
    self.assertEqual(s, p.tostring(pysamf))
  File "pysam/calignedsegment.pyx", line 739, in pysam.calignedsegment.AlignedSegment.tostring (pysam/calignedsegment.c:10523)
  File "pysam/calignedsegment.pyx", line 773, in pysam.calignedsegment.AlignedSegment.tostring (pysam/calignedsegment.c:10383)
  File "pysam/calignedsegment.pyx", line 779, in pysam.calignedsegment.AlignedSegment.get_tag_string (pysam/calignedsegment.c:10644)
  File "pysam/calignedsegment.pyx", line 139, in pysam.calignedsegment.TagToString (pysam/calignedsegment.c:3674)
TypeError: expected bytes, str found
```

**Comment by AndreasHeger** [comment]
Thanks, I will take a look. I think I am still at 3.3 and need to update.

**Comment by AndreasHeger** [comment]
Brief update, I do get the errors with 3.4.

**Comment by AndreasHeger** [comment]
Hi @NoSeatbelts , I am looking into the string issues and I am wondering if converting everything to bytes is a good idea. In my reading of the code, the return type of the tostring method will now be <bytes>, which is probably not something that python3 users expect.

Would you mind if I try to get the cython.str version to work?
Best wishes,
Andreas

**Comment by NoSeatbelts** [comment]
I'd be happy to go with string. I think I ended up doing bytes to be compatible with some existing methods.

I don't mind at all -- thanks for the help!

**Comment by humburg** [comment]
@AndreasHeger , good to hear that you sorted out the *travis* issue and thanks for your efforts to resolve the bytes/str problems.

**Comment by AndreasHeger** [comment]
Thanks both, it should now be fixed.
