### ISSUE TITLE
VariantRecord.items() segfaults on missing genotypes

### ISSUE THREAD

**Issue by andrewparkermorgan** [pysam-developers/pysam#203]
Iteration through sample records of a `VariantFile` throws a segfault (code 11) when any sample has missing genotypes *and* an attempt is made to fetch genotypes for that sample or any other.  Iteration over the `VariantRecordSample` entries appears to be intact as long as the genotypes are not processed.

A minimal example follows.  First the test VCF file (`test.vcf`):
```
##fileformat=VCFv4.1
##contig=<ID=chr1,length=100>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1	sample2
chr1	1	.	A	G	999	.	.	GT	0/0	1/1
chr1	50	.	T	C	999	.	.	GT	./.	0/1
```

And now console output
```
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
>>> from pysam import VariantFile
>>> v = VariantFile("test.vcf")
>>> for site in v:
...     for ss,rec in site.samples.items():
...             print ss,rec
... 
sample1 <pysam.cbcf.VariantRecordSample object at 0x1004e2750>
sample2 <pysam.cbcf.VariantRecordSample object at 0x101fca090>
sample1 <pysam.cbcf.VariantRecordSample object at 0x101fca0d0>
sample2 <pysam.cbcf.VariantRecordSample object at 0x101fca190>
...
>>> v = VariantFile("test.vcf")
>>> for site in v:
...     for ss,rec in site.samples.items():
...             print ss,rec.alleles
... 
Segmentation fault: 11
```

I am using `pysam` v0.8.4 installed with `pip`.

**Comment by AndreasHeger** [comment]
Thanks, I am looking at this.

**Comment by AndreasHeger** [comment]
Thanks, I reproduced the problem.

I have added:
```python
 if r.d.allele == NULL:
      return tuple(["."] * nalleles)
```
to cbcf.pyx, see b4774b6a550c0888d2f53c122319785793f85101

**Comment by bioinformed** [comment]
FYI, I backed out the fix by @AndreasHeger and added a better one.  The problem is that missing alleles are represented as None, not "." in Python-space.

**Comment by andrewparkermorgan** [comment]
@bioinformed Thanks.  I do see some advantage to representing a missing genotype as `None` (which naturally allows shorthand logical tests for existence: `if not record.alleles[0] ...`)

But in any case, the segfault is fixed but there is still an issue with initialization:
```
v = pysam.VariantFile("test.vcf")
for site in v:
    for ss, rec in site.samples.items():
        print ss, rec.alleles
```
Returns, for me, the following:
```
sample1 ('.', '.')
sample2 ('.', '.')
...
```

But doing anything which implicitly accesses the values in `rec` forces initialization, and returns the correct genotypes:
```
v = pysam.VariantFile("test.vcf")
for site in v:
    print rec
    for ss, rec in site.samples.items():
        print ss, rec.alleles
```
yields
```
sample1 ('T', 'C')
sample2 ('C', 'C')
...
```

Although doing something to force initialization of the insides of the `VariantRecord` instance is not that burdensome, ideally I should just be able to access `rec.allelles` and find the correct values there.

If it makes any difference, my `pysam` is compiled against an existing `hstlib-1.3` installation.

**Comment by bioinformed** [comment]
@andrewparkermorgan : I'm working to add support for creating and mutating records now and can look into the problem you note.  Just to simplify tracking, would you mind opening a new issue with the above example?  I'm already working on the fix.

**Comment by andrewparkermorgan** [comment]
@bioinformed I am now having trouble reproducing the issue above.  Let me do some more investigating figure out exactly the conditions under which it arises.  Suspect that it has to do with what does or does not trigger the lazy parsing.

**Comment by bioinformed** [comment]
@andrewparkermorgan No worries-- I was able to reproduce that problem plus a few others like it and have fixed them in my branch (https://github.com/bioinformed/pysam).  I'm still working on a few missing components for full write support and expect these changes will be merged into the master repository soon.
