### ISSUE TITLE
Better performance by subprocess

### ISSUE THREAD

**Issue by andremrsantos** [pysam-developers/pysam#207]
Hi,

I have been using pysam library to process, filter and merge BAM files, but I have been facing some performance issues. Comparing to a script using python subprocess module running `samtools` on shell, I get about twice faster results. Here's a single example trial:

```
~/D/w/tmp ❯❯❯ time python3 subprocess_reader.py
87329 reads were removed.
python3 subprocess_reader.py 6,56s user 0,13s system 58% cpu 11,410 total
~/D/w/tmp ❯❯❯ time python3 pysam_filter.py 
87329 reads were removed.
python3 pysam_filter.py 13,82s user 0,14s system 97% cpu 14,324 total
```

I understand the library must have some overhead to organize the reads information, but I don't believe it explains the difference of almost 2x. Any advice? Am I doing anything stupid maybe?

Follows the code for both alternatives:

_subprocess_

```
with open('temp_.bam', 'wb') as outstream:
    samview = subprocess.Popen(['samtools', 'view', '-h', sam_path],
                               stdout=subprocess.PIPE,
                               stderr=subprocess.DEVNULL)
    bamview = subprocess.Popen(['samtools', 'view', '-bS', '-'],
                               stdin=subprocess.PIPE,
                               stdout=outstream,
                               stderr=subprocess.DEVNULL)
    bamstream = bamview.stdin
    n = 0
    for line in samview.stdout:
        dline = line.decode('ascii')
        if not dline.startswith('@'):
            sequence = dline.split()[9]
            if get_edge(sequence) in to_filter:
                n += 1
                continue
        bamstream.write(line)
    print('%d reads were removed.' % n)
```

_pysam_

```
with AlignmentFile(sam_path, 'rb') as samfile, AlignmentFile(
        'temp.bam', 'wb', template=samfile) as filtered:
    n = 0
    for entry in samfile.fetch(until_eof=True):
        if get_edge(entry.query_sequence) not in to_filter:
            filtered.write(entry)
        else:
            n += 1
    print('%d reads were removed.' % n)
```

**Comment by AndreasHeger** [comment]
Thanks, that is useful feed-back. You are not doing anything wrong. I would have expected pysam to  equally fast as it should implement lazy parsing and thus minimize any unneeded conversion. I will investigate.

Best, Andreas

**Comment by kyleabeauchamp** [comment]
Have you looked at your CPU load in top while doing this analysis?  Using popen means you are doing a multi-threaded computation and essentially sidestepped the GIL.

**Comment by AndreasHeger** [comment]
@kyleabeauchamp likely explains this, closing it for now (though some more benchmarking of pysam is sorely needed).
