### ISSUE TITLE
VCF v4.2 is not supported by pysam.cvcf

### ISSUE THREAD

**Issue by fiapinto** [pysam-developers/pysam#211]
Hi,
I have been using pysam (release 0.8.4) to access VCF v4.1 files without any problems but I am not able to open a VCF v4.2.

I have replaced the header line "##fileformat=VCFv4.2" to "##fileformat=VCFv4.1", which allows the file to be opened, but then I get parsing errors from other header lines that are written in VCF v4.2 format.

So as far as I can tell, VCF v4.2 is not yet supported by pysam.

One of your developers told me about the API pysam.VariantFile. I tried to open and read a VCF v4.2 with the API and it did work.

However, I already have a pipeline implemented using pysam.cvcf and I would rather not to have to change it.

Is it possible to make pysam.cvcf work with VCF v4.2?

Another question, with this API will pysam.cvcf still be used or will it become obsolete?

Thanks,
Sofia

**Comment by AndreasHeger** [comment]
Thanks, We will add VCF v4.2 compatibility to pysam.cvcf and we will continue to support cvcf as a reference implementation of a validating parser. However, the default and high-performing API will be pysam.VariantFile.

This part of the code is still under development and thus not well documented, please bear with us.
