### ISSUE TITLE
pysam.sort doesn't play well with nosetests output buffering on python 3

### ISSUE THREAD

**Issue by timodonnell** [pysam-developers/pysam#219]
There seems to be a problematic interaction between `pysam.sort` and nosetests output buffering on python 3, which we've hit in one of our [projects](https://github.com/hammerlab/varlens). Running with output buffering disabled (`nosetests -s`) succeeds, but running with `nosetests .` gives this error:

```
======================================================================
ERROR: test.test_reads.test_round_trip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tim/venvs/py3/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tim/sinai/git/varlens/test/test_reads.py", line 97, in test_round_trip
    "--out", out,
  File "/Users/tim/sinai/git/varlens/varlens/commands/reads.py", line 119, in run
    pysam.sort("-o", args.out, "-T", "varlens_reads", args.out)
  File "/Users/tim/venvs/py3/lib/python3.4/site-packages/pysam/__init__.py", line 74, in __call__
    self.dispatch, args, catch_stdout=kwargs.get("catch_stdout", True))
  File "pysam/csamtools.pyx", line 85, in pysam.csamtools._samtools_dispatch (pysam/csamtools.c:3166)
nose.proxy.UnsupportedOperation: fileno
-------------------- >> begin captured stdout << ---------------------
Sorting.
```

Any idea? Thanks!

**Comment by humburg** [comment]
I had a similar issue and found that an alternative to running nosetests without output buffering is to call `pysam.sort` with `catch_stdout=False`, which is fine if you provide an output file name explicitly. The way things stand at the moment you have to choose between *pysam* and *nosetests* for capturing output (which I would consider to be an issue with nose rather than pysam).

**Comment by timodonnell** [comment]
That fixed it, thanks @humburg !
