### ISSUE TITLE
PySAM VCF reading doesn't split INFO field

### ISSUE THREAD

**Issue by david4096** [pysam-developers/pysam#221]
I presume this should be an issue against samtools, but having only tested against pysam I'm reporting it here.

Info fields can be split using a comma separated convention and pyvcf correctly handles this case, while pysam appears to ignore the comma separator.

https://gist.github.com/david4096/925f6ebad62fa0bec0e6

**Comment by AndreasHeger** [comment]
Thanks, I will take a look.

**Comment by bioinformed** [comment]
The soon-to-be-released version of pysam does the right thing in this case.  Feel free to give this branch a try:  https://github.com/bioinformed/pysam

Note that pysam still does not match pyvcf exactly, since it returns tuples and not lists for non-scalar INFO and FORMAT values.

**Comment by david4096** [comment]
Thanks @bioinformed!
