### ISSUE TITLE
Inconsistent reference bases in get_aligned_pairs(with_seq=True) on same reference positions

### ISSUE THREAD

**Issue by olingerc** [pysam-developers/pysam#225]
It could be that I do not understand something completely, but here is my issue:

I use pileups to get all reads on a certain position. I wanted to get the base in the reference, so I iterate over get_aligned_pairs(with_seq=True) and take the tuple that has my reference position in it. Logically, I expected to have the same reference base for all of the reads (sometimes lowercase for substitutions). I did not expect to have a different base for some reads? How is that possible? Here the code and the output:

```python
# 7577625 is my position in the reference
for alignment_tuple in enumerate(pileupread.alignment.get_aligned_pairs(with_seq=True)):
   if alignment_tuple[1] == 7577625:
      print(alignment_tuple)
```

```
...
(92, 7577625, 'C')
(92, 7577625, 'C')
(93, 7577625, 'c')
(92, 7577625, 'C')
(93, 7577625, 'c')
(93, 7577625, 'c')
(93, 7577625, 'c')
(92, 7577625, 'C')
(92, 7577625, 'C')
(96, 7577625, 'A') # What ???
(92, 7577625, 'C')
(92, 7577625, 'C')
(92, 7577625, 'C')
...
```

**Comment by iskandr** [comment]
That definitely breaks my expectations for how `get_aligned_pairs` works.

**Comment by AndreasHeger** [comment]
Hi @olingerc , many thanks, that looks like a bug. Could you provide example data? 

Best wishes,
Andreas

**Comment by olingerc** [comment]
I've put the bam file [here](http://1drv.ms/1TuUGkc)
It is assembled to hg19 and contains a lot of adapter sequences and such so it is real "dirty".

**Comment by AndreasHeger** [comment]
Thanks! I should be looking at chr1, 7577625?

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
found it (chr17).

**Comment by olingerc** [comment]
Yep. 17. Sorry for not mentioning it.

**Comment by AndreasHeger** [comment]
Thanks, @olingerc , your data expose a pretty serious, conceptual bug. Basically, get_reference_sequence did not treat insertions and deletions properly and as a consequence get_aligned_pairs() was off.
