### ISSUE TITLE
Default RNEXT and PNEXT to '*'

### ISSUE THREAD

**Issue by jpfeil** [pysam-developers/pysam#236]
I am writing BAM files from scratch using pysam and I am trying to set RNEXT and PNEXT to \* because I cannot make any assumptions about the next position in the template. However, when I ignore this attribute, pysam defaults to =. Pysam requires that this field be the index of the reference, but I would like to set it to *. Please let me know if there is a way to do this.

**Comment by AndreasHeger** [comment]
This is now possible.
