### ISSUE TITLE
htslib 1.3 test samtools index: "ex2_truncated.bam" is corrupted or unsorted

### ISSUE THREAD

**Issue by smoe** [pysam-developers/pysam#238]
Hello,
compiling on Ubutu trusty, I run into
<pre>
make[2]: Entering directory `/home/steffen/debian-med/git/python-pysam/tests/pysam_data'
samtools index ex2_truncated.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
samtools index: "ex2_truncated.bam" is corrupted or unsorted
make[2]: *** [ex2_truncated.bam.bai] Error 1
</pre>
which was reported on the Debian sides of life before
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814765
and interpreted as an intermezzo with another version of htslib (1.3) that Debian ship separately. Your upcoming 8.5 is expected to fix that one, but is there possibly a chance to become less htslib-version sensitive here?
Cheers,
Steffen

**Comment by AndreasHeger** [comment]
Hi @smoe , this should indeed be fixed in the new version - the index of the truncated BAM file is not being built any more.
Best wishes,
Andreas
