### ISSUE TITLE
Redirected stdout (e.g., with pysam.idxstats) now has a different format

### ISSUE THREAD

**Issue by dpryan79** [pysam-developers/pysam#245]
In versions previous to 0.9.0, a command like `pysam.idxstats("foo.bam")` would produce a list of lines. In 0.9.0, one instead gets a single string of everything. Thus, instead of:

    >>> pysam.idxstats('foo.bam')
    ['1\t195471971\t13186418\t21638\n', '10\t130694993\t8695225\t14791\n', '11\t122082543\t8350803\t15876\n', ...

one now gets:

    >>> pysam.idxstats('foo.bam')
    '1\t195471971\t13186418\t21638\n10\t130694993\t8695225\t14791\n11\t122082543\t8350803\t15876\n12\t120129022\t8021634\t27456\n13\t120421639\t8119102\t19602\n14\t124902244\t8548846\t74064\n15\t104043685\t6917153\t12046\n16\t98207768\t6453436\t14843\n17\t9...

Granted, one can `foo.strip().split('\n')` on the output, but any code that uses this now needs to be updated.

**Comment by dpryan79** [comment]
Relatedly, `pysam.index()` seems to no longer work inside a doctest. It looks like `sys.stdout` or `sys.stderr` are being reassigned to a StringIO or something like that, which crashes thing:

    File "/home/dpryan/.local/lib/python2.7/site-packages/deeptools/correctGCBias.py", line 298, in deeptools.correctGCBias.writeCorrectedSam_worker
    Failed example:
        idx = pysam.index(tempFile)
    Exception raised:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/doctest.py", line 1315, in __run
            compileflags, 1) in test.globs
          File "<doctest deeptools.correctGCBias.writeCorrectedSam_worker[4]>", line 1, in <module>
            idx = pysam.index(tempFile)
          File "/home/dpryan/.local/lib/python2.7/site-packages/pysam/utils.py", line 56, in __call__
            catch_stdout=kwargs.get("catch_stdout", True))
          File "pysam/cutils.pyx", line 385, in pysam.cutils._pysam_dispatch (pysam/cutils.c:6242)
          File "pysam/cutils.pyx", line 386, in pysam.cutils._pysam_dispatch (pysam/cutils.c:5971)
          File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
            return self.gen.next()
          File "pysam/cutils.pyx", line 241, in stdout_redirector (pysam/cutils.c:4841)
        AttributeError: _SpoofOut instance has no attribute 'fileno'

**Comment by dpryan79** [comment]
Ah, the `_SpoofOut` stuff is a known issue with doctests, please ignore that.

**Comment by AndreasHeger** [comment]
Thanks, @dpryan79 , that will be helpful.

Indeed, the returned stdout of samtools is now unsplit. This was because a some commands
provide non-textual output and splitting on new-line chars would not have made sense.

On hindsight, I should have made this change optional. I will introduce an option to return
split output in the next version that will optionally restore the old behaviour, though I suggest the default should now remain the unsplit output.

**Comment by dpryan79** [comment]
@AndreasHeger Makes sense, thanks!

**Comment by kyleabeauchamp** [comment]
If the old functions support **kwargs, it might be possible to make the fix backwards compatible.  E.g.

```
lines = pysam.bedcov(bed, bam, old_school=True)
```

Also, I think the issue with doctest also indicates an issue running these commands from an IPython session.

**Comment by kyleabeauchamp** [comment]
I have verified that on pysam 0.8.4, I can add an optional kwarg without any negative consequences:

```
x = pysam.bedcov("./ex1.bed", "ex1.bam", oldschool=True)
```

This will help downstream software implement code that doesn't have to do pysam version checking.

**Comment by kyleabeauchamp** [comment]
You could even just add something simple like the following:


```
if old_style_output:
    result = "\n".join(result)
```

**Comment by AndreasHeger** [comment]
Thanks! I would prefer "split_lines" as the name of the parameter. old_school requires a lot of context to understand.

On my todo list is also to have samtools/bcftools command accept kwarg arguments. For bcftools, they could be automatically derived by inspection from the command line help.

Best wishes,
Andreas

**Comment by kyleabeauchamp** [comment]
I think you meant to close #257

**Comment by AndreasHeger** [comment]
Apologies!
