### ISSUE TITLE
Regression in v0.9.0

### ISSUE THREAD

**Issue by mdshw5** [pysam-developers/pysam#246]
I've noticed a regression when running my unit tests under pysam-0.9.0. You can see on [line 185](https://travis-ci.org/mdshw5/pyfaidx/jobs/107766571) of the CI log file that my builds are passing in py2.6-3.5 as well as pypy/3 when using pysam-0.8.4. However, after running a new integration test (for a change unrelated to the code using pysam) my test [utilizing pysam now fails](https://travis-ci.org/mdshw5/pyfaidx/builds/113426831) in py2.7.9 with pysam-0.9.0. The test only fails on py2.7, and so far I haven't taken the time to reproduce the failure on 2.7.10, so maybe this is something that only shows up with 2.7.9.

**Comment by mdshw5** [comment]
Let me know how I can help further reproduce this issue for you.

**Comment by AndreasHeger** [comment]
Thanks, I think I will need some help. Are you referring to messages such as:

>ERROR: test_all_diff (test_FastaVariant.TestFastaVariant)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/home/travis/build/mdshw5/pyfaidx/tests/test_FastaVariant.py", line 57, in test_all_diff
>    assert all(ref['22'][pos-1] != fasta['22'][pos-1] for pos in fasta['22'].variant_sites)
>  File "/home/travis/build/mdshw5/pyfaidx/pyfaidx/__init__.py", line 599, in variant_sites
 >  var = self._fa.vcf.fetch(self.name, 0, len(self))
 > File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/vcf/parser.py", line 599, in fetch
 >   self.reader = self._tabix.fetch(chrom, start, end)
>  File "pysam/ctabix.pyx", line 403, in pysam.ctabix.TabixFile.fetch (pysam/ctabix.c:4618)
> ValueError: start out of range (49691432)

If so, what is the size of chromosome 22?
