### ISSUE TITLE
Compilation error of htslib/hfile_libcurl.c:125  OSX 10.9.5  Py 2.7.11

### ISSUE THREAD

**Issue by tmargus** [pysam-developers/pysam#247]
Hi,
I get an compilation error for htslib when running pysam installation script 
`python setup.py `build``   
but compiling htslib separately (in htslib folder ./configure   and make ) runs without errors.

I am using:
OS-X ver 10.9.5
Python  ver 2.7.11 (virtual environment created under anaconda)

Best,
Tonu

Screen output:
`tmargus@:pysam-0.9.0$ python setup.py build 
# pysam: htslib mode is shared
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for curl_easy_pause in -lcurl... yes
checking for CCHmac... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating config.h
# pysam: htslib configure options: --enable-libcurl
# pysam: libcurl of builtin htslib has been enabled, adding shared libcurl and libcrypto
running build
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-2.7
creating build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/bcftools.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/config.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/namedtuple.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/Pileup.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/samtools.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/utils.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/version.py -> build/lib.macosx-10.5-x86_64-2.7/pysam
creating build/lib.macosx-10.5-x86_64-2.7/pysam/include
copying pysam/include/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/pysam/include
package init file 'htslib/__init__.py' not found (or not a regular file)
package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
package init file 'samtools/__init__.py' not found (or not a regular file)
package init file 'bcftools/__init__.py' not found (or not a regular file)
package init file 'samtools/win32/__init__.py' not found (or not a regular file)
copying pysam/calignedsegment.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/calignmentfile.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/cbcf.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/cfaidx.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/chtslib.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/csamfile.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/ctabix.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/ctabixproxies.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/cutils.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/cvcf.pxd -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/htslib_util.h -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/pysam_stream.h -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/pysam_util.h -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/samfile_util.h -> build/lib.macosx-10.5-x86_64-2.7/pysam
copying pysam/tabix_util.h -> build/lib.macosx-10.5-x86_64-2.7/pysam
creating build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib
copying htslib/config.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib
copying htslib/hfile_internal.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib
copying htslib/hts_internal.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib
copying htslib/version.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib
creating build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/bgzf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/cram.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/faidx.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/hfile.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/hts.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/hts_defs.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/kbitset.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/kfunc.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/khash.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/khash_str2int.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/klist.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/knetfile.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/kseq.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/ksort.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/kstring.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/regidx.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/sam.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/synced_bcf_reader.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/tbx.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/vcf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/vcf_sweep.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
copying htslib/htslib/vcfutils.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/htslib/htslib
creating build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/bam.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/bam2bcf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/bam_endian.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/bam_lpileup.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/bam_plbuf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/bam_tview.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/errmod.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/kprobaln.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/pysam.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/sam.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/sam_header.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/sam_opts.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/sample.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/samtools.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/stats_isize.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
copying samtools/version.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools
creating build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/bcftools.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/call.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/convert.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/filter.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/gvcf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/HMM.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/khash_str2str.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/kmin.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/ploidy.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/prob1.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/pysam.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/rbuf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/tsv2vcf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/vcmp.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
copying bcftools/version.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/bcftools
creating build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools/win32
copying samtools/win32/xcurses.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools/win32
copying samtools/win32/zconf.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools/win32
copying samtools/win32/zlib.h -> build/lib.macosx-10.5-x86_64-2.7/pysam/include/samtools/win32
running build_ext
cythoning pysam/chtslib.pyx to pysam/chtslib.c
building 'pysam.libchtslib' extension
creating build/temp.macosx-10.5-x86_64-2.7
creating build/temp.macosx-10.5-x86_64-2.7/pysam
creating build/temp.macosx-10.5-x86_64-2.7/htslib
creating build/temp.macosx-10.5-x86_64-2.7/htslib/cram
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c pysam/chtslib.c -o build/temp.macosx-10.5-x86_64-2.7/pysam/chtslib.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c pysam/htslib_util.c -o build/temp.macosx-10.5-x86_64-2.7/pysam/htslib_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c htslib/bgzf.c -o build/temp.macosx-10.5-x86_64-2.7/htslib/bgzf.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c htslib/faidx.c -o build/temp.macosx-10.5-x86_64-2.7/htslib/faidx.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c htslib/hfile.c -o build/temp.macosx-10.5-x86_64-2.7/htslib/hfile.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c htslib/hfile_libcurl.c -o build/temp.macosx-10.5-x86_64-2.7/htslib/hfile_libcurl.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
htslib/hfile_libcurl.c: In function ‘easy_errno’:
htslib/hfile_libcurl.c:125: error: ‘ENOTRECOVERABLE’ undeclared (first use in this function)
htslib/hfile_libcurl.c:125: error: (Each undeclared identifier is reported only once
htslib/hfile_libcurl.c:125: error: for each function it appears in.)
error: command 'gcc' failed with exit status 1
`

**Comment by kyleabeauchamp** [comment]
Do you need libcurl support?  I think you should be able to get the build to work with libcurl disabled by doing this export before calling setup.py: `export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"`

**Comment by jmarshall** [comment]
You must have quite an old Xcode.  Anyway, you can fix this by applying samtools/htslib@ae4c86a17c950925a2861a5ad38c5e8552cd838c.

**Comment by tmargus** [comment]
Thanks a lot
I am using Xcodec version 6.2
`export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"`
helps overcome this particular problem but `python setup.py build` fails a little later when it tries compile executable from *.o & *.so files. 

`......
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c htslib/cram/vlen.c -o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/vlen.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -fno-strict-aliasing -I/Users/tmargus/anaconda/envs/py27/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ipysam -I. -Ihtslib -I/Users/tmargus/anaconda/envs/py27/include/python2.7 -c htslib/cram/zfio.c -o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/zfio.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
gcc -undefined dynamic_lookup -L/Users/tmargus/anaconda/envs/py27/lib -isysroot /Developer/SDKs/MacOSX10.5.sdk -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/pysam/chtslib.o build/temp.macosx-10.5-x86_64-2.7/pysam/htslib_util.o build/temp.macosx-10.5-x86_64-2.7/htslib/bgzf.o build/temp.macosx-10.5-x86_64-2.7/htslib/faidx.o build/temp.macosx-10.5-x86_64-2.7/htslib/hfile.o build/temp.macosx-10.5-x86_64-2.7/htslib/hfile_net.o build/temp.macosx-10.5-x86_64-2.7/htslib/hts.o build/temp.macosx-10.5-x86_64-2.7/htslib/kfunc.o build/temp.macosx-10.5-x86_64-2.7/htslib/knetfile.o build/temp.macosx-10.5-x86_64-2.7/htslib/kstring.o build/temp.macosx-10.5-x86_64-2.7/htslib/md5.o build/temp.macosx-10.5-x86_64-2.7/htslib/plugin.o build/temp.macosx-10.5-x86_64-2.7/htslib/regidx.o build/temp.macosx-10.5-x86_64-2.7/htslib/sam.o build/temp.macosx-10.5-x86_64-2.7/htslib/synced_bcf_reader.o build/temp.macosx-10.5-x86_64-2.7/htslib/tbx.o build/temp.macosx-10.5-x86_64-2.7/htslib/vcf.o build/temp.macosx-10.5-x86_64-2.7/htslib/vcf_sweep.o build/temp.macosx-10.5-x86_64-2.7/htslib/vcfutils.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_codecs.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_decode.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_encode.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_external.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_index.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_io.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_samtools.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/cram_stats.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/files.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/mFILE.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/open_trace_file.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/pooled_alloc.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/rANS_static.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/sam_header.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/string_alloc.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/thread_pool.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/vlen.o build/temp.macosx-10.5-x86_64-2.7/htslib/cram/zfio.o -Lpysam -L. -Lbuild/lib.macosx-10.5-x86_64-2.7/pysam -L/Users/tmargus/anaconda/envs/py27/lib -Lpysam -L. -Lbuild/lib.macosx-10.5-x86_64-2.7/pysam -lz -o build/lib.macosx-10.5-x86_64-2.7/pysam/libchtslib.so -dynamiclib -rpath /Users/tmargus/anaconda/envs/py27/lib/python2.7/site-packages -Wl,-headerpad_max_install_names -Wl,-install_name,@rpath/pysam-0.9.0-py2.7-macosx-10.5-x86_64.egg/pysam/libchtslib.so -Wl,-x
ld: in /Users/tmargus/anaconda/envs/py27/lib/python2.7/site-packages, can't map file, errno=22
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1`

**Comment by AndreasHeger** [comment]
Thanks. The following seems relevant:

http://stackoverflow.com/questions/16436333/cant-map-file-errno-22-for-architecture-x86-64

Does the directory /Users/tmargus/anaconda/envs/py27/lib/python2.7/site-packages exist or is
there anything odd with it or in it?

Apologies, I don't often compile on OSX

**Comment by tmargus** [comment]
Many thanks Andreas. You comment and reference was really helpful.

The directory `/Users/tmargus/anaconda/envs/py27/lib/python2.7/site-packages`  exists and missing `-I` before it is systematic error for compiling in this virtual environment.  I overcome it a bit forceful way by adding -I every time when compilation gives `error=22` and then run `python setup.py install` again. 

Only reason I have to install pysam under python 2 is because it is prerequisite for HTSeq and HTSeq is supports Python 2 so far.  Python3 version installs easily with `pip install pysam`
