### ISSUE TITLE
Should set_tag support long integer arrays?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#250]
I was playing with the code in https://github.com/pysam-developers/pysam/blob/master/benchmark/AlignedSegment_bench.py#L12 and I noticed that pysam gives an exception (python 2.7, pysam 0.9) when I change the array type to unsigned 4 byte integers.  

```
        read.set_tag('FZ', array.array('B', range(10)))  # Works fine
        read.set_tag('FZ', array.array('H', range(10)))  # Works fine
        read.set_tag('FZ', array.array('L', range(10)))  # Error shown below


Exception ValueError: ValueError("unknown conversion for array typecode '76'",) in 'pysam.calignedsegment.map_typecode_python_to_htslib' ignored

pysam/calignedsegment.pyx in pysam.calignedsegment.AlignedSegment.set_tag (pysam/calignedsegment.c:19424)()

pysam/calignedsegment.pyx in pysam.calignedsegment.AlignedSegment.set_tag (pysam/calignedsegment.c:18888)()

pysam/calignedsegment.pyx in pysam.calignedsegment.packTags (pysam/calignedsegment.c:5253)()

ValueError: invalid value type '' (<type 'str'>)

```

**Comment by kyleabeauchamp** [comment]
See #252.  Currently it seems that things fail for types l, L, and d.

**Comment by kyleabeauchamp** [comment]
FYI @AndreasHeger : PR #252 was now merged, but that means the master tests are probably going to be failing now on the cases of I, L, and d.  We can either fix those dtypes for arrays or I can adjust the tests to skip those cases for now.

**Comment by AndreasHeger** [comment]
Thanks! I am working on it now. What is failing is actually the error propagation of "unknown" type codes. Once that is fixed, we can modify the tests or look into supporting l, L and d.

**Comment by kyleabeauchamp** [comment]
SGTM, I just wanted to make sure you had a heads-up for why your tests might be failing :)

**Comment by AndreasHeger** [comment]
Thanks!

**Comment by kyleabeauchamp** [comment]
The answer to this is no: not all dtypes are supported.  We have implemented better type checking and tests for all supported and unsupported dtypes in array tags.  See the following commits:

https://github.com/pysam-developers/pysam/pull/252

https://github.com/pysam-developers/pysam/commit/c1757c1b5d798b7f7177fe1a43e9708d1aed55c9
