### ISSUE TITLE
cannot import name csamtools

### ISSUE THREAD

**Issue by hkkme** [pysam-developers/pysam#253]
I have installed pysam with pip and it works fine, but `from pysam import csamtools` gives me this error: `cannot import name csamtools`. I have installed samtools. Do I have to configure or install csamtools separately? If so, how? Thanks!

**Comment by AndreasHeger** [comment]
Thanks, there should be no need to import csamtools directly as all functionality is brought into the pysam main package. What is your use case?

**Comment by timeu** [comment]
I guess some 3rd party tools still import it (see https://github.com/elzbth/jitterbug/issues/2). 
In which verison of pysam was csamtools removed ?

**Comment by AndreasHeger** [comment]
Hi, csamtools was renamed to libcsamtools in version 0.10.0. I have added a text to the FAQ.

**Comment by Lila14** [comment]
I also need csamtools for a 3rd party tool. I tried installing 0.9.1.4 but still get the same error. I'm confused because it seems like libcsamtools.pxd wasn't added until 0.11.

**Comment by emrahkirdok** [comment]
Hi,

I am trying to install pysam through pip. Installation is ok but I have the exact same problem on importing csamtools. I have the latest version of pysam (0.14.1). On the FAQ of pysam (http://pysam.readthedocs.io/en/latest/faq.html), there is an information on this issue but I don't understand how to solve it. 

I will be very happy if you can help me.

**Comment by stupidstupidstupidstupid** [comment]
I met the same question in pysam-win
