### ISSUE TITLE
Installation on Python 3 misses Cython dependency (0.9.0 regression)

### ISSUE THREAD

**Issue by martijnvermaat** [pysam-developers/pysam#260]
Since release 0.9.0, `pip install pysam` on Python 3 fails because Cython is missing:

```
$ virtualenv -p `which python3.5` py35
$ . py35/bin/activate
$ pip install pysam
Collecting pysam
  Using cached pysam-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    checking for gcc... gcc
    checking whether the C compiler works... yes
...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8096gdno/pysam/setup.py", line 290, in <module>
        .format(fn))
    ValueError: no cython installed, but can not find pysam/chtslib.c.Make sure that cython is installed when building from the repository
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8096gdno/pysam
```

Release 0.8.4 was good.

I tested Python 3.3, 3.4, and 3.5, they all fail in the same way. Python 2.7 seems to be good though, I'm not sure why.

It looks like the `requires` argument to setup is ignored (it lists `cython (>=0.21)`). I have no idea what causes this, but there have been quite some changes to `setup.py` since 0.8.4.

**Comment by zyxue** [comment]
I looked a bit into this issue, here is what I found. With python-2.7 and pip-8.1.1, `pip install pysam` finishes successfully, but it doesn't install cython, either. Instead, it uses the `pysam/chtslib.c` that comes with `pysam-0.9.0.tar.gz`. You can check the stuffs inside the tar ball after `pip download pysam`.

The steps are shown as below
```
pip --version
pip 8.1.1 from /path/to/venv2/local/lib/python2.7/site-packages (python 2.7)
```
```
pip download pysam
Collecting pysam
  Using cached pysam-0.9.0.tar.gz
  Saved ./pysam-0.9.0.tar.gz
Successfully downloaded pysam
```
However, if I repeat the above process with Python-3.5 (I used Python-3.5 from Anaconda3, so the virtual environment layout is a bit different from python-2.7)
```
pip --version
pip 8.1.1 from /path/to/venv3/lib/python3.5/site-packages (python 3.5)
```
```
pip download pysam
Collecting pysam
  Using cached pysam-0.9.0.tar.gz
  Saved ./pysam-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
 ...
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for curl_easy_pause in -lcurl... no
    checking for curl_easy_init in -lcurl... no
    configure: error: libcurl library not found
    
    Support for HTTPS and other SSL-based URLs requires routines from the libcurl
    library <http://curl.haxx.se/libcurl/>.  Building HTSlib with libcurl enabled
    requires libcurl development files to be installed on the build machine; you
    may need to ensure a package such as libcurl4-{gnutls,nss,openssl}-dev (on
    Debian or Ubuntu Linux) or libcurl-devel (on RPM-based Linux distributions)
    is installed.
    
    Either configure with --disable-libcurl or resolve this error to build HTSlib.
    # pysam: htslib mode is separate
    # pysam: htslib configure options: None
    # pysam: could not configure htslib, choosing conservative defaults
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gr629jb_/pysam/setup.py", line 290, in <module>
        .format(fn))pip --version
pip 8.1.1 from /home/zxue/Downloads/lele/venv2/local/lib/python2.7/site-packages (python 2.7)
(venv2)cluster-3-m[0]:pip download pysam
Collecting pysam
  File was already downloaded /home/zxue/Downloads/lele/pysam-0.9.0.tar.gz
Successfully downloaded pysam

    ValueError: no cython installed, but can not find pysam/chtslib.c.Make sure that cython is installed when building from the repository
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gr629jb_/pysam/
```
I am not sure why pip tries to look into the tar ball even if it's just a **download** command. Does it look like a problem of pip or setup.py for Python3? I am not sure how to debug pip or setup.py, pdb doesn't seem to very informative when it involves compiling C code.

Also strangely, since it's the same tarball from that downloaded by python-2.7, the `chtslib.c` is indeed there.
```
ls pysam-0.9.0/pysam/chtslib.c 
pysam-0.9.0/pysam/chtslib.c
```

**Comment by zyxue** [comment]
I've found the problematic [lines](https://github.com/pysam-developers/pysam/blob/7e51ff34c5344302fe92a5a3c4c8f43b4b3b047d/setup.py#L284):
```
# remove existing files to recompute
# necessary to be both compatible for python 2.7 and 3.3
if IS_PYTHON3:
    for part in parts:
        try:
            os.unlink("pysam/c%s.c" % part)
        except:
            pass
```
which basically removes the `pysam/c%s.c` that comes with the tar ball downloaded by pip. I wonder what's the intention of such removal?

Also, since `pysam/c%s.c` files are ignored in `.gitignore`, how are they generated during a release for PyPI? It seems haven't been documented on http://pysam.readthedocs.org/en/latest/developer.html yet.

**Comment by zyxue** [comment]
I don't if the unlink part is really necessary. I downloaded `pysam-0.9.0.tar.gz`, commented out the above code section in `setup.py`, and then run `python setup.py install` using python3, it finishes successfully.

**Comment by AndreasHeger** [comment]
Thanks, this has already been fixed in my local repos and will be part of the next bugfix release (very soon).

See also here:

https://groups.google.com/forum/#!topic/pysam-user-group/5TP_1P2EeNw

Best wishes,
Andreas

**Comment by zyxue** [comment]
Thanks, Andreas, but I just wonder if cython can be installed as depency or not? It seems not to me.  For example, on this post, http://stackoverflow.com/questions/18023546/marking-cython-as-a-build-dependency, it says that you'd better provide the platform independent c code if `setup.py` finds there is no cython installed yet on the user's side.

**Comment by hanfeisun** [comment]
+1 for cython dependency missing on python3

**Comment by zyxue** [comment]
@hanfeisun I don't think cython can be specified as a dependency at all in `setup.py`, even if it's specified, it seems to be ignored. In Python2.7, it's actually the pre-generated C code that comes together `pysam` getting used.

**Comment by golharam** [comment]
This issue still exists:
```
$ python3.6 -m venv env
$ source env/bin/activate
(env) $ which pip
/scratch/env/bin/pip
$ pip install pysam
Collecting pysam
  Using cached https://files.pythonhosted.org/packages/25/7e/098753acbdac54ace0c6dc1f8a74b54c8028ab73fb027f6a4215487d1fea/pysam-0.15.4.tar.gz
    Complete output from command python setup.py egg_info:
    # pysam: no cython available - using pre-compiled C
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oa2dhqq3/pysam/setup.py", line 193, in <module>
        .format(fn))
    ValueError: no cython installed, but can not find pysam/libchtslib.c.Make sure that cython is installed when building from the repository
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oa2dhqq3/pysam/
```

**Comment by erdanieee** [comment]
> This issue still exists:
> 
> ```
> $ python3.6 -m venv env
> $ source env/bin/activate
> (env) $ which pip
> /scratch/env/bin/pip
> $ pip install pysam
> Collecting pysam
>   Using cached https://files.pythonhosted.org/packages/25/7e/098753acbdac54ace0c6dc1f8a74b54c8028ab73fb027f6a4215487d1fea/pysam-0.15.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     # pysam: no cython available - using pre-compiled C
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-oa2dhqq3/pysam/setup.py", line 193, in <module>
>         .format(fn))
>     ValueError: no cython installed, but can not find pysam/libchtslib.c.Make sure that cython is installed when building from the repository
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oa2dhqq3/pysam/
> ```

`pip install --upgrade pip` solves the problem!
