### ISSUE TITLE
Unbundling samtools

### ISSUE THREAD

**Issue by SoapGentoo** [pysam-developers/pysam#261]
Dear Andreas,
given your efforts of allowing users to use the system htslib, could the same also be achived for samtools (and bcftools?) we at Gentoo would like to unbundle all bundled libs, as this makes maintenance easier and reduces fixing when a bug is found in one samtools version. Thanks for your time.

**Comment by AndreasHeger** [comment]
Dear @SoapGentoo, many thanks for your suggestion, but I would believe this to be impractical. Samtools/bcftools are command line tools and provide no API. The samtools/bcftools versions within pysam are stripped of the main() functions and heavily patched to achieve stderr redirection and resolve naming conflicts such as two "merge" functions of the same name.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Thanks, closing this for now.
