### ISSUE TITLE
Support for bams on S3

### ISSUE THREAD

**Issue by msto** [pysam-developers/pysam#263]
Hi,

Are there plans to provide support for bams on S3? This functionality was recently added in samtools 1.3, but I get an `IOError` "File not found" when I try to create an `AlignmentFile` based off an S3 path.

Thanks!

**Comment by AndreasHeger** [comment]
Hi @msto, S3 support should be already present through htslib. Do you have an example code snippet and/or example data to test? Best wishes, Andreas

**Comment by msto** [comment]
Hi Andreas,

I worked around the problem when I first encountered it and haven't needed the functionality again since. However, I recently tried again and I'm still facing troubles accessing bams hosted on S3.

The example is pretty straightforward. The following samtools command works:

```$ samtools view s3://path/to/bam```

But the following pysam code does not:

```
In [1]: import pysam                                                                                                                                                                                                                                                    [8/1570]
In [2]: bam = pysam.AlignmentFile('s3://path/to/bam')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-3f85d0d43729> in <module>()
----> 1 bam = pysam.AlignmentFile('s3://path/to/bam')

pysam/libcalignmentfile.pyx in pysam.libcalignmentfile.AlignmentFile.__cinit__ (pysam/libcalignmentfile.c:5831)()

pysam/libcalignmentfile.pyx in pysam.libcalignmentfile.AlignmentFile._open (pysam/libcalignmentfile.c:7556)()

OSError: file `b's3://path/to/bam'` not found
```

I'm using htslib 1.4.1 and pysam 0.11.1, installed through anaconda. However, I also tried uninstalling pysam and reinstalling from source with `pip install --no-binary`. I tried both setting the appropriate options for an internal htslib compilation and explicitly linking to the installed htslib, per the [docs](https://pysam.readthedocs.io/en/latest/installation.html), but neither worked.

Could you please let me know if there's a configuration option I'm missing or if there's a different approach to try?

Thanks!

**Comment by kyleabeauchamp** [comment]
If you can use the S3 HTTPS protocol, that should work in the interim.

Regarding S3 proper access: it appears we currently have tests for direct S3 access, so we may need to add some tests to the suite.

**Comment by kyleabeauchamp** [comment]
*edit* meant to say we lack tests...

**Comment by msto** [comment]
Hi Kyle,

Thanks for the quick response. The bucket isn't publicly accessible, so I don't think I can use the https protocol. (At least, I hit a 403 error when I try.) I can pipe in from samtools in the interim, but would appreciate the internal interface when it's available.

Thanks!

**Comment by bioinformed** [comment]
You can use a signed URL to access a private bucket via HTTPS.

**Comment by AndreasHeger** [comment]
Seems to have been resolved upstream, closing for now.
