### ISSUE TITLE
Inconsistent iteration / indexing of samples in VariantRecord

### ISSUE THREAD

**Issue by brendanofallon** [pysam-developers/pysam#265]
This isn't a bug, but the iteration behavior over samples within a VCF record when using pysam.VariantFile feels pretty inconsistent. For instance, 

```
for var in pysam.VariantFile("my.vcf"):
    sample = var.samples[0]  # Returns a VariantRecordSample object
    for sample_name in var.samples:  # But this iterates over sample names
        print sample_name
```

Not a showstopper, but feels like a 'gotcha'.

**Comment by bioinformed** [comment]
Samples follows a mapping protocol for iteration (defaults to keys), while file iteration follows a sequence protocol (defaults to records).  There is an argument to changing iteration over samples to a sequence protocol, but it would require a two-stage indexing operation (first to find the sample index, the second to extract the index).

**Comment by bioinformed** [comment]
Closing, since nobody else has piled on with concerns about the dict-vs-sequence iteration differences.
