### ISSUE TITLE
Installation fails on Python 2.6

### ISSUE THREAD

**Issue by bamyasi** [pysam-developers/pysam#266]
[xxx@yyy pysam-0.9.0]# python2.6 setup.py install
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    IS_PYTHON3 = sys.version_info.major >= 3
AttributeError: 'tuple' object has no attribute 'major'

This is a CentoOS 5 system with Python 2.6 installed:

$ python2.6 --version
Python 2.6.5

This seems to be a well known setup.py bug, see first page of Google search hits for "AttributeError: 'tuple' object has no attribute 'major'" keywords. Would be nice to have it fixed, especially considering documentation claims pysam is compatible with Python 2.6.

Thanks,
bamyasi

**Comment by AndreasHeger** [comment]
@bamyasi, pysam does not support python 2.6 and I can't find where it states that it does.

Could you point me to the right place?
Thanks,
Andreas

**Comment by kyleabeauchamp** [comment]
Found it :) #276

**Comment by AndreasHeger** [comment]
Thanks both!
