### ISSUE TITLE
FastaFile filepath_index parameter bug

### ISSUE THREAD

**Issue by david4096** [pysam-developers/pysam#270]
I'm having some trouble using the filepath_index argument of FastaFile: `pysam.FastaFile(filename, filepath_index=index)`. It appears that pysam checks for the presence of the file, but then generates a `.fai` and a `.gzi` for the Fasta alongside it regardless.

If you touch a file named like an index next to the Fasta and `chmod` it so it can't be rewritten an IOError will occur.

I wrote up a demonstration showing that the filepath_index argument might not be handled properly:

https://gist.github.com/david4096/ee80aaca8a4104eaae03da6b507c496a

**Comment by AndreasHeger** [comment]
Thanks! Indeed, specifying a filepath_index does not work. It seems there is no API in htslib to
specify the path for an index file. 

I have changed the code to raise a NotImplementedError and will raise a ticket with htslib.

**Comment by AndreasHeger** [comment]
Referenced here: https://github.com/samtools/htslib/issues/375

**Comment by AndreasHeger** [comment]
Took a while, but call to fai_load3 is now implemented.
