### ISSUE TITLE
Non-standard, uppercase RG header record tags stripped silently.

### ISSUE THREAD

**Issue by MurphyMarkW** [pysam-developers/pysam#277]
As per the comment in #71 @natechols noticed that non-standard, uppercase RG header record tags (such as PM) were being silently stripped from header records in 0.9.0. Can confirm this:

```
$ pip freeze
pysam==0.9.0
```

```python
#!/usr/bin/env python

import pysam

i = pysam.AlignmentFile('i.sam', 'r')
o = pysam.AlignmentFile('o.bam', 'wb', header=i.header)
```

```
$ cat i.sam
@HD	VN:1.5	SO:coordinate
@SQ	SN:chr1	LN:248956422
@RG	ID:1	PM:yolo

$ ./strip

$ samtools view -h o.bam
@HD	VN:1.5	SO:coordinate
@SQ	SN:chr1	LN:248956422
@RG	ID:1
```

It looks like this must be during serialization to the output bam, as the in-memory header looks good:

```python
#!/usr/bin/env python

import json
import pysam

i = pysam.AlignmentFile('i.sam', 'r')

print(json.dumps(i.header, indent=2))
```
```json
$ ./header
{
  "SQ": [
    {
      "LN": 248956422,
      "SN": "chr1"
    }
  ],
  "RG": [
    {
      "ID": "1",
      "PM": "yolo"
    }
  ],
  "HD": {
    "SO": "coordinate",
    "VN": "1.5"
  }
}
```
Looking through the code that handles header serialization, it seems that the behavior comes about from not handling unknown uppercase tags [here](https://github.com/pysam-developers/pysam/blob/master/pysam/calignmentfile.pyx#L140-L142).

I'll take a stab at putting together a pr for this tonight.

**Comment by natechols** [comment]
This seems to have fixed my problem:

https://github.com/pysam-developers/pysam/pull/274

**Comment by MurphyMarkW** [comment]
Oh hey, awesome! Closing. :)
