### ISSUE TITLE
error when importing

### ISSUE THREAD

**Issue by east-of-mars** [pysam-developers/pysam#289]
Hi,

I got this error when importing pysam:

`>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(//anaconda/lib/python3.5/site-packages/pysam/libchtslib.cpython-35m-darwin.so, 2): Library not loaded: libcurl.4.dylib
  Referenced from: //anaconda/lib/python3.5/site-packages/pysam/libchtslib.cpython-35m-darwin.so
  Reason: Incompatible library version: libchtslib.cpython-35m-darwin.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
`

Python 3.5.1 |Anaconda 2.5.0 (x86_64)
curl 7.43.0

**Comment by AndreasHeger** [comment]
Thanks, maybe there are several libcurl versions available in your system?
