### ISSUE TITLE
idxstats in python3 returns a byte object instead of a string

### ISSUE THREAD

**Issue by fidelram** [pysam-developers/pysam#292]
I am using pysam version 0.9.0 and python3.4.

When running idxstats I get a bytes object instead of an string. Python 2 returns a string.

```
>>> idxstat = pysam.idxstats(bam_file)
>>> type(idxstat)
<class 'bytes'>
```

This is problematic because if one tries to split `idxstats` and error occurs:

```
>>> idxstat.split("\n")
TypeError: a bytes-like object is required, not 'str'
```

The solution is to use `decode()` to convert the bytes object into a `str` but I think that pysam should return a string by default. 

This problem could be related to pysam opening a file as binary (see http://stackoverflow.com/questions/33054527/python-3-5-typeerror-a-bytes-like-object-is-required-not-str)

**Comment by AndreasHeger** [comment]
Thanks, it seems to work in the  development branch, I have added unit tests to make sure it does not regress.
