### ISSUE TITLE
Fetching from a CRAM file fails if multiple_iterators is False

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#293]
The following fails for CRAM files, but works for BAM files:

``` python
        for a, b in zip(samfile1.fetch(contig, start, stop,
                                       multiple_iterators=False),
                        samfile1.fetch(contig, start, stop,
                                       multiple_iterators=True)):
            self.assertEqual(a.compare(b), 0)
```

while the following works in both cases:

``` python
        for a, b in zip(samfile1.fetch(contig, start, stop,
                                       multiple_iterators=False),
                        samfile1.fetch(contig, start, stop,
                                       multiple_iterators=True)):
            self.assertEqual(a.compare(b), 0)
```

See AlignmentFile_test.py testDoubleFetchCRAMWithRegion.

**Comment by AndreasHeger** [comment]
Still an issue with latest version.

**Comment by nspies** [comment]
Any leads here? I'm having several issues parsing cram files using pysam, one of which seems to be that specifying `multiple_iterators=True` makes the fetch operation start from the beginning of the file, rather than the specified coordinates.

**Comment by spaceben** [comment]
The optional argument `multiple_iterators` in `pileup()` seems to be undocumented though.
