### ISSUE TITLE
where is release 0.9.1?

### ISSUE THREAD

**Issue by jcgu** [pysam-developers/pysam#295]
A naive question... 

I thought I installed 0.9.1 and run into an error with AttributeError as I realized that AlignedSegment.get_cigar_stats method was added in 0.9.1. Right now, the latest release on Github is 0.9.0. 

So the pysam doc version is for 0.9.1. Will the 0.9.1 version be released soon? Thanks!

**Comment by AndreasHeger** [comment]
It is coming tonight. 

I had to fix a couple  of last-minute bugs.

Best wishes, Andreas

**Comment by jcgu** [comment]
cool! look forward to it. Thank you for developing it.
