### ISSUE TITLE
Travis CI build failed with pysam install

### ISSUE THREAD

**Issue by qqss88** [pysam-developers/pysam#298]
Our Travis CI pop out the following error message related to pysam setup. Any ldea what is going on. It is running ok previously.

building 'pysam.csamfile' extension
    creating build/temp.linux-x86_64-2.7/samtools
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c pysam/csamfile.c -o build/temp.linux-x86_64-2.7/pysam/csamfile.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c pysam/htslib_util.c -o build/temp.linux-x86_64-2.7/pysam/htslib_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c pysam/samfile_util.c -o build/temp.linux-x86_64-2.7/pysam/samfile_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c samtools/kprobaln.c -o build/temp.linux-x86_64-2.7/samtools/kprobaln.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c htslib/tbx.c -o build/temp.linux-x86_64-2.7/htslib/tbx.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c htslib/plugin.c -o build/temp.linux-x86_64-2.7/htslib/plugin.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -Isamtools -I. -Ihtslib -I/opt/python/2.7.11/include/python2.7 -c htslib/hfile_libcurl.c -o build/temp.linux-x86_64-2.7/htslib/hfile_libcurl.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    htslib/hfile_libcurl.c:630:2: error: #error No HMAC() routine found by configure
    htslib/hfile_libcurl.c: In function ‘add_s3_settings’:
    htslib/hfile_libcurl.c:888:30: error: ‘DIGEST_BUFSIZ’ undeclared (first use in this function)
    htslib/hfile_libcurl.c:888:30: note: each undeclared identifier is reported only once for each function it appears in
    htslib/hfile_libcurl.c:889:9: warning: implicit declaration of function ‘s3_sign’ [-Wimplicit-function-declaration]
    error: command 'gcc' failed with exit status 1

```
----------------------------------------
```

Command "/home/travis/virtualenv/python2.7.11/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-CuTj0V/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-Wx2inG-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python2.7.11/include/site/python2.7/pysam" failed with error code 1 in /tmp/pip-build-CuTj0V/pysam/
The command "pip install boto3 Flask flask-cors tornado coverage codeclimate-test-reporter ddt PyJWT requests pysam" failed and exited with 1 during .
Your build has been stopped.

**Comment by AndreasHeger** [comment]
Thanks. We have run into similar trouble. It seems in our case that jenkins is found:

```
...
    checking for curl_easy_pause in -lcurl... yes
    checking for CCHmac... no
    checking for library containing HMAC... -lcrypto
    configure: creating ./config.status
    config.status: creating config.mk
    config.status: creating config.h
    config.status: config.h is unchanged
...
```

but then, the compilation fails.  The relevant lines in hfile_libcurl.c are here:
https://github.com/pysam-developers/pysam/blob/master/htslib/hfile_libcurl.c#L601

```
#if defined HAVE_COMMONCRYPTO
...
#elif defined HAVE_HMAC
...
#else
#error No HMAC() routine found by configure
#endif
```

At the moment I am not sure why the problem occurs. There is a config.h that is part of the tar-ball, but I would expect it to be overwritten (or leave if unchanged). Possible solutions:
1. define the environment variable HTSLIB_CONFIGURE_OPTIONS=--disable-libcurl
2. make sure that the package `libssl-dev` (ubuntu) installed?

**Comment by kyleabeauchamp** [comment]
FWIW, here are the exact build steps and build requirements that we used for building the bioconda packages.  Not sure if this can help with your CI system or not, as we have a fairly different build and CI system.  

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pysam/build.sh

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pysam/meta.yaml

**Comment by AndreasHeger** [comment]
Thanks, @kyleabeauchamp

**Comment by AndreasHeger** [comment]
It is interesting to note that in our CI the compilation fails for the csamfile extension, but works for the chtslib extension. Also, the build-mode in our CI uses build mode `separate` and not `shared`. This mode is selected if cython is not installed (or can't be imported). Solution number 3 would thus be:

3. install cython before pysam.
