### ISSUE TITLE
Installation of Pysam

### ISSUE THREAD

**Issue by j0hnn0** [pysam-developers/pysam#299]
Hi
The pysam packaging is SEVERELY broken. I have never been able to install it without issues, even when all the prerequisites are met. PLEASE could you try and fix all the _known_ issues properly in a new release - such as all those that you help users with.

At the very least, remove the "simply type pip install pysam" part in all your documentation. Its _not_ true, and it creates the false impression with users that this is a trivial exercise, which it is not.

**Comment by AndreasHeger** [comment]
Thanks, can you please be more specific? I am currently only aware of one issue (#298) in the 0.9.1 release.

Unfortunately I can't fix all install issues as the systems in use are just too diverse. I am always happy to accept pull requests.

**Comment by hermesfj** [comment]
I have been trying to download deeptools the past two days going in a circle of errors,  but all of the errors have to do with pysam... Could this be related?

**Comment by AndreasHeger** [comment]
@hermesfj, that depends, what is the specific issue? I am working on an update that might solve a few issues on systems that don't have devel header libraries installed.

**Comment by hermesfj** [comment]
I am so sorry I forgot to reply! I was helped by another gentleman earlier
and he helped me get through the error.
