### ISSUE TITLE
Strange err about function count_coverage

### ISSUE THREAD

**Issue by star013** [pysam-developers/pysam#302]
Hello.
I use pysam like this:

f1=pysam.AlignmentFile('sorted.bam.bam','rb') 
c1=f1.count_coverage()

But it reported TypeError like this:
<ipython-input-56-7c60647dc6d3> in <module>()
----> 1 c1=f1.count_coverage()
/usr/local/lib/python2.7/dist-packages/pysam/calignmentfile.so in pysam.calignmentfile.AlignmentFile.count_coverage (pysam/calignmentfile.c:12583)()
TypeError: an integer is required`

I am using ubuntu 14.04 and I think I installed pysam correctly because when I used other method such as f1.fetch(), everything was OK.

Could you give me some advice? Thanks.

**Comment by AndreasHeger** [comment]
Thanks, this looks like a bug. Could you please send the full traceback to the error? It would help me
to know at exactly which line in the file calignmentfile.pyx the error occured.

Best wishes,
Andreas

**Comment by davidealbanese** [comment]
The problem is in the first two lines of `count_coverage()`:
```cython
cdef int _start = start
cdef int _stop = end
```
Here cython requires an integer, but `None` is passed by default.

Davide

**Comment by MortazaG** [comment]
I'm getting the same error as OP while using samfile.count_coverage():
Here's the whole error:

`Traceback (most recent call last):
  File "avt.py", line 58, in <module>
    main()
  File "avt.py", line 42, in main
    print samfile.count_coverage(1, 2)
  File "pysam/libcalignmentfile.pyx", line 1201, in pysam.libcalignmentfile.AlignmentFile.count_coverage (pysam/libcalignmentfile.c:13387)
TypeError: an integer is required

`

**Comment by juliambrosman** [comment]
I am also encountering this error:

In:
```
af =  pysam.AlignmentFile(bam, "rb")
print("read count is", af.count(reference=gp))
print("count_coverage is", af.count_coverage(reference=gp)
```

Out:

```
read count is 4

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-c3aa16e751f1> in <module>()
      1 print("read count is", af.count(reference=gp))
----> 2 af.count_coverage(reference=gp)

pysam/libcalignmentfile.pyx in pysam.libcalignmentfile.AlignmentFile.count_coverage (pysam/libcalignmentfile.c:12881)()

TypeError: an integer is required
```

python 3.5, pysam version 0.10.0

**Comment by AndreasHeger** [comment]
Thanks, fixed!
