### ISSUE TITLE
conda install doesn't work on Windows 10 64 bit

### ISSUE THREAD

**Issue by parashardhapola** [pysam-developers/pysam#303]
Got following error when trying to install using `conda install pysam`

    Fetching package metadata .......
    Solving package specifications: .
    Error: Package missing in current win-64 channels:
        - pysam
    Close matches found; did you mean one of these?
        pysam: pysal, pyamg, pyyaml
    You can search for packages on anaconda.org with
        anaconda search -t conda pysam

**Comment by kyleabeauchamp** [comment]
We only built conda packages for linux and osx, so this is expected.

**Comment by parashardhapola** [comment]
Is there a hope for Windows conda build too?

**Comment by kyleabeauchamp** [comment]
As far as I know, it is not planned.

**Comment by parashardhapola** [comment]
Too bad :-1: 
Anyway, will be looking forward to it. Thank you for the response.
