### ISSUE TITLE
Trouble installing with pip 

### ISSUE THREAD

**Issue by IvantheDugtrio** [pysam-developers/pysam#306]
Installing with CentOS 7.2 ppc64, pip 8.1.2 (python 2.7) I get the following error:

/bin/ld: cannot find -lchtslib

Here's the complete output:
[pysam-error.txt](https://github.com/pysam-developers/pysam/files/328968/pysam-error.txt)

**Comment by sndrtj** [comment]
I'm having the exact same error on Ubuntu 14.04. Trying `pip install pysam==0.9.1` (the previous version) *also* crashes, with a different gcc error. 

see:
[pysam_0.9.1.err.txt](https://github.com/pysam-developers/pysam/files/329600/pysam_0.9.1.err.txt)

The most recent installable version through pip on my machine is `0.8.4.`

**Comment by AndreasHeger** [comment]
Thanks, I will take a look this evening.

Best wishes,
Andreas

**Comment by jyuan1322** [comment]
We had the same issue, and it seemed to involve cython. Try running:

`sudo pip install cython`

This was successful for me.

**Comment by AndreasHeger** [comment]
Hi, I have created a release 0.9.1.2 that - hopefully - work a bit better when there is no cython and libcurl present. Unfortunately I have issues uploading to pypi. I will try again tomorrow, but In the meantime, a tar ball is here:

https://github.com/pysam-developers/pysam/archive/v0.9.1.2.tar.gz

Best wishes,
Andreas

**Comment by osoylemez** [comment]
I had the same problem on Ubuntu 14.04. @jyuan1322's suggestion to run <cython> first worked for me.

**Comment by barboteur** [comment]
Hello, I tried v0.9.1.2 this morning and the bug fix does not work on ubuntu 14.04 and CentOS 7.
To fix the problem I have to install cython first.

**Comment by AndreasHeger** [comment]
Thanks. Do you still have the full output of the install? I added some more debugging printouts that might help identifying the problem.

**Comment by sndrtj** [comment]
Hi,

On a fresh virtual environment on Ubuntu 14.04 this indeed still crashes. See the attached file for the log. As others have mentioned, installing cython in advance does work. 

[pysam_0.9.1.2.txt](https://github.com/pysam-developers/pysam/files/336840/pysam_0.9.1.2.txt)

**Comment by barboteur** [comment]
I have a few different log file (no libcurl)

[install_pysam.txt](https://github.com/pysam-developers/pysam/files/336962/install_pysam.txt)

**Comment by AndreasHeger** [comment]
@barboteur , @sndrtj,  Thanks!

**Comment by AndreasHeger** [comment]
Hi all, I have created a new release 0.9.1.3 that should take care of the missing libhtslib.so issue. I managed to reproduce this and solved it locally. However, with all the different OS and python versions around I might not have covered all environments (tested on CentOs 7 and python 2.7/3.5).

**Comment by kyleabeauchamp** [comment]
If people still have issues, I think we can potentially push more people to use the `bioconda` packages: `conda install -c bioconda -c R pysam`.

**Comment by AndreasHeger** [comment]
I would not mind that at all!
Best wishes,
Andreas

**Comment by sndrtj** [comment]
@AndreasHeger This now works for me on Ubuntu 14.04 ! :-)

**Comment by barboteur** [comment]
Hello, it now works on my ubuntu 14.04 and on CentOS7. Thanks.
