### ISSUE TITLE
PileupRead() indel property and deletions

### ISSUE THREAD

**Issue by ronammar** [pysam-developers/pysam#31]
I'm observing instances where .indel = 0 and .is_del = 1. The base upstream of the deletion, is flagged as -1. Is this an error? Based on the documentation, I would expect deletion positions to have .indel = -1 and .is_del = 1.

**Comment by AndreasHeger** [comment]
No follow-up - closing for now.

**Comment by afif-elghraoui** [comment]
Hi, I just ran into this problem. I tried this with pysam v0.8.4 on CentOS (python2) and pysam v0.8.3 on Debian with both python2 and python3.

This is what I see:

pos10: read.indel == -1 and read.is_del == 0
pos11: read.indel == 0 and read.is_del == 1

**Comment by afif-elghraoui** [comment]
I got permission from my supervisor to send you one of our bam files for debugging purposes. I will send you an email with a link you can download it from.

**Comment by afif-elghraoui** [comment]
Were you able to find out anything about this? I found out that the BAM files we're working with have some problematic (consecutive I's and D's) CIGAR substrings. I thought this might be the problem, so we cleaned up the BAM files to get rid of these issues, but there are still discrepancies with `read.indel` and `read.is_del`.

Could this problem have something in common with #93?

**Comment by AndreasHeger** [comment]
Thanks, apologise, I will see if I can take a look this w/e.

**Comment by AndreasHeger** [comment]
I am downloading the data now. The documentation in the htslib source says:

```
@field  indel      indel length; 0 for no indel, positive for ins and negative for del 
@field  is_del     1 iff the base on the padded read is a deletion
@field  is_head    ???                                                               
@field  is_tail    ???                                                               
@field  is_refskip ???   
```

The relevant logic is in sam.c:
```
        p->is_del = p->indel = p->is_refskip = 0;
        if (s->x + l - 1 == pos && s->k + 1 < c->n_cigar) { // peek the next operation
            int op2 = _cop(cigar[s->k+1]);
            int l2 = _cln(cigar[s->k+1]);
            if (op2 == BAM_CDEL) p->indel = -(int)l2;
            else if (op2 == BAM_CINS) p->indel = l2;
            else if (op2 == BAM_CPAD && s->k + 2 < c->n_cigar) { // no working for adjacent padding
                int l3 = 0;
                for (k = s->k + 2; k < c->n_cigar; ++k) {
                    op2 = _cop(cigar[k]); l2 = _cln(cigar[k]);
                    if (op2 == BAM_CINS) l3 += l2;
                    else if (op2 == BAM_CDEL || op2 == BAM_CMATCH || op2 == BAM_CREF_SKIP || op2 == BAM_CEQUAL || op2 == BAM_CDIFF) break;
                }
                if (l3 > 0) p->indel = l3;
            }
        }
        if (op == BAM_CMATCH || op == BAM_CEQUAL || op == BAM_CDIFF) {
            p->qpos = s->y + (pos - s->x);
        } else if (op == BAM_CDEL || op == BAM_CREF_SKIP) {
            p->is_del = 1; p->qpos = s->y; // FIXME: distinguish D and N!!!!!
            p->is_refskip = (op == BAM_CREF_SKIP);
        } // cannot be other operations; otherwise a bug
        p->is_head = (pos == c->pos); p->is_tail = (pos == s->end);
```

**Comment by AndreasHeger** [comment]
Hi @afif-elghraoui and @ronammar. I probably don't understand the situation fully, but it seems to me from the output and also from the code above, that is_del is a property of the current base in the read, while indel refers to the next operation in the cigar string.

I assume this is useful if want to write an alignment viewer such as samtools tview. Scanning the indel column for the max will tell you how much "padding" will be required for the next column(s).

pysam simply propagates these quantities from the underlying htslib engine. I will add some code to the documentation.

Please let me know if this answers your question.

**Comment by AndreasHeger** [comment]
I am closing the issue for now, please reopen if you think necessary.

Many thanks for raising this and providing example data.

**Comment by afif-elghraoui** [comment]
Thanks for taking a look and clearing this up. It was just a bit counterintuitive at first.
