### ISSUE TITLE
Malformed 'CL' tag, missing 'PP'

### ISSUE THREAD

**Issue by david4096** [pysam-developers/pysam#311]
The previous program tag within the repeated programs is malformed during translation to BAM using the pysam methods.

https://github.com/ga4gh/server/issues/1265

Note for this [SAM](https://raw.githubusercontent.com/ga4gh/compliance/master/test-data/brca1_HG00101.sam), when copying over the header to a new BAM, errors were induced.

```
import pysam
input = pysam.AlignmentFile("../compliance/test-data/brca1_HG00101.sam")
output = pysam.AlignmentFile("out.bam", 'wb', header=input.header)
print input.header.get('PG')[1].get('PP')   # prints "bwa_index"
print output.header.get('PG')[1].get('PP') # print None
print output.header.get('PG')[1]
# {'PN': 'bwa', 'ID': 'bwa_aln_fastq', 'VN': '0.5.9-r16', 'CL': 'bwa aln -q 15 -f $sai_file $reference_fasta $fastq_file\tPP:bwa_index'}
```

**Comment by AndreasHeger** [comment]
Thanks. The issue is parsing the CL tag causes the subsequent PP tag to be ignored. Working on a fix.
