### ISSUE TITLE
Is there a VariantRecord constructor?

### ISSUE THREAD

**Issue by winni-genp** [pysam-developers/pysam#314]
I would like to create new VariantRecord objects and write them to a BCF output stream.  Is there a way of doing this?

**Comment by AndreasHeger** [comment]
Hi @winni-genp @holtgrewe,

at the moment there is not. This part of pysam is still in development. 
Best wishes,
Andreas

**Comment by bioinformed** [comment]
Working on this feature now.

**Comment by holtgrewe** [comment]
@bioinformed I could contribute some work here as well. Is there anything I can help with?

**Comment by msto** [comment]
Hi, 

Are there any updates on the creation of new VariantRecords or adding of new fields to existing VariantRecords?

Thanks!

**Comment by bioinformed** [comment]
The current development branch has the ability to add most fields to a
VariantRecord.  I'll add a method to VariantFile and VariantHeader to
create new VariantRecords shortly.

**Comment by msto** [comment]
Great, thanks. I know VCF support is still under development and documentation is a little sparse, but would it be possible to get an example of how to add new INFO fields to a VariantRecord? 

I didn't see a specific development branch available, and installed the latest commit from master. Under that version, I haven't been able to add new INFO fields.

	In [2]: import pysam
	In [3]: pysam.__version__
	Out[3]: '0.9.2'

	In [4]: from pysam import VariantFile
	In [5]: svfile = VariantFile('raw_vcf/delly/delly.11194.vcf.gz')
	In [6]: record = next(svfile)
	
	In [11]: 'SVTYPE' in record.info.keys()
	Out[11]: True
	In [12]: record.info['SVTYPE'] = 'BND'

	In [13]: 'STRANDS' in record.info.keys()
	Out[13]: False
	In [14]: record.info['STRANDS'] = '++'
	---------------------------------------------------------------------------
	KeyError                                  Traceback (most recent call last)
	<ipython-input-13-d816b4ae3d92> in <module>()
	----> 1 record.info['STRANDS'] = '++'

	pysam/cbcf.pyx in pysam.cbcf.VariantRecordInfo.__setitem__ (pysam/cbcf.c:33891)()

	pysam/cbcf.pyx in pysam.cbcf.bcf_info_set_value (pysam/cbcf.c:10412)()

	KeyError: 'unknown INFO'

I did try creating a new VariantRecordInfo object, but that yields a segmentation fault and I haven't found any docs on the parameters the constructor takes.

    In [1]: from pysam.cbcf import VariantRecordInfo
    In [2]: info = VariantRecordInfo({'a': 1})
    In [3]: info.keys()
    Segmentation fault (core dumped)

**Comment by bioinformed** [comment]
Thanks for the detailed report.  I think there are two things going on:

1. Some objects aren't supposed to be instantiated from Python (e.g. VariantRecordInfo).  I've made that illegal.
2. In order to set INFO values, the ID must be present in the header.  In your example, is 'STRANDS' already present in the header as an INFO type?  If not, you'll need to do the following:

```
    svfile.header.info.add('STRANDS', number=1, type='String', description='...')
```

Otherwise, what you are seeing is a bug and it would be useful to have your test file to track it down.

**Comment by bioinformed** [comment]
There is now a `VariantHeader.new_record()` and a `VariantFile.new_record()` method.  Please give them a try.

**Comment by hsiaoyi0504** [comment]
For those seeking where it is like me, check this: https://github.com/pysam-developers/pysam/commit/edce283b0f979373959cdd1a83e261b1193571ab.
