### ISSUE TITLE
question - version 0.7.7 vs 0.8.4 vs 0.9.1.4

### ISSUE THREAD

**Issue by mink2mink2** [pysam-developers/pysam#315]
Hello, nice guys.
I'm a beginner of B.I.
I had tested this issue many times but I didn't get a solution.

When I install using "apt-get install python-pysam" on ubuntu 16.04,
1. python version is 0.7.7 
2. pysam.view("-F4", "-c", "test.bam"); is working good.

when I install using "pip install pysam==0.8.4" on same os, still working good.

However, when I install using "pip install --upgrade pysam" on same os,
1. python version is 0.9.1.4.
2. pysam.view("-F4", "-c", "test.bam"); is now working
result is "Segmentation Fault (core dumped)"

I'm not sure whether it is new issue or my mistake.
Could you please check it out once?
If you do, really appreciate for that.

Have a nice day.

**Comment by AndreasHeger** [comment]
Thanks, will check.

**Comment by AndreasHeger** [comment]
Many thanks, that was indeed a bug. 'samtools view -c' outputs to stdout even if -o option is given.
