### ISSUE TITLE
pip install of version 0.9.1.4 fails on OS X 10.11.6 both with gcc and clang

### ISSUE THREAD

**Issue by gtamazian** [pysam-developers/pysam#323]
The installation of version 0.9.1.4 via **pip** fails with both the **gcc** and OS X-native **clang** compilers. The default installation by

```
pip install pysam
```

crushes like it is described in #267. The installation using the **gcc** compiler

```
env CC=/usr/local/bin/gcc-6 pip install pysam
```

shows the following error message (as in #307):

```
gcc-6: error: unrecognized command line option '-rpath'
```

**Comment by AndreasHeger** [comment]
Thanks. 

The first issue might be htslib related, could you try install htslib from source with clang and - if it works - copy the compilation log?

The second issue is a pysam issue. I will need to read up on gcc option differences.

**Comment by gtamazian** [comment]
@AndreasHeger, I successfully compiled _htslib_ using _clang_:
```
CC=clang ./configure
make
```
The logs produced by _configure_ and _make_ are attached.

[htslib_clang_configure.txt](https://github.com/pysam-developers/pysam/files/434768/htslib_clang_configure.txt)
[htslib_clang_make.txt](https://github.com/pysam-developers/pysam/files/434769/htslib_clang_make.txt)

**Comment by AndreasHeger** [comment]
Thanks, @gtamazian , and apologies for the delay. Will hopefully pick this up again this week.

**Comment by AndreasHeger** [comment]
Closing this for now, please reopen if still present in latest versions.
