### ISSUE TITLE
Full header not returned in AlignmentFile text() method for specific bam file

### ISSUE THREAD

**Issue by kiramt** [pysam-developers/pysam#325]
I've been working with a bam file GSM850906_brain-E14.5-1.bam which can be obtained here:
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM850906

When I run the following code:

`sample = pysam.AlignmentFile("GSM850906_brain-E14.5-1.bam", "rb")`
`result = samfile.text`

result only contains the first 2 lines of the header:

'@HD    VN:1.0  SO:sorted
@PG ID:TopHat   VN:1.0.14   CL:/home/fyue/tophat/bin/tophat --solexa1.3-quals -o brain-e14.5-zy45.tophat -p 8 /home/fyue/tophat/index/mm9 brain-e14.5-zy45.fastq.cut
'

The header actually looks like this:
@HD VN:1.0  SO:sorted
@PG ID:TopHat   VN:1.0.14   CL:/home/fyue/tophat/bin/tophat --solexa1.3-quals -o brain-e14.5-zy45.tophat -p 8 /home/fyue/tophat/index/mm9 brain-e14.5-zy45.fastq.cut
@SQ SN:chr10    LN:129993255
@SQ SN:chr11    LN:121843856
@SQ SN:chr12    LN:121257530
@SQ SN:chr13    LN:120284312
@SQ SN:chr13_random LN:400311
@SQ SN:chr14    LN:125194864
@SQ SN:chr15    LN:103494974
@SQ SN:chr16    LN:98319150
@SQ SN:chr16_random LN:3994
@SQ SN:chr17    LN:95272651
@SQ SN:chr17_random LN:628739
@SQ SN:chr18    LN:90772031
@SQ SN:chr19    LN:61342430
@SQ SN:chr1 LN:197195432
@SQ SN:chr1_random  LN:1231697
@SQ SN:chr2 LN:181748087
@SQ SN:chr3 LN:159599783
@SQ SN:chr3_random  LN:41899
@SQ SN:chr4 LN:155630120
@SQ SN:chr4_random  LN:160594
@SQ SN:chr5 LN:152537259
@SQ SN:chr5_random  LN:357350
@SQ SN:chr6 LN:149517037
@SQ SN:chr7 LN:152524553
@SQ SN:chr7_random  LN:362490
@SQ SN:chr8 LN:131738871
@SQ SN:chr8_random  LN:849593
@SQ SN:chr9 LN:124076172
@SQ SN:chr9_random  LN:449403
@SQ SN:chrM LN:16299
@SQ SN:chrUn_random LN:5900358
@SQ SN:chrX LN:166650296
@SQ SN:chrX_random  LN:1785075
@SQ SN:chrY LN:15902555
@SQ SN:chrY_random  LN:58682461

I don't have this problem with other bam files I am using.

Packages in my environment:
$ conda list
bcftools                  1.3.1                         0    bioconda
curl                      7.45.0                        1    bioconda
htslib                    1.3.1                         0    bioconda
pysam                     0.9.1                    py27_0    bioconda
python-dateutil           2.3                      py27_0    bioconda
samtools                  1.3.1                         2    bioconda
drmaa                     0.7.6                     <pip>
mkl                       11.3.3                        0
numpy                     1.11.1                   py27_0
openssl                   1.0.2h                        1
pandas                    0.18.1              np111py27_0
pip                       8.1.2                    py27_0
pysam                     0.9.1.4                   <pip>
python                    2.7.12                        1
pytz                      2016.6.1                 py27_0
PyYAML                    3.11                      <pip>
libgcc                    4.8.5                         1    r
ncurses                   5.9                           8    r
zlib                      1.2.8                         1    r
readline                  6.2                           2
scipy                     0.18.0                    <pip>
setuptools                25.1.6                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0

(Note I have pysam installed twice because of issue #231 )

**Comment by jmarshall** [comment]
BAM files contain a text header containing the textual `@` headers present and a binary header with the basic details of the sequences mapped against.  If the text contains no `@SQ` headers (which is uncommon but valid nonetheless), `samtools view` and other tools will reconstruct basic `@SQ` headers with just `SN` and `LN` fields from the binary header.  (There's a bit more discussion of this in samtools/samtools#548.)

_GSM850906_brain-E14.5-1.bam_ has only two actual text headers: the `@HD` line and the `@PG` line.  The `@SQ` information is present only in the binary header, and has been reconstructed on the fly by whatever tool you used to print out the headers.

So the question here is whether the `AlignmentFile text()` method should learn to do this reconstruction.  (At present, it is `sam_hdr_write()` that does this reconstruction in HTSlib, which is slightly unfortunate.)

**Comment by AndreasHeger** [comment]
Thanks both, I can see that this would be useful. I will check what is involved in adding this.
