### ISSUE TITLE
Coordinates in pileup

### ISSUE THREAD

**Issue by vineeth-s** [pysam-developers/pysam#327]
samfile.pileup ignores the coordinates specified in 

samfile.pileup("reference_chr",10,20) 

and instead retrieves the data for the entire range of positions in reference_chr

does the BAM file have to be sorted in any particular fashion for this to work ?

**Comment by AndreasHeger** [comment]
Hi, this should work, note though that pileup will return the region spanned by the longest extension of any reads. Specify ``truncate=True`` to only get residues 10 to 19.

**Comment by AndreasHeger** [comment]
Closing for now.
