### ISSUE TITLE
How to set verbose level in pysam

### ISSUE THREAD

**Issue by diegodiazd** [pysam-developers/pysam#330]
Hi all,
First of all, thanks for this wrapper, very useful. I am working on an application which uses pysam for random access to FASTA files. I would like to avoid printing htslib messages but I don't know now to control verbose level. I am aware that a verbose control feature was recently committed, but I didn't get how to use it ( specially for the pysam.Fastafile class)

Any help will be appreciated.

Thanks in advance.

Diego

**Comment by AndreasHeger** [comment]
Hi, 

does pysam.set_verbosity(0) have any effect? It might be that not all messages are captured, can you provide an example?

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Closing for now.
