### ISSUE TITLE
vcf reset

### ISSUE THREAD

**Issue by zju3351689** [pysam-developers/pysam#331]
While  reading the vcf file,  the class VariantFile's reset were used to locate to the file position after header region. But an error raise as follows:
Traceback (most recent call last):
  File "XXX.py", line 27, in <module>
    bvcf.reset()
  File "pysam/cbcf.pyx", line 3533, in pysam.cbcf.VariantFile.reset (pysam/cbcf.c:48219)
TypeError: seek() takes exactly one argument (2 given) 

my code is :
  7 bvcf = pysam.VariantFile(sys.argv[1],"r")
 27bvcf.reset()

**Comment by zju3351689** [comment]
A alternative method for reset
bvcf = pysam.VariantFile(sys.argv[1],"r")
headerpos = bvcf.tell()
bvcf.seek(headerpos)

**Comment by bioinformed** [comment]
Thanks for filing an issue.  I should have a fix for you shortly.

**Comment by bioinformed** [comment]
Fixed in the dev branch.
