### ISSUE TITLE
Hardclipped bases in cigar ignored by pysam.AlignedSegment.infer_query_length()

### ISSUE THREAD

**Issue by amblina** [pysam-developers/pysam#332]
The [ `pysam.AlignedSegment.infer_query_length`](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.infer_query_length) method ignores hardclipped bases.  The method states that it gets the:

> inferred read length from CIGAR string.

this is in contrast with the [`pysam.AlignedSegment.query_length`](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.query_length)

> This value corresponds to the length of the sequence supplied in the BAM/SAM file. The length of a query is 0 if there is no sequence in the BAM/SAM file. In those cases, the read length can be inferred  from the CIGAR alignment, see `pysam.AlignmentFile.infer_query_length()`.

With a cigar value of `58H150M` which represents an alignment where 58 bases have been hardclipped (not present in the alignment or SEQ section) and 150 matches. The SEQ section has 150 bases.  If `query_length=150` and `infer_query_length()=150`, however this should be: `infer_query_length()=208` by my understanding of the docs.  Am I missing something / is this intentional or just something to be corrected at some point?

Example of this can be found and run here: https://gist.github.com/amblina/795d30b5e04f87090d61739cb1846c1b 

Output:

```
@HD VN:1.3  SO:unsorted
@SQ SN:Test_reference   LN:200
query1  0   Test_reference  51  255 58H150M *   0   0   TCTCCGACTGTTCCCAAATTGTAACTTATCGTTCCGTGAAGGCCAGAGTCACTTCCCGGCCCTTTCCATGCGCGCACCATACCCTCCTAGTTCCCCGGTTATCTTTCCGAAGTGGGAGTGAGCGAACCTCCGTTTACGTCTTGTTACCAA  *   NM:i:1  AS:i:148

Infered length of query: 150
SEQ field length: 150
CIGAR field: 58H150M, length: 208
Actual length of original query: 208
```

**Comment by AndreasHeger** [comment]
Merged and closed.

**Comment by AndreasHeger** [comment]
Hi @amblina, just thought about it a bit more. I think the current behaviour was intentional to ensure consistency for infer_query_length when setting always=True and always=False to avoid the following situation:

```
>>> read.infer_query_length(True)
40
>>> read.infer_query_length(False)
30
```

Maybe there should be an additional option (e.g. include_hard_clipped) that is by default set to False to preserve the current default behaviour?

The reason is that hard-clipped bases are not stored within the BAM.

**Comment by amblina** [comment]
Hi @AndreasHeger thanks for looking through my PR 👍 .  I see where you are coming from in regards to the consistency, but I don't think it's necessarily bad it would give two different answers as they are using two different sources of 'truth' and the current code looks like it would already give inconsistent answers.  Most of my argument below is predicated on my understanding of the code-base being correct, if it isn't then all bets are off and I totally welcome correction.  Sorry for the long-winded response!

My understanding of the code (I'm less familiar with cython so I may be totally mistaken) is that the bool determines what the user wishes to use as evidence/source of truth of the original read/query length.  If `true`, the function uses information from the cigar (returning 0 if cigar is not present) and the length of the SEQ field(?) if `false`.  With the current functionality, a read that contains SEQ but not CIGAR e.g. an unaligned record as produced by bwa mem, would produce the following which would also be inconsistent:

```
>>> read.infer_query_length(True)
0
>>> read.infer_query_length(False)
30
```

From what I can see, the functionality of `infer_query_length()` at this time is only useful for inferring the length of SEQ field, not the original read/query sequence, whether the record has a filled SEQ field or not.  It would make more sense in that case to have it by default, attempting to `len(SEQ)` and if that field was empty to attempt inferring the length of SEQ from cigar (with the bool to force one behaviour over the other).

If the functionality is `infer_query_length()` is actually to infer the original read/query sequence (as is suggested by documentation) then it would make more sense to include H ops.  It would also explain the bool arg as this by default checks the cigar which is potentially more accurate because of the presence of H ops but can be overridden to check the SEQ field.

In regards to chimaeric reads, including the H ops will allow for consistent reporting of query length across reads whereas ignoring them will result in inconsistent results:

```
ref: NNNAAANNNBBBBNNN
qry: AAABBBB
actual query_length == 7

alignment 1:
NNNAAANNNBBBBNNN
   AAA

SEQ: AAA
CIGAR: 3M3H
current infer_query_length == 3
proposed infer_query_length == 7

alignment 2:
NNNAAANNNBBBBNNN
         BBBB

SEQ: BBBB
CIGAR: 3H3M
current infer_query_length == 4
proposed infer_query_length == 7
```

**Comment by amblina** [comment]
Hi @AndreasHeger have you had the opportunity to review my comments above?  I'm not sure adding an additional optional arg will fix the situation as the functionality of the current `infer_query_length()` would be better suited to a function called `infer_seq_length()` or similar.

**Comment by AndreasHeger** [comment]
@amblina, yes I have, quite busy at the moment. Can I get back to you by Wednesday?

**Comment by amblina** [comment]
@AndreasHeger - this is totally fine - not trying to rush you at all :+1:

**Comment by AndreasHeger** [comment]
Hi @amblina, many thanks for your comments, apologies for the delay. I think you are right. I will merge your pull request.

Best wishes,
Andreas

**Comment by bioinformed** [comment]
@AndreasHeger: I agree with the suggestion in this issue -- split `infer_query_length` into `infer_query_length` and `infer_read_length`.  The former would ignore hard-clipped bases and the latter would not.

**Comment by AndreasHeger** [comment]
Thanks both, sounds sensible, will put it in this release as other potential breaking changes already.
