### ISSUE TITLE
A bug for get_reference_sequences 

### ISSUE THREAD

**Issue by WinterLi1993** [pysam-developers/pysam#335]
Hello,
      I am using pysam for my bam file , I wanna get references sequences with get_reference_sequences(), but  I do know what the meanning about "This method requires the MD tag to be set" that from help doc . so can you give me an example for how-to-use that function ??

thank you !

**Comment by AndreasHeger** [comment]
Hi, the MD tag is set by the mapping tool such as BWA. Does
```
samtools view ex1.bam | grep MD: | head
```
any output?

**Comment by WinterLi1993** [comment]
yep , get output .  object.get_reference_sequences()  worked and I got the reference sequences  , the reference is from hg19   ??

**Comment by AndreasHeger** [comment]
That depends on what reference you mapped the reads against. Closing this for now.

Best wishes,
Andreas

**Comment by WinterLi1993** [comment]
Hi ,@AndreasHeger,
      what do you mean ? my bam file was mapped to hg19 . if I mapped that to hg38 ,I use get_reference_sequences() ,then ,I will get sequences from hg38 ?
