### ISSUE TITLE
pileup: filter reads and bases by sequence quality

### ISSUE THREAD

**Issue by snayfach** [pysam-developers/pysam#341]
It is possible to filter reads and bases by sequence quality from a pileup in pysam?

```
baseq = 30
mapq = 20
readq = 20
samfile = pysam.AlignmentFile("bampath", "rb")
for p in samfile.pileup():
	for r in p.pileups:
           if r.baseq < baseq: continue
           elif r.mapq < mapq: continue
           elif r.readq < readq: continue 
```

Thanks,
Stephen

**Comment by amblina** [comment]
Hi @snayfach could you confirm how you are measuring read quality i.e. are you recording this in an optional tag or something like the mean qscore of the record?

**Comment by amblina** [comment]
@snayfach I've written up some sample code, based on some snippets from the pysam docs intro.  Please reply if this is what you are /aren't looking for.

https://gist.github.com/amblina/5ed9a61ce74ad90668f4e29d62e7eb79

**Comment by snayfach** [comment]
This is exactly what I was looking for. Thanks!!

**Comment by amblina** [comment]
No worries, glad to help ^^
