### ISSUE TITLE
Problem with samtools view command within pysam

### ISSUE THREAD

**Issue by pavanvidem** [pysam-developers/pysam#342]
When I tried to use samtools view using pysam, I get "ValueError: option -o is forbidden in samtools view". But for samtools view option "-o" seems valid. This is how I called it: pysam.view("-bS", "-F", "4", "-o", filePrefix + ".unsorted.bam", filePrefix + ".sam").

**Comment by amblina** [comment]
Hi @pavanvidem,
In order to get the behaviour you are looking for, you will need to use the `catch_stdout` arg and set it to `False`.  I have added an example of this working as expected here:

https://gist.github.com/amblina/4264ebd193c9c4b9f099bc6ab85921ee

**Comment by AndreasHeger** [comment]
Thanks @amblina , closing for now.

**Comment by pavanvidem** [comment]
Thanks, it worked!

**Comment by usamacheema** [comment]
How pileup() can be used to print strand specific coverage fof bases??
