### ISSUE TITLE
Package Version from PKG_INFO on PyPI

### ISSUE THREAD

**Issue by IanSudbery** [pysam-developers/pysam#343]
pysam is a dependency for our package, UMI-tools, which we are distributing using setuptools (as well as conda). 

If we specify pysam>=0.8.4 in the install_requires, then our setup will always download and install pysam 0.9.1.4, but then say it has successfully installed version 0.2.3 before complaining that is can't find 0.8.4.

Starting the python interpreter, importing pysam and asking for the version returns 0.9.1.4:

```
>>>import pysam
>>>pysam.__version__
'0.9.1.4'
```

but if you ask for the path, the directory has 0.2.3 in the its name, and if you look in the PKG_INFO it says its version 0.2.3. 

If we remove the '>=0.8.4' requirement from our setup, it works fine.

**Comment by AndreasHeger** [comment]
@IanSudbery , thanks, strange. Could you provide an install log?

I can't find the string 0.2.3 anywhere in the repository.

**Comment by AndreasHeger** [comment]
Checked 0.9.1.4 tar-ball from pypi, PKG_INFO looks ok, closing for now.
