### ISSUE TITLE
pysam wheels not available at www.cgat.org?

### ISSUE THREAD

**Issue by cgates** [pysam-developers/pysam#344]
Until today there was a pysam wheelhouse at:
https://www.cgat.org/downloads/public/pysam/wheels/
(The wheels make using TravisCI much nicer.)
The cgat.org site appears to be down: is that no longer supported?
If not, is there a better source for pysam wheels?

Thanks!
cg

**Comment by AndreasHeger** [comment]
Hi Cg,

we are moving the server to a new network (new IP adresses, etc),
but it should reappear again as www.cgat.org.

It should be back up soon, I will ask.

Best wishes,
Andreas

**Comment by cgates** [comment]
All is well.  Thanks!!!

**Comment by graingert** [comment]
@AndreasHeger can you publish manylinux1 wheels on PyPI instead?

**Comment by AndreasHeger** [comment]
Ok, will do.

**Comment by AndreasHeger** [comment]
Pysam wheels now on pypi.
