### ISSUE TITLE
Incorrect read coordinates and incorrect TLEN after Fetching alignment record from a BAM file

### ISSUE THREAD

**Issue by ChristopheLegendre** [pysam-developers/pysam#350]
Hi Pysam team,
I just installed  version pysam==0.9.1.4, and see the following problem while capturing the read lines. The CHROM and POS for both the read and its mate are shifted by one (1) from the original line in the BAM file.
So the **columns 3, 4, 7 and 8 are incorrect**. 

Also, the TLEN or column 9 is totally different from the original value. In the example below you can see that the original value is -872 and was converted to 57.

Furthermore, using the code x.next or x.rnext, the returned values are correct, that is identical to the ones in the BAM, but  using the code x.start or x.next_start give the incorrect coordinates. (see code below for details).  So chromosomes names are ok but not their coordinates.

BAM files are supposed to be 0-based; In the pysam documentation, the display of coordinates is said to be a 0-based (inclusive) information, so I guess as I have used a BAM file as input, I should not have any discrepancies between the coordinates from the BAM and the one showed by pysam. 

I used python 3.5.0 and pysam 0.9.1.4. and used the following code to extract the alignment records:

```
import pysam
bamf = pysam.AlignmentFile(mybam, "rb")
iter = bamf.fetch(chr, pos, pos+100)
for x in iter: 
    print(str(x))
    print(type(x))
    print("x.rnext \t" + str(bamf.get_reference_name(x.rnext)))
    print("x.rname \t" + str(bamf.getrname(x.rname)))
    print("x.start \t" + str(x.reference_start))
    print("x.next_start \t" + str(x.next_reference_start))
```
## Examples

**Here the line extracted and printed by pysam:**
D87P8DQ1:274:C59G0ACXX:5:2315:19806:57716       83      **20**      33157236        0       29S57M  **20**      33156421        **57**      CTCCCTCGACTCCAGCCGCATCCCCTCCCCCACCACCACCACCACCACCACCACCACCACCACCACCACCACCACCACCACCATCA       array('B', [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 30, 29, 29, 32, 30, 25, 30, 31, 28, 16, 32, 29, 31, 29, 28, 6, 31, 27, 25, 31, 27, 31, 31, 29, 25, 31, 28, 30, 31, 29, 31, 31, 30, 31, 31, 30, 31, 31, 30, 31, 31, 31, 31, 32, 28, 31, 32, 31, 32, 31, 31, 27, 31, 29])  [('MC', '1S57M28S'), ('BD', 'IIIIONMMLLKKJJJJJJIIIIIIIIIIIIIIMIKLHKLHKLHKLHKLHKLHKLHKLHKLHKLHKLHKLILMILNJMOLPQRLMII'), ('MD', '54C2'), ('PG', 'MarkDuplicates'), ('RG', 'C59G0ACXX_5'), ('BI', 'LLLLSRQPPOOONNNMMMMMMLLLLLLLLLLLNLPNLOMKOMKOMKOMKOMKOMKOMKOMKOMKOMKOMKOMKOMLPNMQPRPPLL'), ('NM', 1), ('MQ', 0), ('AS', 54), ('XS', 57)]

x.rnext  21
x.rname  21
x.start  33157236
x.next_start  33156421

**Here the original line in the Bam file:**
D88P9DQ1:274:C59G0ACXX:5:2315:19806:57716       83      **21**      33157237        **0**       29S57M  =       33156422        **-872**    CTCCCTCGACTCCAGCCGCATCCCCTCCCCCACCACCACCACCACCACCACCACCACCACCACCACCACCACCACCACCACCATCA       ################################?>>A?:?@=1A>@>='@<:@<@@>:@=?@>@@?@@?@@?@@@@ A= @ A@A@@@  MC:Z:1S57M28S   BD:Z:IIIIONMMLLKKJJJJJJIIIIIIIIIIIIIIMIKLHKLHKLHKLHKLHKLHKLHKLHKLHKLHKLHKLILMILNJMOLPQRLMII  MD:Z:54C2       PG:Z:MarkDuplicates     RG:Z:C59G0ACXX_5        BI:Z:LLLLSRQPPOOONNNMMMMMMLLLLLLLLLLLNLPNLOMKOMKOMKOMKOMKOMKOMKOMKOMKOMKOMKOMKOMLPNMQPRPPLL     NM:i:1  MQ:i:0  AS:i:54 XS:i:57

Let us know if you have any questions or comments.
Thanks,
Best,
Chris.

**Comment by bioinformed** [comment]
I have not looked closely at your data, but the position difference is likely due to SAM using 1-based coordinates and pysam using 0-based coordinates.

**Comment by ChristopheLegendre** [comment]
@bioinformed 
Hi Kevin,
Thanks for your reply.
I know the discrepancy you are referring to (0-based vs. 1-based) because it has been described in the pysam user manual section 1.8.3.
But I found differences between the chromosome values using pysam versus samtools, and also using two different ways with pysam (print(str(x)) versus str(bamf.getrname(x.rname))), as I described in the reported issue (sorry the issue was a long description :)   ).

I put in bold the 0/1-based independent differences between the two cases, i.e. the BAM record printed using samtools and the BAM record printed using pysam (print(str(x))).

samtools shows: D88P9DQ1:274:C59G0ACXX:5:2315:19806:57716 83  **21**  33157237 0 29S57M  **=**  33156422   **-872**
Pysam shows: D87P8DQ1:274:C59G0ACXX:5:2315:19806:57716 83  **20**  33157236 0 29S57M  **20**  33156421   **57**    

I am ok to consider the difference for the column "position", but the difference in the "Chromosome" name can not happen since this is not due to the 0- vs. 1-based system.
Also, the value -872 turned to 57 in column 9.

Thanks,
Best,
Chris.

**Comment by bioinformed** [comment]
Pysam's `str(x)` prints the alignment start coordinate using the 0-based convention, so that isn't intended to match the SAM file.   Does the output from `x.tostring(bamf)` look right?

I'm still not sure what is happening with the chromosome names, but let's work through this one step at a time.

**Comment by AndreasHeger** [comment]
Hi @ChristopheLegendre 

the str() method is really only for debugging purposes. With respect to chromosome names, I expect what happens that str() outputs the chromosome id, which is a number from 0 to n, while samtools of course outputs the chromosome name. Depending how things are sorted, chromosome "1" might be 0 and chromosome "2" might be 1, etc. Note that samtools outputs '=' if the mate is on the same chromosome.

The value before the sequence is the read.query_alignment_length, which is different the SAM format, which contains then "signed template length", which would be read.template_length.

**Comment by ChristopheLegendre** [comment]
Hi Andreas,

Thanks for your reply and for the checking and fix.
If the problem persists, I will let you know.
Thanks,
**Chris**
