### ISSUE TITLE
pysam configuration with libpython in setup.py  

### ISSUE THREAD

**Issue by Amjadhpc** [pysam-developers/pysam#354]
Hello,

I want to install the pysam 0.9.4 on RHEL 5.x using python 2.7. Pysam will be used to work with bcbio frane work.  However i need cutils.so to be linked with libpython.so
What options should i pass in setup.py to have cutils.so link with libpython.so

**Comment by AndreasHeger** [comment]
Hi, linking should be happening automatically - do you observe an error?

**Comment by AndreasHeger** [comment]
Closing for now.
