### ISSUE TITLE
Pysam fetch for records not exists in VCF files

### ISSUE THREAD

**Issue by snashraf** [pysam-developers/pysam#359]
f1 = pysam.VariantFile("test.vcf.gz")

for f in f1.fetch(str(chr), int(start), int(end)):

```
        if f:
                print "yes"  
        else :
                print "hello"
```

In the above example Its not printing "hello" even for cases which doesn't have entry into VCF. I want to print program "hello" for cases where VariantFile doesn't have variants records.

Its their a way to do this ?

Thanks

**Comment by bioinformed** [comment]
This is a Python question more than pysam question.  Here is one way to do what you want.
```
empty = next(f1.fetch(chr, start, end), None) is None
if empty:
    print 'fetch returned no records'
else:
    print 'fetch returns at least one record'
```

Hope this helps...

**Comment by WinterLi1993** [comment]
why  use next  ?? what's that function in python ?

**Comment by bioinformed** [comment]
See https://docs.python.org/2/library/functions.html#next

**Comment by WinterLi1993** [comment]
thank you ! @bioinformed   
could you please read #363  ?

**Comment by WinterLi1993** [comment]
@snashraf   do you have solved your question ?

**Comment by WinterLi1993** [comment]
@snashraf   f1.fetch(str(chr), int(start), int(end)) will return  a Iterator .  you can use next() to get the value .
