### ISSUE TITLE
Support for CSI indexed BAM files

### ISSUE THREAD

**Issue by MikkelSchubert** [pysam-developers/pysam#370]
Pysam currently does not support random access for BAM files indexed using the 'CSI' format (e.g. via samtools index -c input.bam), which is required for alignments involving sequences longer than the maximum of 2^29 - 1 bp supported by the BAI index format.

However, support for CSI is already part of HTSLib, and as far as I can tell, the only thing preventing the use of CSI index files (for local files) in Pysam is the following check in libcalignmentfile.pyx:

                    if self.is_bam \
                            and not os.path.exists(filename + b".bai") \
                            and not os.path.exists(filename[:-4] + b".bai"):
                        self.index = NULL
                        has_index = False

https://github.com/pysam-developers/pysam/blob/56cc5ba6b5c91bf9127056ca8f5d2e6e0c583d76/pysam/libcalignmentfile.pyx#L627-L631

Simply changing the above to something like the following appears to be sufficient for random access to 'CSI' indexed BAM files, based on my limited testing:

                    if self.is_bam \
                            and not os.path.exists(filename + b".bai") \
                            and not os.path.exists(filename[:-4] + b".bai") \
                            and not os.path.exists(filename + b".csi") \
                            and not os.path.exists(filename[:-4] + b".csi"):
                        self.index = NULL
                        has_index = False

But as I am not comfortable enough with the Pysam code-base to be sure that this is all that needs to be changed, and I am opening this issue as a feature-request, rather than doing a pull request.

Cheers

**Comment by AndreasHeger** [comment]
Thanks for the suggestion and providing the fix. Apologies for taking so long.

**Comment by galaxy001** [comment]
What about csi index for bcf/vcf files ?

**Comment by AndreasHeger** [comment]
I will open a new ticket.
