### ISSUE TITLE
AlignedSegment hash logic is faulty

### ISSUE THREAD

**Issue by IosifSpulber** [pysam-developers/pysam#375]
From the Python [docs](https://docs.python.org/2/reference/datamodel.html#object.__hash__):
> \_\_hash\_\_() should return an integer. The only required property is that objects which compare equal have the same hash value

This is a source of erratic behaviour and extremely hard to track bugs. For example:
`al_seq in my_dict` -> `False`
`al_seq in my_dict.keys()` -> `True`

**Comment by AndreasHeger** [comment]
Thanks, was not aware of this. I have created an improved implementation, please see #384

**Comment by AndreasHeger** [comment]
Fixed, see #384
