### ISSUE TITLE
Mac OS X 10.11.6 pysam import error - lib curl version incompatibility

### ISSUE THREAD

**Issue by MikeDMorgan** [pysam-developers/pysam#376]
I can successfully install pysam 0.9.1.4 through either bioconda or pip.  However, upon import I receive the following error:

>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michaelm/anaconda2/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(/Users/michaelm/anaconda2/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: libcurl.4.dylib
  Referenced from: /Users/michaelm/anaconda2/lib/python2.7/site-packages/pysam/libchtslib.so
  Reason: Incompatible library version: libchtslib.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

$ curl --version
curl 7.49.0 (x86_64-apple-darwin11.4.2) libcurl/7.49.0 OpenSSL/1.0.2j zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

$ samtools --version
samtools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.

**Comment by AndreasHeger** [comment]
See #231, will this help?

**Comment by AndreasHeger** [comment]
Thanks, closing for now.

**Comment by BEFH** [comment]
This problem is back with 0.14.1

**Comment by acorella143** [comment]
I have the same problem with 0.15.3 and solution linked to does not solve.
