### ISSUE TITLE
Sam file header not written when using non-binary output

### ISSUE THREAD

**Issue by mjafin** [pysam-developers/pysam#380]
Hi there,
Maybe I'm missing something, but when I do the following:
```
samfile = pysam.AlignmentFile("-", "r")
samout = pysam.AlignmentFile("output.sam", "w", template=samfile)
testread = samfile.next()
samout.write(testread)
samout.close()

```
The read is in the output sam file but the header isn't. I'm actually not interested in writing sam files per se but outputting to stdout without any compression slowing me down. I tried versions `0.9.0` and `0.9.1.4`.

Any advice how to force output the header?

**Comment by AndreasHeger** [comment]
Hi, please try the mode "wh", which should include the header.

**Comment by mjafin** [comment]
@AndreasHeger that did the trick, thanks! I can now see `wh` mentioned at http://pysam.readthedocs.io/en/latest/api.html? but it's not that clearly spelled out. Might be useful to more clearly mention it under http://pysam.readthedocs.io/en/latest/usage.html#using-streams don't you think?
