### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ernfrid** [pysam-developers/pysam#381]
I'm using bwa 0.7.15 and was curious if you'd be willing to push out a new release incorporating #326 so that the BWA header is parsed properly.

Thanks for your consideration!

**Comment by AndreasHeger** [comment]
Thanks, I hope to put a new release together before christmas.

Best wishes,
Andreas

**Comment by ernfrid** [comment]
That sounds good to me. Thanks so much for continuing to support pysam!
