### ISSUE TITLE
Problem with samtools view command within python pysam

### ISSUE THREAD

**Issue by ammarsabircheema** [pysam-developers/pysam#382]
I am using this code to filter a bam file for mapping quality but its not working rightly. Instead of producing a new file it is giving strange characters.
My pysam version is 0.9.1.4 on ubuntu 15.10. The code is given below 
print(filename)

'aligned_reads.q30.bam'
pysam.view("-q", "30","-c",filename)
' '
pysam.view("-q", "30","-b",filename,"pysam.bam")
'\x1f\x8b\x08\x04\x00\x00\x00\x00\x00\xff\x06\x00BC\x02\x00\xbf\x00sr\xf4e\x9c\xc1\xc0\xc0\xe0\xe0\xe1\xc2\x19\xe6ge\xa8g\xcc\x19\xeco\x95\x9c\x9f_\x94\x92\x99\x97X\x92\xca\xe5\x10\x1c\xc8\x19\xecg\x95\x9eYcdjhalhh`VS\x94\x9aV\xe3\xe7\x1co`hdid\xa0gX\xc3\xe9\x03\xd4ifjf\xc9\xe5\x10\xe0\xce\xe9\xe9b\x95T\x9e\xc8\x19\xe0\x07\xa6\x80\x86\x1a\xe8\x99\xeb\x19\x1a\xe9\x16\x19\x1a\x18[r:\xfb\x80\x84\x15\x8a\x13s\x8bS\x15\x8a\x92\x8b\x8a\xf5\xd2\x12\x15\x12s\xf2",,\xf4\x8a\x133\x15"\n\x8aR\x8b\x8b\x81\x9c\xb4\xc4\xe2\x92B.F\xa0\xdb\xe4\x80\x18\xaf\xfd\x0c;\x1d\x18\x18\x00\x99\x18\x95\x8c\xca\x00\x00\x00\x1f\x8b\x08\x04\x00\x00\x00\x00\x00\xff\x06\x00BC\x02\x00\x1b\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00'
`

**Comment by AndreasHeger** [comment]
Hi, -b returns data in BAM format, which is a binary format.

**Comment by AndreasHeger** [comment]
Closing for now.
