### ISSUE TITLE
Read-level in PileupRead contains bogus values

### ISSUE THREAD

**Issue by bjoernpollex** [pysam-developers/pysam#383]
When looking at the `level` property of `PileupRead` in a pileup that otherwise looks perfectly fine, I get bogus values like -123310336. Could it be that the field is not initialized correctly? There is a [mention][1] in the htslib documentation that there are two different APIs for constructing pileups, and only one of them calculates the level. Could this be the problem here?

[1]: https://github.com/pysam-developers/pysam/blob/4672fb2a26d7696d9a2d4179e9b4b374e05c506f/htslib/htslib/sam.h#L399

**Comment by AndreasHeger** [comment]
Thanks! Indeed, that is the case. I added a sentence to the docstring, but leave the level property in for the moment.

Do you require the attribute to be set? If so, please reopen the issue.
