### ISSUE TITLE
Pileup using the 'samtools' stepper fails

### ISSUE THREAD

**Issue by vladimirg** [pysam-developers/pysam#386]
Running `bamfile.pileup(stepper="samtools", fastafile=fasta_ref)` (where `fasta_ref` seems to have been initialized without error) fails with the following error:

	Traceback (most recent call last):
	   File "main.py", line 25, in <module>
	     fastafile=fasta_ref):
	   File "pysam/calignmentfile.pyx", line 1112, in pysam.calignmentfile.AlignmentFile.pileup (pysam/calignmentfile.c:12728)
	   File "pysam/calignmentfile.pyx", line 2148, in pysam.calignmentfile.IteratorColumn.__cinit__ (pysam/calignmentfile.c:23006)
	 TypeError: Cannot convert pysam.cfaidx.FastaFile to pysam.cfaidx.Fastafile

pysam version is 0.9.1.4, OS is Mac OS X, running through Anaconda2. I can upload the script and the data, but the data is large. In any case, I think that even if I did something wrong, the error should be a little more informative :)

**Comment by AndreasHeger** [comment]
Thanks. This use case is covered by our tests, see

https://github.com/pysam-developers/pysam/blob/master/tests/AlignmentFile_test.py#L2116

I will need more information to reproduce the issue, such as the function call and how the objects are created.

**Comment by jhmarcus** [comment]
I am having the same issue. I'm using the reference genome and a bam (ENCODE) from ucsc so we can reproduce the error on the same data. To download the data:

```
wget http://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/chr1.fa.gz
gunzip chr1.fa.gz
wget http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/wgEncodeSydhNsome/wgEncodeSydhNsomeGm12878AlnRep1.bam
wget http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/wgEncodeSydhNsome/wgEncodeSydhNsomeGm12878AlnRep1.bam.bai
```

I index the the reference:

```
samtools faidx chr1.fa
```

Here is the python code to generate the error

```
import pysam

chrom = 'chr1'
start_pos = 10151
end_pos = 10600
fasta = pysam.FastaFile('chr1.fa')
sam = pysam.AlignmentFile('wgEncodeSydhNsome/wgEncodeSydhNsomeGm12878AlnRep1.bam', 'rb' )
for pileupcolumn in sam.pileup(chrom, start_pos, end_pos, stepper='samtools', fastafile=fasta):
# ... counts etc.
```

**Comment by jhmarcus** [comment]
as an aside does the stepper='samtools' arg allow one to iterate over positions in the reference where no reads align to in the sam file?
