### ISSUE TITLE
AlignmentFile_test.BasicTestCRAMFromFetch) Segmentation fault on 32-bit platforms

### ISSUE THREAD

**Issue by 0xaf1f** [pysam-developers/pysam#388]
In Debian, we found that the test suite fails on 32-bit platforms. See, for example, [the build log on x32](https://buildd.debian.org/status/fetch.php?pkg=python-pysam&arch=x32&ver=0.9.1.4%2Bds-1&stamp=1479247995).

```
testPairedBools (AlignmentFile_test.BasicTestBAMFromFilename) ... ok
testPresentOptionalFields (AlignmentFile_test.BasicTestBAMFromFilename) ... ok
testTags (AlignmentFile_test.BasicTestBAMFromFilename) ... ok
testARQueryLength (AlignmentFile_test.BasicTestCRAMFromFetch) ... Segmentation fault
```

The Debian bug report is at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834856

**Comment by AndreasHeger** [comment]
Thanks.

**Comment by AndreasHeger** [comment]
Sorry, really hard for me to test, but from the bug report it does not seem to be an issue any more.
Most likely this is an upstream issue either in cython or htslib.
I am closing this for now.
