### ISSUE TITLE
BAM file created by BWA with -R argument causes 'ValueError: unknown field code 'SM' in record 'PG''

### ISSUE THREAD

**Issue by pmarks** [pysam-developers/pysam#39]
The BAM file was created with a BWA 0.7.9a-r786.
It inserted the following @PG header line:

```
@PG     ID:bwa  PN:bwa  VN:0.7.9a-r786  CL:bwa mem -p -t 8 -M -R @RG    ID:None SM:None /mnt/data/hg19.fa /mnt/analysis/default-0.fastq
```

The -R argument to bwa is used to supply the read group header, and BWA help instructs the user to supply tab-delimted fields to that argument:

```
       -R STR     read group header line such as '@RG\tID:foo\tSM:bar' [null]
```

The problem is that BWA puts the whole command-line, including the tab-delimited -R argument in the `@PG` `CL:` field.  But the SAM header format apparently doesn't have a way to escape tabs in the values, so pysam is interpreting the SM:None field as a field in the `@PG` header, rather than as part of the `CL:` string.  Seems that the real problem is in the SAM spec. Should pysam be made more forgiving of this case?

```
In [1]: import pysam

In [2]: sf =pysam.Samfile("/mnt/data/output.bam")

In [3]: sf.header
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-40307eadca76> in <module>()
----> 1 sf.header

/mnt/home/pat/code/pl2/devpipes/anaconda/1.9.2/lib/python2.7/site-packages/pysam/csamfile.so in pysam.csamfile.Samfile.header.__get__ (pysam/csamfile.c:12899)()

ValueError: unknown field code 'SM' in record 'PG'

In [4]: pysam.version.__version__
Out[4]: '0.8.0'
```

**Comment by smowton** [comment]
Ran into a similar problem, created https://github.com/lh3/bwa/pull/46 to address this in BWA.
