### ISSUE TITLE
Help with installing pysam in Cygwin

### ISSUE THREAD

**Issue by smanivannan1986** [pysam-developers/pysam#396]
Hello,

I am trying to install pysam using pip in Cygwin. 

pip install pysam

and I keep getting the following error:
    build/temp.cygwin-2.6.1-x86_64-2.7/pysam/htslib_util.o:htslib_util.c:(.rdata$.refptr.seq_nt16_table[.refptr.seq_nt16_table]+0x0): undefined reference to `seq_nt16_table'
    build/temp.cygwin-2.6.1-x86_64-2.7/pysam/htslib_util.o:htslib_util.c:(.rdata$.refptr.hts_verbose[.refptr.hts_verbose]+0x0): undefined reference to `hts_verbose'
    build/temp.cygwin-2.6.1-x86_64-2.7/pysam/samfile_util.o: In function `bam_prob_realn_core':
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:78: undefined reference to `bam_aux_get'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:78:(.text+0x44c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_get'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:79: undefined reference to `bam_aux_get'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:79:(.text+0x46b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_get'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:86: undefined reference to `bam_aux_del'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:86:(.text+0x4b8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_del'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:82: undefined reference to `bam_aux_del'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:82:(.text+0x55a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_del'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:176: undefined reference to `bam_aux_append'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:176:(.text+0xd40): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_append'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:79: undefined reference to `bam_aux_get'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:79:(.text+0xd84): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_get'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:177: undefined reference to `bam_aux_append'
    /tmp/pip-build-xGbGOa/pysam/pysam/samfile_util.c:177:(.text+0x14ca): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `bam_aux_append'
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1

I am new to pysam and would appreciate any help in troubleshooting this error

**Comment by AndreasHeger** [comment]
merged with issue #575
