### ISSUE TITLE
bgzf errors when using pysam.AlignmentFile.fetch in parallel (with multiprocessing)

### ISSUE THREAD

**Issue by blaiseli** [pysam-developers/pysam#397]
I have a generator wrapping an iteration over a call to `pysam.AlignmentFile.fetch` in which I pass the `AlignedSegment` objects to a function that extracts information from them and yields this information:

```python
with pysam.AlignmentFile(args.bamfile, "rb") as bamfile:
    def generate_annotations():
        """Generates annotations for the alignments in *bamfile*."""
        for i, ali in enumerate(bamfile.fetch(), start=1):
            # [some code to display progress information]
            yield process_annotations(get_annotations(ali), ali)
```

I tried to "fork" this generator using `itertools.tee` in order to perform 4 different computations on the information extracted from the `AlignedSegment`, and then use each of the 4 resulting generator in a different process using `multiprocessing.Process` (synchronizing the processes with a lock in order to avoid too much memory usage by the tee). On a small test bam file, this seems to work.
However, on a larger bam file, this results in the following errors:

```
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::inflate_block] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::inflate_block] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::inflate_block] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::inflate_block] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::inflate_block] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::inflate_block] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
```

These errors are just printed, but do not seem to trigger an exception in python. If I understand correctly, this is because they are defined at the htslib C-code level (in file bgzf.c), and those errors are not treated as errors by pysam.

When I perform these computations in a pseudo-parallel approach (based on zipped accumulators as here: <http://stackoverflow.com/a/29509642/1878788>), I don't observe these error messages.

Note: I initially thought the problem had to do with pybedtools (<https://github.com/daler/pybedtools/issues/194>), but it seems that it is more a pysam issue.

**Comment by raonyguimaraes** [comment]
I'm experiencing the same problem while trying to use pysam and multiprocessing

**Comment by tianguolangzi** [comment]
As far as I know, you should create an object  in each process. Here is a example.
```python
def work(BAM):
    samfile = pysam.AlignmentFile(BAM, "rb")
     for read in samfile.fetch(CHR, START, END):
          pass

pool=Pool(processes=CPU)
for i in range(9):
    pool.apply_async(work, (BAM,))
pool.close()
pool.join()
```

**Comment by AndreasHeger** [comment]
Thanks, the solution by @tianguolangzi should work.

If multiple iterators are required within the same process, try adding using
```
samfile.fetch(multiple_iterators=True)
```
This will provide each iterator with its own file, but will be slow if there are many fetch operations as files are frequently opened and closed.

Closing this issue for now.
