### ISSUE TITLE
Allow use of '*' in region string

### ISSUE THREAD

**Issue by kghosesbg** [pysam-developers/pysam#399]
A very useful feature of `samtools view` is the `*` region tag that allows us to fetch all the unmapped reads in the file stuck at the end because they have no reference_id. It would be nice to have this in `psyam.fetch`. Currently the code complains `ValueError: invalid reference '*'`. Thanks so much!

**Comment by AndreasHeger** [comment]
Thanks, I did not even know that was possible. Will add this for the next release.

**Comment by byb121** [comment]
Hi,
I encountered the same issue, so just wondering what's the progress on this. 

Thanks,

**Comment by AndreasHeger** [comment]
Thanks for reminding me, this has now been added.

**Comment by dpryan79** [comment]
Great minds think alike? I assume that that'll work. Since it's in master now I'll just test that on a CRAM file to double check. I'll open a PR based on that should it be needed.
