### ISSUE TITLE
pysam sort removes last x sequences

### ISSUE THREAD

**Issue by vladie0** [pysam-developers/pysam#404]
Dear developers, 
I've discovered an issue with pysam.sort() where the last x lines are discarded from the sorted output. Even when you provide a file with only for example 2 lines no output will be generated in the sorted file. 

This has been verified in several cases. 
As an example I've included a google drive link containing a sam file with only 2 lines, when converted to BAM, these 2 lines are still present, however, when sorting using your pysam tool, a blank file is generated. 

https://drive.google.com/open?id=0B3z-MmiBk77oNld0cDNDMnJuOHc

Executing the conversion and sorting with samtools (not pysam) does not generate these problems. If you look at the size of the ouput files, the pysam files are always smaller as they exclude the last x lines.

**Comment by AndreasHeger** [comment]
Thanks, I will take a look at this.

**Comment by AndreasHeger** [comment]
Hmm, I am not sure I can reproduce the issue, see for example:

```
  python -c 'import pysam; print pysam.sort("-O", "SAM", "error.bam")'
@HD     VN:1.0 SO:coordinate    SO:coordinate
@SQ     SN:chr2 LN:182113224    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr17        LN:94987271     AS:GRCm38       SP:mus_musculus
@SQ     SN:chr9 LN:124595110    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr15        LN:104043685    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr6 LN:149736546    AS:GRCm38       SP:mus_musculus
@SQ     SN:chrX LN:171031299    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr18        LN:90702639     AS:GRCm38       SP:mus_musculus
@SQ     SN:chr5 LN:151834684    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr3 LN:160039680    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr14        LN:124902244    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr13        LN:120421639    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr8 LN:129401213    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr1 LN:195471971    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr16        LN:98207768     AS:GRCm38       SP:mus_musculus
@SQ     SN:chr10        LN:130694993    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr12        LN:120129022    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr19        LN:61431566     AS:GRCm38       SP:mus_musculus
@SQ     SN:chr7 LN:145441459    AS:GRCm38       SP:mus_musculus
@SQ     SN:chrY LN:91744698     AS:GRCm38       SP:mus_musculus
@SQ     SN:chr4 LN:156508116    AS:GRCm38       SP:mus_musculus
@SQ     SN:chr11        LN:122082543    AS:GRCm38       SP:mus_musculus
@SQ     SN:chrMT        LN:16299        AS:GRCm38       SP:mus_musculus
ms_run[0]:index=47241   16      chr7    80799930        255     20M3191N52M     *       0       0       CCTCTCATTATCCAGGACGGAGCCATAGTGCGGCCGGACCACACCCAGGCCATCAACCTCCTCCGCGGCGGA        *    NH:i:1   XA:i:0  XB:f:0.00143232 XC:i:3  XE:i:1  XF:Z:0,1        XG:Z:N  XI:f:0  XL:i:1  XM:Z:0-UNIMOD:1 XN:i:0  XO:Z:*  XP:Z:SAAEEVDGLGVVRPHYGSVLDNER   XQ:f:9.00731e-10        XR:Z:SAAEEVDGLGVVRPHYGSVLDNER XS:f:100        XT:i:3  XU:Z:*  YA:Z:LT YB:Z:AM YP:Z:ENSMUST00000167377 ZA:Z:ENSMUST00000167377
ms_run[0]:index=47152   16      chr7    80799930        255     20M3191N52M     *       0       0       CCTCTCATTATCCAGGACGGAGCCATAGTGCGGCCGGACCACACCCAGGCCATCAACCTCCTCCGCGGCGGA        *    NH:i:1   XA:i:0  XB:f:0.00106232 XC:i:3  XE:i:1  XF:Z:0,1        XG:Z:N  XI:f:0  XL:i:1  XM:Z:0-UNIMOD:1 XN:i:0  XO:Z:*  XP:Z:SAAEEVDGLGVVRPHYGSVLDNER   XQ:f:2.76483e-18        XR:Z:SAAEEVDGLGVVRPHYGSVLDNER XS:f:100        XT:i:3  XU:Z:*  YA:Z:LT YB:Z:AM YP:Z:ENSMUST00000167377 ZA:Z:ENSMUST00000167377
```

What version of pysam are using?

**Comment by vladie0** [comment]
Dear AndreasHeger, 

Thank you for your fast response, 
I suspect I've found the error behind my output. When I generate the output in the following way:
    infile = pysam.AlignmentFile((directory+name+'.sam'), "r")
    outfile = pysam.AlignmentFile((directory+name+'.bam'), "wb", template=infile)
    for s in infile:
        outfile.write(s)

print pysam.sort("-O", "SAM", "error.bam")'
only the first line is printed in the final output. However when infile and outfile are closed prior to sorting, the correct output is generated. I suspect that there is a delay between writing and saving.

Apologies for early bug report, I could have figured this out myself...

**Comment by AndreasHeger** [comment]
Thanks, no problem. Closing for now.
