### ISSUE TITLE
Missing header for SAM output?

### ISSUE THREAD

**Issue by brendanofallon** [pysam-developers/pysam#405]
Not sure if this is intentional or not, but looks like when writing SAM (but not BAM) files the header is omitted. For instance, following the example from readthedocs: 

```
inbam = pysam.AlignmentFile("test/test_data/small.lmna.bam", "rb")
pairedreads = pysam.AlignmentFile("allpaired.bam", "wb", template=inbam)
for read in inbam.fetch():
     if read.is_paired:
             pairedreads.write(read)

pairedreads.close()
inbam.close()
```

...this works as expected and creates a correctly formatted BAM file.  However, replacing the second line with
```
pairedreads = pysam.AlignmentFile("allpaired.sam", "w", template=inbam)
```
results in a file with no header and just the reads. 

Seems a bit inconsistent, but perhaps there's a good reason for it?

**Comment by bioinformed** [comment]
This is one of my least favorite behaviors in `pysam` (that is inherited from `htslib`).  When writing SAM files, one must include the 'h' mode to get a header.

**Comment by brendanofallon** [comment]
Thanks Kevin, that makes sense (well, mostly). Good ol' mode "h"...

**Comment by AndreasHeger** [comment]
... I reopen this, time to add a add_header option to AlignmentFile(). Default should be true I guess.

**Comment by pfaucon** [comment]
seconded, I just ran into this same problem.  At the minimum if the header is not written by default then Pysam should be able to handle SAM files without a header...

**Comment by bioinformed** [comment]
As much as I dislike the current behavior, this will be a breaking change for any applications that currently use mode `h` to control this behavior.  Assuming htslib 1.4 also introduces fairly big changes, can we roll this into a `1.0.0` release?

**Comment by pfaucon** [comment]
That would be fair. For my use-case I don't particularly care whether there is a header (I prefer one, but it doesn't matter).   My use-case only requires(would like) that files written using pysam with default write options can also be read using pysam with default read options.
