### ISSUE TITLE
pysam.sort not compatible with samtools version

### ISSUE THREAD

**Issue by creisle** [pysam-developers/pysam#410]
Hi,

I was trying to use the pysam.sort method to sort a bam. I followed the instructions in the documentation 

    pysam.sort("/path/to/input/bam", "output/bam/prefix")

but I am getting the following error

    pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\nUsage: samtools sort [options...] [in.bam]\nOptions:\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n  -n         Sort by read name\n  -o FILE    Write final output to FILE rather than standard output\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n  -@, --threads INT\n             Set number of sorting and compression threads [1]\n      --input-fmt-option OPT[=VAL]\n               Specify a single input file format option in the form\n               of OPTION or OPTION=VALUE\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n               Specify output format (SAM, BAM, CRAM)\n      --output-fmt-option OPT[=VAL]\n               Specify a single output file format option in the form\n               of OPTION or OPTION=VALUE\n      --reference FILE\n               Reference sequence FASTA FILE [null]\n'

I suspect that the code for this method was not updated when the backend samtools moved from v0+ to v1+ as that is where the sort command differs and now requires the -o flag

Thanks,

Cara

**Comment by JureZmrzlikar** [comment]
I had the same problem, one possible workaround is:
`pysam.sort("-o",  output_bam, input_bam)`

**Comment by AndreasHeger** [comment]
Thanks, I have updated the docs.
