### ISSUE TITLE
HTSlib/Samtools/BCFtools 1.4

### ISSUE THREAD

**Issue by mp15** [pysam-developers/pysam#413]
Hi pysam folks,

Just a quick heads up from the @samtools team that HTSlib/samtools/bcftools 1.4 has been released and a warning that it slightly breaks ABI/API compatibility from 1.3.1 (we have bumped the SO version).

**Comment by AndreasHeger** [comment]
Thanks, @mp15 

@bioinformed , I can create a branch and to the part this weekend.

**Comment by bioinformed** [comment]
@AndreasHeger, how is the update to 1.4 coming along?  I'm happy to help.

**Comment by AndreasHeger** [comment]
@bioinformed , I did a first merge yesterday. I think the core functionality such as VariantFile and AlignmentFile should be ok.

However, a headache is that now there are common source files in both bcftools and samtools that share the same symbols, but which are not identical (example: bam2bcf.c). This means that the bcftools and samtools APIs each need to be put into separate shared libraries at the minimum and maybe even need same name mangling.

**Comment by AndreasHeger** [comment]
I have another half hour today and will push as far as I have gotten to.

**Comment by AndreasHeger** [comment]
I added htslib and pushed changes to branch htslib-1.4. 

Compilation works and the majority of tests pass, but there is a segfault in the CRAM tests.

**Comment by AndreasHeger** [comment]
@bioinformed, the issue seems to be when opening CRAM files. The segfault appears here:

https://github.com/pysam-developers/pysam/blob/htslib-1.4/pysam/libchtslib.pyx#L194

I have not much experience with CRAM files in htslib, do you know that could be the reason?

**Comment by bioinformed** [comment]
I suppose I'm not surprised.  I think we're using too low a level API for
seeking that isn't correct for CRAM files.  I'll do some research into the
proper way.

**Comment by AndreasHeger** [comment]
@bioinformed, I think I solved the segfault, but only by digging yet deeper (pushed changes). Tests still fail at stream processing and bcftools system.

**Comment by jkbonfield** [comment]
The bgzf_seek call only works on bgzf streams (so gzipped SAM or BAM, but not CRAM).  I'm suprised this ever worked with CRAM!  Did it, or this this a new feature you're testing?

I'm not entirely familier with which seeking functions work in htslib as I know there have been some problems in the past.  The recommended interface is via iterators, such as ```hts_itr_query / next / destroy```.  These work for all indexed file formats.

**Comment by bioinformed** [comment]
@jkbonfield: This feature never worked on CRAM.  The goal here is to make all HTS files work consistently as file-like objects in Python, which means that we want `seek` and `tell` to work on all HTS file types.  It *feels* wrong to dig into the low-level APIs to do so, but it has worked well enough in the past.

**Comment by jkbonfield** [comment]
I'm unsure of the robustness of using it, but there is ```hseek``` too.  It is used internally by ```bgzf_seek``` and also by samtools reheader for CRAMs.  However it works on the internal ```hFile``` structure rather than the higher level ```htsFile``` so is sub-format specific.  There is also ```hts_useek```  defined in hts.c as:

```
int hts_useek(htsFile *fp, long uoffset, int where)
{
    if (fp->is_bgzf)
        return bgzf_useek(fp->fp.bgzf, uoffset, where);
    else
        return (hseek(fp->fp.hfile, uoffset, SEEK_SET) >= 0)? 0 : -1;
}
```

I'm afraid I'm not up to speed enough to understand all the nuances surrounding seeking and to say which ones work in which environments.  I have vague alarm bells ringing about one of these interfaces not working as people expect, but I cannot recall what that conversation was about.  However these are probably starting points to experiment with if you still need the low level interface, just check thoroughly!  Maybe @jmarshall recalls the specific details.

What is it specifically which you are trying to do?  Is this seeking in a compressed context or uncompressed one?  Are you seeking to computed new locations, or only to places you have previous been to and got an offset from a corresponding tell command?

Ultimately though, I still think the preferred interface is using iterators instead to achieve the same goal as they are definitely supported fully.

**Comment by bioinformed** [comment]
The greater goal is to have a fully abstract file-like object, though my primary use case is to be able to reset the file position to just after the header to allow iteration over all records.  i.e. I do a `tell` after the header is read and then `seek` to that location to reset it.  @AndreasHeger, are you aware of other use-cases?

**Comment by AndreasHeger** [comment]
@bioinformed, I can't think of any other use case and not sure if seek/tell are widely used - certainly not on CRAM files so far. Could it be useful when processing unordered collections of reads, such as 'unmapped BAM files'?

There is a toy implementation of building an in-memory index of reads by name, in applications where you might need reads mapping in a region, but also need to locate a read. Long time ago and I can't remember in what context I was playing around with this.

**Comment by AndreasHeger** [comment]
@jkbonfield, many thanks for the pointers, I will take a look. So far we have no tests for CRAM seeking so don't even know if the current way with htell works (I just see that I forgot to add CRAM seek, only CRAM tell).

**Comment by AndreasHeger** [comment]
Hi @bioinformed , htslib 1.4 conversion is now complete, though there are still a few odds and ends. I propose to release a new pysam 0.11 as soon as possible, even if no new features are enabled, just to resolve the dependency problems people have. What do you think?

**Comment by bioinformed** [comment]
Great!  I agree. I have two pending bug fixes that I will be able to finish on Saturday.

**Comment by AndreasHeger** [comment]
Thanks, @bioinformed, will aim to release on Monday.

**Comment by AndreasHeger** [comment]
Closing this for now, htslib 1.4 is in.
