### ISSUE TITLE
Cannot import pysam: ModuleNotFoundError: No module named 'pysam.libchtslib'

### ISSUE THREAD

**Issue by dyao267** [pysam-developers/pysam#414]
Hi, I've been trying to install and import the latest version of pysam (from the tar) for Python 3.6. The installation successfully finishes, but when I enter into Python 3.6 and try to import pysam, I get the error:

ModuleNotFoundError: No module named 'pysam.libchtslib'

As an aside, installing pysam using pip (into Python 2.7) works, and importing pysam into Python 2.7 also works without any problems.

I'm really new to programming, but please let me know if there's any other information I can help provide. Thanks for any help!

**Comment by AndreasHeger** [comment]
Hi, sorry to hear that, can you please provide the sequence of commands you use for the python3.6 installation?

**Comment by pfaucon** [comment]
I have a similar problem, I installed from pip:
pip3 install pysam
Collecting pysam
  Downloading pysam-0.11.tar.gz (2.4MB)
    100% |████████████████████████████████| 2.4MB 410kB/s 
Installing collected packages: pysam
  Running setup.py install for pysam ... |
done
Successfully installed pysam-0.11

error is:
[my code]
    import pysam
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:7724)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysam/libcutils.so, 2): Library not loaded: @rpath/pysam-0.11-py3.4-macosx-10.6-x86_64.egg/pysam/libcsamtools.so
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysam/libcutils.so
  Reason: image not found
Process finished with exit code 1


On my other system I've been using pysam 0.10.0 without issue.  After uninstalling and then selecting that version specifically with pip (pip install -I pysam=0.10.0) it seems to work.  I'm not certain of the bug source but a similar bug seems to appear in [issue 308](https://github.com/pysam-developers/pysam/issues/308), perhaps it is related?

**Comment by tedtoal** [comment]
I have exactly the same error message, which occurs when I try to run CrossMap.py, a bioinformatics utility that uses pysam.  libcutils.so seems to be the problem. When I try to install 0.10.0, pip can't find that version.

**Comment by SrijaMukhopadhyay** [comment]
I am installing as
pip install -I pysam==0.8.4
 Collecting pysam==0.8.4
  Using cached pysam-0.8.4.tar.gz
Installing collected packages: pysam
  Running setup.py install for pysam ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yni0nL/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yAm_20-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pysam
    copying pysam/Pileup.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/__init__.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/namedtuple.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/version.py -> build/lib.linux-x86_64-2.7/pysam
    creating build/lib.linux-x86_64-2.7/pysam/include
    copying pysam/include/__init__.py -> build/lib.linux-x86_64-2.7/pysam/include
    package init file 'htslib/__init__.py' not found (or not a regular file)
    package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
    package init file 'samtools/__init__.py' not found (or not a regular file)
    package init file 'samtools/win32/__init__.py' not found (or not a regular file)
    copying pysam/calignedsegment.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/calignmentfile.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/cbcf.pxd -> build/lib.linux-x86_64-2.7/pysam
.................................................[many lines in between]..........................................................
    running install_lib
    creating /usr/lib64/python2.7/site-packages/pysam
    error: could not create '/usr/lib64/python2.7/site-packages/pysam': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yni0nL/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yAm_20-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yni0nL/pysam/


What should I do?

**Comment by pfaucon** [comment]
"error: could not create '/usr/lib64/python2.7/site-packages/pysam': Permission denied" means you are trying to install into a protected directory without privilege.  It's been a while since I worked with this project but if you prepend "sudo " to your command then you will request privileges for the following command.  Generally it is something you should be careful with, but this seems like a reasonable case.

You should also be able to add the option "--user" which should install the package in your user directory only for you if you prefer.

**Comment by AndreasHeger** [comment]
Closing this for now.

**Comment by edwwlui** [comment]
in my case restarting the terminal solved the "ModuleNotFoundError: No module named 'pysam.libchtslib'" error

**Comment by brianpenghe** [comment]
> in my case restarting the terminal solved the "ModuleNotFoundError: No module named 'pysam.libchtslib'" error after an update in pysam

I solved this problem by exporting the correct PYTHONPATH.
