### ISSUE TITLE
tid fetch doesn't work?

### ISSUE THREAD

**Issue by gpratt** [pysam-developers/pysam#415]
Hello, 

I recently ran across a bug with the fetch command in pysam.  It might be worth checking out.  Long story short when I try to fetch a chromosome by the tid, it just fetches all reads in the file.

```
samtool = pysam.Samfile(os.path.join("/home/gpratt/projects/idr/analysis/umi_downsampling", "629_CLIP_S21_L005_R1_001.A03_629_02_UCHL5.adapterTrim.round2.rmRep.sorted.adjusted.bam"))
print "num reads in chr1", len(list(samtool.fetch("chr1")))
tid = samtool.get_tid("chr1")
print "num reads in everything?", len(list(samtool.fetch(tid=tid)))
```

The output is this:
```
num reads in chr1 1021374
num reads in everything? 23325398
```

I'm using pysam version 0.10.0, however due to some backwards compatibility issues on with my scripts I'm not using an updated version of samtools and hitslib.  Currently at versions:

samtools 1.2 
htslib 1.2.1

I've got my easy workaround (just use the chrom name), so its not high priority, but thought I should bring it to your attention.

Hope its just a bug on my end, but let me know if you can repo it! 

Thank you

**Comment by TomSmithCGAT** [comment]
Hi @AndreasHeger. I get the same behaviour. The documentation for _fetch_ doesn't actually mention the _tid_ option but I assume this is not the intended behaviour?

**Comment by AndreasHeger** [comment]
Thanks both, this has now been fixed.
