### ISSUE TITLE
Possible fix for setuptools RPATH

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#416]
The bioconda recipe for Pysam just had a setup.py patch that allegedly improved OSX portability.  I haven't reviewed it yet but I figured I'd post the link in case someone wants to think about it before the 1.4 push.

https://github.com/bioconda/bioconda-recipes/pull/4141

**Comment by bioinformed** [comment]
I'll take a look, but the patch doesn't look right -- it removes the rpath
entirely.  I'll check to be sure, but that chance will break linking
against pysam which is needed by other Cython modules that cimport pysam.

-Kevin

**Comment by bioinformed** [comment]
Verified.  This patch breaks linking against `pysam` on OS X from other non-pysam Cython modules.

**Comment by kyleabeauchamp** [comment]
SGTM, this was just an FYI anyway.

**Comment by AndreasHeger** [comment]
Thanks!
