### ISSUE TITLE
pip install fails for python 3.3.6 (using venv)

### ISSUE THREAD

**Issue by bamyasi** [pysam-developers/pysam#417]
Hi,

I am trying to install pysam 0.10.0 on our Linux cluster. No matter which combination of HTSLIB_MODE and HTSLIB_SOURCE I tried, 'pip install pysam' would always fail with the following error from the linker:

/usr/bin/ld: cannot find -lchtslib

This is python 3.3.6 and pip 9.0.1 run in a virtual environment (created via venv). I have also tried 'python setup.py install' method but it fails with the same error.

Best,
Ivan

**Comment by AndreasHeger** [comment]
Sorry, but we don't support python 3.3 any more. I don't recall the exact reason, but I think it was due to incompatibilities with linking/building to later python 3 versions. Is it possible to upgrade?
