### ISSUE TITLE
constants for flag bitmasks

### ISSUE THREAD

**Issue by jpaul6** [pysam-developers/pysam#419]
Simple question. I know that I can read/set fields on an AlignedRead.flag like is_paired from Python. I see things like BAM_FPAIRED being used (as a bitmask) throughout the pysam code. Is there a way I can import these named bitmasks directly so that I can do bitwise logic in Python? I.e.

```
a = AlignedRead()
.
.
.
a.flag |= BAM_FPAIRED | BAM_FPROPER_PAIR
```

**Comment by AndreasHeger** [comment]
Good suggestion, will look into enum export support in cython.
