### ISSUE TITLE
usage() gives 'csamtools' is not defined error

### ISSUE THREAD

**Issue by garrett-stevens** [pysam-developers/pysam#422]
I'm trying to follow some of the examples in [the docs](https://pysam.readthedocs.io/en/latest/usage.html#using-samtools-commands-within-python). The directions there say:

> In order to get usage information, try:
`print pysam.sort.usage()`

However when I try
`print(pysam.sort.usage())`
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.5/site-packages/pysam/utils.py", line 95, in usage
    retval, stderr, stdout = csamtools._samtools_dispatch(
NameError: name 'csamtools' is not defined
```
I'm using Python 3.5.1 and pysam 0.10.0
Thanks.

**Comment by kyleabeauchamp** [comment]
Pyflakes confirms that this is a bug currently in master:

```
pyflakes utils.py 
utils.py:95: undefined name 'csamtools'
```

**Comment by kyleabeauchamp** [comment]
Not sure when `csamtools.c` disappeared, however---I don't see it being generated when I build the current master.

**Comment by kyleabeauchamp** [comment]
So I see two problems: the lib is not generated, and the import is missing.

**Comment by AndreasHegerGenomics** [comment]
Thanks, this has now been fixed.
