### ISSUE TITLE
 iterate ONLY over the unmapped reads 

### ISSUE THREAD

**Issue by smangul1** [pysam-developers/pysam#424]
Is there a way to iterate ONLY over the unmapped reads?

Thanks,
Serghei

**Comment by AndreasHeger** [comment]
Good question, but I don't think there is, other than iterating over the complete file and filtering by 'unmapped' flag. The problem, I believe, is that unmapped reads can have a contig assigned to them, or not. Thus, unmapped reads might appear in several locations in a sorted BAM and not as a contiguous block.

**Comment by arogozhnikov** [comment]
In my case all unmapped alignments are not assigned to any contig. Still no better way than just iterate over whole file?

**Comment by bw2** [comment]
Same feature request - adding a way to iterate over unmapped reads at the end of a cram file (ie. those with ref seq id = -1 in the cram index).

**Comment by jmarshall** [comment]
Have you tried the [documented way](https://pysam.readthedocs.io/en/stable/api.html#pysam.HTSFile.parse_region) of doing this, which uses the same syntax as the underlying samtools queries:

```python
AlignmentFile.fetch('*')
```

**Comment by bw2** [comment]
Wow, thanks! That's exactly what I was looking for!

The top google hits currently talk about doing this using `fetch(until_eof=True)` 
https://pysam.readthedocs.io/en/latest/faq.html#alignmentfile-fetch-does-not-show-unmapped-reads
https://www.biostars.org/p/361215/
https://www.biostars.org/p/9542602/
etc.
but this is a much better solution.
