### ISSUE TITLE
IndexedReads function failed

### ISSUE THREAD

**Issue by bitezhu** [pysam-developers/pysam#426]
Hi ,recently I've been trying to extract read from bamfile by reads name ,and I found IndexedReads function in pusan module .But here is a error that I couldn't figure out.Any suggestion?
#####code is below
import sys
import pysam

samfile=pysam.AlignmentFile(sys.argv[1],'rb')
print pysam.IndexedReads(samfile,).find(sys.argv[2])

samfile.close()

And then I got the error as below, not sure what's going wrong .
Traceback (most recent call last):
  File "readindex.py", line 6, in <module>
    print pysam.IndexedReads(samfile,).find(sys.argv[2])
  File "pysam/calignmentfile.pyx", line 2517, in pysam.calignmentfile.IndexedReads.find (pysam/calignmentfile.c:24961)
TypeError: argument of type 'NoneType' is not iterable

**Comment by AndreasHeger** [comment]
Hi, sorry, the interface is obtuse. You need to call index.build():

```
index = pysam.IndexedReads(samfile)
index.build()
```
