### ISSUE TITLE
Can pysam return raw read counts instead of alignments?

### ISSUE THREAD

**Issue by Osiris1975** [pysam-developers/pysam#439]
I am looking for a way to get raw count of mapped + unmapped reads from a bam file. It seems to me idxstats and pysam.count both return alignments, not raw reads. If I take a bam file and perform 
samtools view file.bam | cut -f 1 | sort -u > foo | wc -l at terminal, I get a very different number than what pysam.count provides since reads can align to multiple places. So does pysam have a built-in version of what I've done at terminal?

**Comment by dpryan79** [comment]
You can use the `count()` function with a `read_callback` that returns `True` if the read isn't a secondary or supplemental alignment. This would be equivalent to `samtools view -c -F 2304 file.bam`, which is a much faster version of what you've been doing.

**Comment by AndreasHeger** [comment]
Thanks, closing this issue.
