### ISSUE TITLE
infer_query_length() is missing the "always" keyword option.

### ISSUE THREAD

**Issue by dpryan79** [pysam-developers/pysam#440]
As of the last release, the `infer_query_length()` function apparently lost the `always=` keyword argument. This is very problematic, since it breaks a lot of existing code (e.g., deepTools). I'm happy to make a PR to fix this if needed.

**Comment by AndreasHeger** [comment]
Thanks, apologies, doing things in a rush leads to bad choices. I think I prefer the newer API, but happy to restore backwards compatibility.
