### ISSUE TITLE
Unaligned.bam

### ISSUE THREAD

**Issue by Rickyzhang1990** [pysam-developers/pysam#442]
Hi 
Recently I use pysam to deal an unaligned.bam generated by 10xgenomics  longranger basic program.
my code is as follows:
import pysam 
samfile = pysam.AlignmentFile(mybam_file, "rb")
but it didn't work and the error is 
> f = pysam.AlignmentFile("barcoded_unaligned.bam",'rb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/calignmentfile.pyx", line 340, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4559)
  File "pysam/calignmentfile.pyx", line 589, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7130)
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening withcheck_seq=True
>
so this module do not support the unaligned bam?
Thank you 
Best Regards 

chaozhang

**Comment by AndreasHeger** [comment]
pysam should be able to open unaligned bams, could you provide an example?

**Comment by Rickyzhang1990** [comment]
I have fix the problem ,last time my pysam version is 0.6 ,when I update the pysam to the latest,It worked .perhaps some problem in my last version pysam 
Thank you for your reply 
Best  regards

**Comment by AndreasHeger** [comment]
Closing issue.

**Comment by a-slide** [comment]
I recently bumped into the same issue with an unaligned CRAM file using pysam '0.15.3'

```
with pysam.AlignmentFile(fn, "rc") as cram_fp:
    for read in cram_fp:
        print (read)
```

```
---------------------------------------------------------------------------

pysam/libcalignmentfile.pyx in pysam.libcalignmentfile.AlignmentFile.__cinit__()

pysam/libcalignmentfile.pyx in pysam.libcalignmentfile.AlignmentFile._open()

ValueError: file has no sequences defined (mode='rc') - is it SAM/BAM format? Consider opening with check_sq=False
```

**Comment by a-slide** [comment]
I also realised that my CRAM file did not have a header.
Opening the file with `check_sq=False` and getting new reads with `next(fp)` works
At the end of the file it raises a `StopIteration` that one can catch to stop reading
