### ISSUE TITLE
Slight difference between pysam count_coverage and samtools depth

### ISSUE THREAD

**Issue by bowentan** [pysam-developers/pysam#444]
Commands:
* in pysam: 
```
bam = pysam.AlignmentFile('sample.bam', 'rb')
bam.count_coverage('chr6', 28479009 - 1, 28479009, quality_threshold = 0)
```
with output:
```
(array('L', [1L]), array('L', [0L]), array('L', [0L]), array('L', [102L]))
```
So the depth should be 103 in this position
* in samtools: 
```
samtools depth -aa -r chr6:28479009-28479009 sample.bam
```
with output:
```
chr6    28479009        104
```
Actually, with two above commands, I found slight difference in some genomic positions. In pysam,  some positions had lower depths with 1 or 2 fewer coverage than the results of samtools. Why? What did I miss here? The sample files are given as attached. Thanks
[sample.zip](https://github.com/pysam-developers/pysam/files/942043/sample.zip)

**Comment by AndreasHeger** [comment]
Thanks for providing the example. Will get back to you.

**Comment by AndreasHeger** [comment]
Hi, the difference is that there is also one 'N' at this position. pysam discards this, while samtools depth includes this. Will output 'N' counts as well.

**Comment by bowentan** [comment]
Oh, I get it. Thanks for that!
