### ISSUE TITLE
VariantRecord Parsing

### ISSUE THREAD

**Issue by nlapalu** [pysam-developers/pysam#449]
Hi,

I try to parse my vcf with VariantRecord Object (ie):

```
for val in f.fetch(str(contig), int(start), int(end)):
    print list(val.format.keys())                                                                                    
    print list(val.info.keys())
    print list(val.format.values())
    print list(val.info.values())
```
The values method only return "VariantMetadata" object for filter and format method, whereas I get values with info method. (see below). How can I get the values of the fields ?

```

['GT', 'DP', 'RO', 'QR', 'AO', 'QA', 'GL']
['DP', 'DPB', 'EPPR', 'GTI', 'MQMR', 'NS', 'NUMALT', 'ODDS', 'PAIREDR', 'PQR', 'PRO', 'QR', 'RO', 'RPPR', 'G_AN', 'G_AF', 'G_DP', 'G_Base']
[<pysam.cbcf.VariantMetadata object at 0x7fc479d3c5d0>, <pysam.cbcf.VariantMetadata object at 0x7fc479d3ccd0>, <pysam.cbcf.VariantMetadata object at 0x7fc47
9d3cd10>, <pysam.cbcf.VariantMetadata object at 0x7fc479d3cd50>, <pysam.cbcf.VariantMetadata object at 0x7fc479d3cd90>, <pysam.cbcf.VariantMetadata object a
t 0x7fc479d3cdd0>, <pysam.cbcf.VariantMetadata object at 0x7fc479d3ce10>]
[5, 5.0, 3.4445900917053223, 0, 41.0, 1, 0, 0.0, 1.0, 0.0, 0.0, 188, 5, 6.918950080871582, 0, 0.0, 5, 'T']
```

Thanks for your help !

**Comment by bioinformed** [comment]
`format` provides the metadata available from each sample and maps to `VariantMetadata` objects.  To get `format` values, one must access them via `samples`:
  `[sample.items() for sample in val.samples]`

There is some basic API documentation available from http://pysam.readthedocs.io/en/latest/api.html#vcf-files
We know it is fairly minimal, so please feel free to contribute any improvements.

**Comment by nlapalu** [comment]
Hi Kevin,
Thanks for the reply. I get the solution:

`val.samples` return pysam.cbcf.VariantRecordSamples
So, to get my "format" values, I need to call items on VariantRecordSamples and parse the list of tuple (str, VariantRecordSample):

```
for sample in val.samples.items():
     print "sample name: {}".format(sample[0])
     print "format values: {}".format(sample[1].items())
```
results:

```
sample name: G32
format values: [('GT', (1, 1)), ('DP', 3), ('RO', 1), ('QR', 40), ('AO', (2,)), ('QA', (82,)), ('GL', (-6.149899959564209, 0.0, -2.6096301078796387))]
```
