### ISSUE TITLE
Extending pysam

### ISSUE THREAD

**Issue by wckdouglas** [pysam-developers/pysam#451]
On the webpage of [pysam](http://pysam.readthedocs.io/en/latest/usage.html#extending-pysam), importing pysam API in cython require this:

```
from pysam.calignmentfile cimport AlignmentFile, AlignedSegment
```

This works in pysam=0.9.0 but after I updated to 0.11.1, I have been getting an error: 

```error: 'AlignedSegment' is not a type identifier```

I have been able to work around with:

```
from pysam.libcalignmentfile cimport AlignmentFile, AlignedSegment
```

Is this the right way to do it in pysam > 0.9.0?

**Comment by bioinformed** [comment]
Yes.  The renaming was necessary to fix dynamic linking problems across multiple platforms and due to changes in Cython.  Apologies for the inconvenience.
