### ISSUE TITLE
htslib 1.4.1 security release

### ISSUE THREAD

**Issue by mp15** [pysam-developers/pysam#453]
Dear pysam people,

Just to let you know we have had to release htslib 1.4.1 because of a few security vulnerabilities found in the CRAM rANS codec. We have attempted to minimise the number of feature updates we have included in this release. We will have a CVE published for this shortly.

**Comment by AndreasHeger** [comment]
Thanks, @mp15

**Comment by kyleabeauchamp** [comment]
@AndreasHeger  @bioinformed I made a bioconda PR to build the latest patch (https://github.com/bioconda/bioconda-recipes/pull/4680), but I hit a pretty strange import error that wasn't happening previously: https://travis-ci.org/bioconda/bioconda-recipes/jobs/231677004#L3107

```bash
===== testing package: pysam-0.11.2-py27_0 =====
import: 'pysam'
Traceback (most recent call last):
  File "/anaconda/conda-bld/pysam_1494617577468/test_tmp/run_test.py", line 27, in <module>
    import pysam
  File "/anaconda/conda-bld/pysam_1494617577468/_t_env/lib/python2.7/site-packages/pysam/__init__.py", line 20, in <module>
    import pysam.libcvcf as libcvcf
  File "pysam/libctabixproxies.pxd", line 28, in init pysam.libcvcf (pysam/libcvcf.c:32677)
ValueError: pysam.libctabixproxies.GTFProxy has the wrong size, try recompiling. Expected 80, got 88
```

Any ideas?

**Comment by kyleabeauchamp** [comment]
It definitely looks related to some of the last minute GFF/GTF changes, so I think there's some possibility of an issue somewhere.

**Comment by bioinformed** [comment]
I've seen that error when there are multiple versions of pysam installed or when I don't delete my `build` directory and one of the `pxd` files changes.  Could either of those situations be relevant?

**Comment by bioinformed** [comment]
I've been able to reproduce the error and it isn't due to the above items.  Perhaps there is out of date C code in the archive?  Checking now.

**Comment by bioinformed** [comment]
Yes.  @AndreasHeger: The C code in the release archive is out of date.

**Comment by bioinformed** [comment]
Also, the PyPI description is out of date:

```
The current version wraps htslib-1.3.1, samtools-1.3.1 and bcftools-1.3.1.
```

**Comment by AndreasHeger** [comment]
Ahh, I think I know what happened. I released from my laptop pulling the latest changes, but doing a new build. This presumably caused 11.1 pre-compiled .c files to be contained in the build. I will release 0.11.2.1

**Comment by AndreasHeger** [comment]
Ok, released a new build:

```
rm -f pysam/libc*.c
python setup.py build
python setup.py sdist upload
```

I can install the tar-ball:
```
  pip install ~/devel/pysam/dist/pysam-0.11.2.1.tar.gz 
Processing ./devel/pysam/dist/pysam-0.11.2.1.tar.gz
Building wheels for collected packages: pysam
  Running setup.py bdist_wheel for pysam ... done
  Stored in directory: /home/andreas/.cache/pip/wheels/d2/f6/50/a0ad2f9f5f31e05a0a0133a67f8a9039f57e03316528ed2ecf
Successfully built pysam
Installing collected packages: pysam
Successfully installed pysam-0.11.2.1
```
Hopefully this will work now. Apologies, thanks @mp15 for reporting and thanks @kyleabeauchamp and @bioinformed for responding.

**Comment by bioinformed** [comment]
@AndreasHeger: Thanks!

**Comment by AndreasHeger** [comment]
I have trouble building the wheels, but hopefully this is a special issue:
```
  gcc -pthread -fno-strict-aliasing -Wformat -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/opt/_internal/cpython-2.7.13-ucs2/include/python2.7 -c htslib/thread_pool.c -o build/temp.linux-x86_64-2.7/htslib/thread_pool.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  htslib/thread_pool.c: In function �<80><98>hts_tpool_init�<80><99>:
  htslib/thread_pool.c:676:5: warning: implicit declaration of function �<80><98>pthread_mutexattr_settype�<80><99> [-Wimplicit-function-declaration]
       pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
       ^
  htslib/thread_pool.c:676:38: error: �<80><98>PTHREAD_MUTEX_RECURSIVE�<80><99> undeclared (first use in this function)
       pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
                                        ^
  htslib/thread_pool.c:676:38: note: each undeclared identifier is reported only once for each function it appears in
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for pysam
Failed to build pysam
ERROR: Failed to build one or more wheels
```

**Comment by kyleabeauchamp** [comment]
I'm seeing issues on the bioconda build:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/231955784#L930

**Comment by mp15** [comment]
See htslib#532 for a patch.

Martin

> On 13 May 2017, at 23:18, Kyle Beauchamp <notifications@github.com> wrote:
> 
> I'm seeing issues on the bioconda build:
> 
> https://travis-ci.org/bioconda/bioconda-recipes/jobs/231955784#L930
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by AndreasHeger** [comment]
Thanks, @mp15

**Comment by AndreasHeger** [comment]
@kyleabeauchamp can't make much sense of error. It says:
```
samtools/errmod.h:47:5: error: conflicting types for ‘errmod_cal’
```
but such a file does not exist in the repo, nor the tar-ball.
The logs mention
```
BUILD START: pysam-0.9.1.4-py36_1
```
Could this be related?

**Comment by kyleabeauchamp** [comment]
You're totally right, it looks the build failure is something strange and unrelated on an older version.

**Comment by kyleabeauchamp** [comment]
Bioconda builds are now up:

https://anaconda.org/bioconda/pysam/files

**Comment by AndreasHeger** [comment]
Great stuff, @kyleabeauchamp, thanks!
I will close the issue once I get the wheels built.

**Comment by AndreasHeger** [comment]
After some patching the wheels have now been built and published.
