### ISSUE TITLE
Issue with libcvcf on Linux

### ISSUE THREAD

**Issue by standage** [pysam-developers/pysam#463]
With the newest 0.11.2 release, I'm getting the following error when I try to import pysam on Linux.

```
../../../virtualenv/python2.7.12/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
kevlar/__init__.py:18: in <module>
    from kevlar import dump
kevlar/dump.py:14: in <module>
    import pysam
../../../virtualenv/python2.7.12/lib/python2.7/site-packages/pysam/__init__.py:20: in <module>
    import pysam.libcvcf as libcvcf
pysam/libctabixproxies.pxd:28: in init pysam.libcvcf (pysam/libcvcf.c:32677)
    ???
E   ValueError: pysam.libctabixproxies.GTFProxy has the wrong size, try recompiling. Expected 80, got 88
```

See [this log](https://travis-ci.org/dib-lab/kevlar/jobs/231721842) for complete context.

I do not get the error on Mac, or on 0.11.0 or 0.11.1.

**Comment by kyleabeauchamp** [comment]
We've see this, working on it in #453

**Comment by bioinformed** [comment]
Workaround for now is to install `pysam==0.11.1`

**Comment by standage** [comment]
Yep https://github.com/dib-lab/kevlar/pull/77/files#diff-354f30a63fb0907d4ad57269548329e3R15

**Comment by bioinformed** [comment]
pysam 0.11.2.1 has been released with a fix for this bug.
