### ISSUE TITLE
Can't build docs on readthedocs: missing bzip2

### ISSUE THREAD

**Issue by iosonofabio** [pysam-developers/pysam#465]
Dear all,

I maintain [HTSeq](https://github.com/simon-anders/htseq) which depends on pysam and now we cannot build our docs on readthedocs anymore because pysam does not compile in their building environment, complaining the worker has no bzip2 libraries installed (see pic below for log). Needless to say, everything worked like a charm until at least pysam 0.10.

How do you guys build your readthedocs page? Could you please share the options you use or point me to a workaround?

thank you!
Fabio

![firefox_screenshot_2017-05-14t05-38-58 669z](https://cloud.githubusercontent.com/assets/1200640/26031564/fa1ff016-382c-11e7-860b-7985beed64be.png)

**Comment by iosonofabio** [comment]
Ok it's just that release 0.11.2 is incomplete, i.e. wheels are missing. Closing.

**Comment by AndreasHeger** [comment]
Apologies, wheels are coming, but I have trouble compiling on CentOS 5.
