### ISSUE TITLE
`get_cigar_stats` documentation is inaccurate since support for B-tag was added

### ISSUE THREAD

**Issue by j3harvey** [pysam-developers/pysam#467]
The `AlignedSegment.get_cigar_stats` method returns arrays of length 11, not length 10 as implied by the docstring.

The discrepancy is due to the addition of support for a "B" cigar tag that has not been reflected in the docstring (see e6c9bda, although the release notes suggest that the B tag has been recognised since pysam version 0.7).

The `AlignedSegment.get_cigar_stats` is as follows:

```
        """summary of operations in cigar string.
        The output order in the array is "MIDNSHP=X" followed by a
        field for the NM tag. If the NM tag is not present, this
        field will always be 0.
        +-----+--------------+-----+
        |M    |BAM_CMATCH    |0    |
        +-----+--------------+-----+
        |I    |BAM_CINS      |1    |
        +-----+--------------+-----+
        |D    |BAM_CDEL      |2    |
        +-----+--------------+-----+
        |N    |BAM_CREF_SKIP |3    |
        +-----+--------------+-----+
        |S    |BAM_CSOFT_CLIP|4    |
        +-----+--------------+-----+
        |H    |BAM_CHARD_CLIP|5    |
        +-----+--------------+-----+
        |P    |BAM_CPAD      |6    |
        +-----+--------------+-----+
        |=    |BAM_CEQUAL    |7    |
        +-----+--------------+-----+
        |X    |BAM_CDIFF     |8    |
        +-----+--------------+-----+
        |NM   |NM tag        |9    |
        +-----+--------------+-----+
        If no cigar string is present, empty arrays will be returned.
        Parameters
        ----------
        Returns
        -------
        arrays : two arrays. The first contains the nucleotide counts within
           each cigar operation, the second contains the number of blocks for
           each cigar operation.
        """
```

I propose this be ammended to something like:

```
        """summary of operations in cigar string.
        The output order in the array is "MIDNSHP=XB" followed by a
        field for the NM tag. If the NM tag is not present, this
        field will always be 0.
        +-----+--------------+-----+
        |M    |BAM_CMATCH    |0    |
        +-----+--------------+-----+
        |I    |BAM_CINS      |1    |
        +-----+--------------+-----+
        |D    |BAM_CDEL      |2    |
        +-----+--------------+-----+
        |N    |BAM_CREF_SKIP |3    |
        +-----+--------------+-----+
        |S    |BAM_CSOFT_CLIP|4    |
        +-----+--------------+-----+
        |H    |BAM_CHARD_CLIP|5    |
        +-----+--------------+-----+
        |P    |BAM_CPAD      |6    |
        +-----+--------------+-----+
        |=    |BAM_CEQUAL    |7    |
        +-----+--------------+-----+
        |X    |BAM_CDIFF     |8    |
        +-----+--------------+-----+
        |B    |B tag         |9    |
        +-----+--------------+-----+
        |NM   |NM tag        |10   |
        +-----+--------------+-----+
        If no cigar string is present, empty arrays will be returned.
        Parameters
        ----------
        Returns
        -------
        arrays : two arrays. The first contains the nucleotide counts within
           each cigar operation, the second contains the number of blocks for
           each cigar operation.
        """
```

The B tag is not standard SAM and I haven't been able to find a definition: can anyone shed light on what it means? Someone who knows what this B tag is about might suggest a better entry for the table.

**Comment by jkbonfield** [comment]
B in cigar strings is a backwards skip - like a negative N operator.

It was added for certain instrument types (I forget which now. Complete genomics maybe?) that worked on oligo/primer sequencing with the possibility of oligos being overlapping.   That gives a small stutter in the sequence, which can be compensated for by a negative skip to rewind a few bases on the reference.

In practice it was never supported well as it causes lots of headaches for algorithms like pileup, plus IIRC the instrument manufacturer had a tool to output merged data that removed the B ops anyway.

I'd just expunge it and pretend it never existed. :-)

**Comment by j3harvey** [comment]
> B in cigar strings is a backwards skip - like a negative N operator.

Thank you very much for the clarification @jkbonfield. From the Bad Old Days when sequencers sometimes went backwards, eh? ;-)

**Comment by AndreasHeger** [comment]
Thanks @j3harvey for raising this, and thanks @jkbonfield for answering. Glad to have learned something!

I am leaving the code (and docs) as is.

**Comment by AndreasHeger** [comment]
... actually, updating the doc string to reflect that the size of the array is 11, not 10.

**Comment by j3harvey** [comment]
Fantastic, thanks @AndreasHeger for all the good work.
