### ISSUE TITLE
explain in the manual how to fetch genotypes from a VCF file

### ISSUE THREAD

**Issue by tommycarstensen** [pysam-developers/pysam#469]
It is not explained in the manual how to fetch genotypes from a VCF file, unless this is opened with `pysam.tabix`. Perhaps good to add this to the manual? Is this the simplest way to do it?

    for rec in vcf.fetch(chrom, pos):
        GTs = [s.split(':', 1)[0] for s in str(rec).split()[9:]]

**Comment by bioinformed** [comment]
This is a much better way:
```python
for rec in vcf.fetch(chrom, start, stop):
    gts = [s['GT'] for s in rec.samples.values()]
```

**Comment by DGMichael** [comment]
Useful, thanks
