### ISSUE TITLE
Is there code in pysam for writing fastx files?

### ISSUE THREAD

**Issue by wkretzsch** [pysam-developers/pysam#471]
I'd be happy to contribute if not...

**Comment by bioinformed** [comment]
There are a number of things called FASTX.  Can you please elaborate on which one?

**Comment by wkretzsch** [comment]
Oh, ok.  I mean the [FastxFile](https://pysam.readthedocs.io/en/latest/api.html#pysam.FastxFile). Does this have a write mode yet?

**Comment by kyleabeauchamp** [comment]
I would support a fastq/fasta writer.  My wish list would be:

1.  Anything that works and has tests
2.  Something written in cython for better performance
3.  Something that uses a separate gzip thread (using, e.g., https://github.com/marcelm/xopen)

**Comment by AndreasHeger** [comment]
At the moment the fasta/fastq support is read-only only. Adding modification and write-support is on my todo-list, any contributions would be welcome! 

The current implementation uses htslib / samtools functionality and my approach would be to continue using this, i.e. write a wrapper for C library functions, but this could be changed if it becomes overly complex and there are no speed benefits. 

The current implementation has some issues when using multiple iterators on the same FastxFile (see issue #409 and #352) and needs revisiting. If using the existing approach, the same solution as for AlignmentFile can be used (i.e. providing each iterator with a separate file)

**Comment by AndreasHeger** [comment]
... should add, what I say is for in-place modification of the Proxies. For writing, I thought outf.write(str(record)) should be sufficient where outf can be whatever the user wishes, i.e. a file with open, gzip.open or xopen.open.

**Comment by wkretzsch** [comment]
Ok, great.  I'll see if a need arises on my side for implementing this, and if so I'll open a new issue.
