### ISSUE TITLE
Error when mate unmapped

### ISSUE THREAD

**Issue by davidecarnevali** [pysam-developers/pysam#472]
While dealing with RNA-seq bam file from TCGA i got this error iterating over the bam file using HTSeq:

File "python2/src/HTSeq/_HTSeq.pyx", line 1338, in HTSeq._HTSeq.SAM_Alignment.from_pysam_AlignedSegment (src/_HTSeq.c:30737)
  File "pysam/libcalignmentfile.pyx", line 1635, in pysam.libcalignmentfile.AlignmentFile.getrname (pysam/libcalignmentfile.c:18952)
  File "pysam/libcalignmentfile.pyx", line 699, in pysam.libcalignmentfile.AlignmentFile.get_reference_name (pysam/libcalignmentfile.c:9684)
ValueError: reference_id -1 out of range 0<=tid<2779

The problem seems due to this kind of reads in the bam file:

UNC11-SN627_70:1:1101:3483:1995	69	*	0	0	*	*	0	0	NGGTGCTTTATTCTCCACAGAGTGATACATGCTAAGGTGGGTTGGGCTTG	#:99:;<<<;D:7DDDDDDDDD@DDDDDDDDDDDDDDDDD6:DDDDDDDD	NH:i:0	HI:i:0	AS:i:49	nM:i:0	uT:A:4	RG:Z::110325_UNC11-SN627_0070_AB02DVABXX.1

The 69 flag tells the read is unmapped while the mate is mapped, however the sam line reports '*' for the mate too which is not a valid chromosome and is not in the ref sequences that indeed are 2779

I'm using:
HTSeq v. 0.7.2
pysam  0.11.2

Is it possible to fix it to handle these kind of exceptions?
Thanx

**Comment by bioinformed** [comment]
This appears to be a bug/limitation of HTSeq and not pysam.  

The code here (https://github.com/simon-anders/htseq/blob/master/python2/src/HTSeq/_HTSeq.pyx#L1340)  assumes that the `read.mate_is_unmapped` flag and mate contig (`read.mrnm`) are consistent and should either 
  * check that the `read.mrnm` isn't -1 before attempting to look up the reference or 
  * should handle the except that results when it is -1

**Comment by AndreasHeger** [comment]
Thanks both. Indeed, there will be no way for pysam to deduce the reference sequence name if it is not set in the BAM.

I will close this issue for now.

**Comment by iosonofabio** [comment]
Hej, I am the mainteiner of HTSeq and trying to fix this. Let me understand: `read.mate_is_unmapped` and `read.next_reference_id != -1` *should* be consistent, shouldn't they? What to do if they disagree, e.g. `read.mate_is_unmapped` is `False` but `read.next_reference_id` is `-1`?
