### ISSUE TITLE
Add example of writing fastq

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#473]
#471 asked for fastq writing capabilities.  I think we already have this, but it's a bit hard to find.  Basically, the `__str__()` member function FastqProxy does what we need for writing, so we might as well add an example of this.

```
for line in fastq:
   fh.write(str(line))
```

The only other thing that might be desirable is to have a constructor for FastqProxy that creates an object from the name, seq, and qual strings.

**Comment by AndreasHeger** [comment]
Good points, I will see if I can polish this part this weekend.

**Comment by AndreasHeger** [comment]
Done, see 1c28fcb1277e16da31ca5af11fc18ad737dd862e
