### ISSUE TITLE
pysam-0.11.2.1 error on Mac OS/X Sierra 

### ISSUE THREAD

**Issue by diekhans** [pysam-developers/pysam#475]
pip install of pysam-0.11.2.1 on Mac OS/X Sierra with python installed with macports results in a broken installation due to dynamic library reference to the wrong location

    Python 2.7.13 (default, Apr 23 2017, 16:50:35) 
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
    >>> import pysam
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
        from pysam.libchtslib import *
      File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:12515)
    ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysam/libcutils.so, 2): Library not loaded: @rpath/pysam-0.11.2.1-py2.7-macosx-10.12-x86_64.egg/pysam/libcsamtools.so
      Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysam/libcutils.so
      Reason: image not found

libcsamtools.so is actually installed in:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysam/libcsamtools.so

**Comment by diekhans** [comment]
manually check pysam out of git and compile still requires

  cd /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  sudo ln -s  pysam-0.11.2.1-py2.7-macosx-10.12-x86_64.egg/pysam .

**Comment by bioinformed** [comment]
Thanks for the report.  I'm working on a fix.

**Comment by maximilianpress** [comment]
Same issue with a pip install, except pysam 0.11.2.2 and system Python (a virtualenv Python installed elsewhere shows same problem), MacOSX Sierra. I was able to resolve by uninstalling the pip version and just using git-->compile but I am not totally clear on the causality there. 

Possibly I did something stupid while setting my environment up in the first place.

Unlike @diekhans, as far as I can tell everything is in the right location for both pip and the manual build but in the pip install it seems that Python is not loading the library even though it is looking in the right place. 

Thanks, max

```
# (pip install of pysam), same behavior observed with Python 2.7.13
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:12515)
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pysam/libcutils.so, 2): Library not loaded: @rpath/pysam/libcsamtools.so
  Referenced from: /usr/local/lib/python2.7/site-packages/pysam/libcutils.so
  Reason: image not found

# libcsamtools.so is in the right place?
$ ls /usr/local/lib/python2.7/site-packages/pysam/
Pileup.py		csamtools_util.h	libcbcftools.pxd	libcsamtools.pxd	libcvcf.so		utils.py
Pileup.pyc		htslib_util.h		libcbcftools.so		libcsamtools.so		namedtuple.py		utils.pyc
__init__.py		include			libcbgzf.so		libctabix.pxd		namedtuple.pyc		version.py
__init__.pyc		libcalignedsegment.pxd	libcfaidx.pxd		libctabix.so		pysam_stream.h		version.pyc
bcftools.py		libcalignedsegment.so	libcfaidx.so		libctabixproxies.pxd	pysam_util.h
bcftools.pyc		libcalignmentfile.pxd	libchtslib.pxd		libctabixproxies.so	samfile_util.h
cbcftools_util.h	libcalignmentfile.so	libchtslib.so		libcutils.pxd		samtools.py
config.py		libcbcf.pxd		libcsamfile.pxd		libcutils.so		samtools.pyc
config.pyc		libcbcf.so		libcsamfile.so		libcvcf.pxd		tabix_util.h
```

**Comment by diekhans** [comment]
@maximilianpress , this is the same thing I am seeing.  libcutils.so is reference libsamtools.so, which can't be found because it is looking for @rpath/pysam/libcsamtools.so.  This has something to do with the ay libcutils.so was built, most likely using the wrong -rpath value.

**Comment by bioinformed** [comment]
@diekhans, @maximilianpress: Thanks for the interest in tracking down the source of this bug.  For more insight into what is happening, look at https://github.com/pysam-developers/pysam/blob/master/cy_build.py .  Therein is some hairy code that attempts to infer which one of the multitude of installation methods and path adjustments to use to set the correct rpath.   I've been looking into how to improve our logic to properly set rpath, but every potential fix I've found ends up breaking other installation methods.

The best workaround is to install from a wheel file.  That case is working.  Once @AndreasHeger posts an OSX wheel file (hint hint) then installation from pypi will work once more.

**Comment by kyleabeauchamp** [comment]
Have you tried the bioconda builds on Sierra?  Worth a try, it does some funky rpath modifying stuff that may or may not be different.

**Comment by bioinformed** [comment]
@kyleabeauchamp: I've reviewed the bioconda modifications and it works for how bioconda installs packages, but is not a general fix since it breaks other installation modes.

**Comment by splaisan** [comment]
# pysam failure to install prevents me to install CrossMap
sudo -H pip install Crossmap --upgrade
Collecting Crossmap
  Using cached CrossMap-0.2.6-py2-none-any.whl
Collecting pysam (from Crossmap)
  Using cached pysam-0.11.2.2.tar.gz
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/Library/Python/2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by bioinformed** [comment]
@splaisan: This appears to be an unrelated issue and likely not one with pysam.  Can you please open a new issue so that we can track the status properly?

**Comment by AndreasHeger** [comment]
... will look into the OsX wheels.

**Comment by diekhans** [comment]
I am trying to dig into this a bit more.    It doesn't fail on a pip install to a virtualenv, which I found
off.  

In both a system and virtualenv  install, `libcsamtools.so` is in:    `lib/python2.7/site-packages/pysam/libcsamtools.so`

In virtualenv,  `objdump -p` shows `libcutils.so` has the dependency specified as `@rpath/pysam/libcsamtools.so`

while in the system install, it's specified as `@rpath/pysam-0.11.2.2-py2.7-macosx-10.12-x86_64.egg/pysam/libcsamtools.so`

All I have time for now; it's unclear why @path is being set to the wrong location here.  Can you explain the details?

**Comment by splaisan** [comment]
Dear,

First thanks a lot for your efforts to help.
I remember I have once set virtualenv on my mac but found it too complicated to keep and this has left scars which from time to time prevent me from maintaining the system.
I also used mac port to install more recent than system versions of python and this is also likely involved.
I now just set python to the apple build but it did not help in this case.

I am not enough of a python guy to fix these and would really like to perform a clean install of python and remove all non OS traces of it to fix these but fear to break the apple python by doing so.
most of the python pmackages I have installed do work, it is only a few like this one which are bad.
I think time has come for a full clean install of my mac….

Sorry for this issue which is clearly linked to my computer settings.

Best
Stephane



Stéphane Plaisance – Staff Scientist | Bioinformatician 
VIB Nucleomics Core  
Campus Gasthuisberg
Herestraat 49 – Post Box 816 – 3000 Leuven – Belgium 
O&N4 Building – 8th Floor – Room 08.440 
Tel. +32 16 37 31 26  
Lync. +32 16 32 00 60  
www.nucleomics.be  <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.vib.be/>

**Comment by splaisan** [comment]
I made one step progress by aliasing the macport lzma and lzma.h dependencies from /opt/local/include to /usr/local/include (they were absent from the /usr/path)
After that pip install pysam worked as well as pip install CrossMap
I am now stuck when running CrossMap with:
CrossMap.py
```
Traceback (most recent call last):
  File "/usr/local/bin/CrossMap.py", line 22, in <module>
    import pysam
  File "/Library/Python/2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:12515)
ImportError: dlopen(/Library/Python/2.7/site-packages/pysam/libcutils.so, 2): Library not loaded: @rpath/pysam-0.11.2.2-py2.7-macosx-10.10-intel.egg/pysam/libcsamtools.so
  Referenced from: /Library/Python/2.7/site-packages/pysam/libcutils.so
  Reason: image not found
```
which I find elsewhere too (@maximilianpress).
Any idea how I can do better than aliasing the  lzma dependencies, reinstall all and get it running?
I would prefer a solution without additional package installers (bioconda) as my system get too complex with these extra layers.

**Comment by AndreasHeger** [comment]
@splaisan , the build directory looks good. I assume this issue is related to #489 ?

**Comment by oscarestrada05** [comment]
Same error:
Error: Could not import required module 'pysam':
	- dlopen(/usr/local/lib/python2.7/site-packages/pysam/libcutils.so, 2): Library not loaded: @rpath/pysam-0.11.2.2-py2.7-macosx-10.12-x86_64.egg/pysam/libcsamtools.so
  Referenced from: /usr/local/lib/python2.7/site-packages/pysam/libcutils.so
  Reason: image not found
    

$ pip install pysam
Requirement already satisfied: pysam in /usr/local/lib/python2.7/site-packages

**Comment by splaisan** [comment]
Digging in it from a separete post

**Comment by ChrisHIV** [comment]
Sounds like this is my error too. On a new Mac:
```
brew install samtools
brew install python
sudo easy_install pip
sudo -H pip install pysam --upgrade
```
Then in python
```
import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:12515)
ImportError: dlopen(/Library/Python/2.7/site-packages/pysam/libcutils.so, 2): Library not loaded: @rpath/pysam-0.11.2.2-py2.7-macosx-10.12-intel.egg/pysam/libcsamtools.so
  Referenced from: /Library/Python/2.7/site-packages/pysam/libcutils.so
  Reason: image not found
```

**Comment by terrycojones** [comment]
I just ran into this too (OS X 10.10.5, python 3.5).  I got pysam working (in a virtualenv) by:

1. Remove anything in the virtualenv installed by pip install pysam (pip uninstall pysam might be enough).
2. pip install cython  (if you don't have it already)
3. git clone https://github.com/pysam-developers/pysam.git
4. cd pysam
5. python setup.py build
6. python setup.py install

Then python -c 'import pysam' does the import without the error mentioned originally above.

**Comment by splaisan** [comment]
Today i found a new version of pysam (0.12) which built OK under Yosemite. I could finally build CrossMap too. Although I did not test the commands more than printing the help, the building issue at least seems to be fixed. Thanks for this new release.

**Comment by AndreasHeger** [comment]
Thanks, closing this for now.
