### ISSUE TITLE
Allow multiple arguments to read_callback function in count_coverage

### ISSUE THREAD

**Issue by snayfach** [pysam-developers/pysam#477]
I'm using the pysam function `count_coverage`, described [here](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.count_coverage), to compute per-site read depth from a bamfile. Within `count_coverage`, I'm using `read_callback` to specify my own user-defined function for filtering out reads that fail to meet a series of defined conditions. However, the read_callback function can only take one argument, so all other arguments must be global variables. 

It would be great to be able to specify multiple arguments to the read_callback function, instead of using global variables. Is this possible?

This is what I currently have:
```
# read_callback function
def keep_read(aln):
   if np.mean(aln.query_qualities) < min_readq:
      return False
   elif aln.mapping_quality < min_mapq:
      return False
   else:
      return True

# global arguments to read_callback function
min_readq=20
min_mapq=30

# count coverage
with pysam.AlignmentFile(bampath, 'rb') as bamfile:
   counts = bamfile.count_coverage(chrom, start, end, read_callback=keep_read)
```

This is what I'd like:
```
# read_callback function
def keep_read(aln, min_readq, min_mapq):
   if np.mean(aln.query_qualities) < min_readq:
      return False
   elif aln.mapping_quality < min_mapq:
      return False
   else:
      return True

# count coverage
with pysam.AlignmentFile(bampath, 'rb') as bamfile:
   counts = bamfile.count_coverage(chrom, start, end, read_callback=keep_read, args=[20, 30])
```

Thanks,
Stephen

**Comment by kyleabeauchamp** [comment]
You can use a "local" function definition to define a version of the function that captures all of the desired arguments without having to have global variables.

**Comment by snayfach** [comment]
Could you provide an example?

**Comment by snayfach** [comment]
I understand that the variables `min_readq` and `min_mapq` could just be defined within the read_callback function. However in my actual program these variables are defined from the command line and not hardcoded in the program. Therefore they need to be passed as arguments to the read_callback or defined as global variables.

**Comment by bioinformed** [comment]
In addition to the two strategies that you mention, you can also use
functools.partial or pass a function with that parameters defined in an
outer closure.

**Comment by AndreasHeger** [comment]
Closing this, functionality already there.
