### ISSUE TITLE
gcc: pysam/chtslib.c: No such file or directory

### ISSUE THREAD

**Issue by fritzyoski** [pysam-developers/pysam#478]
Hi,
I am trying to build pysam 0.9.1.4 and get the following error:

gcc: pysam/chtslib.c: No such file or directory

cython --version
Cython version 0.24

echo $HTSLIB_LIBRARY_DIR
/share/apps/samtools/1.2/htslib-1.2.1/htslib

echo $HTSLIB_INCLUDE_DIR
/share/apps/samtools/1.2/htslib-1.2.1/cram

What's the magic sauce I am missing?
Thanks
Mike

**Comment by AndreasHeger** [comment]
Not sure what is missing, It would be good to have more of a trace-back.

**Comment by AndreasHeger** [comment]
Closing this for now.
