### ISSUE TITLE
tag for v0.11.2.2 says v0.112.2

### ISSUE THREAD

**Issue by 0xAF1F** [pysam-developers/pysam#481]
This typo will make it appear to our version scanners as the latest version until you actually go up to over 112 minor versions or bump the major version number. For example, we would not notice if you released 0.12.0 since 112 > 12.

**Comment by bioinformed** [comment]
Thanks for the report, @0xAF1F. 

@AndreasHeger: I fixed this on github and hopefully that should be enough.
