### ISSUE TITLE
find intron only return count

### ISSUE THREAD

**Issue by jordi-vaquero** [pysam-developers/pysam#485]
Find intron only return count of reads with N in cigar, is there a way to get a list of reads? or iterator of reads with N in CIGAR not just the number?

**Comment by AndreasHeger** [comment]
Thanks, will take a look. This method is a bit of an odd-end as it is quite specific and generally we aim to provide generic functionality only.
My suggestion for applications such as yours would be to write your own counting loop, the code in intron_counts method could be a starting point:
```
        import collections
        res = collections.Counter()
        for r in read_iterator:
            if 'N' in r.cigarstring:
                last_read_pos = False
                for read_loc, genome_loc in r.get_aligned_pairs():
                    if read_loc is None and last_read_pos:
                        start = genome_loc
                    elif read_loc and last_read_pos is None:
                        stop = genome_loc  # we are right exclusive ,so this is correct
                        res[(start, stop)] += 1
                        del start
                        del stop
                    last_read_pos = read_loc
        return res
```

**Comment by AndreasHeger** [comment]
Closing this issue for now.
