### ISSUE TITLE
printing vcf creates empty lines between variant

### ISSUE THREAD

**Issue by Lafond-LapalmeJ** [pysam-developers/pysam#486]
Hi,
I have install pysam 0.11.2.1 when printing my vcf it creates an empty line between each variant. 
Here is my code:

```
vcf = pysam.VariantFile(args.vcffile, 'r')
for variant in vcf:
   ...
   variant.info[names[i]] = ":".join(output)
   print (variant)
```
Do you have any idea where that problem can come for ? 
Thanks

**Comment by bioinformed** [comment]
The carriage return is part of the string representation of the variant.  To avoid use:
```python
    print(variant, end='')
```
or write updated records to a `VariantFile`:
```python
    vcf = pysam.VariantFile(args.vcffile)
    with pysam.VariantFile(sys.stdout, 'w', header=vcf.header) as vcfout:
        for variant in vcf:
            # ...
            variant.info[names[i]] = ":".join(output)
            outvcf.write(variant)
```

**Comment by Lafond-LapalmeJ** [comment]
It works now! for python > 3 `print(variant, end='')` works.

For python < 3 you should use `sys.stdout(str(variant))`

Thanks for your help
