### ISSUE TITLE
Feature request: Random access into FASTQ files

### ISSUE THREAD

**Issue by wkretzsch** [pysam-developers/pysam#488]
It appears that this can in principle be [done](https://bioinformatics.stackexchange.com/a/813/492) using [grabix](https://github.com/arq5x/grabix). Any thoughts?

**Comment by AndreasHeger** [comment]
Hi Winni! What is your use case? If short-read data, the index itself is likely to be sizeable. Random access of bgzip'ed files is I think possible, there is a HFile API in pysam, which we use internally but have not advertised very much.

**Comment by wkretzsch** [comment]
Hi! Right now it's just sampling for some experiments.  Nothing I couldn't in practice solve with a `shuf` command.  I'm more interested in perhaps adding the functionality myself more as a side project to start contributing to pysam.

**Comment by AndreasHeger** [comment]
Hi, would be great to have your contributions. Playing around with HFile might be a start, but my gut feeling is that random access into fastq files is not something that will be used frequently. As most fastqs are gzip'ed, you will need to recompress with bgzip and then index - and the index will be large.

There are other areas of pysam that might be interesting as well. For example, the pileup engine is a long-standing open issue as it is slow (not lazy enough, instantiates too many objects) and is not customizable. Or there might be additional features in the BCF/VCF support (@bioinformed ?)

**Comment by wkretzsch** [comment]
Ok, working on something more pressing is a good point. Can you point me to a specific issue involving the pileup engine that needs fixing?
