### ISSUE TITLE
Difference in pysam and samtools

### ISSUE THREAD

**Issue by andyjslee** [pysam-developers/pysam#490]
I am curious as to why the output from pysam is different from that of samtools. For example, the the Rnext and Pnext are different. I have attached the screenshots and the python code using pysam.

![default](https://user-images.githubusercontent.com/6372804/27418369-aed25174-5755-11e7-9258-5e417040432a.PNG)
![samtools_and_pysam](https://user-images.githubusercontent.com/6372804/27418370-aefd06a8-5755-11e7-936a-3319c0544abe.PNG)

**Comment by AndreasHeger** [comment]
Hi, I think the confusion might arise due to different representations. samtools outputs '*' if a contig has not been set, while the code is -1 in pysam. Also pysam coordinates are 0-based, while the SAM format is 1-based.

**Comment by AndreasHeger** [comment]
Closing this for now.
