### ISSUE TITLE
some attribute wrong message

### ISSUE THREAD

**Issue by milkcookie** [pysam-developers/pysam#491]
I have installed this package by conda,but when I use it to read bamfile,it says 'module' object has no attribute 'AlignmentFile',did you update the package and not correct the info?

**Comment by AndreasHeger** [comment]
Sorry, I will need more information.

**Comment by milkcookie** [comment]
I can't use the cmd 'samfile = pysam.AlignmentFile(path_in, "rb")' to read sam or bam file, ,it says 'module' object has no attribute 'AlignmentFile'.
the message:
        In [2]: path = 'Top10_contig.bam'

In [3]: import pysam

In [4]: mybam = pysam.AlignmentFile(path,'rb')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d45a7a7636d7> in <module>()
----> 1 mybam = pysam.AlignmentFile(path,'rb')

AttributeError: 'module' object has no attribute 'AlignmentFile'

**Comment by AndreasHeger** [comment]
Hi, is it possible that your are importing pysam within the pysam install directory? Unfortunately there is a name conflict then between the pysam directory and the pysam module.

**Comment by AndreasHeger** [comment]
Closing for now, please reopen if issue persists.
