### ISSUE TITLE
Improve speed of pileup engine

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#493]
pysam's approach is to provide a lazy wrapper around htslib constructs. This approach is violated
in IteratorColumn. IteratorColumn instantiates a full list of AlignedSegment objects even if none or only part of these are used.

A proposed solution is to return a Proxy object in makePileupColumn that will provide lazy access to the aligned reads in a pileup column.

**Comment by AndreasHeger** [comment]
@wkretzsch, would this be something of interest?

**Comment by wkretzsch** [comment]
Cheers.  I'll take a look.
