### ISSUE TITLE
infer_query_length returns zero for unmapped reads in version 0.11.2.2

### ISSUE THREAD

**Issue by bsipos** [pysam-developers/pysam#494]
Dear pysam developers,

I have noticed that both infer_query_length(False) and infer_query_length(True) returns zero for unmapped reads in version 0.11.2.2. For example if the read is:

`9a15f684-fa52-49ac-93f5-2bed0f0ffcb6    4       -1      -1      0       None    -1      -1      1482    CGCGCCTAAATATAATAATA ..... CGCCCGCCCGCCCCAGGCGGCTGCCCCCCCCCCGTTCCGGCGCTGCCGCGCGCCCAACGCCCAATGG  array('B', [1, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ....  28, 11, 24, 1, 19, 21, 29, 1, 3, 1, 6, 10, 18, 15, 9, 7, 8, 3, 4, 1, 29, 1, 14, 2, 1, 1, 12, 4, 9, 1, 1, 3, 3, 13, 14, 4, 1, 1, 1, 1, 1])        [('AS', 0), ('XS', 0)]
`

`print(r.infer_query_length(False))`
0
`print(r.infer_query_length(True))`
0

The Python version was 3.6.0 and pysam was installed via pip.

**Comment by AndreasHeger** [comment]
Thanks. Both methods require an alignment to infer the read/query length. This is useful in cases if the query sequence is not in the BAM file or it has been clipped.

For unmapped reads, the method should return None and not 0, which I will fix.

**Comment by amblina** [comment]
@AndreasHeger surely infer_query_length should defer back to the SEQ field in the event of CIGAR field being unavailable?  The [documentation](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.infer_query_length) for `infer_query_length` currently says:

> infer query length from sequence or CIGAR alignment.

which would imply that if the CIGAR was not available then the value of query_length would be supplied.  The documentation for [query_length](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.query_length) says:

> The length of a query is 0 if there is no sequence in the BAM/SAM file. In those cases, the read length can be inferred from the CIGAR alignment, see pysam.AlignedSegment.infer_query_length().

I'm assuming "can" here means it's something the user could do if they got a 0.  If the user wanted the SEQ field length, they could grab that via query_length whereas if the user specifically wanted the query length inferred from the CIGAR.  From the documentation I would have assumed that "infer_query_length" function would try and intuit the original query length based on the evidence available e.g. CIGAR or SEQ len or alternatively be called something like "infer_query_length_from_cigar" (or something less cumbersome!).  Is that something that can be done confidently, or is there an edge case I'm missing here.

**Comment by AndreasHeger** [comment]
Thanks, @amblina , good point,  I will change 
```
infer query length from sequence or CIGAR alignment.
```
to
```infer query length from CIGAR alignment.
```. 
Hopefully this makes it clear that query_length and infer_query_length do different things and users can build their custom wrapper.
I have also learned to avoid the word 'infer' in function names.
