### ISSUE TITLE
Can't install pysam on Windows 7 with Anaconda Python 3.6

### ISSUE THREAD

**Issue by iv-mariya** [pysam-developers/pysam#499]
I have Anaconda version 4.3.18 with Python 3.6
When I try to install pysam from cmd I get the following error:
![2017-07-04 13 25 52](https://user-images.githubusercontent.com/29889145/27826857-75b6ab62-60bd-11e7-987b-f215577a36de.png)

**Comment by AndreasHeger** [comment]
merged with  #575
