### ISSUE TITLE
count_coverage misses some positions?

### ISSUE THREAD

**Issue by ccedmendoza** [pysam-developers/pysam#500]
Hi,
I am using the count_coverage() method in a script and when I tested it I realised it missed some positions on my test alignment.

You can find the read used as well as the fasta reference and the bam file with its bai in the following zip.
[sample.zip](https://github.com/pysam-developers/pysam/files/1125202/sample.zip)

Now the example ::
```
>>> import pysam
>>> bamfile = pysam.AlignmentFile('error_data.bam', 'rb')
>>> head = bamfile.header['SQ'][0]['SN']  # There is only one header for the example
>>> bamfile.fetch(head).next().get_reference_positions()
[23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]
```
> Here you can see that the read aligns from positions 23 to 45
```
>>> for arr in bamfile.count_coverage(head,start=23,end=45):
...    print("Coverage : %s" % arr)
Coverage : array('L', [1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L])
Coverage : array('L', [0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L])
Coverage : array('L', [0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L])
Coverage : array('L', [0L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L])
```
>And here you will notice that in positions **37**, **38** and **39** there is no match for the coverage.

Well that's it for the example. I find this quite peculiar since other functions don't miss those positions. If you proceed with a fetch in those three positions you will find a read and it is the same with a count which is normal because the read matches those positions.

Thank you for your help.

P.S. If this is normal I would like to know why please.

**Comment by mvdbeek** [comment]
The default `quality_threshold` is 15,  and the positions that are missing are 14, 13 and 7. See http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.count_coverage

**Comment by ccedmendoza** [comment]
Oh. Indeed thank you fot your help.
