### ISSUE TITLE
htslib version

### ISSUE THREAD

**Issue by guillermomarco** [pysam-developers/pysam#501]
@AndreasHeger I'm currently updating all my system libs including pysam. I've a question I couldn't solve looking at the installation manual.
It's written that current pysam version (0.11.2.2) wraps htslib-1.3, samtools-1.3 and bcftools-1.3.
However I'm currently using on my work environment htslib-1.5, samtools-1.5 and bcftools-1.5.
I'm scared to have some inconsistencies in data analysis if those version differ (system vs pycharm). 

Would it be safe to install pysam using `HTSLIB_LIBRARY_DIR` and `HTSLIB_INCLUDE_DIR` pointing to **htslib-1.5**?

**Comment by AndreasHeger** [comment]
Apologies, the docs are wrong, 0.11 wraps htslib 1.4. The latest version in the repository wraps 1.5 already and we are planning to release soon.
Building a against an external htslib 1.5 will probably work and likely not to cause inconsistencies, but of course there is no guarantee. If in a rush, my suggestion would be to install the latest pysam repository clone, which should already be fairly close to the next release.

**Comment by guillermomarco** [comment]
Thank you for fast answer. I'm not in a rush so I'll wait for new pysam release. Thanks!
