### ISSUE TITLE
Create more test cases when linking against pysam

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#503]
Create test cases linking against pysam and show what works.

see #489

@bioinformed wrote:
```
I'll create a dummy app, since I don't have permission to share this app. However, here is how I link from setup.py:

ext_modules = [Extension('helix_app_covetous.libcovetous',
                        ['helix_app_covetous/libcovetous.pyx'],
                         include_dirs=pysam.get_include()+[np.get_include()],
                         extra_link_args=pysam.get_libraries(),
                         define_macros=pysam.get_defines(),
                         )]

(covetous is a coverage analysis app developed by Helix that extracts coverage information from BAMs, stores it in a highly compressed manner, and allows running queries on many thousands of samples very quickly. It isn't open source yet, but that is planned when it is feature complete and stable.)
```

**Comment by AndreasHeger** [comment]
Hi @bioinformed, I have added a couple of tests for linking, please see:
https://github.com/pysam-developers/pysam/blob/master/tests/linking_test.py

At the moment, two packages are built, without and with rpath set, the latter uses the following template:

```
pysam_libraries = pysam.get_libraries()
pysam_libdirs, pysam_libs = zip(*[os.path.split(x) for x in pysam_libraries])
pysam_libdir = pysam_libdirs[0]
# remove lib and .so
pysam_libs = [x[3:-3] for x in pysam_libs]

TestModule = Extension(
    "{}.BuildRead".format(test_module_name),
    ["{}/BuildRead.pyx".format(test_module_name)],
    include_dirs=pysam.get_include(),
    library_dirs=[pysam_libdir],
    libraries=pysam_libs,
    extra_link_args=['-Wl,-rpath,{}'.format(pysam_libdir)],
    language="C",
)
```
Please let me know what you think.

**Comment by bioinformed** [comment]
@AndreasHeger: I've added some extra htslib and utils dependencies to ensure linking is working for more cases.  On OS X, the "without_rpath" method fails when LD_LIBRARY_PATH is not set, while the "with_rpath" works when LD_LIBRARY_PATH is not set.  

Are you suggesting that we keep the current pysam behavior on OS X (set rpath to @loader_path) and put the burden on linking applications to provide the explicit rpath?

**Comment by AndreasHeger** [comment]
@bioinformed, I have very little practical experience with OS X linking. Guided by my unix experience I created the following three tests:

The three test cases are:
1. with_rpath: should work
2. without_rpath: should fail
3. without_rpath, but with LD_LIBRARY: should work

Hence, I am not suprised that also on OS X without_rpath fails without LD_LIBRARY_PATH.
Googling what loader_path is, I found the following summary: 

https://wincent.com/wiki/%40executable_path%2C_%40load_path_and_%40rpath

From there, it seems that on OS X @rpath should be used?

**Comment by bioinformed** [comment]
Yes -- it seems like the current solution isn't working on OS X.  I suggest we revert it for now, live with absolute paths for now, and revisit after this release.

**Comment by AndreasHeger** [comment]
Thanks, you mean reverting #489

**Comment by bioinformed** [comment]
Yes

**Comment by jvkersch** [comment]
Sorry for being late to the discussion, but would you mind pointing out which test case fails on Mac OS? I would really like to give this a closer look before you revert it, but I'll leave it up to you to decide.

**Comment by bioinformed** [comment]
@jvkersch: Please see `tests/linking_test.py`.  The primary aim is for the `link_without_rpath` to pass on OS X without having to set LD_LIBRARY_PATH.

**Comment by jvkersch** [comment]
Thanks, I will look at it ASAP.

**Comment by jvkersch** [comment]
@AndreasHeger @bioinformed Just to be clear, the goal is for [this test](https://github.com/pysam-developers/pysam/blob/78e95ef4ebdde5bd5def01df4dc8cc137a2c493b/tests/linking_test.py#L72-L75) to pass without having to set LD_LIBRARY_PATH, right? (As an aside, I didn't know that LD_LIBRARY_PATH would work on Mac OS, in addition to the more canonical DYLD_LIBRARY_PATH).

To be honest, I don't know how this test is supposed to work in the first place. If I locally revert #489 and run the test without LD_LIBRARY_PATH set, it still fails (since it has no way of knowing where the pysam libraries are installed). I'm probably misunderstanding something, so please let me know what I'm overlooking.

**Comment by bioinformed** [comment]
@jvkersch: The method I use to link when #489 is reverted is:

```python
from cy_build import CyExtension as Extension, cy_build_ext as build_ext

ext_modules = [Extension('helix_app_covetous.libcovetous',
                        ['helix_app_covetous/libcovetous.pyx'],
                         include_dirs=pysam.get_include()+[np.get_include()],
                         extra_link_args=pysam.get_libraries(),
                         define_macros=pysam.get_defines(),
                         )]
```

I can add that as a third test case.

**Comment by AndreasHeger** [comment]
@jvkersch , thanks. I wrote these tests based on my linux knowledge - they might need to made OS dependent, for example using DYLD_LIBRARY_PATH or turned on/off selectively.

Yes, the test you link to (TestLinkWithoutRpath.test_package_tests_pass_if_ld_library_path_set) should pass. I think it does so on  travis, including I think the conda OS X environment, but I might need to take a closer look at the logs.

**Comment by AndreasHeger** [comment]
Just to confirm, the linking tests are executed and  target is x86_64-apple-
darwin15.6.0.

**Comment by bioinformed** [comment]
@jvkersch: Have you been able to make any progress on this issue?

**Comment by jvkersch** [comment]
@bioinformed Apologies for the delay. I made a small testcase based on the snippet you posted but I haven't been able to devote much time to this. I was quite hopeful to find a fix that would work for everybody involved, since Mac OS allows you to set several run paths and it will try each one in succession. So we could combine in principle the existing behavior with the pre-#489 behavior (I haven't tried this out, this is speculation at this stage). I will try to implement this today.

**Comment by bioinformed** [comment]
@jvkersch: Thanks!  Please note the test case that I added in `link_pre_489/`

**Comment by jvkersch** [comment]
@bioinformed Thanks for the extra test case (I overlooked it initially).

I've been looking into this, with partial success. It's possible to infer the install location of pysam, and then to add a second rpath for this path in `cy_build_ext`. This is sufficient to make the test pass without having to set LD_LIBRARY_PATH. This is quite easy to do.

However, this only works if the "secondary package" (i.e. the one that tries to make use of pysam) is built on the same machine that has pysam installed. Consider e.g. the example where someone has pysam installed via `python setup.py develop` and installs an pre-built wheel containing a secondary package depending on pysam. This package will have the pysam paths built in for the machine where the wheel was built, and these will probably not match the install location of pysam on the user's machine. I'm not sure this scenario was supported with the pre-#489 implementation, though.

My recommendation at this stage would be to add a second rpath to `cy_build_ext` with the install location for pysam. This will fix the situation for people that install secondary packages locally (either via `develop`/`install`, or by building a wheel on their machine and then installing it). For the case where this is not sufficient, I would admit defeat and advise users to set `LD_LIBRARY_PATH` (or tell them to `import pysam` before using any Cython modules that cimport from pysam).

@AndreasHeger @bioinformed What do you think? I write all of this without knowing the full gamut of linking use cases, so I'm perfectly OK if you decide to go with the old, pre-#489 way of linking.

**Comment by jvkersch** [comment]
The more I think about it, the more I like `import pysam` as a panacea for libraries that try to link against pysam. This will pull in all the required libraries regardless of where they are installed, and will allow the secondary packages to be built with standard distutils/setuptools constructs (i.e. no need for a customized `cy_build_ext` or `Extension` class). All they need to know is the location of the pysam headers.

**Comment by bioinformed** [comment]
@jvkersch: Can you please propose a PR?  @AndreasHeger would like to release later today and I'm working on resolving some of the odd CI failures.

**Comment by jvkersch** [comment]
I'm sorry, but looking at the setup file for https://github.com/pysam-developers/pysam/blob/master/linker_tests/link_without_rpath/setup.py I just don't see how it is possible to build a 3rd party extension without setting the rpath (unless the paths to libraries are hardcoded as they were pre #489). My attempts revolved around trying to set rpath via `cy_build`, since I assumed that was the command used to build the extension, but I see now that that's not accurate.

How about making this easier for the user via an extra stanza `extra_link_args=pysam.get_link_args()` in the description of the extension modules?

**Comment by jvkersch** [comment]
I'm not sure I can make a meaningful contribution here, so if this is holding up the release, please just revert #489.

**Comment by bioinformed** [comment]
@jvkersch (cc: @AndreasHeger): I think #489 is the right thing to do, but I'm going to revert it for this upcoming release.  There will be other breaking changes in the following release, so it makes sense to avoid creating unnecessary churn by delaying #489.  I'll also add some Sphinx docs with more explicit details on how to link against pysam for that future release.  Thanks again for your help on this issue.

**Comment by jvkersch** [comment]
@bioinformed Sounds good to me. Will you introduce the patch again in the future, or do you think a different solution is needed?

**Comment by bioinformed** [comment]
My current idea is to build on #489 and update `pysam.get_libraries()`.

**Comment by bioinformed** [comment]
One last sanity check-- does the current github master branch work with Conda-installs out of the box?  (I don't use it, but want to check that reverting doesn't break native installs for a large proportion of our user base.)

**Comment by kyleabeauchamp** [comment]
https://github.com/bioconda/bioconda-recipes/pull/5733

**Comment by bioinformed** [comment]
@kyleabeauchamp: So the answer is currently, no?  Bioconda still requires an additional rpath patch?

**Comment by kyleabeauchamp** [comment]
AFAIK conda will do a manual (regex-like) rpath patch.  The PR I linked is testing (still running) that master still builds and tests properly on bioconda.  I can also build a local conda recipoe to test that pysam is still behaving properly, as well.

**Comment by bioinformed** [comment]
@kyleabeauchamp: Thanks so much!  Please let us know how those tests go.

**Comment by kyleabeauchamp** [comment]
So the Bioconda recipe apparently did not work out of the box due to the changes in setup.py.  I then tried to replicate locally, still failed.  

I was able to replicate the build failure in a non-conda build with the following script:

```
conda create -c conda-forge -c bioconda -n testpysam htslib samtools pysam cython
source activate testpysam
conda remove pysam  # I installed pysam via conda just to grab zlib and other deps...

export PREFIX=~/miniconda2/envs/testpysam/
export CFLAGS="-I$PREFIX/include"
export CPPFLAGS="-I$PREFIX/include"
export LDFLAGS="-L$PREFIX/lib"

export HTSLIB_LIBRARY_DIR=$PREFIX/lib
export HTSLIB_INCLUDE_DIR=$PREFIX/include
python setup.py install


[...]
bcftools/main.c.pysam.c:27:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
```

This is probably something I could eventually fix by staring at the build script some more, but it is a bit strange that it used to work in the conda recipe but now fails.

**Comment by kyleabeauchamp** [comment]
Anyone else have any thoughts?

**Comment by AndreasHeger** [comment]
@kyleabeauchamp many thanks, have been travelling, but back now. 

Will look at this. The config.h script is auto-generated, this must have gone wrong somehow.

**Comment by AndreasHeger** [comment]
Hi, the issue has been that bcftools from version 1.5 requires a config.h file. I have added this file to the list of files that are created by setup.py (previously only samtools/config.h and htslib/config.h). The tests are currently building, but will try to release a fix version 0.12.0.1 tomorrow morning.

**Comment by kyleabeauchamp** [comment]
Thanks @AndreasHeger!

**Comment by kyleabeauchamp** [comment]
My preliminary (local) conda build test seems to be working on master, so I think there's a good chance things will work for the Bioconda build as well.

**Comment by AndreasHeger** [comment]
I have uploaded a new release with the config.h fixed. I can try building the conda package this evening.

**Comment by kyleabeauchamp** [comment]
Thanks, I've updated my Bioconda PR (https://github.com/bioconda/bioconda-recipes/pull/5733) so hopefully that builds now.

FWIW, I wish there were a way to streamline the HTSLib packaging that goes on in pysam.  I feel like a lot of your time is spent dealing with headaches associated with bundling and embedding HTSLib.

**Comment by kyleabeauchamp** [comment]
PR is merged, so Bioconda recipe should be live in a couple hours

**Comment by kyleabeauchamp** [comment]
Files are live: https://anaconda.org/bioconda/pysam/files?version=0.12.0.1

**Comment by AndreasHeger** [comment]
Thanks, @kyleabeauchamp that is great news!
Yes, it feels like >50% of my time is spent on platform, packaging and compilation issues, but doing this on the pysam level hopefully has large benefits for the community. It is also quite educational, and it is great to have your support! (and of the many others reporting build issues and submitting PRs)

**Comment by AndreasHeger** [comment]
Closing this issue for now. More tests would definitely be good.
