### ISSUE TITLE
Data loss when fetching from S3/HTTP/HTTPS

### ISSUE THREAD

**Issue by bioinformed** [pysam-developers/pysam#504]
Using pysam 0.11.2.2 linked against libcurl (version tbd), I was fetching 4,000 BCF files via signed S3 HTTPS URLs one chromosome at a time by specifying both BCF and index URLs.  A very few number of those fetches failed, but either due to a failure in htslib or in pysam, the failure was not retried until success nor was the error propagated to the calling code.  This failure led to silent data loss.

I'm going to investigate more deeply and request clarification from the htslib developers on how error and retry handling are performed when htslib is linked against libcurl.

**Comment by jmarshall** [comment]
HTSlib does no retrying, but propagates all errors to its callers (modulo bugs, but unlike some earlier HTSlib code, this code was written with correct error handling as an explicit goal).

(Were unreported transfer failures in BCF or index files? There is more older code involved with indices, so there is more scope there for less careful HTSlib code.)

**Comment by bioinformed** [comment]
@jmarshall: Thanks for the timely reply.  I suspect the error may have been propagated via a NULL return from `hts_itr_querys`, which is currently treated as an empty query result in pysam.  I need to look more closely at why this was done, but I vaguely remember that queries for a valid contig with no resulting records could result in a NULL value from `hts_itr_querys`.

- See https://github.com/pysam-developers/pysam/blob/master/pysam/libcbcf.pyx#L3743

The error handling around fetching records from an iterator appears to be more sound.

- See https://github.com/pysam-developers/pysam/blob/master/pysam/libcbcf.pyx#L3788

While this failure appears to be due to pysam, it would be very nice if there could be more documentation on the iteration API.  It would also be ideal to have a method to determine which operations could be retried versus those that are doomed to always fail.
