### ISSUE TITLE
Exit with no error in pysam.bcftools

### ISSUE THREAD

**Issue by garrettjstevens** [pysam-developers/pysam#506]
I'm using the Python interactive interpreter to work with pysam.bcftools. However, some commands cause the interpreter to immediately exit with no error message. For example:
```python
>>> import pysam.bcftools as bcftools
>>> # This works as expected:
... a = bcftools.stats('my.vcf')
>>> # This causes the interpreter to immediately exit:
... a = bcftools.norm('my.vcf')
user@home:~$

>>> # These also cause the interpreter to immediately exit:
... print(bcftools.stats.usage())
user@home:~$

>>> print(bcftools.norm.usage())
user@home:~$
```

I'm using pysam 0.11.2.2, Python 3.5.1, and SAMtools/BCFtools/HTSlib 1.5.
Thanks.

**Comment by AndreasHeger** [comment]
Yes, that is an issue because bcftools tools use the exit() function at multiple places in the source code. There is no recovery from a call to exit(). I have been hesitant to do too much patching to the tools to keep the wrapping simple, but maybe I need to revisit that.

**Comment by garrett-stevens** [comment]
Well, there's certainly something to be said for simplicity. I mostly reported it because it was something I noticed, not necessarily something I really need. I won't mind if this stays low on your priority list.

**Comment by AndreasHeger** [comment]
Thanks for reporting. I will certainly keep the issue open as it requires a solution.

**Comment by sarahbuzz** [comment]
I'm having this same issue (pysam v0.14, bcftools/htslib v1.5) using the same commands in the original post.
I'm hoping to use this instead of a subprocess call to bcftools. Would you be able to revisit this issue soon?

Thank you!
