### ISSUE TITLE
Confusion identifying R1 (forward) and R2 (reverse) reads with paired-end BAM

### ISSUE THREAD

**Issue by guillermomarco** [pysam-developers/pysam#507]
I'm currently parsing a BAM file of Illumina paired-end reads. I'm in need to apply certain specific filters to R1 (forward read) and other specific filter to R2 (reverse read).

I was inferring that `AlignmentFile` properties `is_read1` and `is_read2` indicate if read is R1 (forward) or R2 (reverse read) for paired-end data, but I think I'm assuming something wrong from readthedocs API or indeed there's a bug. So should I be using `is_reverse` attribute to determine this?

I attach my test BAM file with a pair of reads. The information below is what I observe employing `pysam 0.11.2.2`
[example.zip](https://github.com/pysam-developers/pysam/files/1156226/example.zip)

**R1 forward read:**
```
is_read1 = {bool} False
is_read2 = {bool} True
is_reverse = {bool} False
```

**R2 reverse read:**
```
is_read1 = {bool} True
is_read2 = {bool} False
is_reverse = {bool} True
```

**Comment by bioinformed** [comment]
`is_read1` and `is_read2` are functioning as you expect.

`is_reverse` is set when a read is aligned to the reference genome as the reverse complement of the read generated by the sequencer.  All alignments in SAM/BAM are relative to the forward strand of the reference genome, which means that the read must sometimes be strand-swapped. 
 i.e. to recover the original read bases, the sequence in the SAM/BAM file must be reverse complemented and the quality scores must be reversed.

The example that you show above (assuming R1 and R2 are properly paired in the FR orientation) occurs when the entire sequenced template fragment aligns to the reverse strand of the reference genome contig.  (You have the labels swapped above.)

**Comment by bioinformed** [comment]
@guillermomarco: My comment on your results being swapped related to the text above in your initial report.  The block you label as "R1 forward read" is actually "R2 reverse read" and vice-versa.  The fact that the `is_reverse` flag is opposite of what you expect is because the read pair are aligned to the reverse genomic strand.

**Comment by guillermomarco** [comment]
@bioinformed Indeed you was right, I now understand it. I was swaping labels because I was working with a BAM file where a third person messed around SAM flags and swapped R1 and R2. I was going crazy. Thank you so much for clarification.
