### ISSUE TITLE
Return read counts per chromosome

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#512]
Similar to idxstats, return for each chromosome:

1. Total read count
2. Mapped read count
3. Unmapped read count (e.g. where one of a pair is mapped and the other is not)

**Comment by bioinformed** [comment]
This feels like functionality that belongs to an application, not the core library.  I agree this would be useful functionality, but what will we do when users request counts based on BED file masking, on/near/off-target counts, stratification by mapping quality, etc?  That said, I don't have a problem if the application is part of pysam -- just that we don't attempt to build all of this functionality into the `AlignmentFile` object.

**Comment by AndreasHeger** [comment]
Thanks. The gist of this feature is simply to expose the data that is contained in the BAM index anyways, i.e. there is not any algorithmic component.

**Comment by bioinformed** [comment]
Ah-- I thought you meant to build a counter function that generated data similar to idxstats.  It all that is being proposed is an API to expose idxstats then I withdraw all objections.

**Comment by AndreasHeger** [comment]
Note to self: add total
