### ISSUE TITLE
Keep header when file is closed

### ISSUE THREAD

**Issue by bjoernpollex** [pysam-developers/pysam#517]
After closing an `AlignmenFile`, the `reference_name` attribute of `AlignedSegment` instances from that file cannot be accessed anymore, because the header data has been deleted. Example:

```python
from pysam import AlignmentFile

def load(path):
    with AlignmentFile(path) as bam:
        return next(bam)

al = load('some.bam')
al.reference_name
```

The last line results in the following error:

```
ValueError: I/O operation on closed file
```

Would it be possible to keep the header information around to support that operation after the file is closed? Would it be possible to store the reference names as Python strings in a tuple, and reference that in `AlignedSegment`? This way Python's own resource management mechanism would handle it.

**Comment by bioinformed** [comment]
@AndreasHeger: Should we consider splitting the `AlignmentHeader` from `AlignmentFile` akin to what is done for `VariantFile` and `VariantHeader`?  The overhead of storing a reference to the header is fairly minor and can finally remove the need for having to even think about translating to and from `tid`s.

**Comment by AndreasHeger** [comment]
@bjoernpollex thanks for reporting and @bioinformed, yes. I realize not providing a full abstraction on top of htslib requires a lot of understandable confusion, such as here #509.
I will do this today.

**Comment by bjoernpollex** [comment]
Thanks, this is really an essential project to our work, and the support is much appreciated!
