### ISSUE TITLE
Can I batch write reads to a file at the same time?

### ISSUE THREAD

**Issue by verne91** [pysam-developers/pysam#524]
I do not find this fuction in `pysam.AlignmentFile`.

**Comment by bioinformed** [comment]
@verne91: It sounds like you have multiple problems.

Re can't find `pysam.AlignmentFile` -- make sure you're not running your script from the `pysam` source directory.

Re batch writing reads: `pysam.AlignmentFile` implements internal buffering, so there is no major advantage to batch writing (beyond the overhead of the method call per write).  Can you explain your use-case for batch writing in more detail?

**Comment by verne91** [comment]
I use the example from the mannual.

```
import pysam
samfile = pysam.AlignmentFile("ex1.bam", "rb")
pairedreads = pysam.AlignmentFile("allpaired.bam", "wb", template=samfile)
for read in samfile.fetch():
     if read.is_paired:
             pairedreads.write(read)

pairedreads.close()
samfile.close()
```

If I need to deal with each read form one bam file and output to another bam file, do I have any method to accelerate writing?
Thanks.

**Comment by bioinformed** [comment]
There is little overhead to writing one record at a time, since there is internal buffering.  Each written record doesn't translate directly into an IO operation.  Do you have any specific performance concerns?

**Comment by verne91** [comment]
I have a about 90Gb bam file and I deal with it as the example said. It takes about 32 hours and the real used CPU time is just about 3 hours. I think most time was used on IO.

**Comment by bioinformed** [comment]
Ah-- the biggest speedup will be to allow allocating more compression threads.  It has been on my TODO list for some time.  Though it sounds like IO throughput limitations are your biggest bottleneck, which can't be solved by pysam.  To better understand your use-case, can you benchmark the same operation using `samtools view`, also writing to a BAM file?

**Comment by AndreasHeger** [comment]
See #579 , closing this ticket for now.
