### ISSUE TITLE
translate aligned read to unaligned read in bam

### ISSUE THREAD

**Issue by lituan** [pysam-developers/pysam#529]
sometimes it needs to realign reads in a aligned bam file, for example, use tmap to realign the reads to a specific segment of genome, and realigning reads needs to convert reads to unaligned state. So it would be nice if this could be done easily using pysam.

**Comment by AndreasHeger** [comment]
HI @lituan , not sure I fully understand, but you could set the mapped flag:

```
with pysam.AlignmentFile("x.bam") as inf:
    with pysam.AlignmentFile("out.bam", "wb") as outf:
        for read in inf:
             read.flag |= pysam.FUNMAP
             outf.write(read)
```

**Comment by lituan** [comment]
Thank you @AndreasHeger , what I mean is that, I want to translate the read to original unmapped state. As a read mapped to the reverse strand will be transformed (reverse complement) after aligning. So I need to do another transformation (reverse complement) to transform it to original unmapped state.

**Comment by AndreasHeger** [comment]
I see. I can add a get_reverse_complement() function.
