### ISSUE TITLE
Tag data types do not conform SAM

### ISSUE THREAD

**Issue by karel-brinda** [pysam-developers/pysam#531]
According to the [SAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf), tags can be of six data types:
* `A` – Printable character
* `i` – Signed integer
* `f` – Single-precision floating number
* `Z` – Printable string, including space
* `H` – Printable string, including space
* `B` – Byte array in the Hex format

However, PySam implements a slightly different set: `Z`, `i`, `d`, `f`, `B`; i.e., it adds `d` for doubles, and does not support `H` and `A`. Especially `d` causes various issues as it is used as the [automatically deduced type for floats/doubles](https://github.com/pysam-developers/pysam/blob/bd4d8f9e2c78a3c72223da070a45699d82147c71/pysam/libcalignedsegment.pyx#L155).

I think that these two functions need to be fixed:
* https://github.com/pysam-developers/pysam/blob/bd4d8f9e2c78a3c72223da070a45699d82147c71/pysam/libcalignedsegment.pyx#L1912
* https://github.com/pysam-developers/pysam/blob/bd4d8f9e2c78a3c72223da070a45699d82147c71/pysam/libcalignedsegment.pyx#L145

**Comment by AndreasHeger** [comment]
Thanks. Pysam is following the format definitions implemented in htslib, see here:

https://github.com/samtools/htslib/blob/develop/sam.c#L1070

Will make sure the missing formats are added.

**Comment by karel-brinda** [comment]
Thanks for your answer.

> Pysam is following the format definitions implemented in htslib

I don't know the history of data types in SAM, but it looks like they are just trying to be backward compatible with some older version of SAM.

> Will make sure the missing formats are added.

Thank you.

Would it be possible to change `d` to `f` in the automatic type detection step? Adding a new tag with a float value to an SAM existing record currently makes the record invalid according to the current specification.

This might not be trivial: you probably want to keep existing `d`'s as `d`'s, but SAM types are deduced from Python data types, and Python implements only doubles (but they are called floats). I see 3 possible solutions:
* storing SAM datatype as an integer/string (like in you [example](https://github.com/samtools/htslib/blob/develop/sam.c#L1070), unfortunately Python doesn't have char)
* an internal bit flag for numbers (double vs. float)
* [array](https://docs.python.org/3/library/array.html) with a single entry (then it's possible to distinguish between doubles and floats)

**Comment by AndreasHeger** [comment]
Hi @karel-brinda 

Good points. I have changed the default, so that a python float is mapped to 'f' in SAM.
Pysam will still read and write 'd's, but I agree that an automatically deduced type code needs to be specification conform.

**Comment by karel-brinda** [comment]
@AndreasHeger Great, thank you for fixing.
