### ISSUE TITLE
Wheels packages on PyPI missing

### ISSUE THREAD

**Issue by SoapGentoo** [pysam-developers/pysam#535]
@AndreasHeger 
The current version is missing the wheels package on PyPI, would it be possible for you to post an updated wheels package? Thanks for a great package :smiley:

**Comment by jean-philippe-martin** [comment]
+1: I ran into the same issue. The missing precompiled wheel files prevent pysam-0.12.0.1 from working with Google Dataflow (pysam-0.12.0 works fine).

**Comment by AndreasHeger** [comment]
Apologies, will put them up this evening.

**Comment by AndreasHeger** [comment]
The wheels are now available.
