### ISSUE TITLE
compilation error for release 0.5

### ISSUE THREAD

**Issue by shukwong** [pysam-developers/pysam#538]
I am having trouble compiling htslib in release 0.5. I was wondering if you could help? 

Thanks,
Wendy

cd lib/htslib && make
make[1]: Entering directory `<local>/HipSTR-0.5/lib/htslib'
gcc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
thread_pool.c: In function ‘hts_tpool_init’:
thread_pool.c:676:5: warning: implicit declaration of function ‘pthread_mutexattr_settype’ [-Wimplicit-function-declaration]
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
     ^
thread_pool.c:676:38: error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
                                      ^
thread_pool.c:676:38: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [thread_pool.o] Error 1
make[1]: Leaving directory `<local>/HipSTR-0.5/lib/htslib'
make: *** [lib/htslib/libhts.a] Error 2

**Comment by AndreasHeger** [comment]
Hi, this issue might better be raised with the htslib project.

**Comment by AndreasHeger** [comment]
Closing for now.
