### ISSUE TITLE
Test failures not fully solved

### ISSUE THREAD

**Issue by tillea** [pysam-developers/pysam#541]
Hi,
when trying to build pysam on a chroot not connected to the interned (as its done when building the Debian package) there are remaining test failures which are most probably related to issue #534 .  The build log says:

    test_sequence_lengths_are_available (faidx_test.TestRemoteFileFTP) ... ok
    test_package_can_be_installed (linking_test.TestLinkWithRpath) ... SKIP: enable linking tests by setting PYSAM_LINKING_TESTS environment variable
    test_package_tests_pass (linking_test.TestLinkWithRpath) ... SKIP: enable linking tests by setting PYSAM_LINKING_TESTS environment variable
    test_package_can_be_installed (linking_test.TestLinkWithoutRpath) ... SKIP: enable linking tests by setting PYSAM_LINKING_TESTS environment variable
    test_package_tests_fail_on_import (linking_test.TestLinkWithoutRpath) ... SKIP: enable linking tests by setting PYSAM_LINKING_TESTS environment variable
    test_package_tests_pass_if_ld_library_path_set (linking_test.TestLinkWithoutRpath) ... SKIP: enable linking tests by setting PYSAM_LINKING_TESTS environment variable
    test_package_can_be_installed (linking_test.TestLinking) ... SKIP: enable linking tests by setting PYSAM_LINKING_TESTS environment variable
    linking_test.check_tests_pass ... ERROR
    testEmptyIndex (samtools_test.EmptyIndexTest) ... ok

Any hint how to fix this?
Kind regards, Andreas.

**Comment by AndreasHeger** [comment]
Thanks, sorry about this. It seems that pytest picks up the check_tests_pass method. I am trying to reproduce this. Using only the linking_test.py file I get:
```
  pytest tests/linking_test.py 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /ifs/home/andreas/miniconda3/envs/pysam-devel/bin/python
cachedir: .cache
rootdir: /ifs/devel/andreas/pysam, inifile: setup.cfg
plugins: xdist-1.18.2
collected 6 items 

tests/linking_test.py::TestLinking::test_package_can_be_installed SKIPPED
tests/linking_test.py::TestLinkWithRpath::test_package_can_be_installed SKIPPED
tests/linking_test.py::TestLinkWithRpath::test_package_tests_pass SKIPPED
tests/linking_test.py::TestLinkWithoutRpath::test_package_can_be_installed SKIPPED
tests/linking_test.py::TestLinkWithoutRpath::test_package_tests_fail_on_import SKIPPED
tests/linking_test.py::TestLinkWithoutRpath::test_package_tests_pass_if_ld_library_path_set SKIPPED
```

**Comment by AndreasHeger** [comment]
Running all tests using pytest, check_tests_pass is not present:
```
pytest >& out
grep check_tests_pass out
```
At the moment I am at the loss what could be the issue.

**Comment by AndreasHeger** [comment]
Ahh, I think the issue is with nose:
```
/ifs/home/andreas/miniconda3/envs/pysam-devel/bin/python /ifs/home/andreas/miniconda3/envs/pysam-devel/bin/nosetests -v linking_test.py
linking_test.check_tests_pass ... ERROR

======================================================================
ERROR: linking_test.check_tests_pass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/home/andreas/miniconda3/envs/pysam-devel/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: check_tests_pass() missing 1 required positional argument: 'statement'

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (SKIP=6, errors=1)
```
We have switched to pytest recently, is this something you could do as well? Otherwise, I am renaming the method to prevent it from being picked up by nose.

**Comment by AndreasHeger** [comment]
I have pushed a change, please reopen ticked if the problem persists.
