### ISSUE TITLE
pysam.is_unmapped doesn't work

### ISSUE THREAD

**Issue by marvel64** [pysam-developers/pysam#55]
Hello,

When I try to filter a 5.3 GB coordinate sorted BAM file for unmapped reads, I end up with only 27 reads
in the resulting file. 

bam = pysam.Samfile("mybam.bam", "rb")

for i in bam.fetch():
    if i.is_unmapped:
        print(i)

or

for i in bam.fetch():
    if i.flag == 4:
        print(i)

doesn't work as expected.

I have a small (238 KB) test file that I could provide.

Sincerely,
Kemal

**Comment by smangul1** [comment]
Dear Andreas,

Is there a way to iterate ONLY over the unmapped reads?

Thanks,
Serghei

**Comment by AndreasHeger** [comment]
@serghei, I don't think there is, other than fetching and filtering by flag.
