### ISSUE TITLE
Coordinates and  duplication

### ISSUE THREAD

**Issue by gotyca** [pysam-developers/pysam#552]
Hello.

I have a question regarding how pysam calculates reference_end.

Here is a piece of my sam file:

NB502029:10:HLHHMBGX3:1:11206:6289:11333	163	chrX	48312853	60	75M	=	48312902	124	CCTGAAGTCGCGCCTGCCCCTCAGCCTGGGGGTCTGATGGCTCCGCAAGCGGGGGTCCAGCCCAACGACTGCCCT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEE/EE<EEEEEEE	X0:i:1	X1:i:0	MD:Z:75	PG:Z:MarkDuplicates	XG:i:0	AM:i:37	NM:i:0	SM:i:37	XM:i:0	XO:i:0	XT:A:U
NB502029:10:HLHHMBGX3:1:11206:6289:11333	83	chrX	48312902	60	75M	=	48312853	-124	CGGGGGTCCAGCCCAACGACTGCCCTGAGCTGCCGCCCGACCTCCTGCTGGCCGAGCCGGCTGAACCGGCGCCGG	EEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	X0:i:1	X1:i:0	MD:Z:75	PG:Z:MarkDuplicates	XG:i:0	AM:i:37	NM:i:0	SM:i:37	XM:i:0	XO:i:0	XT:A:U
NB502029:10:HLHHMBGX3:1:12312:7639:19146	163	chrX	48312902	60	75M	=	48312984	157	CGGGGGTCCAGCCCAACGACTGCCCTGAGCTGCCCCCCGACCTCCTGCTGGCCGAGCCGGCTGAACCGGCGCCCG	AA//AA/EAAAEEEEAEA/<EEE<E/<///EEAE/EAE6/EAEE//EEE/EEE6//EAAE//EE/EEEEEEEE/E	X0:i:1	X1:i:0	MD:Z:34G38G1	PG:Z:MarkDuplicates	XG:i:0	AM:i:25	NM:i:2	SM:i:37	XM:i:2	XO:i:0	XT:A:U
NB502029:10:HLHHMBGX3:1:12312:7639:19146	83	chrX	48312984	60	75M	=	48312902	-157	GCCTGAGGTGGAGGCAGAGGGCCGGGCCGCCGCCGAGAGTCCCCGCAGGCCGCGGGGCCCGGGCCCGGGCGTGGG	EEA/<AEE/EA/EEAAE/EEEE/EEE<EAA/AA/E/AAE/AEEAE///EE/AE</EAAA/EAEE6EEAEEA/AA/	X0:i:1	X1:i:0	MD:Z:8A21A22T20T0	PG:Z:MarkDuplicates	XG:i:0	AM:i:25	NM:i:4	SM:i:25	XM:i:4	XO:i:0	XT:A:U

When I read this sam file with pysam (print read.reference_name + '\t' + str(read.reference_start) + '\t' + str(read.reference_end)) it gives me:

chrX	48312901  	48312976
chrX	48312901	48312976

I understand both reads mapped to reference_start 48312902 (equivalent in pysam to 48312901). But I don't get it how pysam calculated the reference_end. According to pysam I have duplicated reads but the bam used was processed with Pickard to have duplicates removed.

Could you please help me?

Thank you.

**Comment by AndreasHeger** [comment]
Hi, I think what you have is two paired-end reads, where one read of each pair maps to the same location, but the other reads don't. Hence Picard will not regard this as a duplication.

I am closing the issue, please reopen if you think there is a bug.
