### ISSUE TITLE
retrieve all the bases at a genomic position

### ISSUE THREAD

**Issue by ju-cheng** [pysam-developers/pysam#553]
I want to retrieve all the bases at a genomic position. I tried pileup and looked into the pysam documentation, the example assign the position by pileupread.query_position, where query_position is the order the base of the read. Instead, I want to use genomic_position. Is there any method/attribute can do that? Thanks a lot!

**Comment by AndreasHeger** [comment]
Sorry, this would be useful functionality, but at the moment this is not implemented. Instead, you will need to iterate through the pileup yourself and extract the appropriate base.

I keep this ticket open.

**Comment by zqHealth** [comment]
I have a similar question.
**QUESTION 1**
I'd like to get the base from each pileup_read, there is an example in [pysam readme](http://pysam.readthedocs.io/en/stable/api.html#introduction): 

> import pysam
samfile = pysam.AlignmentFile("ex1.bam", "rb" )
for pileupcolumn in samfile.pileup("chr1", 100, 120):
    print ("\ncoverage at base %s = %s" %
           (pileupcolumn.pos, pileupcolumn.n))
    for pileupread in pileupcolumn.pileups:
        if not pileupread.is_del and not pileupread.is_refskip:
            # query position is None if is_del or is_refskip is set.
            print ('\tbase in read %s = %s' %
                  (pileupread.alignment.query_name,
                   pileupread.alignment.query_sequence[pileupread.query_position]))
samfile.close()

where I found `pileupread.query_position` didn't return the position of the base at `query_sequence` as the example said. 
Frist I think it returned the first aligned base position at `query_sequence `, just like `pysam.AlignedSegment.query_alignment_start`.
But finally I think it more likes the index of `pileupcolumn `.

It seems there is no 'attribute' or 'method' can directly get the base and base quality of each read at pileup_read. It will be realizable in the future?


**QUESTION 2**
When I pileup at just 1-bp region,  it loops `pileupcolumn` more than one time.
e.g.:

> out_reads = {}
        for pileup_column in samfile.pileup('chr%s' % chrom, pos-1, pos):  # get reads at chr:pos
            print(chrom, pos, rs, pileup_column.reference_pos, pileup_column.reference_name)  # test
            for pileup_read in pileup_column.pileups:
                if pileup_read.is_del or pileup_read.is_refskip:
                    continue  # query position is None if is_del or is_refskip
                segment = pileup_read.alignment
                if segment.query_name in out_reads:
                    continue  # ? it seems pileup() output read many times

It excutes the test  **`print()`**  sentence executes many times. I wasn't what I thought it was. What happened?

Looking for ward to your reply.
