### ISSUE TITLE
Could not open alignment file S3 protocol not supported

### ISSUE THREAD

**Issue by dmmiller612** [pysam-developers/pysam#557]
Hello,

I was recently trying to use the pysam.Alignmentfile class on an s3 file in a lambda container, but received an error saying the protocol wasn't supported. I am using pip as the installation, which includes cython and pysam among other dependencies.

The error locations are:

`File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__`
`File "pysam/libcalignmentfile.pyx", line 621, in pysam.libcalignmentfile.AlignmentFile._open`

with the error message:
`IOError: [Errno 93] could not open alignment file `s3://some-bucket/full.bam`: Protocol not supported`

What is weird is that it seems to work locally (s3 that is),  but as soon as I deploy to lambda, I having issues. Any idea what could be causing this? My requirements are the following:

```
argcomplete==1.9.2
base58==0.2.4
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
Cython==0.27.2
docutils==0.14
durationpy==0.5
Flask==0.12.2
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==1.0
placebo==0.8.1
pysam==0.12.0.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.2
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3
```

**Comment by AndreasHeger** [comment]
Hi, do you have access to the install log files. I expect that maybe libcurl or something else is missing. The pip install will no install system libraries and will build an htslib without libcurl enabled.

**Comment by dmmiller612** [comment]
That is a good point. I'll dig a little deeper today and report on what I find

**Comment by dmmiller612** [comment]
@AndreasHeger So AWS lambdas are a little weird in that all of your executables need to be in your zipped package. I tried adding curl to my zipped package and updated the path to use Curl, but I got the same error. Not sure if that is enough though.

**Comment by dmmiller612** [comment]
With that in mind, can I set a curl environment variable to overwrite the pysam curl? 

I'll create an example of this, if I get it working. I think others might like this as well.

**Comment by AndreasHeger** [comment]
Thanks. Sorry, I have no first-hand experience of AWS lambdas. Setting PATH for the curl executable is likely not enough. You will need a pysam compiled against libcurl as well as the libcurl shared libraries in your zipped package. A first step into that direction might be if you get samtools compiled in such a way to access the BAM file of interest.

**Comment by AndreasHeger** [comment]
Closing this issue for now, seems more to be a system configuration issue. Please reopen if a pysam problem.
