### ISSUE TITLE
error under cygwin

### ISSUE THREAD

**Issue by jchenpku** [pysam-developers/pysam#563]
I was trying to install pysam under cygwin but it returned several "undefined reference" error. The copy of pysam source was cloned from github.

build/temp.cygwin-2.9.0-x86_64-2.7/samtools/bam.c.pysam.o:bam.c.pysam.c:(.rdata$.refptr.pysam_stdout[.refptr.pysam_stdout]+0x0): undefined reference to `pysam_stdout'
build/temp.cygwin-2.9.0-x86_64-2.7/samtools/bam2bcf.c.pysam.o:bam2bcf.c.pysam.c:(.rdata$.refptr.pysam_stderr[.refptr.pysam_stderr]+0x0): undefined reference to `pysam_stderr'
build/temp.cygwin-2.9.0-x86_64-2.7/samtools/bam_md.c.pysam.o:bam_md.c.pysam.c:(.rdata$.refptr.pysam_stdout_fn[.refptr.pysam_stdout_fn]+0x0): undefined reference to `pysam_stdout_fn'
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by AndreasHeger** [comment]
merged with #575
