### ISSUE TITLE
wrong coverage and not starting from beginning

### ISSUE THREAD

**Issue by mictadlo** [pysam-developers/pysam#569]
Hi, 
I used the following code example:

```
import pysam
samfile = pysam.AlignmentFile("data/chr01.bam", "rb" )
for pileupcolumn in samfile.pileup("chr01"):
    print ("\ncoverage at base %s = %s" %
           (pileupcolumn.pos, pileupcolumn.n))
    for pileupread in pileupcolumn.pileups:
        if not pileupread.is_del and not pileupread.is_refskip:
            # query position is None if is_del or is_refskip is set.
            print ('\tbase in read %s = %s' %
                  (pileupread.alignment.query_name,
                   pileupread.alignment.query_sequence[pileupread.query_position]))
```
It appears it made mistakes on the coverage:

```
coverage at base 1754 = 1
	base in read BTJCct_51882_4100 = G
```
Looking at Tablet (BAM viewer) it appers taht the coverage is `3` and are `G`s.

I install pysam (0.13.0py27) with help of `conda`. 

Please find [here](https://drive.google.com/drive/folders/1NtwgMu6v6bQ2sJQEUogz4M6P0EbFOVSD?usp=sharing) my data.  

Why do I get the wrong coverage and  why it starts not from position 466?

Thank you in advance.

Michal

**Comment by AndreasHeger** [comment]
Hi Michal,

please try ```stepper="samtools"``` as arguments to pileup.

**Comment by AndreasHeger** [comment]
Closing for now, please reopen if you think it is a bug.

**Comment by mictadlo** [comment]
Thank you, it works
