### ISSUE TITLE
Release GIL for calls to  htslib 

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#57]
See discussion here: https://groups.google.com/forum/#!topic/pysam-user-group/KNYbFdAKVX4

Calls to htslib do not release the GIL and potentially cause blocking in multi-threading applications where one thread waits from I/O from another thread.

**Comment by bioinformed** [comment]
I didn't realize that functions declared extern nogil didn't release the GIL.  I'll start converting VariantFile and related classes to release the GIL in places where IO, particularly network IO, can block.

**Comment by AndreasHeger** [comment]
Thanks!
