### ISSUE TITLE
Setting alleles removes END by overwriting rlen

### ISSUE THREAD

**Issue by msto** [pysam-developers/pysam#571]
Hi,

I'm not sure whether this is intended behavior, but setting the `ref` or `alts` attributes of a `VariantRecord` removes the record's `stop`/`END`. The alleles setter method and the ref setter method overwrite the record's `rlen` with the length of the reference allele. In the case of symbolic alleles, this removes the true `rlen`. Is it possible to remove these two lines?

https://github.com/pysam-developers/pysam/blob/27d84526c13a8ffb8231b5c2db713bc7341ffdd5/pysam/libcbcf.pyx#L3142

https://github.com/pysam-developers/pysam/blob/27d84526c13a8ffb8231b5c2db713bc7341ffdd5/pysam/libcbcf.pyx#L3180

**Comment by bioinformed** [comment]
It is intentional in order to avoid inconsistent stop coordinates, as VCF leaves the stop coordinate as implicit most of the time.  These aren't ideal semantics, so please feel free to propose something more sane and less surprising.

**Comment by msto** [comment]
Can I update the code to overwrite the rlen only if the alternate allele is not a symbolic allele (per the VCF spec, "an angle-bracketed ID string '<ID>'")?

**Comment by bioinformed** [comment]
That is a totally reasonable request.

**Comment by msto** [comment]
Fixed in #570 .
