### ISSUE TITLE
`reference_name` on `reference_id = -1` should return "*"

### ISSUE THREAD

**Issue by kghosesbg** [pysam-developers/pysam#580]
@AndreasHeger may I request issue #268 be re-opened: 

I understand the point about invalid `reference_id`, but the -1 coordinate is returned for reads from the NOCOOR region, which is, by convention, referenced as '\*'. I would request that pysam return '*' for this. 

Thanks!

**Comment by AndreasHeger** [comment]
Sounds reasonable.

**Comment by AndreasHeger** [comment]
After a check, the reference_name for NOCOOR is None, I think this is something that got added during the recent header refactoring.
I think None for NOCOOR is a reasonable pythonic mapping but I have added the possibility to set reference_name to "*".
