### ISSUE TITLE
reads with samflags 99/147 have reference coordinates differing by one compared to 88/163

### ISSUE THREAD

**Issue by canthonyscott** [pysam-developers/pysam#582]
Hi all,

I am using pysam to parse paired-end whole-genome bisulfute sequencing bam files generated by Bismark/Bowtie2. 

I am using pysam to pull out all reads in specific regions. For reads with samflags 88 or 163 everything appears to be as expected. For example: If i use `read.get_reference_positions()` and compare the bases at these positions back reference back to the genome I find the base I expect, in my case  the CpG I am looking for. 

However if the read has samflags of 99 or 147 the base reference position appears to be shifted by one compard to its expected reference position in the genome. For example, when the reference position should point to a CpG it actually points to an A  in a ACG or C in a CCG or even a G in a GCG. No matter the context they appears to be off by one base-pair.

Is this a bug? Or is there some underlying function I am just misunderstanding that has something to do with these samflags?

Thanks for your time.

**Comment by canthonyscott** [comment]
After discussing this issue with some colleagues they have seem to encountered it as well even when not using pysam. Its possible this bug could be being introduced further upstream, maybe at the bismark level, and not by pysam.

**Comment by AndreasHeger** [comment]
Thanks. I will close this issue for now.
