### ISSUE TITLE
Error parsing VCF format line 'AD' when 'Number=R'

### ISSUE THREAD

**Issue by timothymillar** [pysam-developers/pysam#584]
Hi, thanks for pysam! 

There's an issue when parsing the vcf format line:
`##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele">`

VCF version 4.2 uses the symbol `R` for representing the fields that have one value for each possible allele (including the reference).
This should include the field `AD` ("Number of observation for each allele") but pysam (versions `0.13` and `0.11.2.2` on OSX) throws an error:
```
ValueError: Formatting error in the format string in line 70: '##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele">'
Error BADLY_FORMATTED_FORMAT_STRING: Formatting error in the format string
```
If the `R` is replaced with `.` the vcf is parsed without issue.

The vcf was output from freebayes version `1.1.0`.

Also see this related [issue from gatk](https://gatkforums.broadinstitute.org/gatk/discussion/6919/change-format-of-ad-field-to-number-r).

EDIT: Full traceback:

```
In [1]: from pysam import VCF

In [2]: vf = VCF()

In [3]: vf.connect('example.vcf.gz')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
pysam/libcvcf.pyx in pysam.libcvcf.VCF.parse_format (pysam/libcvcf.c:9831)()

ValueError: invalid literal for int() with base 10: 'R'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-13babc2ab02f> in <module>()
----> 1 vf.connect('example.vcf.gz')

pysam/libcvcf.pyx in pysam.libcvcf.VCF.connect (pysam/libcvcf.c:29036)()

pysam/libcvcf.pyx in pysam.libcvcf.VCF._parse_header (pysam/libcvcf.c:25407)()

pysam/libcvcf.pyx in pysam.libcvcf.VCF.parse_header (pysam/libcvcf.c:14770)()

pysam/libcvcf.pyx in pysam.libcvcf.VCF.parse_format (pysam/libcvcf.c:10102)()

pysam/libcvcf.pyx in pysam.libcvcf.VCF.error (pysam/libcvcf.c:8207)()

ValueError: Formatting error in the format string in line 70: '##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele">'
Error BADLY_FORMATTED_FORMAT_STRING: Formatting error in the format string

```

**Comment by bioinformed** [comment]
Ah-- this failure is against the older custom VCF parser in pysam.  @AndreasHeger, is that code being maintained?  @timothymillar, have you tried the newer and better maintained `pysam.VariantFile` API?

**Comment by AndreasHeger** [comment]
Thanks, this code is not maintained and needs to be deprecated in favour of the VariantFile API.

Will make this clear in the docs and the next release notes.

**Comment by timothymillar** [comment]
Thanks @bioinformed, @AndreasHeger, `pysam.VariantFile` has no issues with my file.
