### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by pkerpedjiev** [pysam-developers/pysam#585]
I just tried installing pysam 0.13.0 via pip:

```
pip install pysam==0.13.0
```

and got the following set of errors:

```
sers/peter/miniconda3/envs/cenv3/include/python3.6m -c htslib/cram/cram_index.c -o build/temp.macosx-10.9-x86_64-3.6/htslib/cram/cram_index.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    In file included from htslib/cram/cram_index.c:65:
    In file included from htslib/hts_internal.h:29:
    htslib/htslib/hts.h:142:9: error: missing ',' between enumerators
        json HTS_DEPRECATED_ENUM("Use htsExactFormat 'htsget' instead") = htsget,
            ^
            ,
    htslib/htslib/hts.h:142:29: error: expected '= constant-expression' or end of enumerator definition
        json HTS_DEPRECATED_ENUM("Use htsExactFormat 'htsget' instead") = htsget,
                                ^
    2 errors generated.
    error: command 'gcc' failed with exit status 1
```

Installing pysam 0.12.0.1 doesn't produce any errors. Any suggestions? Should I post this issue on the htslib repo as well?

**Comment by AndreasHeger** [comment]
Thanks, this looks like an htslib issue, but before posting I would try to install htslib 1.6 from source to see if the same error occurs.

**Comment by pkerpedjiev** [comment]
It's almost certainly an htslib issue but doesn't pysam import its own copy of the htslib code? I installed htslib from source and got the same error.

**Comment by AndreasHeger** [comment]
Thanks for checking. In this case, could you open a ticket in the htslib repo?

You are correct that pysam has a copy of htslib included. This is an unmodified copy of the latest released htslib and so will have the same issues that the original htslib will have. If there is a problem such as yours, it is best to address this in the upstream htslib repo.

**Comment by AndreasHeger** [comment]
The reason for the htslib copy is to support installing pysam via pip without having any external dependencies.

**Comment by AndreasHeger** [comment]
Closing this issue for now.

**Comment by YanCCscu** [comment]
I met the same issue when I tried to install htslib >1.6 for samtools, I fianlly figured out that it was the previously installed htslib v1.5 that caused the problem. It is all OK after deleting htslib.pc and include/htslib  in DESTDIR of htslib v1.5.
