### ISSUE TITLE
BAM bin validation exceptions when changing a read to unmapped

### ISSUE THREAD

**Issue by nh13** [pysam-developers/pysam#590]
If I set a read to be unmapped, and change no other value, I get the following error when I run picard's ValidateSamFile: `bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned`.  This is because the bin field is not getting updated when `is_unmapped` is set to `True` (see [this line](https://github.com/pysam-developers/pysam/blob/1ff9e9a9ddb7197c14d4b30d6565a2090d408580/pysam/libcalignedsegment.pyx#L1483)).

I also looked at a few other places where `hts_reg2bin` was getting called and found some issues:
1. [In `reference_start`'s `__set__` method](https://github.com/pysam-developers/pysam/blob/1ff9e9a9ddb7197c14d4b30d6565a2090d408580/pysam/libcalignedsegment.pyx#L1167), we should be checking the unmapped FLAG bit, not call `pysam_get_n_cigar`.  See [note 18 on page 13 in the SAM spc](https://samtools.github.io/hts-specs/SAMv1.pdf).  Also note that when the unmapped field is set, no other assumptions can be made about CIGAR in particular, i.e. it is perfectly valid to have an unmapped read with a CIGAR.  I think it _should_ work, since we call `bam_endpos` when we have cigar elements, but I thought I would still point it out.  In my code, I did try setting `reference_start = reference_start` to trigger the bin update, but I still got errors.
2. Similarly the `__set__` method in `cigartuples` also delegates to `bam_endpos` when calling `hts_reg2bin`.

**Comment by AndreasHeger** [comment]
Thanks for the report. I have pushed a change that should fix this.

**Comment by nh13** [comment]
Thanks @AndreasHeger , any chance for a new release?

**Comment by AndreasHeger** [comment]
Hi, will have a look at the state of things over the weekend, but I don't think there are major blockers. @bioinformed, do you know of any?

**Comment by bioinformed** [comment]
I have some pending fixes that will close a few issues.  Can we plan to release on Monday?

**Comment by AndreasHeger** [comment]
Certainly.
