### ISSUE TITLE
Support for csi indexed VCF/BCF files

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#591]
see #370

**Comment by AndreasHeger** [comment]
I think this functionality was already there. Added some tests to ensure this and allow tabix_index to create .csi indices.

**Comment by mikpom** [comment]
Dear pysam devs, 
sorry for bumping this old issue. 

It didn't give clarity whether I can use BCF with CSI index  and `fetch` ? I am getting 

`OSError: could not open index for ...`

when trying  instantiate `pysam.TabixFile` with BCF and CSI index.

Thanks,
Mikhail
