### ISSUE TITLE
Failing to install pysam 0.13

### ISSUE THREAD

**Issue by rtasakis** [pysam-developers/pysam#595]
Hi,
I keep on failing to install pysam 0.13 on MacOS High Sierra: 
**I tried pip installation** and I stepped over this: https://github.com/pysam-developers/pysam/issues/281
**I also tried python setup.py install** and - kinda summed up - I get this: 
htslib/htslib/hts.h:142:9: error: missing ',' between enumerators
    json HTS_DEPRECATED_ENUM("Use htsExactFormat 'htsget' instead") = htsget,
        ^
        , 
htslib/htslib/hts.h:142:29: error: expected '= constant-expression' or end of
      enumerator definition
    json HTS_DEPRECATED_ENUM("Use htsExactFormat 'htsget' instead") = htsget,
                            ^
2 errors generated.
error: command 'gcc' failed with exit status 1

Any ideas how to overcome this installation issue? 
Thanks in advance!

PS: gcc works fine in any other type of installations

**Comment by rtasakis** [comment]
Actually I solved it :P 
So the problem was the htslib... Solved with:
```
export HTSLIB_LIBRARY_DIR=/usr/local/lib
export HTSLIB_INCLUDE_DIR=/usr/local/include
pip install pysam
```

**Comment by AndreasHeger** [comment]
Thanks, closing this issue.

**Comment by jsmedmar** [comment]
Hello @AndreasHeger, wondering why mac users have to do:

```
export HTSLIB_LIBRARY_DIR=/usr/local/lib
export HTSLIB_INCLUDE_DIR=/usr/local/include
pip install pysam
```

Shouldn't that be part of the installation recipe? I had some trouble finding this solution ticket 😅

**Comment by jmarshall** [comment]
That error message would indicate that the compilation is picking up a _htslib/hts_defs.h_ file from an installation of an earlier version of HTSlib, one that does not have `HTS_DEPRECATED_ENUM`.

**Comment by j-funk** [comment]
you may also want to `brew install htslib` if the above is not working for you.
