### ISSUE TITLE
Import Error after clean pip install

### ISSUE THREAD

**Issue by guillermomarco** [pysam-developers/pysam#60]
Hello,

I'm getting the following error when trying to import pysam:

`import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/apps/local/python/lib/python2.7/site-packages/pysam/__init__.py", line 13, in <module>
    import pysam.csamtools as csamtools
ImportError: /share/apps/local/python/lib/python2.7/site-packages/pysam/csamtools.so: undefined symbol: regcompA`

PySam was installed with pip install on my machine, no errors so far. Any ideas? I've been googling without luck.

**Comment by AndreasHeger** [comment]
No more information, closing.

**Comment by guillermomarco** [comment]
Sorry for no answer, I was missing some SO libs. Thanks.

**Comment by batxes** [comment]
Could you tell me which SO libs are those? I have the same error, but only happens in one particular computer. Not in my laptop.
