### ISSUE TITLE
does not compile: "recompile with -fPIC"

### ISSUE THREAD

**Issue by jean-philippe-martin** [pysam-developers/pysam#600]
I'm trying to install pysam and it fails. I get the same error when trying with pip or from code freshly downloaded from the repository:

```
$ python setup.py install
(...)
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.a: error adding symbols: Bad value
```

The error message suggests a remedy. But where and how should I specify this "-fPIC" ?

**Comment by jean-philippe-martin** [comment]
Strange. Upgrading my version of `pip` allowed `pip install pysam` to work. I'm baffled, but glad I can make progress.

**Comment by AndreasHeger** [comment]
Thanks, glad this works now.
