### ISSUE TITLE
AlignmentFile.header attribute has changed type

### ISSUE THREAD

**Issue by marcelm** [pysam-developers/pysam#618]
I need to access read group information from the BAM/CRAM header.

This works in pysam 0.13.0:
```python
import pysam
af = pysam.AlignmentFile('pysam_data/ex3.bam')
print(af.header['RG'])
```
Using current master, I get:
```
TypeError: 'pysam.libcalignmentfile.AlignmentHeader' object is not subscriptable
```
The `header` attribute is documented as "two-level dictionay with header information from the file." It appears that an extra type has been introduced that replaces it. I thinkthis  is a good idea, but in its current form, this isn’t backwards compatible. I can use `.header.to_dict()['RG']`, but then it won’t work with pysam <= 0.13.

**Comment by AndreasHeger** [comment]
Hi @marcelm ,  indeed, header has changed - it is now its own class instead of a dictionary. The change was to improve consistency with the VariantFile/VariantHeader design. 

I agree though we should ensure as much backwards compatibility is possible, so will add a __getitem__ and __setitem__ method.

**Comment by marcelm** [comment]
I’m using `.get()` in my code, and I guess others may be using `.keys()` and `.items()` etc., so I don’t think just implementing `__setitem__`/`__getitem__` is enough. The safest route would be to have `.header` call the current `.header.to_dict()` internally and make the new `AlignmentHeader` available under a different name.

**Comment by AndreasHeger** [comment]
No worries, I will add most of the dict interface. 

I would like to keep the .header to be consistent with VariantFile.header.

**Comment by marcelm** [comment]
Thanks Andreas! :-)
