### ISSUE TITLE
preparing for pysam unittests fails in tests/pysam_data

### ISSUE THREAD

**Issue by nieder** [pysam-developers/pysam#622]
I'm updating to pysam-0.14 (yay it builds thanks to all the work from the earlier build problems on 0.13). I'm using the [Github tarball](https://github.com/pysam-developers/pysam/archive/v0.14.tar.gz).

When running the following to prepare the tests, I get this error in pysam_data:
~~~
make all -C tests/cbcf_data
make all -C tests/pysam_data
pytest-2.7 tests
~~~
This fails when Making inside pysam_data:
~~~
samtools faidx ex1.fa.gz
cp ex1.bam ex1_csi.bam
samtools index -c ex1_csi.bam
make: *** No rule to make target `example_reverse_complement.bam', needed by `all'.  Stop.
~~~

If I remove the attempt to create `example_reverse_complement.bam` in `tests/pysam_data/Makefile`, then the tests finish:
~~~
895 passed, 15 skipped, 1 warnings in 152.92 seconds
~~~

Is the `example_reverse_complement.bam` a leftover line from earlier tests?

**Comment by AndreasHegerGenomics** [comment]
Ah, sorry, yes, this is due to a half-baked test.
