### ISSUE TITLE
Add FILTER and set it in VariantRecord

### ISSUE THREAD

**Issue by dariober** [pysam-developers/pysam#628]
I'm trying to set the FILTER field of a `VariantRecord` but I can't find the way to do it.

With this

    vcf_in = pysam.VariantFile('my.vcf')
    vcf_in.header.filters.add('FAIL', None, None, 'Failed')

I open a VCF file and add a new filter. Then I would like to do this:

    for variant in vcf_in:
        variant.filter= 'FAIL'

which results in `attribute 'filter' of 'pysam.libcbcf.VariantRecord' objects is not writable`

This is with pysam 0.14

**Comment by mflevine** [comment]
It looks like you can add the filter to the record by doing:

```
for variant in vcf_in:
    variant.filter.add("FAIL")
```
