### ISSUE TITLE
When will pysam drop py27 support?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#644]
Many scientific packages are starting to commit to a py27 sunset timeline (https://python3statement.org/), so it might make sense for pysam to also begin such planning.

**Comment by kyleabeauchamp** [comment]
Oops, typo in original title.  Fixed :)

**Comment by jmarshall** [comment]
Pysam dropped Python 2.7 support in version 0.21.0, released in April 2023. 🎉
