### ISSUE TITLE
Support libdeflate?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#652]
The latest HTSLib (https://github.com/samtools/htslib/releases/tag/1.8) now supports libdeflate as an allegedly faster compression backend for BAM/CRAM.  

If it is indeed faster, it would be good to support on the pysam side of things.

**Comment by kyleabeauchamp** [comment]
FWIW, I have preliminary evidence (below) that libdeflate-based gzip is faster for both compression and decompression, so I think this might be worthwhile:

```
$ time gzip -c ~/dat/genomes/hg19/bwa_ref/hg19.bwa_mem.fa > out.fa.gz

real	8m17.887s
user	8m12.304s
sys	0m3.715s
$ time ./gzip -c ~/dat/genomes/hg19/bwa_ref/hg19.bwa_mem.fa > out2.fa.gz

real	1m38.979s
user	1m32.337s
sys	0m3.826s

$ time gunzip -c out2.fa.gz  > /dev/null 

real	0m8.089s
user	0m7.719s
sys	0m0.338s
$ time ./gunzip -c out2.fa.gz  > /dev/null 

real	0m6.580s
user	0m5.096s
sys	0m1.452s
```

**Comment by kyleabeauchamp** [comment]
FYI here is a PR for bioconda that enables libdeflate for HTSLib, samtools, and bcftools:

https://github.com/bioconda/bioconda-recipes/pull/8521

**Comment by jkbonfield** [comment]
It helps too if you compile libdeflate with native CPU support.  Right now I don't think it has the capability of building multiple variants and choosing on-the-fly the best for your current CPU.

It doesn't make much difference with CRAM though, as most compression there isn't gzip (ie deflate based).

**Comment by kyleabeauchamp** [comment]
For the Bioconda builds, I plan on using recent compilers and better optimizations in a future PR---there's some infrastructure work that needs to happen to enable that.  So things will be three steps: first libdeflate then compilers then optimizations.

**Comment by AndreasHeger** [comment]
Thanks, @kyleabeauchamp . Is it necessary for pysam to be libdeflate aware? I think there are three installation modes in order of preference:

1. conda -> preferred installation method and for most users, whether or not libdeflate is enabled depends on the htslib conda recipe.

2. setup.py/pypi with external htslib -> for power users, and  up to user to configure htslib to their wishes

3. setup.py/pip install pysam with internal htslib -> for non-power users which have limited experience in compiling software. Here I would prefer to keep a conservative configuration that compiles on most systems to reduce the compilation issues that users run into.

Hope I get time to update to htslib 1.8 soon.

**Comment by kyleabeauchamp** [comment]
I _think_ (1) should be fine.  Once we have an HTSLib18 branch, I can start testing whether the pysam build chain is properly linking to libdeflate.

**Comment by kyleabeauchamp** [comment]
I *appear* to have a working bioconda PR for HTS18 + pysam15 + libdeflate (https://github.com/bioconda/bioconda-recipes/pull/8562).  It is based off of my PR #660.  So hopefully things will just "work" once we finish the HTS18 upgrade.

**Comment by kyleabeauchamp** [comment]
I've revisited testing a bioconda build for pysam 0.15 with libdeflate enabled: https://github.com/bioconda/bioconda-recipes/pull/10044

I'll also try to test the same build locally to see if I can confirm correct linkage to libdeflate.

**Comment by kyleabeauchamp** [comment]
OK, it looks like that PR is successfully building a lib-deflate linked version of pysam, and I can confirm that (libdeflate+pysam0.15) is about twice as fast as pysam 0.14.1 when walking over each read in a bam.

**Comment by kyleabeauchamp** [comment]
This issue is resolved.  The latest bioconda package (pysam 0.15.0) now links to libdeflate.
