### ISSUE TITLE
Does linking work for SAMtools/BCFtools?

### ISSUE THREAD

**Issue by garrett-stevens** [pysam-developers/pysam#653]
Hello there,

I have a question about how the HTSlib/SAMtools/BCFtools code is used in pysam. From what I understand, pysam contains a copy of all the necessary code for those three tools, and that you can also build against an external already-installed copy of HTSlib. My question is, then, is it possible to use an external SAMtools or BCFtools? Maybe that doesn't even make sense since SAMtools and BCFtools are command-line tools while HTSlib is a library, so sorry if that's the case, I'm just trying to figure out how this all fits together.

Thanks for your time and for a great tool.

**Comment by AndreasHeger** [comment]
Sorry, samtools and bcftools are binary tools and do not offer a shared library to link against, as opposed to htslib, which is a library only.
Pysam does some code acrobatics to export some of the command line interfaces for samtools and bcftools. Using an external samtools/bcftools command via python subprocess should in most cases be equally fast, unless you need to call a particular command thousands of times. 
The pysam samtools/bcftools functionality remains for backwards compatibility.

**Comment by garrett-stevens** [comment]
Got it, I wondered if something like that was happening. Thanks for helping me understand!
