### ISSUE TITLE
PyCharm and Mypy cannot find pysam classes

### ISSUE THREAD

**Issue by nh13** [pysam-developers/pysam#654]
I am using PyCharm for development and mypy for static type checking, and unfortunately they are not able to find the some of the core pysam classes, for example `pysam.AlignmentFile`:

```
class SamFile(pysam.AlignmentFile):
    pass
```

Trying to figure out why, I found that `__al_l_` is not only defined in `pysam.__init__.py`, but that `__all__` imports the classes to make public from each of the `libc*` files, for example `libcalignmentfile.__all__`.  I believe that `libcalignmentfile.pyx`, where `libcalignmentfile.__all__` is defined, gets compiled to C, and so the IDE cannot find the definition.  Perhaps I am missing something (I often do).

It would really help developers who use pysam to be able to use PyCharm and mypy with pysam.  Thanks for any help you can offer in advance.

**Comment by AndreasHeger** [comment]
Sorry, not using PyCharm and mypy. The class definitions are in .pyx file (cython) - are these IDE's aware of these? It might be that they only look for .py files.

**Comment by AndreasHeger** [comment]
Closing for now, unless anyone has anyone has a suggestion.

**Comment by kevinjacobs-progenity** [comment]
I don't have much time lately, but I've been working on adding type hint stubs for pysam.  I don't have an ETA when this will be ready, but I'll re-open this when I need testers.
