### ISSUE TITLE
Submodule?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#657]
Random question: have we ever considered adding HTSLib as a git submodule versus plaintext vendoring?  I understand that there many cons to submodule, but I personally have difficulty understanding "which things are vanilla HTSLib" and "which things are pysam-specific".  

I suppose there are lots of other ways to streamline the HTSLib upgrade process as well.  I'm mostly just curious to brainstorm etc, as currently I find the upgrade process somewhat opaque...

**Comment by kyleabeauchamp** [comment]
I'm particular, I should stress that I'm *not* advocating that we use submodule, but more broadly come up with ways to streamline the HTSLib upgrade process...

**Comment by AndreasHeger** [comment]
Hi @kyleabeauchamp , the upgrading is fairly automatic, see the import.py script. What takes longer is - depending on what the upgrade contains, implementing any new features that htslib provides.

**Comment by AndreasHeger** [comment]
htslib is added as is, samtools and bcftools are heavily modified.

**Comment by kyleabeauchamp** [comment]
Thanks, `import.py` was the missing step that I didn't know about.
