### ISSUE TITLE
pileupcolumn.nsegments does not equal len(pileup_column.get_query_names())

### ISSUE THREAD

**Issue by pkMyt1** [pysam-developers/pysam#663]
If I run
samtools depth -m 1000000 -r chr3:128481829-128481831 17002_GATAGACA_dedup_sorted.bam
chr3	128481829	18344
chr3	128481830	16330
chr3	128481831	22078
I get the same results as pileupcolumn.nsegments run with 
qbam.pileup(region=chr3:128481829-128481831, truncate=True, max_depth=10000000).  However len(pileup_column.get_query_names()) reports 11117 instead of 16330 for example.  When I iterate all bases in this column I also only get 11117.  Any idea where my missing 5000 nucleotides are?

**Comment by pkMyt1** [comment]
This is not a pysam issue.  Something I don't understand about the depth calls.  Samtools mpilup results in the same 11117 that pysam does.

**Comment by Huanle** [comment]
@pkMyt1 , so have you finally figured this out?

**Comment by woodword** [comment]
try add "ignore_overlaps= False" option in qbam.pileup()
