### ISSUE TITLE
TLEN vs query_alignment_length

### ISSUE THREAD

**Issue by betteridiot** [pysam-developers/pysam#667]
Just wondering if there was something in the BAM format that suggests if you should return the read length when there is no paired read and TLEN == 0?

Example:
`samtools`
```bash
samtools view SRR1585557_sort_resort.bam chr10:138870-138900
$ SRR1585557.11734192     16      chr10   138872  25      21M     *       0       0       GAGTTGATGGTCTAGCGATTG   `RRJ^[bZeb[_Q``Q\Sc_^   XT:A:U  NM:i:2  X0:i:1  X1:i:0  XM:i:2  XO:i:0      XG:i:0  MD:Z:11G4C4
```
`pysam`
```python
import pysam
b = pysam.AlignmentFile('SRR1585557_sort_resort.bam' ,'rb')
print(next(b.fetch('chr10',138870-138900)))
>>>SRR1585557.11734192	16	0	138871	25	21M	-1	-1	21	GAGTTGATGGTCTAGCGATTG	array('B', [63, 49, 49, 41, 61, 58, 65, 57, 68, 65, 58, 62, 48, 63, 63, 48, 59, 50, 66, 62, 61])	[('XT', 'U'), ('NM', 2), ('X0', 1), ('X1', 0), ('XM', 2), ('XO', 0), ('XG', 0), ('MD', '11G4C4')]
```

I know that samtools is doing something with regard to RNEXT and PNEXT, I was just wondering why Pysam reports the seq length and not 0. 

**Note:**  I know that this 0 for TLEN is stored in the AlignedSegment object as `.template_length`

P.S. this post is out of curiosity because of my own project, and not meant to be contentious.

**Comment by jkbonfield** [comment]
*Shudder* 

From a SAM perspective, I tried to rationalise TLEN at one point and it was like repeatedly hitting myself around a head with a cricket bat - both clumsy to manage without outside help and also uncomfortable!

My own conclusion is TLEN is so broken and ill defined (well actually it's tightly defined, but most implementations have completely different and incompatible definitions) plus no one actually seemed to care, that it's best off treating it as implementation specific.  Don't make any assumptions on the contents.

Anyway, the SAM spec itself clearly states that it is zero for the single-template case.

**Comment by AndreasHeger** [comment]
Thanks @betteridiot  for the question and @jkbonfield  for giving context
I have on insight myself - closing this issue for now.
