### ISSUE TITLE
Possible query alignment length bug?

### ISSUE THREAD

**Issue by vsbuffalo** [pysam-developers/pysam#67]
It's very possible that I've missed something strange about this alignment, but at first glance this appears to be a bug because since query_alignment_length is supposed to be qend - qstart (according to the [documentation](http://pysam.readthedocs.org/en/latest/api.html#pysam.AlignedSegment.query_alignment_length)), and it's not:

    >>> import pysam
    >>> bf = pysam.AlignmentFile('example.sam')
    >>> read = bf.next()
    >>> read.query_length
    51
    >>> read.query_alignment_length
    51
    >>> read.query_alignment_start
    0
    >>> read.query_alignment_end
    35
    >>> len(read.query_alignment_sequence)
    35

`example.sam` can be retrieved for reproducibility from: https://gist.githubusercontent.com/vsbuffalo/94be7da4654d2af37c06/raw/c28fd61b34cd1ab811a8b3c1580c70887e685d1a/example.sam (it's a single read from 1KG data).

    >>> pysam.__version__
    '0.8.1'

Installed via pip.

**Comment by AndreasHeger** [comment]
Thanks, this has been fixed by bfd56dcd6557dd62609cf101226198c07bc11218
