### ISSUE TITLE
[docs] Mismatching pileup documentation?

### ISSUE THREAD

**Issue by SamStudio8** [pysam-developers/pysam#671]
Hi `pysam`,
I discovered today that by default, `pysam` appears to suppress overlapping mate pairs in a `pileup`, but couldn't seem to find anything in the relevant [online documentation](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.pileup) regarding this.

A little search against the source led me to [these lines](https://github.com/pysam-developers/pysam/blob/master/pysam/libcalignmentfile.pyx#L1253), which seem to give much more information regarding your pileup API than is presented online, including the `ignore_overlaps` option.

Is this intentional? i.e. Is `ignore_overlaps` internal and not necessarily intended to be exposed to `AlignmentFile.pileup`? Or is the documentation out-of-sync?

Thanks!

**Comment by AndreasHeger** [comment]
Thanks, I have updated the docs. I was under the impression this happens automagically, but apparently not.
