### ISSUE TITLE
bcftools sort

### ISSUE THREAD

**Issue by thomasfaraut** [pysam-developers/pysam#674]
Hi pysam developpers,

We have been using pysam with great success to handle both bam files and vcf/bcf files.

The tabix_index provides a useful interface for the tabix index command line, 
but the content of the file must be sorted by contig and position. 
Is it planned to add an interface to the bcftools sort command (just like pysam.sort for 
bam files), preventing from having to sort the file through a call to the bcftools sort 
command or to load the file and sort it in python ?

Thanks in advance for your answer,
Thomas Faraut

**Comment by AndreasHeger** [comment]
Thanks, will look into this.

**Comment by jmarshall** [comment]
Since 0.16, `pysam.bcftools.sort('-o', outfname, infname, catch_stdout=False)` provides access to bcftools's sort subcommand.
