### ISSUE TITLE
Coverage and number of bases at position differs in pileup

### ISSUE THREAD

**Issue by MarcSaric** [pysam-developers/pysam#676]
Hi,

I tried using pysam to extract bases from an NGS dataset for a list of SNP positions.

Alignment of the reads was against hg19. Data is in bam format. If I open the bam file in IGV, it shows me 124 reads for a given position and a 65:35% distribution for G and A.

If I open the same bam file with pysam and run the following code for the same position (-1-corrected), it also reports 124 reads, but only 98 bases. There are no Ns or (apparently) low quality reads

```
# Get the first entry of the SNP list for testing purposes 
first_snp = lst_of_snps[0]
chrom = "chr" + first_snp["Chromosome"]
pos = int(first_snp["Position (Hg19)"])-1 # Correct for zero based counting
start = int(first_snp["Position (Hg19)"])-50 
end = int(first_snp["Position (Hg19)"])+50 

print("Extracting from", chrom, "on position", pos, "from start", start, "to end", end)

G = 0
A = 0
T = 0
C = 0
something = []

for pileupcolumn in samfile_blood_normal.pileup(chrom, start, end):
    if pileupcolumn.pos == pos:
        print("\ncoverage at base {0} = {1}".format(pileupcolumn.pos,
                                                    pileupcolumn.n))
        for pileupread in pileupcolumn.pileups:
            thebase = pileupread.alignment.query_sequence[pileupread.query_position]
                if thebase == "A":
                    A+=1
                elif thebase == "G":
                    G+=1
                elif thebase == "C":
                    C+=1
                elif thebase == "T":
                    T+=1
                else:
                    something.append(pileupread.alignment.query_sequence[pileupread.query_position])
print( G+A+C+T, G, A, T, C, something)

```

This returns

Extracting from chr1 on position 179520505 from start 179520456 to end 179520556

coverage at base 179520505 = 124
98 55 43 0 0 []

**Comment by alimanfoo** [comment]
I'm not a pysam dev but FWIW we have noticed some changes recently to how ``pileup()`` filters reads, which can cause a discrepancy between the value of pileupcolumn.n and the number of reads you get when iterating over the pileupcolumn. In particular it may be due to values of parameters ``min_base_quality``, ``stepper``, ``flag_filter``, ``min_mapping_quality`` or ``ignore_overlaps``. I would guess particularly ``min_base_quality`` which defaults now to 17, you could try setting this to 0.

xref https://github.com/alimanfoo/pysamstats/pull/77

**Comment by MarcSaric** [comment]
@alimanfoo :+1: Thank you for the hint. There are way to many switches and options to take care of. Works as expected, if you enable the min_base_quality filter as suggested.
