### ISSUE TITLE
pysam.view() outputs to stdout even if -o is given

### ISSUE THREAD

**Issue by haowenz** [pysam-developers/pysam#677]
Hi,

pysam.view() outputs to stdout even if -o is given. Just tested it with my own data using the command as follows. 

`pysam.view("-o", "xxx.bam", "xxx.sam")`

Please fix it. Thanks.

**Comment by AndreasHeger** [comment]
ok, will check

**Comment by yhoogstrate** [comment]
Hi there, I've found a workaround for the time being:

```
# first 'touch' the output file, so that the `c_open` function can open it
fh = open(output_bam_file, 'w')
fh.close()

# second, use the hidden save_stdout command (to write to file) and add '-o' to avoid duplicate writing to stdout
pysam.view('-o', output_bam_file, '-b', sam_file, save_stdout=output_bam_file)

```
I hope it helps.

Youri

**Comment by MatteoSchiavinato** [comment]
Any update on this one? I am struggling with the same thing. I do open the file as @yhoogstrate suggested, and close it afterwards so it's just "touched", but nothing, I still get the view output in my python console. 

```
infile = "test.bam" 
outfile = "test.f.bam"
open(outfile, "w").close()
pysam.view("-F", "0x0100", "-F", "0x4", "-b", "-h", "-o", outfile, infile)
```

**Comment by yhoogstrate** [comment]
did you set the `save_stdout=outfile` within `pysam.view` ?

**Comment by MatteoSchiavinato** [comment]
That's how I sorted it out.  However, since I set an outfile with `-o`, I was not expecting this to happen.

**Comment by bakerwm** [comment]
you can try this option: `catch_stdout=False` @MatteoSchiavinato 

```
pysam.view('-F', '0x4', '-b', '-h', '-o', outbam, inbam, catch_stdout=False)
```

**Comment by aretchless** [comment]
It may help to put this work-around in the examples provided in the [usage guide](https://pysam.readthedocs.io/en/latest/usage.html#using-samtools-commands-within-python): 

> For example:
> 
> pysam.sort("-o", "output.bam", "ex1.bam")
> corresponds to the command line:
> 
> samtools sort -o output.bam ex1.bam

**Comment by jmarshall** [comment]
Pre-“touching” the output file will no longer be necessary in the next pysam release. However some subcommands e.g. `view` remain a little too familiar with the underlying `-o` option and may require further changes.
