### ISSUE TITLE
Pysam not displaying certain reference bases from .get_aligned_pairs 

### ISSUE THREAD

**Issue by jdparker101** [pysam-developers/pysam#683]
I have a number of bam files which I have subsetted for reads originating from the mitochondrial chromosome and am running them through some code which detects mismatches in RNA-seq reads in terms of their alignment to the genome. However, when I pull the contents of a read using .get_aligned_pairs(with_seq=True), on some bases the third component of the aligned_pairs (corresponding to the identity of the base in the reference sequence and what with_seq=True pulls back) appears as a very strange character. 

In the example below, the "problem" base is occurring at a position where there is a mismatch:

This is the output of .get_aligned_pairs (subsetted for convenience), the error causing base is at index position 14 (in bold):
[(0, 3229, 'G'), (1, 3230, 'T'), (2, 3231, 'T'), (3, 3232, 'A'), (4, 3233, 'A'), (5, 3234, 'G'), (6, 3235, 'A'), (7, 3236, 'T'), (8, 3237, 'G'), (9, 3238, 'G'), (10, 3239, 'C'), (11, 3240, 'A'), (12, 3241, 'G'), (13, 3242, 'A'), **(14, 3243, '\x87')**, (15, 3244, 'C'), (16, 3245, 'C'), (17, 3246, 'C'), (18, 3247, 'G'), (19, 3248, 'G'), (20, 3249, 'T')

However, the base in the read looks to be normal (in bold) and the MD tag looks normal, representing a C to G mismatch, and indeed according to my code the position at this base in the reference genome is a G based on the fasta file I am using, and looking at this position in a genome browser corroborates this:

ST-E00192:575:HFJWHCCXY:8:2110:18933:43220	163	chrM	3230	255	150M	=	3347	267	GTTAAGATGGCAGA**C**CCCGGTAATCGCATAAAACTTAAAACTTTACAGTCAGAGGTTCAATTCCTCTTCTTAACAACATACCCATGGCCAACCTCCTACTCCTCATTGTACCCATTCTAATCGCAATGGCATTCCTAATGCTTACCGAAC	AAFFFJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJ<FJJJJJJJJJJJJJJJJJJJJJJJJ<JJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJ	NH:i:1	HI:i:1	AS:i:296	nM:i:1	NM:i:1	MD:Z:14g135

**Comment by AndreasHeger** [comment]
Thanks, I will investigate.

**Comment by AndreasHeger** [comment]
Hi, the issue is the lower-case g in the MD-tag, only the following characters are allowed according to the SAM spec:


MD:Z:
[0-9]+(([A-Z]|\^[A-Z]+)[0-9]+)*
String for mismatching positions.
```

**Comment by AndreasHeger** [comment]
Not sure how often this occurs in the wild. I will add an error to pysam.
