### ISSUE TITLE
Error in parsing while using bcftools

### ISSUE THREAD

**Issue by vivekruhela** [pysam-developers/pysam#689]
I am trying to convert tsv to vcf using bcftools convert utility but I am getting an error of parsing. Here is the command I am using for conversion:

`./bcftools convert --tsv2vcf /mnt/storage/Vivek/MM_Data/SM_5_WES/Variant-Calling/SM_5_filtered.tsv --fasta-ref /mnt/storage/Vivek/refs/ucsc.hg19.fasta --samples SM_5`

and here is the error I am getting:
`Error parsing the site chr1:68374, expected two characters`

Can anyone suggest me how to remove this error. 
Thanks.

**Comment by AndreasHeger** [comment]
Sorry, very likely this is the input. Have you managed to resolve it?
You mgiht also want to ask at the bcftools project.
