### ISSUE TITLE
Rename pysam.Fastqfile to pysam.Fastxfile (or something else)

### ISSUE THREAD

**Issue by brwnj** [pysam-developers/pysam#69]
kseq.h is providing iteration for both file types, or even mixed for that matter, so users should know that they can use this class for fastx file iteration.

The test sequence file (test.seq) delivered with kseq.h (http://lh3lh3.users.sourceforge.net/kseq.shtml):
```
>1
acgtacgtacgtagc
>2 test
acgatcgatc
@3 test2
cgctagcatagc
cgatatgactta
+
78wo82usd980
d88fau

238ud8
```

Output:
```
In [1]: import pysam

In [2]: pysam.__version__
Out[2]: '0.8.1'

In [3]: for record in pysam.FastqFile("test.seq"):
    print record.name, record.sequence, record.comment, record.quality
   ...:     
1 acgtacgtacgtagc None None
2 acgatcgatc test None
3 cgctagcatagccgatatgactta test2 78wo82usd980d88fau238ud8
```

**Comment by AndreasHeger** [comment]
Thank you for the suggestion, I will change this.

Best wishes,
Andreas
