### ISSUE TITLE
find_introns function reported an UnboundLocalError

### ISSUE THREAD

**Issue by Krascal** [pysam-developers/pysam#695]
When I used the find_introns function to get the intron region in an expected region, it reported UnboundLocalError: local variable 'start' referenced before assignment.
The instruction I used and the reported error are as below:

>>> a=samfile.find_introns(read for read in samfile.fetch(region = "chr2:200334618-200341658"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/libcalignmentfile.pyx", line 1266, in pysam.libcalignmentfile.AlignmentFile.find_introns
UnboundLocalError: local variable 'start' referenced before assignment

If I changed the regions, some regions didn't report this error. I don't know why, can anyone help me?

**Comment by wckdouglas** [comment]
can you provide the version of pysam that you are using?

[line 1266](https://github.com/pysam-developers/pysam/blob/master/pysam/libcalignmentfile.pyx#L1266) doesn't seem to contain the variable ```start``` in the current version.

And the current [find_introns function](https://github.com/pysam-developers/pysam/blob/master/pysam/libcalignmentfile.pyx#L1626) doesn't contain the variable ```start```, so I am guessing an update for pysam may fix it.

**Comment by Krascal** [comment]
Hi Douglas, thanks your for your suggestions. The version of pysam I used is 0.12.0.1.  I updated the pysam packages, and found that the bugs have been fixed. Many thanks!
