### ISSUE TITLE
No header is written when create a new sam file

### ISSUE THREAD

**Issue by MPez** [pysam-developers/pysam#70]
Using pysam.AlignmentFile("foo.sam", "w", template=samfile) no header is written on the new sam file created.
Instead using pysam.AlignmentFile("boo.bam", wb" , template=samfile) the header is correctly written.
Even if I use different arguments like 'header' or 'referencename' and 'referencelengths' to create the sam file I get the same problem.

**Comment by AndreasHeger** [comment]
Please use "wh" as file mode to output the header.

Best wishes
