### ISSUE TITLE
get_aligned_pairs with multiple alignments in samfile

### ISSUE THREAD

**Issue by npavlovikj** [pysam-developers/pysam#702]
Hi,

I have a function where I pass a **samfile**, **start and end reference position**, and extract some information for the alignments that are in that region.
As part of my code I have:
_...
    for read in samfile.fetch(until_eof=False):
        if read.reference_id == -1:
            sys.exit()
        else:
            ref_start = int(read.reference_start)
            ref_end = int(read.reference_end)
            pairs = read.get_aligned_pairs(with_seq=True)
..._
The samfile has multiple alignments.
However, in my case, the variable "**pairs**" has value only for the first alignment.
For the second alignment, I get the following error for the variable "**pairs**" (the values of "_ref_start_" and "_ref_end_" are printed fine though):
_File "pysam/libcalignedsegment.pyx", line 1888, in pysam.libcalignedsegment.AlignedSegment.get_aligned_pairs
File "pysam/libcalignedsegment.pyx", line 855, in pysam.libcalignedsegment.build_reference_sequence
File "pysam/libcalignedsegment.pyx", line 729, in pysam.libcalignedsegment.build_alignment_sequence
TypeError: expected bytes, NoneType found_

I believe I am missing something crucial in fetching multiple alignments, so I would appreciate your help with it.

Thank you,
Natasha

**Comment by AndreasHeger** [comment]
Thank you. Is it possible that there is no read sequence in your BAM file?

get_aligned_pairs does require better error handling.

**Comment by npavlovikj** [comment]
Thanks @AndreasHeger !

I don't use "bam" files, but only "sam", and the file has multiple alignments.
Here is a part of it, named "test.sam":
`@SQ     SN:U00096.3     LN:4641652
@PG     ID:minimap2     PN:minimap2     VN:2.10-r761    CL:minimap2 -t 1 -ax map-ont --MD ecoli_K12_MG1655.fasta 1397.fasta
U00096.3_1299657_aligned_18117_R_78_543_4       0       U00096.3        3652529 0       69M2D5M1D19M1D6M2D7M2I3M4D2M1D3M1D42M1I25M1D9M2D13M2D9M1I22M3D2M3D50M1D4M3D29M1D
25M1D6M3D5M2D1M1D4M5D14M1D37M1I13M1D6M5I15M1D2M2D9M1D10M1D12M2D16M      *       0       0       CATGCAGCAGTTTAACCTCCTGATTGAGGTCATGCTCGTTGGCCGCGAACGTGACCAGGCTGTGGGTCACCC
CTATGGCATCGACACCAATGTGGCCTTTGCCCAACTATGTGTTGCTTTCTTGGTCTGATGCATCTCCGAGTCGCGTTGCTGTTCTTCTGTTCTTGGTCGAGCTGGCTGACTCATCCTGGTGACCGACCAAGGTGTTGAGTCATACATGACGCCTGCTTCGGCTAGCCG
GATGGTCTTGAAAAATTGGCGGGCCAGTTGATGCTGCTCCAGCAGGTGTCGAAAATGATGGTATTGCCATCCGGCAAGGCGCTTCCAGGGATAACCGGGCAAACAGACCATGGAGATTTTCGGATTCCATCGCGCCATGCTCAGGTTGTACCAATGCTGCATGCAGTG
AATGCGTGAGGATGGTTTCCACGGATATTGTCAGGTCGCCGGCCATTCCCCTTGGTGTAAACGGCTCGTTTCTTACACCATTTTGCCATGGCAGAA        *       NM:i:91 ms:i:550        AS:i:550        nn:i:0  tp:A:P
cm:i:8  s1:i:66 s2:i:66 dv:f:0.1248     MD:Z:10A3C2A0G28G0T0G19^GG2A2^C0T18^G6^CA4A2G2^CCAC2^A3^C24G0A11C22G2C3^A2G0A5^GC1T11^CC27C3^CAG2^ATT12C35G1^G4^TTC8G0G3G0G14^A2
5^G6^GGC5^CG1^A1A2^GCATC14^C39C10^G21^A2^AG6G2^A10^A1G0A3C5^TG16
U00096.3_1299657_aligned_18117_R_78_543_4       272     U00096.3        1299658 0       15M2D10M1D10M1D12M2D2M1D15M5I6M1D13M1I37M1D14M5D2M4D2M1I4M3D7M1D25M1D29M3D3M1D51
M5D1M1D23M1I9M2D11M2D10M1D26M1I41M1D4M1D2M1I2M3D9M2D4M1D19M1D7M2D69M    *       0       0       *       *       NM:i:91 ms:i:550        AS:i:550        nn:i:0  tp:A:S
cm:i:8  s1:i:66 dv:f:0.1248     MD:Z:15^AC6G3^T0C1T7^T5C6^CT2^T21^C10G39^G14^GATGC2^TGTA6^CGC7^C25^T14C0C3C0C8^GAA3^C2C35G12^AATCG1^T4G27^GG11^AT1C5T0C1^T4G2C22G11T0C23
^G4^T2G1^GGC1C2T4^TG4^C19^A1G2T2^CC19C0A0C28C0T2G3T10`

If I run:
`test=test.sam
samfile = pysam.AlignmentFile(test, check_sq=False)
for read in samfile.fetch(until_eof=False):
    print(read.get_aligned_pairs(with_seq=True))`
on "test.sam", I get the error I mentioned earlier.

Again, this happens only when the "sam" file has multiple alignments - everything works fine with a single alignment.

Thank you,
Natasha

**Comment by npavlovikj** [comment]
Yes, you are correct - the alignment I have issue with does not indeed have the read sequence. Thanks for pointing this out @AndreasHeger  - I will check with the author of the tool I used.
