### ISSUE TITLE
difference between pileups and nsegments

### ISSUE THREAD

**Issue by lituan** [pysam-developers/pysam#703]
Hi, I use pysam to get reads aligned to a certain base,  the code is as following:

import pysam 
samfile = pysam.AlignmentFile(test.bam)
for pileup_column in samfile.pileup(region='1:115256530-115256530', max_depth=200000):
      print(pileup_column.nsegments)
      print(len(pileup_column.pileups)

the result is nsegments is 11948 but len(pileups) is 5981, so  I wonder why reads are missing in pileups

**Comment by AndreasHeger** [comment]
Hi, n_segments ignores any base-quality filters that mgiht be applied. Would this explain your discrepancy?

**Comment by lituan** [comment]
Hi, my reads is PE reads with long overlap, it seems that pileup mainly output PE1 reads but ignore most PE2 reads,  and the following attachment is the bam I used
[pysam_pileup_question.zip](https://github.com/pysam-developers/pysam/files/2239457/pysam_pileup_question.zip)

**Comment by lituan** [comment]
Hi,
after set ignore_overlaps=False, no reads is missed.
