### ISSUE TITLE
ValueError: unknown field code 'PM' in record 'RG'

### ISSUE THREAD

**Issue by cc2qe** [pysam-developers/pysam#71]
Thanks for maintaining this great piece of software Andreas.

I get an error with this example script and SAM file below. It appears that my BAM uses an unrecognized tag in the header. I realize that "PM" is not in the SAM spec, but is it possible to make pysam more lenient instead of crashing? In general I do not expect pysam to validate my BAM files, and this is also a TCGA file downloaded from CGHub.

```
$ ./parse_rg.py
Traceback (most recent call last):
  File "./parse_rg.py", line 7, in <module>
    for tag in bam.header['RG']:
  File "csamfile.pyx", line 1052, in pysam.csamfile.Samfile.header.__get__ (pysam/csamfile.c:12899)
ValueError: unknown field code 'PM' in record 'RG'
```

parse_rg.py:
```python
#!/usr/bin/env python

import pysam

bam = pysam.Samfile("example.sam", 'r')

for tag in bam.header['RG']:
    print tag
bam.close()
```

example.sam:
```
@HD   VN:1.5  SO:coordinate
@SQ   SN:1    LN:249250621
@SQ   SN:2    LN:243199373
@SQ   SN:3    LN:198022430
@RG   ID:BCM:0    PL:ILLUMINA CN:BCM  DT:2012-08-24T21:00:00Z LB:WGS:BCM:IWG_THNSCG.CV-7090-10AN_1pA  PM:Illumina HiSeq 2000  SM:mysample PU:BCM:120807_SN601_0319_BC10LPACXX_8
@RG   ID:BCM:0_1  PL:ILLUMINA CN:BCM  DT:2012-12-08T10:00:00Z LB:WGS:BCM:IWG_THNSCG.CV-7090-10AN_1pA  PM:Illumina HiSeq 2000  SM:mysample PU:BCM:121117_SN898_0330_BD1DYHACXX_7_ID05
@RG   ID:BCM:0_1_1    PL:ILLUMINA CN:BCM  DT:2012-09-04T19:00:00Z LB:WGS:BCM:IWG_THNSCG.CV-7090-10AN_1pA  PM:Illumina HiSeq 2000  SM:mysample PU:BCM:120822_SN580_0246_AC119AACXX_8
@RG   ID:BCM:0_2  PL:ILLUMINA CN:BCM  DT:2012-09-04T20:00:00Z LB:WGS:BCM:IWG_THNSCG.CV-7090-10AN_1pA  PM:Illumina HiSeq 2000  SM:mysample PU:BCM:120822_SN580_0246_AC119AACXX_7
```

Thanks,
Colby

**Comment by cc2qe** [comment]
Oh, also this was with pysam 0.8.0 so it is not the latest version, and I wasn't able to test whether 0.8.1 also has this behavior

**Comment by cc2qe** [comment]
Found a way to bypass this behavior via manually parsing the header with [pysam.AlignmentFile.text](http://pysam.readthedocs.org/en/latest/api.html#pysam.AlignmentFile.text). all is well

**Comment by AndreasHeger** [comment]
Many thanks, and thanks to @MurphyMarkW this now fixed in principle!

**Comment by natechols** [comment]
Are you certain this is fixed in practice?  When I try passing a header containing PM in the read group to pysam.AlignmentFile (0.9.0), it gets stripped out (without any warning).  I noticed it's not listed here:

https://github.com/natechols/pysam/blob/master/samtools/sam_header.c#L65

but I don't know enough about the code base to tell if that's related.
