### ISSUE TITLE
Segmentation violation when writing using a dict header

### ISSUE THREAD

**Issue by terrycojones** [pysam-developers/pysam#716]
I ran into a problem with an occasional segmentation violation when passing a `dict` header when writing a SAM file. I narrowed it down to the following:

```python
#!/usr/bin/env python

from pysam import AlignmentFile

header = {
    'SQ': [{'SN': 'NT_166394.1', 'LN': 191521}],
    'PG': [{'ID': 'bwa', 'PN': 'bwa', 'VN': '0.7.15', 'CL': 'bwa mem xx -'}],
}

sam = AlignmentFile('in.sam')
out = AlignmentFile('out.sam', mode='w', header=header)

for alignment in sam.fetch():
    out.write(alignment)

sam.close()
out.close()
```

Put the following into `in.sam` and run the above script:

```
@SQ	SN:NT_039593.1	LN:100803
@SQ	SN:NT_166394.1	LN:191521
@PG	ID:bwa	PN:bwa	VN:0.7.15	CL:bwa mem mouse -
query	0	NT_166394.1	156606	0	5M	*	0	0	CGCTC	A330A
```

I get a segmentation fault under both
* OS X (10.13.5) with pysam 0.15.0 and Python 3.6.2
* Scientific Linux 7.4 (Nitrogen) with pysam 0.14.1 and Python 3.6.5

I narrowed this down from an input file that had many more (240) @SQ headers, in which case the segmentation fault occasionally did not occur. 

If you swap the order of the @SQ lines in the above input file, the segmentation fault does not occur.

In earlier tests (with more headers) when the segmentation fault did not occur, the SAM output was not correct. The reference sequence name (field 3) in the output would sometimes be all digits, sometimes contain unprintable (non-UTF8, I guess) characters.

There's probably no need to add that this looks like a memory corruption issue.  I've not gone to look at the pysam code.

Let me know if I can help in any way.

**Comment by terrycojones** [comment]
Could the error be here https://github.com/pysam-developers/pysam/blob/master/pysam/libcalignmentfile.pyx#L239 ?

Maybe that line:

```c
memcpy(self.ptr.text, ctext, l_text + 1)
```

should be

```c
memcpy(self.ptr.text, ctext, l_text)
self.ptr.text[l_text] = NULL
```

I'm not sure if I have the syntax right, but what I'm doing should be obvious.

This might correspond to the SEGV not happening when the reference name is not the last in the file.

**Comment by terrycojones** [comment]
Hello?

**Comment by AndreasHeger** [comment]
Thanks for reporting this, I will check

**Comment by terrycojones** [comment]
Thanks @AndreasHeger

**Comment by AndreasHeger** [comment]
Thanks for the great test case, I can reproduce it.

**Comment by AndreasHeger** [comment]
which is when the chromosome is written:
```
kputs(h->target_name[c->tid] , str)
```

**Comment by terrycojones** [comment]
Thanks for digging into this. I was being a bit lazy at the time, and also wanted to see if the suggested fix (just from eyeballing the code) could be right. I've done only a little with C extensions, so am happy you're onto it. I guess that string is somehow not terminated, but I'm sure you know that :-) Thanks again.

**Comment by AndreasHeger** [comment]
Ahh, I see. The underlying issue is that the header supplied and the header in the SAM-file do not match.

While 
```
'SQ': [{'SN': 'NT_166394.1', 'LN': 191521}],
```
will produce header mapping where tid=0 => NT_166394.1, the SAM file has a header where the mapping is tid=0 => NT_039593.1, tid=1 => NT_166394.1. When writing, sam_write1 tries to access tid==1, which does not exist.
The fundamental issue is that AlignmentRecords do not record the chromosome,, but only the entry in the sequence translation table. When moving from one file to another it is important that the sequence translation table in the remains the same. Not sure there is a good solution, but will add a check so that at least it fails with an error and not a segfault.

**Comment by terrycojones** [comment]
OK, I think I follow that.  The reason I was trying this was because I am filtering a SAM file to only have certain matches in it and I wanted to create a header that also only had @SQ lines for the sequences that are named in the alignments.

I guess a solution would be to look through the two headers and create a tid-to-tid mapping of the common sequence names.  And still to give an error not a segfault if a too-big index was later encountered.

**Comment by AndreasHeger** [comment]
Unless there are very many sequences, I don't think filtering the header will give you much of a gain.
Again, many thanks for reporting.

**Comment by terrycojones** [comment]
You're welcome & thanks too.  I was trying to get rid of the header lines for sequences that have no matches (once I have done my filtering) so that other code would not need to deal with sequences that weren't present other than in the header. In any case there are of course other ways to get rid of those lines! :-)
