### ISSUE TITLE
How can I use get_query_sequences() when the average depth is more than 10000

### ISSUE THREAD

**Issue by hitcat1** [pysam-developers/pysam#717]
when I used `pileupcolumn.get_query_sequences`  , I got a error : ` File "pysam/libcalignedsegment.pyx", line 3041, in pysam.libcalignedsegment.PileupColumn.get_query_sequences
AssertionError`

   I noticed `cdef uint32_t MAX_PILEUP_BUFFER_SIZE = 10000` ,  but at some positions in my bam, the depth may be more than it.  And I do not want to change the source code , because that will not work on my professor's cluster.
   What should I do ?

`pysam.__version__
'0.15.0' `

**Comment by woodword** [comment]
I don't think it 's the depth problem. Use picard ValidateSamFile to check your bam file.

**Comment by mariasirenko** [comment]
@hitcat1 I am having the same issue with a very high depth bam. Did you find a solution aside from changing the source code?

**Comment by bkohrn** [comment]
I am having a similar issue with a high depth bam, and I reasonably expect to have BAM files with depths > 10,000 on a regular basis.  I don't think it's a problem with anything else.  

There does seem to be an option to set max_depth, but it doesn't seem to get passed on to the pileup_column.  

I have seen proposals to just iterate over the pileup_reads, but I don't want to do that because I feel that will be too slow as a operation.  

I am working on Mac OS X 10.12.6, with samtools 1.6 and pysam 0.15.1.
My code looks something like:

```
import pysam
# I mave an input bam file in_bam, and an input fasta file in_fasta
inBam = pysam.AlignmentFile(in_bam, "rb")
inFasta = pysam.FastaFile(in_fasta)
for pileup_column in self.inBam.pileup(
        fastafile=self.inFasta, 
        truncate=True, 
        stepper="nofilter", 
        max_depth=1000000
        ):
    myReads = Counter(
        [x.translate(self.rmNumTable) 
            for x in pileup_column.get_query_sequences(
                add_indels=True
                )
            ]
        )
# Do things with myReads, mostly involving variant examination
```

and I get the following final error:

> File "pysam/libcalignedsegment.pyx", line 3041, in pysam.libcalignedsegment.PileupColumn.get_query_sequences
AssertionError

Any advice would be appreciated.

**Comment by bkohrn** [comment]
After a bit of investigation, I think I'm most of the way to a fix; it involves changes to two (possibly three) files.  First off, it involves a change to the makePileupColumn function (defined in libcalignmedsegment.pyx) to allow for max_depth to be passed on to the PileupColumn, and saves it as dest.max_depth.  Second, it removes the fixed MAX_PILEUP_BUFFER_SIZE (in libcalignmedsegment.pyx) and changes all references to it into self.max_depth.  Third, it changes the calls to maxePileupColumn to include passing on max_depth from IteratorColumn (in libcalignmentfile.pyx).  It seems to work, with the issue that it gives me a warning as follows:

> /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: pysam.libcalignedsegment.PileupColumn size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)

Does anyone have any idea how to fix this?  I think it has to do with the fact that I added an extra property to the pileup column, but I'm reluctant to try pushing my change until I figure this out, as (obviously) this sort of warning isn't ideal for a widely-distributed module like pysam.

**Comment by bkohrn** [comment]
Nevermind; I found that if I removed all the .C files created by cython and reran setup.py, that error disappeared.  However, it has been mentioned to me that it might be a good idea to do a check to make sure the user doesn't allocate too much memory to the buffer; anyone have a good idea of how to do that / if it's already happening somewhere in the background?  I'm still a bit new to cython.

**Comment by jmarshall** [comment]
Check for `NULL` just as you would in C.

But I'd suggest using `realloc` as necessary for `buf` rather than having a fixed limit for this buffer.

**Comment by bkohrn** [comment]
So `calloc` will return null if there would be an overflow, or if I request too much memory?
Also, your saying you would start with a set buffer size, and then allow it to increase up to max_depth?  

Again, I'm fairly new to C and Cython, and haven't really delved into memory management that much yet.  My entry into this was the buffer being a fixed (hard-coded) size and therefore failing an assertion in a high-depth file.  It sounds like `realloc` would be a good idea for speed in lower-depth regions, but would require a bit more reprogramming to get it to work than just setting a fixed-size buffer based on max_depth.

**Comment by jmarshall** [comment]
In fact `buf` is used solely within `get_query_sequences()` to build up a long string to be returned. So rather than managing memory directly, the best way to make this part work without any hard-coded limit would be to recode it in terms of a `kstring_t` instead.

This would be a fairly steep introduction for someone new to C and Cython, so I'm happy to draft something for you to test if you like.

**Comment by bkohrn** [comment]
That would be nice.  I've created a fork with my attempt at fixing it (https://github.com/bkohrn/pysam/tree/bkohrn-patch-1), if you want to look at it; it seems to work, but is probably slower than necessary for most situations.

**Comment by jmarshall** [comment]
I had a look; some of those NULL checks aren't really the ones that are needed, but it's in the right direction!

Give PR #804 a go.

**Comment by bkohrn** [comment]
It compiles, but I'm getting an assertion error as 

> File "pysam/libcalignedsegment.pyx", line 3032, in pysam.libcalignedsegment.PileupColumn.get_query_sequences
AssertionError
