### ISSUE TITLE
Documentation unclear / absent for VariantRecord FORMAT field

### ISSUE THREAD

**Issue by brendanofallon** [pysam-developers/pysam#719]
Looks like the current documentation for VariantFile (https://pysam.readthedocs.io/en/latest/usage.html#working-with-vcf-bcf-formatted-files) is missing some information about how to parse information from sample FORMAT fields.  There's an example about INFO fields, but FORMAT appears to work differently. The API docs for VariantRecord aren't really helpful, the entry for 'format' just says 'sample format metadata' and contains a broken link to something called 'VariantRecordFormat', which doesn't seem to appear anywhere else in the docs (looks most of the VariantRecord attributes contain broken links).  
 Just a working example or two I'm guessing would save users a bunch of time, right now it's pretty difficult to find out how to use VariantRecords. Or maybe I missed it somewhere?

**Comment by aunderwo** [comment]
I agree the documentation could be clearer.
The reason why the API is different is because a VCF can record formats for one OR MORE samples. Therefore FORMAT is associated with the records samples. An example of how to parse them is as follows:

```
for record in vcf_reader.fetch():
    # get all samples stored in the VCF file (could be just 1)
    for sample in record.samples:
        # find all items stored in thE FORMAT and print out the value for that item in the current sample
        for metric in record.format:
            print('{0}:{1}'.format(metric, sample[metric]))
```

**Comment by mjobin** [comment]
I've been trying the code above and have been running into some problems. When I try it just as written:
`    outvcf = pysam.VariantFile(basename + ".mpileup.vcf")
    for rec in outvcf.fetch():
        for sample in rec.samples:
            for metric in rec.format:
                print('{0}:{1}'.format(metric, sample[metric]))
`

I get the error:

> TypeError: string indices must be integers

I thought maybe what was meant was sample.format[metric] not sample[metric], so I tried that:
`    outvcf = pysam.VariantFile(basename + ".mpileup.vcf")
    for rec in outvcf.fetch():
        for sample in rec.samples:
            for metric in rec.format:
                print('{0}:{1}'.format(metric, sample.format[metric]))`

but that gives the error:

> TypeError: 'builtin_function_or_method' object is not subscriptable

I have checked with print statements that there is indeed data in the records and samples. Is there anything else I could try to get data out of a FORMAT column?

**Comment by sheerun** [comment]
Is it possible to write to this field? I get an error:

```
NotImplementedError: Subscript assignment not supported by pysam.libcbcf.VariantRecordFormat
```

**Comment by caitlin-f** [comment]
I've managed to be able to write to the format field as I wanted to add to this field as follows:
```
vcf_in = VariantFile(file, mode=r)
vcf_in.header.add_meta('FORMAT', items=[('ID', "FT"), ('Number', "."), ('Type', "String"), ('Description', "...")])
for rec in vcf_in.fetch():
        rec.samples[0]["FT"] = "value"
```
Note - I only ever have 1 sample in the vcf files I'm parsing so I'm just indexing into rec.samples rather than iterating through each sample. If you have multiple alternate allele calls you'll need to add your format value for each allele in a comma-separated string (e.g. `rec.samples[0]["FT"] = "value1,value2"`).

**Comment by tahuh** [comment]
I have tried below code and worked fine for me.

The vcf file I'm using is 1000 genome's official release vcf file

```python
import pysam
vcfname = '/data/resources/snps/phase3/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz'
vcf = pysam.VariantFile(vcfname)
chrom = '1'
start = 723753
end = start + 1
# We are interested in genotypes of SNP
# The genotype format keyword is GT here

for r in vcf.fetch(chrom, start, end):
	num_samples = len(r.samples)
	for i in range(num_samples):
		sample = r.samples[i]
		gt = sample['GT']
		print(gt) # (0,1), (0,0), (1,1), etc...
```
