### ISSUE TITLE
macOS and Linux wheels

### ISSUE THREAD

**Issue by pb-dseifert** [pysam-developers/pysam#722]
Hi @AndreasHeger 
would it be possible to get Linux and macOS tarballs for the 0.15.1 release of pysam? Thanks a lot!

**Comment by AndreasHeger** [comment]
Certainly, will build these on the weekend.

**Comment by AndreasHeger** [comment]
I have built the linux wheels, not sure at the moment why there is no python 3.7

**Comment by wm75** [comment]
Hi @AndreasHeger and thanks for all the work!
Would love to see the 3.7 wheel. What is the issue with it?

**Comment by AndreasHeger** [comment]
Thanks, the 3.7 wheel has been uploaded - turns out I had not updated the manywheels docker image for while...

**Comment by wm75** [comment]
Well, that can happen :smile: Thanks for looking into this!

**Comment by kyleabeauchamp** [comment]
I think this is resolved?

**Comment by nsoranzo** [comment]
@kyleabeauchamp I can't find macOS wheels on https://pypi.org/project/pysam/ , so I'd say not completely.

**Comment by kyleabeauchamp** [comment]
Oops, thanks!

**Comment by nsoranzo** [comment]
@kyleabeauchamp @AndreasHeger  Would you be interested in automatic building of wheels and pushing to PyPI on release tagging?
I've recently worked on that for another Python library: https://github.com/bxlab/bx-python/blob/master/.travis.yml

**Comment by AndreasHeger** [comment]
@nsoranzo , that would be very helpful. How do you want to proceed?

**Comment by nsoranzo** [comment]
I can try to work on that in the next few days and open a PR. Someone having PyPI push access for pysam would then need to add their username and encrypted password to `.travis.yml` ( https://docs.travis-ci.com/user/environment-variables#defining-encrypted-variables-in-travisyml ). Sounds good?

**Comment by AndreasHeger** [comment]
Excellent, thanks

**Comment by nsoranzo** [comment]
This issue can be finally closed.
