### ISSUE TITLE
CRAM bug with .pileup

### ISSUE THREAD

**Issue by egafni** [pysam-developers/pysam#725]
Calling `AlignmentFile.pileup('chr2')` on a CRAM does not properly fetch (it iterates over reads starting on chr1).  Converting the same CRAM to a BAM then calling `AlignmentFile.pileup('chr2')` works properly.

pysam 0.12.0.1 works fine, but >=0.14 is definitely not working

**Comment by egafni** [comment]
I'll add that `AlignmentFile.fetch('chr2)` is working fine on CRAMs, it's only pileup that seems to be broken

**Comment by eugenegardner** [comment]
I can second this issue. No matter what syntax you use (some combination of region, contig, start, stop, end) pileup always starts at chromosome 1 when using CRAM.

**Comment by AndreasHeger** [comment]
For the record, I am building a bugfix release. As this is an API change, I will change the default only for CRAM files.
