### ISSUE TITLE
get_forward_sequence() does not give the reverse complement of read mapping to negative strand

### ISSUE THREAD

**Issue by isthisthat** [pysam-developers/pysam#726]
Minimal example:

    echo -e "@HD\tVN:1.0\tSO:coordinate\n@SQ\tSN:chr1\tLN:249250621\tM5:1b22b98cdeb4a9304cb5d48026a85128\tUR:/Genomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa\nHYGVKADXX:2:1115:960284:0\t81\tchr1\t10147\t0\t72S3M\t=\t10147\t2\tCCCGAACCCGAACCCGAACCCTAACCCGAACCCGAACCCGAACCCGAACCCGAACCCGAACCCTAACCCGAACCC\tFB70BBFB70B7FB77BBFBBB<7B<<0FFFB<7FBIFB<FFIIIFFBIFFFFBFFFBFBIIFFFFFFFFFBBBB\tSM:i:88\tRG:Z:3\tNM:i:0\tBC:Z:AAGAGGC\nHYGVKADXX:2:1115:960284:0\t161\tchr1\t10147\t0\t3M72S\t=\t10147\t-2\tCCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCGAACCCGAACCCGAACCCGAACCCGAACC\tBBBFFFFFFFFFFFIIIIIIIIIIIIIIIIIFIIIIIIII<FFIIIIIIFIIFFFFFFFFFBFFBBBBBF<BFFF\tSM:i:31\tRG:Z:3\tNM:i:0\tBC:Z:AAGAGGC" > bamlet.sam

in python:

    from pysam import Samfile
    f=Samfile("bamlet.sam", "r")
    for read in f.fetch(): print read.get_forward_sequence()

expecting:

    CCCGAACCCGAACCCGAACCCTAACCCGAACCCGAACCCGAACCCGAACCCGAACCCGAACCCTAACCCGAACCC
    CCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCGAACCCGAACCCGAACCCGAACCCGAACC

instead get:

    GGGTTCGGGTTAGGGTTCGGGTTCGGGTTCGGGTTCGGGTTCGGGTTCGGGTTAGGGTTCGGGTTCGGGTTCGGG
    CCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCGAACCCGAACCCGAACCCGAACCCGAACC

using `pysam-0.15.1`

Thank you!

**Comment by isthisthat** [comment]
I think the problem is that `query_sequence` already returns the reverse complement of a read mapping to the reverse strand. At least in the example above. So this line:
https://github.com/pysam-developers/pysam/blob/0720fbf1ca8f6f7f7ae59c8b9efd657046ffabd5/pysam/libcalignedsegment.pyx#L1845
reverses it again.

**Comment by isthisthat** [comment]
I think I was confused with the "forward" bit. The Docstring says "return the original read sequence". I'd highly recommend changing `get_forward_sequence` to `get_original_sequence` and `get_forward_qualities` to `get_original_qualities`.

**Comment by wdecoster** [comment]
This seems not to be solved? read.get_forward_sequence() does not return the reverse complement for reads on the reverse strand? @AndreasHeger

**Comment by jmarshall** [comment]
It returns the reverse complement for reverse strand reads that I was expecting. What exactly were you expecting?

`read.query_sequence` returns the sequence exactly as it is stored in the SAM file (here `CCC…` for both reads).

`read.get_forward_sequence()` returns the read sequence as it originally came off the sequencing machine, i.e., it reverse complements the bases as stored in the SAM file for reads mapped to the reverse strand. (Here `GGG…` for the first — reversed — read, and `CCC…` for the unreversed second read.)

So there's nothing to solve in the behaviour, which seems sensible to me — there are two functions and they do different things.

If there is a problem, it is that the naming is not unconfusing. This usually gets referred to as the “original orientation in which the read came off the sequencing machine” (see e.g. the SAM spec); here I guess it's going for the “forward (i.e. 5' to 3') from the read's point-of-view“ sequence.

I think there'd be some support for renaming these to `get_original_sequence()` and `get_original_qualities()` as @isthisthat suggested, while keeping the existing names as deprecated equivalents.

**Comment by wdecoster** [comment]
Well, [the documentation](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.get_forward_sequence) states "Reads mapping to the reverse strand will be reverse complemented.", which seems to suggest that it does not return the original sequence of the read if the read aligns to the reverse strand. 

I agree that renaming the methods would avoid some confusion.

**Comment by jmarshall** [comment]
You didn't answer the question about what it was you were expecting.

Given that the method has nothing but the `AlignedSegment` record to work from (and that the code itself is right there a few lines below!), I think it's pretty clear that it means “…will be reverse complemented [from what is stored in the `AlignedSegment`]”. Anyway, bd4b335f03583f150f1fd161af84a6ab2edb468b clarifies the documentation further. Thanks.
