### ISSUE TITLE
pip install pysam and conda install pysam do not work with Mac OS X Mojave and Anaconda 5.3 (Python 3.7)

### ISSUE THREAD

**Issue by daquang** [pysam-developers/pysam#731]
I believe some changes in Xcode between High Sierra and Mojave is causing some compilation issues. I also cannot use 'conda install pysam', because I get the following error:

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==5.3.0=py37_0
  - pysam

**Comment by kyleabeauchamp** [comment]
We don't have a python 3.7 conda package yet

**Comment by daquang** [comment]
Do you have an ETA on when we can expect one?

**Comment by kyleabeauchamp** [comment]
Several more weeks, it depends on the conda-forge rebuild: https://conda-forge.org/status/

**Comment by daquang** [comment]
Great, thanks! I hope the pip install option will work by then too :)
