### ISSUE TITLE
MAX_POS too small

### ISSUE THREAD

**Issue by SergejN** [pysam-developers/pysam#732]
Dear pysam authors,

I am trying to work with a large genome, but unfortunately, I am not able to convert my BAM files to bigwig using deeptools. Digging in the code lead me to the suspicion that the problem comes from the module pysam/libchtslib.pyx. Indeed, if you check the source code you see that MAX_POS is defined as 2^29 instead of 2^31 (BAM format): Line 44: cdef int   MAX_POS = 2 << 29

Is it something that can be easily fixed?
I would appreciate that. Thank you!
Sergej

**Comment by AndreasHeger** [comment]
Certainly, this should be an easy fix.

**Comment by rembart** [comment]
hey i just had a look at the fix, and without being experienced in cython it seems to me that you just oversized the int32 - I would suggest to use an unsigned int or a long for the loops
otherwise the max_pos will default to "0" since 2^31 is not a valid "positive" int32 value

i haven't tested this but please have a look

best klaus

**Comment by jmarshall** [comment]
The C code effectively uses `(2 << 31) - 1` for this, which fits in an int32 and has the desired behaviour (modulo thinking about a couple of `<=` vs. `<` in the pysam code…).

**Comment by AndreasHeger** [comment]
Thanks, will do the same.

**Comment by jmarshall** [comment]
Uh, when I said the C code **effectively** uses `(1 << 31) - 1`, I meant it writes it as `INT_MAX` or `2147483647` or `0x7FFFFFFF` or similar. Writing `(1 << 31) - 1` overflows in C and perhaps should make you nervous in a .pyx file…

Perhaps this would be better using `from libc.stdint cimport INT32_MAX` as already is imported in several of these files?
