### ISSUE TITLE
Uneven string length in added FORMAT field

### ISSUE THREAD

**Issue by MagdalenaZZ** [pysam-developers/pysam#734]
Hi,

I tried to add a field to a VCF file, with two samples in it.

myvcf.header.formats.add('HP', ".", "String", "Hello")

But, I noticed that when I tried to fill it, in cases when the two samples had strings of different length:
r.samples[0]['HP'] = "world"
r.samples[1]['HP'] = "universe"

Then the vcf.c script fails.

((0, 0), 'chr21', 5219178, 'A', 'T', 0.010869565217391304, 0, 0, '91', '1', 'LP3000370-DNA_H05')
((0, 0), 'chr21', 5219178, 'A', 'T', 0.06639004149377593, 0, 0, '225', '16', 'LP3000335-DNA_D12')
Assertion failed: (!fmt->p_free), function bcf_update_format, file vcf.c, line 3496.
Abort trap: 6

I could rescue the behaviour by padding out with leading 0s:
r.samples[0]['HP'] = "000world"
r.samples[1]['HP'] = "universe"

But I think it is really weird not to be able to add format strings of different length to different samples.

**Comment by hzpc-joostk** [comment]
Hi. I've stumped upon the same error.

I was trying to set FORMAT/AD on some sample in some BCF record, recycling the original AD definition (from FreeBayes). I am sure the number of values I am setting is equal to the number of alleles (`len(rec.alleles)`) as FMT/AD is defined as `Number=R`.
Setting the new values worked for 23357 previous attempts. But not for this particular one.

    python: vcf.c:3496: bcf_update_format: Assertion `!fmt->p_free' failed.

Running pysam 0.15.0: https://github.com/pysam-developers/pysam/blob/v0.15.0/htslib/vcf.c#L3496

Related to this: samtools/htslib#813

**Comment by bioinformed** [comment]
This is an htslib bug that needs to be fixed upstream. The (ugly) workaround is to delete the AD field and re-add it.

**Comment by jmarshall** [comment]
This has been fixed since pysam 0.16.0 (when used with HTSlib 1.10 — which fixed the underlying problem — or later).
