### ISSUE TITLE
pileup using min_base_quality threshold by default - and the default value is not documented

### ISSUE THREAD

**Issue by RaverJay** [pysam-developers/pysam#735]
Just now realized that
> pysam.AlignmentFile.pileup()

always applies
> min_base_quality (int) – Minimum base quality. Bases below the minimum quality will not be output.

with some undocumented default value. [docs](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.pileup)

While this is probably useful for Illumina read mappings, it seems really impractical for mapped nanopore reads as qualities assigned by the basecaller vary wildly.

What is the default value anyway?
That should at least be documented - and imho the default should be 0.

Cheers

**Comment by Marijn-Schipper** [comment]
The default value is 8. I totally agree that this feature seems less usefull for mapped nanopore reads.

Cheers

**Comment by jmarshall** [comment]
The default value is in fact 13, and the lack of documentation was recently corrected in b82cbcae22c088e64fdb58f8acaf1e9773c7b088.

While I don't disagree that not filtering would be a more appropriate default, I think there would be little appetite for changing the default at this point.
