### ISSUE TITLE
segmentation fault -PileupColumn get_query_sequences

### ISSUE THREAD

**Issue by chartl** [pysam-developers/pysam#746]
get_query_sequences() is throwing a segmentation fault for me. I have attached a bam file and pasted in code which generates the error; and the IGV shot of the site is here:

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/976675/50039781-ce1a6080-ffec-11e8-94cf-ce98053c4a2e.png">

```
# generates a segfault
import pysam
test_bam_file = './chr12_test_1mb_3x.bam'
sam_reader = pysam.AlignmentFile(test_bam_file, 'r')
varloc = ['chr12', 66165, 66166]
pile = [x for x in sam_reader.pileup(*varloc) if x.pos == varloc[1]][0]
pile.n  # 3
pile.get_query_sequences()  # Segmentation fault: 11
```

Using python 2.7.15 (Anaconda)
pysam 0.14.1

[chr12_test_1mb_3x.bam.zip](https://github.com/pysam-developers/pysam/files/2682430/chr12_test_1mb_3x.bam.zip)

**Comment by chartl** [comment]
Also segfaults on 0.15.1

**Comment by AndreasHeger** [comment]
Thanks for the test case, I can reproduce it.

**Comment by AndreasHeger** [comment]
Ah, I see what is the issue. Pileup columns are proxy objects, meaning they point to the current iterator within htslib. Using a pileup object outside a loop will fail. The following works:
```
