### ISSUE TITLE
FastaFile.fetch() gives error "no sequence/region supplied" in v0.15 but not v0.14.1

### ISSUE THREAD

**Issue by rlorigro** [pysam-developers/pysam#747]
I have pysam v0.14.1 and v0.15 in separate environments. When running the same script on different versions, I either get an error, or not. 

On v0.15 I am attempting to access a region of the E. Coli reference fasta well within the bounds of its length:
```
fasta.fetch(region=chromosome_name, start=start, end=stop)
```
Where `chromosome_name="gi"`, `start=100` and `stop` is something like ~1.9Mbp and the error I get is:

```
  File "pysam/libcfaidx.pyx", line 293, in pysam.libcfaidx.FastaFile.fetch

ValueError: no sequence/region supplied.
```

This error disappears when I switch to v0.14.1. The v0.15 error has been replicated in 2 genomes (human and E. coli) on 3 different machines (all linux based), with fresh installations of pysam.

**Comment by llevar** [comment]
I get this on Mac OS too.

**Comment by AndreasHeger** [comment]
Thanks, for reporting this. Could you try:
```
