### ISSUE TITLE
Update bioconda deployment to Python3.7

### ISSUE THREAD

**Issue by MatthewPorterGN** [pysam-developers/pysam#749]
Hi,

We at GenomeNext enjoy using Anaconda to help manage packages, however I have noticed during an attempt to upgrade some of our systems to Python3.7 that pysam interferes with our upgrade process. It looks like [it has been built](https://anaconda.org/bioconda/pysam/files) for Python 3.5 and 3.6 but not 3.7, the new Anaconda standard deployment version. Maybe this could be a relatively easy update to make?

**Comment by kyleabeauchamp** [comment]
I pinged Bioconda and we're still waiting on some final fixes for py37, see response below:

"conda-forge has build all its packages against py37 already, and I will vote tomorrow to switch the labels from this timepoint on, you could migrate single packages with the conda_build_config overwrite against 3.7 I'm not sure when we will start to bulk-rebuild everything against 3.7
this will probably be a large coordinated effort together with the rebuild against GCC7
"
cc @bgruening

**Comment by AndreasHeger** [comment]
Thanks @kyleabeauchamp. pysam is 3.7 compatible, a temporary solution would be to install from pypi, thought this would require some compilation overhead.

**Comment by kyleabeauchamp** [comment]
Python 3.7 is now available on bioconda: https://anaconda.org/bioconda/pysam/files?version=0.15.2
