### ISSUE TITLE
pileup TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by kforti** [pysam-developers/pysam#754]
I am using python 3.6 and pysam 0.15.2. 

I can do samfile.count_coverage() just fine, but samfile.pileup() raises an error. In both cases, I specify the same contig, start and stop.

Thanks for any help,
Kevin

**Comment by kforti** [comment]
I fixed this issue by uninstalling pysam and reinstalling in a Python 3.7 environment. I noticed an issue with conda install during this process- it seems that conda install for pysam has not been updated in a while. I used pip.

**Comment by nigiord** [comment]
This is strange because the conda version I see is the last release (0.15.2):

https://anaconda.org/bioconda/pysam

Did you use the bioconda channel?

**Comment by pkerpedjiev** [comment]
Just tried uninstall and reinstalling in a Python 3.7 environment and get the same error. Any other suggestions?
