### ISSUE TITLE
pysam-0.15.2/setyp.py: bundled/anticipated versions are out of date

### ISSUE THREAD

**Issue by mmokrejs** [pysam-developers/pysam#757]
Hi Andreas,

  the Release notes on github state:

```
Release 0.15.0.1

This release wraps htslib/samtools/bcftools version 1.9.0.
```

but the code in `setup.py` states:

```
The current version wraps htslib-1.7, samtools-1.7 and bcftools-1.6.
```

Please  change it to 

```
The current version 0.15.2 wraps htslib-1.9, samtools-1.9 and bcftools-1.9.
```

**Comment by kyleabeauchamp** [comment]
In #758, I've opted to just delete that line entirely from setup.py.  I think it's best to not have redundant information that tends to get out-of-date.

**Comment by mmokrejs** [comment]
But then either README.rst or INSTALL files need to include what is bundled in the tarball (and be kept up-to-date). It takes so much effort to others to realize what this package really needs.

**Comment by kyleabeauchamp** [comment]
Good point.  I've added the versions to README.rst.   I think it will be harder to get out of date when it's on the main page.

**Comment by mmokrejs** [comment]
Agreed.

**Comment by mmokrejs** [comment]
And maybe,

`The current version of pysam wraps htslib-1.9, samtools-1.9, and bcftools-1.9.`

could be changed to

`The current version of pysam bundles 3rd-party code from htslib-1.9, samtools-1.9, and bcftools-1.9.`

because of the different licenses.

**Comment by kyleabeauchamp** [comment]
I made a very similar change to what you suggested, but I said "wraps" instead of bundles because the user can actually choose whether to bundle or link to a pre-built shared library.

**Comment by mmokrejs** [comment]
I just opened #759 meanwhile so maybe the INSTALL docs have changed since 0.12.x series and missed that. Let's switch to that thread with discussion how one can use external (read site-wide) htslib and samtools instead of the bundled copies. Thank you.
