### ISSUE TITLE
Test suite failures

### ISSUE THREAD

**Issue by tillea** [pysam-developers/pysam#761]
Hi,
there is a [bug report](https://bugs.debian.org/920250) to the Debian packaged version which contains three failures.  Here is the short version:

    =================================== FAILURES ===================================
    _____________ TestIndexing.test_indexing_to_custom_location_works ______________

    self = <tabix_test.TestIndexing testMethod=test_indexing_to_custom_location_works>

        def test_indexing_to_custom_location_works(self):
            '''test indexing a file with a non-default location.'''

            index_path = get_temp_filename(suffix='custom.tbi')
            pysam.tabix_index(self.tmpfilename, preset="gff",
                              index=index_path, force=True)
    >       self.assertTrue(checkBinaryEqual(index_path, self.filename_idx))
    E       AssertionError: False is not true

    tests/tabix_test.py:89: AssertionError
    ____________ TestIndexing.test_indexing_with_explict_columns_works _____________

    self = <tabix_test.TestIndexing testMethod=test_indexing_with_explict_columns_works>

        def test_indexing_with_explict_columns_works(self):
            '''test indexing via preset.'''

            pysam.tabix_index(self.tmpfilename,
                              seq_col=0,
                              start_col=3,
                              end_col=4,
                              line_skip=0,
                              zerobased=False)
            self.assertTrue(checkBinaryEqual(
    >           self.tmpfilename + ".tbi", self.filename_idx))
    E       AssertionError: False is not true

    tests/tabix_test.py:102: AssertionError
    _________________ TestIndexing.test_indexing_with_preset_works _________________

    self = <tabix_test.TestIndexing testMethod=test_indexing_with_preset_works>

        def test_indexing_with_preset_works(self):
            '''test indexing via preset.'''

            pysam.tabix_index(self.tmpfilename, preset="gff")
            self.assertTrue(checkBinaryEqual(
    >           self.tmpfilename + ".tbi", self.filename_idx))
    E       AssertionError: False is not true

    tests/tabix_test.py:81: AssertionError
    =============================== warnings summary ===============================
    /usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367
      /usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367: FutureWarning:
    Cython directive 'language_level' not set, using 2 for now (Py2). This will
    change in a later release! File:
    /<<BUILDDIR>>/python-pysam-0.15.2+ds/.pybuild/cpython2_2.7_pysam/build/tests/_compile_test.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)

    .pybuild/cpython2_2.7_pysam/build/tests/AlignmentFile_test.py::TestTruncatedBAM::testTruncatedBamIterator

    /<<BUILDDIR>>/python-pysam-0.15.2+ds/.pybuild/cpython2_2.7_pysam/build/tests/AlignmentFile_test.py:1459:
    UserWarning: no BGZF EOF marker; file may be truncated
        ignore_truncation=True)

    -- Docs: https://docs.pytest.org/en/latest/warnings.html
    ======== 3 failed, 906 passed, 17 skipped, 2 warnings in 60.36 seconds =========

Please let me know if you need more information.
Kind regards, Andreas.

**Comment by mr-c** [comment]
The difference between the Debian -10 release of htslib v1.9 and the Debian -9 release of htslib is that libdeflate, GCS, and S3 are enabled.

This even changes the output of `tabix` itself when indexing https://github.com/pysam-developers/pysam/blob/master/tests/tabix_data/example.gtf.gz so it is no surprise that these pysam tests break.

**Comment by tillea** [comment]
On Wed, Feb 20, 2019 at 08:39:02AM +0000, Michael R. Crusoe wrote:
> The difference between the Debian -10 release of htslib v1.9 and the Debian -9 release of htslib is that libdeflate, GCS, and S3 are enabled.
> 
> This even changes the output of `tabix` itself when indexing https://github.com/pysam-developers/pysam/blob/master/tests/tabix_data/example.gtf.gz so it is no surprise that these pysam tests break.

So your suggestion is to generate a new example.gtf.gz to compare with the test result?
If yes, would you mind creating such a file to fix the test suite?
Thanks for your investigation in any case, Andreas.

**Comment by mr-c** [comment]
@tillea I'm testing such a solution right now. One does wonder if the index format should be changing at all, though.

**Comment by tillea** [comment]
On Wed, Feb 20, 2019 at 08:49:23AM +0000, Michael R. Crusoe wrote:
> @tillea I'm testing such a solution right now. One does wonder if the index format should be changing at all, though.
I agree that it sounds a bit suspiciuos.

**Comment by mr-c** [comment]
Okay, the indices are the same, just the compression is slightly different; I'll push my workaround to reindex using Tabix before running the tests. A proper fix would involve `gunzip`ing the reference file and the produced file and then comparing their contents.

**Comment by mr-c** [comment]
see https://github.com/samtools/htslib/issues/827#issuecomment-465489408 for more details

**Comment by jmarshall** [comment]
Is your test suite testing the system compression library or htslib/pysam's tabix implementation?

Clearly you want a `checkUncompressedBinaryEqual` function that compares the decompressed bytestreams.

**Comment by mr-c** [comment]
Not my test suite, I'm just helping with the Debian packaging.

Here is our patch for the issue: https://salsa.debian.org/med-team/python-pysam/commit/09438982e1cf86c0d4b7e8aa4815ad6fad7e0305

**Comment by jkbonfield** [comment]
> Clearly you want a checkUncompressedBinaryEqual function that compares the decompressed bytestreams.

This is precisely how we worked around this problem in htslib.

https://github.com/samtools/htslib/commit/7c226d39

We used the bgzip binary itself as it's already part of htslib, but depending on your test harness you may simply want to use the native deflate support.

**Comment by jmarshall** [comment]
@mr-c: “Your” being pysam-developers, which you represent when you go to other projects and file issues saying that pysam has been broken.

Anyhow, your patch does what I said (with a different name). So that's good. Maybe Debian would like to send their patch to upstream pysam… :smile:

**Comment by mr-c** [comment]
@jmarshall Yes, we will send our patch upstream once all of our testing has passed :-)

Thanks for your help.

**Comment by AndreasHeger** [comment]
Thanks all. A lot of these binary tests predate htslib when I did want to make sure that the files output by pysam were exactly identical to the files output by samtools - different compression libraries were not an option. A lot of this needs refactoring.
