### ISSUE TITLE
extract bam header only

### ISSUE THREAD

**Issue by bernt-matthias** [pysam-developers/pysam#762]
Just a question: is it possible to extract the header of a bam file without reading it entirely. 

This could be useful for the Galaxy project: https://github.com/galaxyproject/galaxy/blob/f84a29b9545d544d8d1bbe0a433f3e8dd647cbaf/lib/galaxy/datatypes/binary.py#L264

**Comment by mvdbeek** [comment]
that's what we're doing in the lines you linked.

**Comment by bernt-matthias** [comment]
nice to see you here :)

I just had problems with a collection of bam files (produced with stacks tsv2bam). and memory consumption seemingly killed at least one mule (memory is limited on our test galaxy). Furthermore processing each bam file needed ~40s-60s.

I just have seen in the logs that the reference_names and -lengths are not set, because they are to large. So I guessed that the main bam content is the culprit, since I could not imagine that reading the header could take that much memory and time... but maybe. 

Any idea how I could test this?

**Comment by bernt-matthias** [comment]
Files have several hundred thousands of SQ lines (eg. 773386). 

But as you said memory seems not to be the problem. At least not this line.

**Comment by mvdbeek** [comment]
I think this might be a Galaxy / Galaxy configuration / tool issue. `set_meta` should run together with the job and not in the job_handler/mule/etc. I don't think this is a pysam issue pe se. Maybe we can continue this over in the Galaxy issues ?
