### ISSUE TITLE
pysam apparently stumbles over bam files with empty header lines

### ISSUE THREAD

**Issue by bernt-matthias** [pysam-developers/pysam#763]
When executing 

```
import pysam
bam_file=pysam.AlignmentFile("81_CG.matches.bam", mode='rb')

print bam_file.header.items()
```

on a bam file generated with stacks tsv2bam (https://nc.ufz.de/f/15436887 password pysamdebug)

I get: 

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    bam_file.header.items()
  File "pysam/libcalignmentfile.pyx", line 545, in pysam.libcalignmentfile.AlignmentHeader.items
  File "pysam/libcalignmentfile.pyx", line 423, in pysam.libcalignmentfile.AlignmentHeader.to_dict
AssertionError: header line without '@': ''
```

I guess there is an empty header line. Question if my guess is correct and if this should be handled here or upstream.

**Comment by jmarshall** [comment]
What username should be used to look at your test file?

**Comment by bernt-matthias** [comment]
Sorry, did not work as expected. Take this link: http://pacosy.informatik.uni-leipzig.de/~maze/81_CG.matches.bam

**Comment by jmarshall** [comment]
There is nothing wrong with this BAM file. It is somewhat atypical in that its headers (`l_text`/`text` in the BAM spec) are terminated with a NUL character, but that is entirely valid.

Pysam is failing to deal with this NUL terminator character. A small test case can be generated from any BAM file by using htslib's **test_view**:

```
htslib/test/test_view -b -Z1 tests/pysam_data/example_no_seq_in_header.bam > bork.bam
```

**Comment by mvdbeek** [comment]
Thanks for checking @jmarshall. Should be fixed by https://github.com/pysam-developers/pysam/pull/764
