### ISSUE TITLE
Explore pyproject.toml / pep518

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#766]
In another repo, someone mentioned how we might use pep518 to annotate cython and other dependencies earlier than setup.py.  Could be useful for streamlining the pysam setup.py.  

https://github.com/mdtraj/mdtraj/issues/1433

https://github.com/QuLogic/cartopy/commit/e2dd1f69f65627e62edf655c603e339f676ea999

**Comment by kyleabeauchamp** [comment]
For another example of implementation, see https://github.com/mdtraj/mdtraj/pull/1434

**Comment by mvdbeek** [comment]
Might be a good idea to also publish OSX wheels, that would reduce the audience to people that intentionally want to build from source. I'm amazed by how easy it is to build wheels using https://github.com/joerick/cibuildwheel. I've implemented that in https://github.com/mvdbeek/pysam-compare-reads with automatic uploading to pypi (which could also target test.pypi if you want to have a last check before releasing).

**Comment by jmarshall** [comment]
Since 0.21.0 pysam uses a _pyproject.toml_ file, and since 0.22.0 we produce wheels for both x86_64 and ARM macOS.
