### ISSUE TITLE
Error Reading header

### ISSUE THREAD

**Issue by pziarsolo** [pysam-developers/pysam#77]
Hi,
I Have a problem with pysam 8.1. 
When I try to read the header of a bam file generated by bwa, pysam gives this error:
In [1]: import pysam
In [2]: sam = pysam.Samfile('merged.sample2.bam')
In [3]: sam.header

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ac1760b5c470> in <module>()
----> 1 sam.header

/home/peio/devel/lib/python2.7/site-packages/pysam/calignmentfile.so in pysam.calignmentfile.AlignmentFile.header.__get__ (pysam/calignmentfile.c:13319)()

ValueError: unknown field code 'LB' in record 'PG'

I think the bug is because in the PG line of the header, bwa writes the command  with <tab> in the RG definition option( as it is specified in the command line):

$ samtools view -H /tmp/merged.sample2.bam|grep "^@PG" |cat -A
@PG^IID:bwa^ILB:ECU1032 /home/jope/tomato_6/reads/raw/ECU1032_1.fastq.gz /home/jope/tomato_6/reads/raw/ECU1032_2.fastq.gz^IVN:0.7.10-r789^ICL:bwa mem -t 120 /home/jope/genomes/tomato/S_lycopersicum_chromosomes.2.50.fa -R @RG^ISM:ECU1032^IPL:illumina^IPN:bwa$

To bypass this error I am removing the PG line of my bams, but I think that it should be resolved in othre way? Do you consider this a bug of pysam or a bug of bwa?
Thanks

p.

**Comment by AndreasHeger** [comment]
Thanks for letting me know.  At first I thought this is linked to issue #39. However, if pysam code sees a CL tag, it will expect the rest of the line to be part of the command line statement.

In the line you specify, the LB code occurs before any CL tag. It looks as if this is the library tag and should be part of an @RG line, not an @PG line. Could this be a bwa bug?

Best wishes,
Andreas

**Comment by pziarsolo** [comment]
Hi Andreas,
I have found the bug and it was in the scripts I used to launch bwa. When I generated the RG string Y used this: 
rg_str = "@RG\tID:{ID}\tSM:{SM}\tPL:{PL}\tLB:{LB}".format(**readgroup)
When bwa is executed python "translates" \t to {tab} and bwa writes the tab into the header. In a post processing of the bam the order of the tab separated items in the PG line is changed. And this is producing my error.

To solve that I have changed the rg_str to:
rg_str = r"@RG\tID:{ID}\tSM:{SM}\tPL:{PL}\tLB:{LB}".format(**readgroup)

It produces a PG line without {tab}s inside the CL "item".

I am going to close the issue.

Best wishes, 
Peio

**Comment by AndreasHeger** [comment]
Thanks!
