### ISSUE TITLE
HTSlib Documentation

### ISSUE THREAD

**Issue by chkcole** [pysam-developers/pysam#788]
Hey guys, this isn't an issue with the pysam module. I'm actually interested in using htslib for some of my own C/C++ programs that I am working on, however I can't find any online documentation describing how the libraries work. You guys seem like you know what you are doing. How did you figure out how to use the libraries? I've been poking around the samtools git but was hoping there would be a less ad hoc way of learning how the libraries work. I apologize if this isn't the appropriate venue for asking this question, but I couldn't figure out how to contact you otherwise.

Thank you for your time,
Charles Cole

**Comment by jmarshall** [comment]
The better venue would be to ask the HTSlib folks the same question. See e.g. samtools/htslib#114.

**Comment by Nheyer** [comment]
@chkcole  the HTSlib documentation "is the headers" also I would recommend closing this issue

**Comment by jmarshall** [comment]
As mentioned, there is function documentation in the HTSlib header files, and the samtools and bcftools source code serves as (somewhat over-complicated for pedagogical purposes) example code. Beyond that, this is a question for [HTSlib](https://github.com/samtools/htslib).
