### ISSUE TITLE
Pysam builds failing on TravisCI

### ISSUE THREAD

**Issue by jeromekelleher** [pysam-developers/pysam#79]
Since 0.8.2 was released, Pysam builds seem to fail on TravisCI. See

https://travis-ci.org/ga4gh/server/builds/51162225

for example. We get `gcc: error: pysam/csamtools.c: No such file or directory` and compilation fails.

**Comment by AndreasHeger** [comment]
Thanks. It seems that csamtools.c was not added to the tar-ball, I am 
not sure why.

I will release a fixed version later today.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Can you please try again? It seems to install cleanly via pip.

Best wishes,
Andreas

**Comment by jeromekelleher** [comment]
This works now; thanks @AndreasHeger!

**Comment by jeromekelleher** [comment]
Closing this issue as our Travis builds are now working. Thanks for the quick fix @AndreasHeger.

**Comment by JCSzamosi** [comment]
I am having this issue on Ubuntu with 0.8.4. I tried cloning the repository and now a _different_ file is missing:

x86_64-linux-gnu-gcc: error: pysam/chtslib.c: No such file or directory

**Comment by AndreasHeger** [comment]
Thanks, @JCSzamosi i, do you have cython installed? The .c files are not part of the repository. Best wishes, Andreas

**Comment by JCSzamosi** [comment]
Hi Andreas,

Yes I do have cython installed. From the man page it looks like I have
version 0.20.1post0

On Sat, Feb 6, 2016 at 3:00 PM, Andreas Heger <notifications@github.com>
wrote:

> Thanks, @JCSzamosi <https://github.com/JCSzamosi> i, do you have cython
> installed? The .c files are not part of the repository. Best wishes, Andreas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pysam-developers/pysam/issues/79#issuecomment-180847337>
> .
>



-- 
J. C. Szamosi, M.Sc.
Bioinformatician
Farncombe Metagenomics Facility
McMaster University
