### ISSUE TITLE
support loading reads from a BAM over HTTP

### ISSUE THREAD

**Issue by timodonnell** [pysam-developers/pysam#80]
I hope I'm not overlooking something, but from this [thread](https://groups.google.com/forum/#!searchin/pysam-user-group/url/pysam-user-group/DWLm2jZAEjU/PL_x4MThjpoJ) and my attempts, it does not appear that pysam supports loading reads from a bam over http:

```
>> f = pysam.Samfile("http://server/some.bam", mode="rb")
ValueError: could not open file (mode='rb') - is it SAM/BAM format?
```

would it be possible to support this?

Thanks!

**Comment by AndreasHeger** [comment]
Thanks, can you please give a full example. There are tests for http access and they pass.
(see tests/test_AlignmentFile.py)

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
No update, assuming this is resolved. Please reopen otherwise.
