### ISSUE TITLE
Minor Gripe: consistant parameters

### ISSUE THREAD

**Issue by dantaki** [pysam-developers/pysam#800]
Can pysam use consistent naming for parameters. For example the `fetch()` function for AlignmentFiles and FastaFiles have different parameter names. Minor gripe, I know but I think it should be consistent. 

`AlignmentFile.fetch(self, contig=None, start=None, stop=None...`

`FastaFile.fetch(self, reference=None, start=None, end=None...`

**Comment by bioinformed** [comment]
Not a minor gripe.  This is a real pain point and there have been several
efforts to unify naming.  However, backward compatibility is a major
limitation.  Perhaps when htslib 2.0 comes out it will be time to make
pysam2 and make a clean break.

**Comment by dantaki** [comment]
Great thanks for the info. I am looking forward to htslib2.0 and pysam2 :+1:
