### ISSUE TITLE
samtools index: "./out.bam" is in a format that cannot be usefully indexed\n'

### ISSUE THREAD

**Issue by marcomilanesio** [pysam-developers/pysam#816]
Hi,

I want to delete a specific read in a BAM file, and I'm experiencing the following problem.
Starting from a very simple BAM file (attached):
```
$ samtools view toy.bam 
r1      0       chr1    7       30      8M4I4M1D3M      =       37      39      TTAGATAAAGAGGATACTG     *       XX:B:S,12561,2,20,112
x1      0       chr2    1       30      20M     *       0       0       AGGTTTTATAAAACAAATAA    ????????????????????
```

I use the following code:
```
import pysam

infile = './toy.bam'
outfile = './out.bam'

pysam.index(infile)  # this works as expected
align_file = pysam.AlignmentFile(infile, 'rb')

deleted = pysam.AlignmentFile(outfile, "wb", template=align_file)
for read in align_file.fetch():
    if read.query_name != 'x1':
        deleted.write(read)

pysam.index(outfile)
```
And I get:
```
Traceback (most recent call last):
  File "cli.py", line 14, in <module>
    pysam.index(outfile)
  File "/usr/local/lib64/python3.6/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "./out.bam" is in a format that cannot be usefully indexed\n'
```

However:
```
$ samtools index out.bam
```
Works without any problem, giving me access to the indexed version of the file.

```
$ samtools idxstats out.bam 
chr1    100     1       0
chr2    100     0       0
*       0       0       0
```
I attach the code and the toy.bam file.
[issue.zip](https://github.com/pysam-developers/pysam/files/3350257/issue.zip)

Thanks

**Comment by jmarshall** [comment]
Your problem is that you have not closed `deleted` before you try to index it with `pysam.index(outfile)`.

e.g. if you add

    deleted.close()

before `pysam.index(outfile)` your code will work.

The particular error message is because no data has actually been written out to _./out.bam_ yet; closing or flushing the file fixes this.

**Comment by marcomilanesio** [comment]
Thank you very much for your answer.
Works like a charm. 
I wasn't able to find this info in the docs. Sorry.

Thanks again.
