### ISSUE TITLE
unknown stepper option `pass` in IteratorColumn

### ISSUE THREAD

**Issue by blaiseli** [pysam-developers/pysam#82]
The [documentation](http://pysam.readthedocs.org/en/latest/api.html#pysam.AlignmentFile.pileup) for `pysam.AlignmentFile.pileup` mentions a "pass" stepper option, that doesn't seem to be implemented.

Compare
<https://github.com/pysam-developers/pysam/blob/master/pysam/calignmentfile.pyx#L906-L908>
and
<https://github.com/pysam-developers/pysam/blob/master/pysam/calignmentfile.pyx#L1907-L1921>

**Comment by timodonnell** [comment]
+1, just hit this as well. It is also confusing that `stepper="all"` still removes duplicate reads. (Setting`stepper="nofilter"` seems to retain them.)

**Comment by AndreasHeger** [comment]
Fixed by @TyberiusPrime
