### ISSUE TITLE
Question about get_reference_positions

### ISSUE THREAD

**Issue by weir12** [pysam-developers/pysam#836]
Hi:
I'm a little confused about the return list of this function.
1.As the Introduction saying:_The returned list will thus be of the same length as the read_(if full_length=True).Is the sequence length the same as in fastq files?
2.If I want to know where the tenth base of a read is aligned in the reference sequence.Can I extract it directly by `return_list[9]`?
I want to thank everyone for your help.

**Comment by NickSto** [comment]
@weir12 FWIW, I haven't tried the `full_length` option yet, but that looks correct to me. Just remember the coordinates in the list are 0-based.
