### ISSUE TITLE
FastaFile using '~' (tilde) path fails.

### ISSUE THREAD

**Issue by friend1ws** [pysam-developers/pysam#837]
Hi,

I'm trying to use the FastaFile class in my project.
But when trying to instantiate the FastaFile class using the reference genome path with '~' (tilde), OSError is raised.

Here is what I tried:
```
#! /usr/bin/env python

import pysam

# full path: This is OK.
# fasta = pysam.FastaFile("/home/ubuntu/environment/workspace/seq_data/reference/GRCh37.fa")

# comparative path: This is also OK.
# fasta = pysam.FastaFile("../seq_data/reference/GRCh37.fa")

# path with tilde: 
fasta = pysam.FastaFile("~/environment/workspace/seq_data/reference/GRCh37.fa")
```
And this is the error message:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    fasta = pysam.FastaFile("~/environment/workspace/seq_data/reference/GRCh37.fa")
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 155, in pysam.libcfaidx.FastaFile._open
OSError: file `~/environment/workspace/seq_data/reference/GRCh37.fa` not found
```

I'm using pysam 0.15.2 and python 3.6.7.
I'm happy for your help.

**Comment by jmarshall** [comment]
The same thing would happen with plain Python `open`:

```
>>> f = open("~/environment/workspace/seq_data/reference/GRCh37.fa", "r")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '~/environment/workspace/seq_data/reference/GRCh37.fa'
```

Tilde expansion is a shell feature, not something built in to Python or the filesystem. If the filename is provided as an argument on the command line, the tilde will be expanded before your python script sees it; otherwise, to write paths like this inside your script, you get to write code to expand `environ['HOME']` yourself.

**Comment by friend1ws** [comment]
Thanks!

Now, for the following `pysam_fastafile_test.py` script,
```
#! /usr/bin/env python

import sys
import pysam

ref_file = sys.argv[1]

fasta = pysam.FastaFile(ref_file)
```

```
>> python pysam_fastafile_test.py ~/environment/workspace/seq_data/reference/GRCh37.fa
```
worked fine, and my concern is solved.
