### ISSUE TITLE
Compress a vcf file using pysam

### ISSUE THREAD

**Issue by dridk** [pysam-developers/pysam#845]
Hi,

How can I compress a vcf file to vcf.gz file using bgzip ? 
I would like to reproduce the following command in a python way : 

``` bgzip test.vcf ```

**Comment by jmarshall** [comment]
The function you want is the slightly surprisingly named [`pysam.tabix_compress()`](https://pysam.readthedocs.io/en/stable/api.html#pysam.tabix_compress).
