### ISSUE TITLE
type of AlignedSegment.reference_start

### ISSUE THREAD

**Issue by IanSudbery** [pysam-developers/pysam#854]
Dear Pysam-developers

One of the users of UMI-tools is handling the genome of Ambystoma mexicanum, and finding that only reads mapped to the first 2^31-1 of the genome are being considered (https://github.com/CGATOxford/UMI-tools/issues/374), which is of course the largest int you can store in `uint_32`. We don't convert to `int` at any point, so we were wondering what type `pysam` stored the read position in?

Given that the SAM specification says that the POS field is a 32bit int, I'm not sure what would happen in HTSLIB if the value in the file was bigger, but I thought I'd check with you guys what was happening in `pysam`. 

Cheers.

**Comment by jmarshall** [comment]
As of version 1.10 (December 2019), HTSlib uses 64 bits internally for position values. The first pysam release to contain this HTSlib update was v0.16.0 (June 2020). So for those releases or higher, pysam should be able to represent larger positions — provided you can get the data into it.

(Prior to those releases, at the time of your question, all these components were limited to POS as an `int32_t` signed 32 bit type.)

SAM files are text, so their POS values are not in principle limited in magnitude and current HTSlib and pysam should read and write them happily. OTOH the BAM format limits POS values to 2<sup>31</sup>-1.

Please open a new issue if you encounter problems using large positions from SAM files in current pysam.
