### ISSUE TITLE
Encoding issue in libcutils.pyx (v0.15.3)

### ISSUE THREAD

**Issue by codeunsolved** [pysam-developers/pysam#862]
In v0.15.2, we can `index` a BAM file which contains non-ASCII encoding via code below:

    path_bam = "SampleID.中文.bam"
    pysam.index(path_bam.encode())

But in v0.15.3, it will raise an error:

      File "pysam/libcutils.pyx", line 287, in pysam.libcutils._pysam_dispatch
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str

After digging out, "pysam/libcutils.pyx", line 287 has assumed that all args are string type:

```python
for arg in args:
    if skip_next:
        skip_next = False
        continue
    if arg in SIMPLE_FLAGS or (len(arg) > 2 and arg.startswith('-@')):  # <-- **HERE**
        continue
    if arg in ARGUMENTS:
        skip_next = True
        continue
    if not os.path.exists(arg):
        raise IOError("No such file or directory: '%s'" % arg)
    else:
        break
```

So, I optimize line 287 by `force_bytes` these args:

```python
    if arg in SIMPLE_FLAGS or (len(arg) > 2 and force_bytes(arg).startswith(b'-@')):
```

And I created a pull request for this. However, I am not familiar with the code of this project, I hope my pull request works well for the other part.

Many thanks!

**Comment by codeunsolved** [comment]
By the way, python3 has this issue. It has to encode `unicode` to `bytes`. Python2 doesn't need to encode, and `force_bytes()` will leave `bytes` unchanged.

**Comment by AndreasHeger** [comment]
Thanks, apologies for the delay in merging.
