### ISSUE TITLE
ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 88, got 72

### ISSUE THREAD

**Issue by Acribbs** [pysam-developers/pysam#885]
Hi @AndreasHeger,

Im not sure if this is a pysam or a cgat-apps issue. Has something changed with the ` pysam.libcalignedsegment.PileupColumn` class in pysam since version 0.15.2 of pysam? Conda >0.15.2 versions of pysam create the error below:

```
from cgat.BamTools.bamtools import bam2stats_count
      File "libcalignedsegment.pxd", line 66, in init cgat.BamTools.bamtools
    ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 88, got 72
```

The last changes to the PileupColumn class were 2 years ago which makes me think this might be a problem with the way pysam is packaged in the bioconda channel.
 
Similar issue reported here, : https://github.com/pysam-developers/pysam/issues/687.

**Comment by chris-rands** [comment]
Hello @AndreasHeger  @Acribbs , I just encountered the same `ValueError` did you find a fix that doesn't involve downgrading pysam version?

I did try downgrading, but I encountered `ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`, which has apparently been fixed in later pysam versions https://github.com/bactopia/bactopia/issues/12

**Comment by jmarshall** [comment]
Are you saying that this error is from an executable that comes from cgat-apps, and that you have cgat-apps installed via Conda as well? What does `conda list` say are the exact versions of htslib (if any), pysam, and cgat-apps that are installed?

**Comment by chris-rands** [comment]
@jmarshall Yes, thank you, I created a conda env via `conda create -n cgat_apps pysam=0.16.0.1 cgat-apps`. Here are the versions:
```
$ conda list | grep -E "htslib|pysam|cgat-apps"
cgat-apps                 0.5.3            py36hc40942e_0    bioconda
pysam                     0.16.0.1         py36h61e5637_3    bioconda
```

Full traceback from the `cgat-apps` tool I try to run:
```
$ cgat bam2geneprofile --help
Traceback (most recent call last):
  File "/home/user/.conda/envs/cgat_apps/bin/cgat", line 11, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/cgat_apps/lib/python3.6/site-packages/cgat/cgat.py", line 129, in main
    module = imp.load_module(command, file, pathname, description)
  File "/home/user/.conda/envs/cgat_apps/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/user/.conda/envs/cgat_apps/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.conda/envs/cgat_apps/lib/python3.6/site-packages/cgat/tools/bam2geneprofile.py", line 307, in <module>
    from cgat.BamTools import geneprofile
  File "libcalignedsegment.pxd", line 66, in init cgat.BamTools.geneprofile
ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 88, got 72
```

**Comment by Acribbs** [comment]
Hi @chris-rands, I have been meaning to update chat-apps to work with the newest version of pysam for a while now, but just didn't have time.

At the moment chat-apps will only work with pysam==0.15.2.

Best way to install chat-apps would be:

```
conda install mamba
mamba install -c conda-forge -c bioconda cgat-apps
```

When I have time I will update chat-apps for pysam>=0.16, but this will require modifying cython code that I didn't originally code.

**Comment by chris-rands** [comment]
Hi @Acribbs thanks- I did originally try with an earlier pysam version but then ran into `ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory` error, which was apparently fixed in later pysam versions? (according to https://github.com/bactopia/bactopia/issues/12)

**Comment by Acribbs** [comment]
Strange, the tests dont pick this up and I have never encounter this issue before. 

Can you provide some further information with regards to the operating system you are running, which commands you ran so I can try to reproduce this issue. Thanks

**Comment by Acribbs** [comment]
Also, the output of 

`conda info`
and
`conda list`
would be good. 

However it might be best to open an issue within the cgat-apps repo as this isn't a strictly a pysam related problem.

**Comment by chris-rands** [comment]
@Acribbs I am using CentOS, but I've actually found that with `pysam==0.15.2` it works for me (the `ImportError` I got was with an earlier `pysam`). Perhaps one could pin that correct version of pysam to the requirements.txt/conda equivalent in cgat-apps. Anyway, thank you for your help!

**Comment by Acribbs** [comment]
No problem, the Conda environment is actually pinned to `pysam=0.15.2` (https://github.com/cgat-developers/cgat-apps/blob/19f2b95ae3d8e49308854aa9e53535af785cae31/conda/environments/cgat-apps.yml#L27). But I have removed some redundant requirements.txt files (https://github.com/cgat-developers/cgat-apps/pull/85) and will work on improving the docs further too to avoid confusion on certain things with regards to import issues and pysam versions. Hopefully in the next few weeks.
