### ISSUE TITLE
ModuleNotFoundError: No module named 'pysam'

### ISSUE THREAD

**Issue by mvinyard** [pysam-developers/pysam#888]
Pysam works in a jupyter notebook kernel but I cannot seem to get it to import when using python3 in the command line. 

```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysam'
>>> 
```

**Comment by mvinyard** [comment]
figure it out

**Comment by rtasakis** [comment]
Hi there,
Seems like I'm getting the exact same error (on the python3 / conda forge as well) - but I haven't figured that out. 
Could you let me know how you fixed it? 

Thanks in advance!
R
