### ISSUE TITLE
Conda install broken for s3 access in 0.15.X

### ISSUE THREAD

**Issue by bbreton** [pysam-developers/pysam#920]
I'm not sure whether this should be reported here or to conda. If I should report it there please let me know.

I started up a AWS server using their standard Amazon Linux 2 (ami-0323c3dd2da7fb37d in us-east-1).  I installed miniconda. 

Then I created an environment and installed pysam:
```
conda create --name pysam python=3.7
conda activate pysam
conda install --channel R --channel bioconda pysam
python
```

Then I ran in python:
```
import pysam
samfile = pysam.AlignmentFile("s3://mybucket/mybamfile.bam", "rb")
```

This gives:

>   File "<stdin>", line 1, in <module>
>   File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 940, in pysam.libcalignmentfile.AlignmentFile._open
> OSError: [Errno 93] could not open alignment file s3://mybucket/mybamfile.bam: Protocol not supported

In the past installing with conda support has worked and still works on other older installs of python and pysam from conda.  My guess would be the htslib portion of the build is not working properly and it is being compiled without the full plugin support.

If there is any other info you need please let me know.  I also tried installing  0.15.2 which was the only other version compatible with the release python 3.7.

conda list gives:
```
# packages in environment at /home/bbreton/code/conda/envs/pysam2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
bcftools                  1.9                  ha228f0b_4    bioconda
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py37_0
curl                      7.69.1               hbc83047_0
htslib                    1.9                  ha228f0b_7    bioconda
krb5                      1.17.1               h173b8e3_0
ld_impl_linux-64          2.33.1               h53a641e_7
libcurl                   7.69.1               h20c2e04_0
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.1.0                hdf63c60_0
ncurses                   6.1                  he6710b0_1
openssl                   1.1.1g               h7b6447c_0
pip                       20.0.2                   py37_3
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.6                h0371630_2
readline                  7.0                  h7b6447c_5
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                46.2.0                   py37_0
sqlite                    3.31.1               h7b6447c_0
tk                        8.6.8                hbc83047_0
wheel                     0.34.2                   py37_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

**Comment by jmarshall** [comment]
_Protocol not supported_ means that pysam's htslib contains no code implementing S3 and cannot find it via an htslib plugin either. The conda pysam package has been built with plugin loading disabled, so there is no hope for providing S3 support via a separately installed plugin; and because the build machine did not have libcurl headers available when the package was built, it contains no burnt-in code for libcurl/S3/GCS.

This is a bioconda problem — the conda pysam package was broken by PR bioconda/bioconda-recipes#13093, which was ill-considered in several ways and in particular removed `host: curl` from _meta.yaml_. In the past this worked because prior to that PR the pysam package (while it had its issues) was built against an external htslib that did contain S3 and/or plugin support.

**Comment by jmarshall** [comment]
This may get fixed as a result of this report, but nonetheless it would be beneficial if you would report it against bioconda-recipes directly.
