### ISSUE TITLE
get_query_sequences documentation question

### ISSUE THREAD

**Issue by ionox0** [pysam-developers/pysam#922]
Would it be possible to get clarification for the following description of the `get_query_sequences` method of the `PileupColumn` class?
```
If True, add bases for bases inserted into the reference and 'N's for base skipped from the reference. If a reference sequence is given, add the actual bases.
```
Specifically I'm wondering what is meant by "If a reference sequence is given, add the actual bases", as it seems using True for this parameter should add the inserted bases regardless.

**Comment by jmarshall** [comment]
The actual deleted (“skipped”) bases do not appear in the reads' sequences (i.e., the SEQ fields), so they are only known if there is a reference sequence available; otherwise they are shown as `N`s.

I'm planning to rewrite the description of `add_indels` as follows, which may be clearer:

>    add_indels : bool
>
> If True, add bases for bases inserted into or skipped from the reference. The latter requires a reference sequence file to have been given, e.g., via `pileup(fastafile = ...)`. If no reference sequence is available, skipped bases are represented as `N`s.

**Comment by ionox0** [comment]
Thank you very much, I did understand after reading a second time, but updated description is also helpful.
