### ISSUE TITLE
Error on pysam.bcftools.mpileup: "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by sbslee** [pysam-developers/pysam#928]
Hi,

When using pysam.bcftools.mpileup, I keep getting an error that says: "Segmentation fault (core dumped)". Other commands seem to work fine (e.g. pysam.bcftools.call). Here's a simple example for reproducibility:

[sbslee@grc141 20200613_pysam_test]$ cat pysam-bcftools-mpileup-issue.py
import pysam.bcftools

pysam.bcftools.mpileup()
[sbslee@grc141 20200613_pysam_test]$ python3 pysam-bcftools-mpileup-issue.py
Segmentation fault (core dumped)

As you can see, the error occurs even without any arguments to the function call, which suggests there might be a bug. Could you please look into this?

Notes:
- I downloaded pysam through pip.

- Below is information about the machine I'm using.

[sbslee@grc141 20200613_pysam_test]$ uname -a
Linux grc141.grid.gs.washington.edu 2.6.32-754.28.1.el6.x86_64 #1 SMP Wed Mar 11 18:38:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Below is information about the pysam version I'm using.

[sbslee@grc141 20200613_pysam_test]$ cat /nfs/home/sbslee/.local/lib/python3.6/site-packages/pysam/version.py
# pysam versioning information
__version__ = "0.16.0"

__samtools_version__ = "1.10"
__bcftools_version__ = "1.10.2"
__htslib_version__ = "1.10.2"

**Comment by jmarshall** [comment]
Thanks for the bug report.

This is a pysam bug. As it happens both bcftools and samtools have `mpileup` subcommands (for bcftools this is a fairly recent addition), and the problem here is that despite you asking for `pysam.bcftools.mpileup()` it is the samtools entry point that has been called.

It's not clear why this does not seem happen for e.g. `view` or `index` which are also present in both samtools and bcftools. Probably it's something along the lines of the C function names do not clash for those subcommands, in which case fixing this will be fairly straightforward.

**Comment by jmarshall** [comment]
Confirmed that renaming the internal mpileup subcommand functions to be different (internally to pysam; there's no change to the `pysam.bcftools.mpileup(…)` that you write) resolves this problem. Sadly I investigated and reproduced this back when you reported it, but didn't make the observation about C function names until now.

**Comment by sbslee** [comment]
Thank you very much for looking into this! I thought I was crazy for not being able to run the command. Since I’m very new to pysam (and to Github in general), may I ask what happens next? Since it was rather a simple fix, would the pysam team release a new version soon with the fix (e.g. v1.16.0.2)? Or do you foresee it’s going to take some time for this fix to be updated to the main branch?

**Comment by jmarshall** [comment]
There's a certain amount of effort required to actually make a release, and with the next htslib/samtools/bcftools release fairly imminent the pysam maintainers may decide it's not worth making an intermediate pysam-0.16.0.2 release — see https://github.com/pysam-developers/pysam/issues/901#issuecomment-663441324.

Either way, it'll be fixed within a few weeks. In the meantime, if I prepared the pysam PR to fix this, you would have the option of applying it and building pysam yourself — but if you're new to pysam etc I wouldn't really recommend getting into this.

**Comment by sbslee** [comment]
Thanks for the reply. That sounds fair enough. Looking forward to see this issue resolved in the next pysam version! Appreciate you and the team.

**Comment by sbslee** [comment]
@jmarshall, when you get a chance, could you kindly let me know if there has been any progress regarding this? I still get the same issue with just running:

```
>>> import pysam
>>> pysam.mpileup()
```

The pysam version in my system (macOS):

```
(fuc) sbslee@Seung-beens-Mac-mini docs % conda list | grep "pysam"
pysam                     0.16.0.1         py39h56703ae_3    bioconda
```

**Comment by jmarshall** [comment]
This is fixed on the **master** branch (and doubly so on my upcoming **import-1.12** branch), but regretfully there has still not been a pysam release containing a fix.

The maintainers who make releases have understandably been less active recently than they have in the past. In any case, another new htslib/samtools/etc release is fairly imminent (and includes important bug fixes), so I would want to import both 1.12 and that upcoming release before cranking the wheels to make a new pysam release.

It has not dropped off the radar. Obviously my “within a few weeks” comment last year was way too optimistic, but I would hope that pysam would be in a position to make a release in a month or two.

**Comment by sbslee** [comment]
@jmarshall, thank you so much for your prompt reply. The `pysam` package really opened up a lot of new possibilities for Python developers including myself to develop exciting new bioinformatics tools for genomics. So I don't mind waiting a little longer :) Thank you so much for keeping `pysam` moving forward.

**Comment by jmarshall** [comment]
Version 0.17.0 has now been released and contains this fix.
