### ISSUE TITLE
Pileup is wrong with spliced reads

### ISSUE THREAD

**Issue by TyberiusPrime** [pysam-developers/pysam#93]
If you have  read spliced across a region, pileup will still happily report reference and query positions
even for positions where the read actually has no aligned base.

Toy example: Should not output anything, outputs [(100, 2), (101, 2)...]

import pysam

sam = pysam.AlignmentFile("shu.bam", 'wb', reference_names = ['chr1'], reference_lengths=[100000])
r = pysam.AlignedSegment()
r.query_name = "test1"
r.seq = "ACCT"
r.qual = "xxxx"
r.pos = 100
r.cigartuples = [ (0,2), (3, 500), (0,2)]
sam.write(r)
sam.close()
pysam.index('shu.bam')

sam = pysam.AlignmentFile('shu.bam')
for p in sam.pileup('chr1', 100, 200, truncate=True, stepper='nofilter'):
    for read in p.pileups:
        print 'reference pos', p.reference_pos, 'query pos', read.query_position

**Comment by TyberiusPrime** [comment]
This is a duplicate of #86

**Comment by AndreasHeger** [comment]
Hi @TyberiusPrime  and @sheitandard, 

when a read is not aligned to a position, the read.is_del flag is set. Will this help you?

I am thinking that there might be use cases where it might be of interest to record reads
spanning a region even if they are not actually aligned.

Best wishes,
Andreas

**Comment by TyberiusPrime** [comment]
It would help you, but it's still a very error prone API, getting the same query position multiple times is unexpected to say the least and leads to subtle bugs when counting coverage.

I guess a behavior like get_aligned_pairs(), returning None for .query_position would be more appropriate.

There are also cases where the query_position is outside of the query string - a 1S50M read for example will lead to a .query_position of '50'.

Though that still does not distinguish between deletions and skipped regions. Samtools pileup doesn't either and counts them both as 'coverage' (an unfortunate decision, IMHO).
What do you think about returning both False (skipped) and None (deletion) for the query position in  get_aligned_pairs()?

Also, I was wondering if you'd be open to have a 'get_coverage(contig, start, stop, consider_read_callback, quality_threshold)' function that returns a set of numpy arrays. My own implementation is about a factor of 56 faster than a straightforward iteration through the pileups (and basically limited by .fetch()).

Obviously it's not as universal as the pileup functionality.

So long,
Florian


Ps: While we're working on this, can we remove the naming difference between reference_pos and query_positions?

**Comment by sheitandard** [comment]
read.is_del actually solves my problem
thanks

**Comment by AndreasHeger** [comment]
Thanks both!
@TyberiusPrime, the current implementation mirrors what you get from the htslib API. I would like to preserve this default behaviour, but am happy to add additional flags that can provide a sanitized output.

My reason not to make use of  numpy is that it is a rather heavy dependency. If compilation fails not everyone might be able to resolve those. Thus, I wanted to leave that for downstream packages, but I agree it would be useful. There is array.array?

Best wishes,
Andreas

**Comment by TyberiusPrime** [comment]
Hm, I guess htslib considers the position undefined when is_del is set and simply does not bother updating it - hence receiving the last valid query_position again and again.

So I'd still argue that setting it to None when there is no query_position would be the best way to deal with this .

Second best way is of course to document this idiosyncratic behaviour - I'll submit a pull request for a doc update.

Array.array should work just fine - I'll give it a try.

**Comment by yizhong** [comment]
I strongly agree with TyberiusPrime and sheitandard.
I need to plot read coverage for some genes. I expect to see no read coverage if there is no read aligned to every nucleotide position. However, pileupcolumn.nsegments gives me spliced reads count that are anchored at the upstream and downstream of gene of my interest.
![ppdpf transc 0](https://cloud.githubusercontent.com/assets/2500662/10002240/0419e74e-6074-11e5-99c6-71064aba958f.png)

The baseline coverage is raised up to around 5 for the entire gene, which is not true.

After I filter out splicing read using ".is_del" and "is_refskip", I got the following plot. But ".is_del" and "is_refskip" really takes time, especially for the gene is not short and coverage is not low.
![ppdpf transc](https://cloud.githubusercontent.com/assets/2500662/10002365/a776d4a6-6074-11e5-907d-65d9bdd0002c.png)

**Comment by AndreasHeger** [comment]
Hi @yizhong, I can see that this is a fairly typical use case. I will add a new PileupIterator that purges all unaligned reads before returning them.
