### ISSUE TITLE
Wheel `pysam-0.16.0-cp35-cp35m-manylinux1_x86_64.whl` seems to have missing binaries

### ISSUE THREAD

**Issue by davidnewman02** [pysam-developers/pysam#930]
Downloading the wheel from: https://pypi.org/project/pysam/#files
File: https://files.pythonhosted.org/packages/9c/24/537e86533e773c3dcb6bd05de60bf118cf8ccf60dcf24386a5c3807120bd/pysam-0.16.0-cp35-cp35m-manylinux1_x86_64.whl 
```
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ImportError: libchtslib.cpython-35m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

**Comment by Stikus** [comment]
Same for 2.7 and 3.7:
```
ImportError: libchtslib.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```
But for real these files are in place - adding path to `LD_LIBRARY_PATH` fixed it for me for now:
`LD_LIBRARY_PATH="/usr/local/lib/python3.7/dist-packages/pysam:$LD_LIBRARY_PATH"`

**Comment by AndreasHeger** [comment]
Thanks, I can reproduce this.

**Comment by AndreasHeger** [comment]
See #931

**Comment by AndreasHeger** [comment]
Wheels are building. I have also added a smoketest that should detect this issue should it reappear.

**Comment by AndreasHeger** [comment]
Seems to work now, let me know if there are any more issues.

**Comment by AndreasHeger** [comment]
OSX wheels still outstanding, will need to look into that separately.

**Comment by davidnewman02** [comment]
Thanks for the quick fix @AndreasHeger.  
Tested both the wheel from the website and the wheel available on PyPI and they're now working as expected for me.

**Comment by jmarshall** [comment]
Since the 0.22.0 release, macOS wheels are now included. This appears to have been the only item mentioned on this issue still outstanding.
