### ISSUE TITLE
AlignmentFile.fetch(contig, pos, pos+1) does contain reads with pos

### ISSUE THREAD

**Issue by J-Moravec** [pysam-developers/pysam#932]
If I am reading the documentation correctly, then `AlignmentFile.fetch(contig, start, stop)` should return reads at contig that must contain `start` position (with respect to the reference). However, I have found this to be not true and some reads contain only `stop` position.

Some (not entirely, since it lacks data)) MRE:
```
import pysam

# requires VCF file and associated BAM file, both with existing indexes
bam = pysam.AlignmentFile(bamfile, "rb")
vcf = pysam.VariantFile(vcfile, "rb")

for variant in vcf.fetch():
    test = test_if_reads_contain_variant(variant, bamfile)
    if(test[1] > 0):
        print("Found problematic variant")
        # variable `variant` now contains a problematic variant 
        # and the problem can be further explored
        stop


def test_if_reads_contain_variant(variant, bamfile):
    reads = bamfile.fetch(variant.contig, variant.start, variant.stop)
    counts = reads_contain_variant(reads, variant)
    return (counts.count(True), counts.count(False))



def reads_contain_variant(reads, variant):
    return [read_contain_variant(read, variant) for read in reads]

def read_contain_variant(read, variant):
    return (read.reference_start <= variant.start) and (read.reference_end > variant.start)
```

**Comment by jmarshall** [comment]
Fetch returns reads on `contig` that overlap **at all** with the region `start`…`end`. At the extremes, a read might touch only a single base at `start` or only a single base at the other end.

[This documentation](https://pysam.readthedocs.io/en/latest/usage.html#fetching-reads-mapped-to-a-region) says

> pysam.AlignmentFile.fetch() returns all reads overlapping a region sorted by the first aligned base in the reference sequence. Note that it will also return reads that are only partially overlapping with the region.

The `fetch()` documentation is a bit brief:

> fetch reads aligned in a `region`.

Had you seen the first one? If not, is it clear enough to help?

**Comment by J-Moravec** [comment]
Yes, I am aware of this. I hoped that the included code would clear all the confusion and I understand that my text isn't really clear about it as I concentrated on the problem under certain assumptions.

My point is that `pysam.AlignmentFile.fetch(reference, pos, pos+1)` should, according to documentation **always** return reads that contain pos because, similarly to standard python slicing, `pos+1` is not included in the requested interval (unless the string option is used, which I haven't tested yet, but I will test tomorrow).

I now understand that my example isn't really MRE and I didn't have to include any VCF, but alas, this was the problem that I am currently trying to solve.

**Comment by J-Moravec** [comment]
Turns out after running more tests and printing out variant.start and variant.stop that problem wasn't in the AlignmentFile.fetch, but in the assumption that variant is aligned only to a single position. Aparently I should actually read the VCF specification before doing anything with those files.
