### ISSUE TITLE
pysam error in Conifer program

### ISSUE THREAD

**Issue by amrita1983** [pysam-developers/pysam#935]
Hi,

I am using conifer.py program for my file and it's giving this error

'pysam.libcsamfile.Samfile' object has no attribute '_hasIndex'

I tried to solve with all the options but it is not working, some of the threads suggesting to use pysam 0.8.3 version for the program, but my current phython3.6 is having pysam 0.16.1, i have no idea how to do that, need help on this urgent.
Here is the link fro suggestion but none of them worked for me

https://sourceforge.net/p/conifer/discussion/general/thread/d2fbc181/?limit=25

**Comment by jmarshall** [comment]
The internal function `_hasIndex()` was renamed to a public `has_index()` function in pysam 0.8.4 in 2015. As discussed in the discussion thread you linked to, you should edit the `conifer.py` script to use `has_index()` (or `check_index()`, which would have a similar effect) instead. Or if you cannot do that, you would need to look into installing the very old pysam 0.8.3 or earlier instead — but I would not really recommend that route.

(By now of course the original poster has likely solved their problem or moved on. But this answer may be useful for anyone else still using conifer.)
