### ISSUE TITLE
trying to pickle a bam read gives TypeError

### ISSUE THREAD

**Issue by isthisthat** [pysam-developers/pysam#950]
Steps to reproduce:

    import pysam, pickle
    bam = pysam.AlignmentFile("my.bam", "rb")
    read = next(bam.fetch())
    with open("foo.bar", "w") as foo: pickle.dump(read, foo)

gives:

    in pysam.libcalignedsegment.AlignedSegment.__reduce_cython__()
    TypeError: self._delegate cannot be converted to a Python object for pickling

I'm using `multiprocessing` to speed up an application that processes a bam and passing a function that manipulates reads requires serialisation of the object which gives this error.
Wondering whether this is because `_delegate` is a pointer to a C object and therefore not available to serialise?

Any ideas on how to overcome this exception would be greatly appreciated.

**Comment by jamesbaye** [comment]
[`AlignedSegment.to_string`](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.to_string), `AlignedSegment.from_string` might be what you are looking for?

Alternatively if you have indexed bam files, you could provide each worker with the bam filepath and (contig, start, end) arguments, then have each worker open the filehandle and AlignmentFile.fetch() a region chunk for processing. See [this example](https://github.com/jamesbaye/mppysam/blob/dc205e86fade358b05fd9374674dc98ebd6fb522/mppysam/pysam_helper.py#L17).

**Comment by isthisthat** [comment]
that didn't work for me in this case because I needed some of the abstractions that pysam provides (forgot the specifics now). I did end up going for your second suggestion of having each worker open the bam independently and using the index to fetch a segment. That worked much much better. Thanks for your reply!
