### ISSUE TITLE
get_index_statistics() currently does not return unmapped reads (*)

### ISSUE THREAD

**Issue by Brunox13** [pysam-developers/pysam#968]
The output of the function
```python
pysam.AlignmentFile.get_index_statistics()
```
is similar (except that it outputs total reads instead of the length for each contig) to
```bash
samtools idxstats
```
but it does not output the last row starting with a "*", which indicates the unmapped reads (also described [here](http://seqanswers.com/forums/showthread.php?t=14850)).

The work-around is to use the following command to create a dataframe, but it is a bit unnecessarily cumbersome:
```python
from io import StringIO
import pandas as pd

indStats = pd.read_csv(StringIO(pysam.idxstats(bamfile)), sep = '\t', header = None, names = ['contig', 'length', 'mapped', 'unmapped'])
```
Related to #512.

**Comment by jmarshall** [comment]
Two of the statistics on the `*` line are always zero. The other one is returned by `pysam.AlignmentFile.nocoordinate`.

I've expanded the notes in the documentation for these two functions in 44ecf75d3698ff9afc8f4822baaa7617429196a0.

**Comment by Brunox13** [comment]
I see - thanks for the reply & commit!

That makes sense - it means that
the sum of all reads in `pysam.AlignmentFile.get_index_statistics()` +  `pysam.AlignmentFile.nocoordinate`
= `pysam.AlignmentFile.mapped` + `pysam.AlignmentFile.unmapped`

As a note, from the user perspective, I originally expected that
the sum of all reads in `pysam.AlignmentFile.get_index_statistics()`
= `pysam.AlignmentFile.mapped` + `pysam.AlignmentFile.unmapped`

...hence the surprise at not finding the `pysam.AlignmentFile.nocoordinate` count in `pysam.AlignmentFile.get_index_statistics()`.
