### ISSUE TITLE
pysam 0.9.0 installation in python 3.7 conda environment

### ISSUE THREAD

**Issue by nknewnew** [pysam-developers/pysam#971]
Can I install pysam 0.9.0 in python 3.7 conda environment? It kept reporting errors with PyThreadState in calignme calignedsegment.c  while compiling. Can anyone give me some suggestions? Thanks.

**Comment by jmarshall** [comment]
This sounds as if pysam was being built with a version of Cython that did not support Python 3.7. When such problems appear, the thing to check is whether Cython has been updated to be compatible with a newer version of CPython.

Current versions do not have problems like this at present.
