### ISSUE TITLE
Failed installation/ pysam package wheel build in Jaggu pkg

### ISSUE THREAD

**Issue by mehraj777** [pysam-developers/pysam#979]
I am Dr. Mehraj from SKUAST-Kashmir. I tried to install janggu pkg. but 
> failed several times on account of wheel build failure for pysam and 
> pyBigwig components, while attempted through many ways. i also tried to 
> get it from anaconda but it is not available there in the index. Please 
> suggest the resolution for the error as reproduced down for your 
> information. I am working on Mac Os ElCaptain 10.11 I have already 
>   successfully installed tensor flow and  keras using anaconda within 
> python 3.7 environment.
> 
> Hope this  helps for any solution.
> 
> Best Regards
> Dr. Mehraj
> 
> 
> 
> (base) MEHRAJUDDINs-MacBook-Pro:~ mehraj$ pip install janggu==0.8.4
> 
> Collecting janggu==0.8.4
> 
>    Using cached janggu-0.8.4-py2.py3-none-any.whl (1.3 MB)
> 
> Requirement already satisfied: pydot in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.4.1)
> 
> Requirement already satisfied: h5py in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (2.10.0)
> 
> Requirement already satisfied: pysam in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (0.16.0.1)
> 
> Requirement already satisfied: scikit-learn in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (0.23.2)
> 
> Requirement already satisfied: dash in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.18.1)
> 
> Requirement already satisfied: dash-html-components in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.1.1)
> 
> Requirement already satisfied: dash-renderer in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.8.3)
> 
> Requirement already satisfied: urllib3 in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.25.11)
> 
> Requirement already satisfied: dash-core-components in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.14.1)
> 
> Requirement already satisfied: keras in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (2.4.3)
> 
> Collecting pyBigWig
> 
>    Using cached pyBigWig-0.3.17.tar.gz (64 kB)
> 
> Requirement already satisfied: seaborn in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (0.11.0)
> 
> Requirement already satisfied: Biopython in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.77)
> 
> Requirement already satisfied: matplotlib in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (3.3.2)
> 
> Requirement already satisfied: htseq in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (0.13.5)
> 
> Requirement already satisfied: numpy in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.19.2)
> 
> Requirement already satisfied: pandas in 
> /opt/anaconda3/lib/python3.8/site-packages (from janggu==0.8.4) (1.1.3)
> 
> Requirement already satisfied: pyparsing>=2.1.4 in 
> /opt/anaconda3/lib/python3.8/site-packages (from pydot->janggu==0.8.4) 
> (2.4.7)
> 
> Requirement already satisfied: six in 
> /opt/anaconda3/lib/python3.8/site-packages (from h5py->janggu==0.8.4) 
> (1.15.0)
> 
> Requirement already satisfied: threadpoolctl>=2.0.0 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> scikit-learn->janggu==0.8.4) (2.1.0)
> 
> Requirement already satisfied: joblib>=0.11 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> scikit-learn->janggu==0.8.4) (0.17.0)
> 
> Requirement already satisfied: scipy>=0.19.1 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> scikit-learn->janggu==0.8.4) (1.4.1)
> 
> Requirement already satisfied: plotly in 
> /opt/anaconda3/lib/python3.8/site-packages (from dash->janggu==0.8.4) 
> (4.14.1)
> 
> Requirement already satisfied: flask-compress in 
> /opt/anaconda3/lib/python3.8/site-packages (from dash->janggu==0.8.4) 
> (1.8.0)
> 
> Requirement already satisfied: dash-table==4.11.1 in 
> /opt/anaconda3/lib/python3.8/site-packages (from dash->janggu==0.8.4) 
> (4.11.1)
> 
> Requirement already satisfied: Flask>=1.0.4 in 
> /opt/anaconda3/lib/python3.8/site-packages (from dash->janggu==0.8.4) 
> (1.1.2)
> 
> Requirement already satisfied: future in 
> /opt/anaconda3/lib/python3.8/site-packages (from dash->janggu==0.8.4) 
> (0.18.2)
> 
> Requirement already satisfied: pyyaml in 
> /opt/anaconda3/lib/python3.8/site-packages (from keras->janggu==0.8.4) 
> (5.3.1)
> 
> Requirement already satisfied: python-dateutil>=2.1 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> matplotlib->janggu==0.8.4) (2.8.1)
> 
> Requirement already satisfied: pillow>=6.2.0 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> matplotlib->janggu==0.8.4) (8.0.1)
> 
> Requirement already satisfied: kiwisolver>=1.0.1 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> matplotlib->janggu==0.8.4) (1.3.0)
> 
> Requirement already satisfied: certifi>=2020.06.20 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> matplotlib->janggu==0.8.4) (2020.6.20)
> 
> Requirement already satisfied: cycler>=0.10 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> matplotlib->janggu==0.8.4) (0.10.0)
> 
> Requirement already satisfied: pytz>=2017.2 in 
> /opt/anaconda3/lib/python3.8/site-packages (from pandas->janggu==0.8.4) 
> (2020.1)
> 
> Requirement already satisfied: retrying>=1.3.3 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> plotly->dash->janggu==0.8.4) (1.3.3)
> 
> Requirement already satisfied: brotli in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> flask-compress->dash->janggu==0.8.4) (1.0.9)
> 
> Requirement already satisfied: click>=5.1 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> Flask>=1.0.4->dash->janggu==0.8.4) (7.1.2)
> 
> Requirement already satisfied: itsdangerous>=0.24 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> Flask>=1.0.4->dash->janggu==0.8.4) (1.1.0)
> 
> Requirement already satisfied: Jinja2>=2.10.1 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> Flask>=1.0.4->dash->janggu==0.8.4) (2.11.2)
> 
> Requirement already satisfied: Werkzeug>=0.15 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> Flask>=1.0.4->dash->janggu==0.8.4) (1.0.1)
> 
> Requirement already satisfied: MarkupSafe>=0.23 in 
> /opt/anaconda3/lib/python3.8/site-packages (from 
> Jinja2>=2.10.1->Flask>=1.0.4->dash->janggu==0.8.4) (1.1.1)
> 
> Building wheels for collected packages: pyBigWig
> 
>    Building wheel for pyBigWig (setup.py) ... error
> 
>    ERROR: Command errored out with exit status 1:
> 
>     command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, 
> tokenize; sys.argv[0] = 
> '"'"'/private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/setup.py'"'"'; 
> __file__='"'"'/private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/setup.py'"'"';f=getattr(tokenize, 
> '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', 
> '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
> bdist_wheel -d 
> /private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-wheel-4ilmd2qt
> 
>         cwd: 
> /private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/
> 
>    Complete output (43 lines):
> 
>    /opt/anaconda3/lib/python3.8/distutils/dist.py:274: UserWarning: 
> Unknown distribution option: 'classifier'
> 
>      warnings.warn(msg)
> 
>    running bdist_wheel
> 
>    running build
> 
>    running build_py
> 
>    creating build
> 
>    creating build/lib.macosx-10.9-x86_64-3.8
> 
>    creating build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>    copying pyBigWigTest/__init__.py -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>    copying pyBigWigTest/test.py -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>    running egg_info
> 
>    writing pyBigWig.egg-info/PKG-INFO
> 
>    writing dependency_links to pyBigWig.egg-info/dependency_links.txt
> 
>    writing requirements to pyBigWig.egg-info/requires.txt
> 
>    writing top-level names to pyBigWig.egg-info/top_level.txt
> 
>    reading manifest file 'pyBigWig.egg-info/SOURCES.txt'
> 
>    reading manifest template 'MANIFEST.in'
> 
>    writing manifest file 'pyBigWig.egg-info/SOURCES.txt'
> 
>    copying pyBigWigTest/test.bigBed -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>    copying pyBigWigTest/test.bw -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>    running build_ext
> 
>    building 'pyBigWig' extension
> 
>    Warning: Can't read registry to find the necessary compiler setting
> 
>    Make sure that Python modules winreg, win32api or win32con are installed.
> 
>    C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code 
> -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes 
> -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64
> 
>    creating build/temp.macosx-10.9-x86_64-3.8
> 
>    creating build/temp.macosx-10.9-x86_64-3.8/libBigWig
> 
>    compile options: '-DWITHNUMPY 
> -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig 
> -I/opt/anaconda3/include/python3.8 
> -I/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include 
> -I/opt/anaconda3/include/python3.8 -c'
> 
>    gcc: libBigWig/bwRead.c
> 
>    gcc: libBigWig/bwStats.c
> 
>    gcc: libBigWig/bwValues.c
> 
>    gcc: libBigWig/bwWrite.c
> 
>    gcc: libBigWig/io.c
> 
>    gcc: pyBigWig.c
> 
>    pyBigWig.c:746:12: warning: returning 'const char *' from a function 
> with result type 'char *' discards qualifiers 
> [-Wincompatible-pointer-types-discards-qualifiers]
> 
>        return PyUnicode_AsUTF8(obj);
> 
>               ^~~~~~~~~~~~~~~~~~~~~
> 
>    1 warning generated.
> 
>    gcc -bundle -undefined dynamic_lookup -L/opt/anaconda3/lib -arch 
> x86_64 -L/opt/anaconda3/lib -arch x86_64 -arch x86_64 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwRead.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwStats.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwValues.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwWrite.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/io.o 
> build/temp.macosx-10.9-x86_64-3.8/pyBigWig.o 
> -L/opt/anaconda3/lib/python3.8/site-packages/numpy/core/lib 
> -L/opt/anaconda3/lib -L/opt/anaconda3/lib/python3.8/config-3.8-darwin 
> -L/opt/anaconda3/lib -lm -lz -lcurl -lnpymath -o 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWig.cpython-38-darwin.so
> 
>    error: Invalid value (Producer: 'LLVM10.0.0' Reader: 'LLVM 
> APPLE_1_800.0.42.1_0')
> 
>    clang: error: linker command failed with exit code 1 (use -v to see 
> invocation)
> 
>    error: Command "gcc -bundle -undefined dynamic_lookup 
> -L/opt/anaconda3/lib -arch x86_64 -L/opt/anaconda3/lib -arch x86_64 
> -arch x86_64 build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwRead.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwStats.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwValues.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwWrite.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/io.o 
> build/temp.macosx-10.9-x86_64-3.8/pyBigWig.o 
> -L/opt/anaconda3/lib/python3.8/site-packages/numpy/core/lib 
> -L/opt/anaconda3/lib -L/opt/anaconda3/lib/python3.8/config-3.8-darwin 
> -L/opt/anaconda3/lib -lm -lz -lcurl -lnpymath -o 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWig.cpython-38-darwin.so" failed 
> with exit status 1
> 
>    ----------------------------------------
> 
>    ERROR: Failed building wheel for pyBigWig
> 
>    Running setup.py clean for pyBigWig
> 
> Failed to build pyBigWig
> 
> Installing collected packages: pyBigWig, janggu
> 
>      Running setup.py install for pyBigWig ... error
> 
>      ERROR: Command errored out with exit status 1:
> 
>       command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, 
> tokenize; sys.argv[0] = 
> '"'"'/private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/setup.py'"'"'; 
> __file__='"'"'/private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/setup.py'"'"';f=getattr(tokenize, 
> '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', 
> '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
> install --record 
> /private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-record-p3bdmh37/install-record.txt 
> --single-version-externally-managed --compile --install-headers 
> /opt/anaconda3/include/python3.8/pyBigWig
> 
>           cwd: 
> /private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/
> 
>      Complete output (43 lines):
> 
>      /opt/anaconda3/lib/python3.8/distutils/dist.py:274: UserWarning: 
> Unknown distribution option: 'classifier'
> 
>        warnings.warn(msg)
> 
>      running install
> 
>      running build
> 
>      running build_py
> 
>      creating build
> 
>      creating build/lib.macosx-10.9-x86_64-3.8
> 
>      creating build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>      copying pyBigWigTest/__init__.py -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>      copying pyBigWigTest/test.py -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>      running egg_info
> 
>      writing pyBigWig.egg-info/PKG-INFO
> 
>      writing dependency_links to pyBigWig.egg-info/dependency_links.txt
> 
>      writing requirements to pyBigWig.egg-info/requires.txt
> 
>      writing top-level names to pyBigWig.egg-info/top_level.txt
> 
>      reading manifest file 'pyBigWig.egg-info/SOURCES.txt'
> 
>      reading manifest template 'MANIFEST.in'
> 
>      writing manifest file 'pyBigWig.egg-info/SOURCES.txt'
> 
>      copying pyBigWigTest/test.bigBed -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>      copying pyBigWigTest/test.bw -> 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWigTest
> 
>      running build_ext
> 
>      building 'pyBigWig' extension
> 
>      Warning: Can't read registry to find the necessary compiler setting
> 
>      Make sure that Python modules winreg, win32api or win32con are 
> installed.
> 
>      C compiler: gcc -Wno-unused-result -Wsign-compare 
> -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes 
> -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64
> 
>      creating build/temp.macosx-10.9-x86_64-3.8
> 
>      creating build/temp.macosx-10.9-x86_64-3.8/libBigWig
> 
>      compile options: '-DWITHNUMPY 
> -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig 
> -I/opt/anaconda3/include/python3.8 
> -I/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include 
> -I/opt/anaconda3/include/python3.8 -c'
> 
>      gcc: libBigWig/bwRead.c
> 
>      gcc: libBigWig/bwStats.c
> 
>      gcc: libBigWig/bwValues.c
> 
>      gcc: libBigWig/bwWrite.c
> 
>      gcc: libBigWig/io.c
> 
>      gcc: pyBigWig.c
> 
>      pyBigWig.c:746:12: warning: returning 'const char *' from a 
> function with result type 'char *' discards qualifiers 
> [-Wincompatible-pointer-types-discards-qualifiers]
> 
>          return PyUnicode_AsUTF8(obj);
> 
>                 ^~~~~~~~~~~~~~~~~~~~~
> 
>      1 warning generated.
> 
>      gcc -bundle -undefined dynamic_lookup -L/opt/anaconda3/lib -arch 
> x86_64 -L/opt/anaconda3/lib -arch x86_64 -arch x86_64 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwRead.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwStats.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwValues.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwWrite.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/io.o 
> build/temp.macosx-10.9-x86_64-3.8/pyBigWig.o 
> -L/opt/anaconda3/lib/python3.8/site-packages/numpy/core/lib 
> -L/opt/anaconda3/lib -L/opt/anaconda3/lib/python3.8/config-3.8-darwin 
> -L/opt/anaconda3/lib -lm -lz -lcurl -lnpymath -o 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWig.cpython-38-darwin.so
> 
>      error: Invalid value (Producer: 'LLVM10.0.0' Reader: 'LLVM 
> APPLE_1_800.0.42.1_0')
> 
>      clang: error: linker command failed with exit code 1 (use -v to see 
> invocation)
> 
>      error: Command "gcc -bundle -undefined dynamic_lookup 
> -L/opt/anaconda3/lib -arch x86_64 -L/opt/anaconda3/lib -arch x86_64 
> -arch x86_64 build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwRead.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwStats.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwValues.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/bwWrite.o 
> build/temp.macosx-10.9-x86_64-3.8/libBigWig/io.o 
> build/temp.macosx-10.9-x86_64-3.8/pyBigWig.o 
> -L/opt/anaconda3/lib/python3.8/site-packages/numpy/core/lib 
> -L/opt/anaconda3/lib -L/opt/anaconda3/lib/python3.8/config-3.8-darwin 
> -L/opt/anaconda3/lib -lm -lz -lcurl -lnpymath -o 
> build/lib.macosx-10.9-x86_64-3.8/pyBigWig.cpython-38-darwin.so" failed 
> with exit status 1
> 
>      ----------------------------------------
> 
> ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python 
> -u -c 'import sys, setuptools, tokenize; sys.argv[0] = 
> '"'"'/private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/setup.py'"'"'; 
> __file__='"'"'/private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-install-uc7bsu7m/pybigwig/setup.py'"'"';f=getattr(tokenize, 
> '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', 
> '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
> install --record 
> /private/var/folders/hh/10brr3bx099_g0njr4qk5d000000gn/T/pip-record-p3bdmh37/install-record.txt 
> --single-version-externally-managed --compile --install-headers 
> /opt/anaconda3/include/python3.8/pyBigWig Check the logs for full 
> command output.
> 
> (base) MEHRAJUDDINs-MacBook-Pro:~ mehraj$
>

**Comment by jmarshall** [comment]
The only mention of pysam in this log is `Requirement already satisfied: pysam`; all the errors encountered come from [pyBigWig](https://github.com/deeptools/pyBigWig).

I suggest you report this problem to janggu and/or pyBigWig instead.
