### ISSUE TITLE
pysam.index fails in ipython notebook

### ISSUE THREAD

**Issue by jrderuiter** [pysam-developers/pysam#98]
I have the same problem as #12 but in IPython Notebook on Python 3.4.3 (IPython 3.0.0, pysam 0.8.2.1). Is this a regression?

```{python}

---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-20-714eb49927ea> in <module>()
----> 1 pysam.index(sam_file.filename.decode('UTF-8'))

/Applications/anaconda/lib/python3.4/site-packages/pysam/__init__.py in __call__(self, *args, **kwargs)
     64         '''
     65         retval, stderr, stdout = csamtools._samtools_dispatch(
---> 66             self.dispatch, args)
     67         if retval:
     68             raise SamtoolsError(

csamtools.pyx in pysam.csamtools._samtools_dispatch (pysam/csamtools.c:2811)()

/Applications/anaconda/lib/python3.4/site-packages/IPython/kernel/zmq/iostream.py in fileno(self)
    203 
    204     def fileno(self):
--> 205         raise UnsupportedOperation("IOStream has no fileno.")
    206 
    207     def write(self, string):

UnsupportedOperation: IOStream has no fileno.
```

**Comment by TyberiusPrime** [comment]
This is reproducible with Jupytr  3.0.0-b1-ee6223a and Python 2.7.3.

**Comment by TyberiusPrime** [comment]
It can be 'fixed' by capturing the exception in  csamtools.pyx around line 110, 
similar to the AttributeError already being caught.

[code]
        try:
            stdout_save = Outs( sys.stdout.fileno() )
            stdout_save.setfd( stdout_h )
        except (AttributeError, io.UnsupportedOperation):
            # stdout has already been redirected
            catch_stdout = False
[/code]

but a side effect is that you won't receive output even from those samtool commands that do produce output (eg. mpileup).

**Comment by AndreasHeger** [comment]
Thanks, I can confirm that the issue was never fixed. The samtools access through pysam is hacky, as a stop-gap solution I can only suggest running samtools through the shells in notebooks.

I will put this on the todo list for the next release.

**Comment by AndreasHeger** [comment]
Hi, I have added a "catch_stdout" keyword argument to samtools commands. 

The following should now work in ipython:

```
pysam.index(sam_file.filename.decode('UTF-8'), catch_stdout=False)
```

Best wishes,
Andreas
