### ISSUE TITLE
win32/getopt is missing from the pip-downloaded archive

### ISSUE THREAD

**Issue by fluhus** [pysam-developers/pysam#983]
Hello,

I am trying to `pip install pysam` on Windows 10 + MinGW64.

The error I got:

```
C:\dev\tools\msys64\mingw64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam\htslib -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam\samtools -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam\samtools\lz4 -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam\bcftools -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam\pysam -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam -IC:\Users\amit\AppData\Local\Temp\pip-install-upkf6i4z\pysam\win32 -IC:\dev\tools\python38\include -IC:\dev\tools\python38\include -c win32/getopt.c -o build\temp.win-amd64-3.8\Release\win32\getopt.o
    gcc: error: win32/getopt.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'C:\\dev\\tools\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
```

I looked into the archive manually using `pip download pysam`, and saw that it missed the win32 directory which exists in this repository.

Any idea how to get the missing files in there?
Is there a way to create a `pip install`-able archive locally from this repository?

**Comment by jmarshall** [comment]
It's not obvious that these files are still needed, and it might be interesting to try compiling on WinGW with the following change to _setup.py_:

```diff
--- a/setup.py
+++ b/setup.py
@@ -339,8 +339,8 @@ for fn in config_headers:
 #######################################################
 # Windows compatibility - untested
 if platform.system() == 'Windows':
-    include_os = ['win32']
-    os_c_files = ['win32/getopt.c']
+    include_os = []
+    os_c_files = []
     extra_compile_args = []
 else:
     include_os = []
```

However while these files are used in _setup.py_ they should be in the pip source tarball — which we can arrange by adding them to the manifest. In the meantime, you can get a tarball that includes these files by downloading the [GitHub release tarball](https://github.com/pysam-developers/pysam/releases/tag/v0.16.0.1).
