### ISSUE TITLE
Does the parameter end from VariantFile.fetch is included or excluded

### ISSUE THREAD

**Issue by bioinfornatics** [pysam-developers/pysam#986]
Dear, 
little question, into the documentation it is tell that start and end is 0-based but what about inclusive/exclusive ?
I would like to know if start=0 and end=5 that fetch 6 bases or 5 ?

Thanks

Best regards

**Comment by jmarshall** [comment]
In general in pysam, where parameters are supplied as `start`,`stop` integers, they are 0-based half-open. Where they are supplied as a human-readable `"chr:start-stop"` string, the coordinates are 1-based inclusive.

I've prepared a clarification for the `VariantFile.fetch` documentation accordingly. Thanks for pointing out the documentation deficiency.

**Comment by bioinfornatics** [comment]
Thanks
