### ISSUE TITLE
DOC: Description of "." and "," inconsistent in documentation for PileupColumn.get_query_sequences

### ISSUE THREAD

**Issue by jotasi** [pysam-developers/pysam#990]
The documentation for `PileupColumn.get_query_sequences` quotes from samtools mpileup documentation as follows (emphasize mine):

> [...] At this column, a **dot** stands for a match to the reference base on the **forward strand**, a **comma** for a match on the **reverse strand**, [...]

In the documentation for the parameter `mark_matches` however, the assignment of "." and "," to forward and reverse strand is inverted:

> `mark_matches`` (bool) – If True, output bases matching the reference as **“,” or “.” for forward and reverse strand, respectively**. [...]

Checking the source, the assignment is done [here](https://github.com/pysam-developers/pysam/blob/b09ddca07b10bdd5d25be519e26a8d947435f83d/pysam/libcalignedsegment.pyx#L124) with "." being on the forward and "," being on the reverse strand. "." and "," thus have to be switched in the documentation of the `mark_matches` parameter.

**Comment by jmarshall** [comment]
Thanks for the documentation improvement.
