### ISSUE TITLE
Incorrect error reporting for AlignmentHeader. get_reference_length(self, reference)

### ISSUE THREAD

**Issue by alec-BLI** [pysam-developers/pysam#994]
I recently ran into an issue that broke my code and took me a long time to figure out.  I used bowtie to align my results and then saw an error with this line of code.

`ref_len = record.header.get_reference_length(record.reference_name)`

I was being told that the reference name was unknown.  However the issue was slightly different.  In the implementation of this method the method `get_tid(self, reference)` is called.  It returns -1 if the reference is not found in the header.  But it returns -2 if the header cannot be parsed.  This is because ultimately `get_tid(self, reference)` is calling `htslib.header. sam_hdr_name2tid`.

After discovering that the real issue was that my header couldn't be parsed I found that there was a reference name that occurred twice within the header.  I then confirmed that there was a bug in the code I wrote for building the fasta that the reference was built from to use the same reference name twice.

Once I knew there was a malformed sam header finding the issue was easy.  But there was no mention of the sam header being malformed in the error, and I had to go to the source code to figure it out.

I would like to propose that we update the error reporting for `get_reference_length(self, reference)`, as well as any other method that relies on `get_tid(self, reference)` to add another error message when `get_tid` returns -2 instead of -1.  If this message had indicated that my sam header was malformed instead of telling me that the reference that I could see in the header didn't exist it would have made my life much easier.

**Comment by jmarshall** [comment]
This -2 return code for malformed headers is a relatively recent addition in HTSlib 1.10. You're quite right that it would be good to reflect the distinction in pysam functions that call it.

It's an unusual (and catastrophic) enough case that it would probably be best to just alter `get_tid()` itself to raise an exception with a suitable explanation if `bam_nam2id()` returns < -1.
